#!/usr/bin/env node
// Country packs: validate | list | new | review | vectors | sync | check
//   node country-packs/tools/cli.mjs validate            check every pack against SPEC.md
//   node country-packs/tools/cli.mjs list                one line per country
//   node country-packs/tools/cli.mjs new ZZ --name Zedland --currency ZZD --symbol "Z$" --tax VAT --rate 15
//   node country-packs/tools/cli.mjs review IN --by "A. Kumar, Kumar & Co" --on 2026-10-20 --notes "Checked against the CBIC notifications"
//   node country-packs/tools/cli.mjs vectors             regenerate vectors/tax-vectors.json from the reference engine
//   node country-packs/tools/cli.mjs sync                copy the packs and vectors to where the programs read them
//   node country-packs/tools/cli.mjs check               what the release gate runs: validate + vectors + sync are all current
import { readFileSync, writeFileSync, readdirSync, existsSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { validatePack } from './validate.mjs';
import { calculate, formatMoney } from './reference.mjs';
import { cases, formats } from './vector-cases.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');
const packsDir = join(root, 'packs');
const vectorsFile = join(root, 'vectors', 'tax-vectors.json');
const storefrontGenerated = join(root, '..', 'apps', 'storefront-web-mobile', 'src', 'lib', 'region', 'generated');

const loadPacks = () => Object.fromEntries(readdirSync(packsDir).filter((f) => f.endsWith('.json')).sort().map((f) => [f.replace('.json', ''), JSON.parse(readFileSync(join(packsDir, f), 'utf8'))]));
const args = process.argv.slice(2);
const flag = (name, fallback) => { const i = args.indexOf(`--${name}`); return i >= 0 && args[i + 1] ? args[i + 1] : fallback; };

export function buildVectors(packs) {
  return cases.map((c) => {
    const pack = c.inline ?? packs[c.pack];
    if (!pack) throw new Error(`vector "${c.name}" names an unknown pack ${c.pack}`);
    const expected = calculate(pack, c.context, c.lines, c.adjustments ?? []);
    const out = { name: c.name, ...(c.inline ? { inline: c.inline } : { pack: c.pack }), context: c.context, lines: c.lines };
    if (c.adjustments) out.adjustments = c.adjustments;
    out.expected = expected;
    return out;
  });
}

export function buildFormats(packs) {
  return formats.map(([country, amount]) => ({ pack: country, amount, expected: formatMoney(amount, packs[country].currency) }));
}

const vectorText = (packs) => JSON.stringify({ schema: 1, note: 'Generated by country-packs/tools/cli.mjs vectors. Do not edit.', cases: buildVectors(packs), formats: buildFormats(packs) }, null, 2) + '\n';
const bundleText = (packs) => JSON.stringify(packs) + '\n';
/** The few facts a web page needs about each country (money, language, the tax's name), small enough to ship to a browser. */
const liteText = (packs) => JSON.stringify(Object.fromEntries(Object.entries(packs).map(([code, p]) => [code, {
  name: p.name, currency: p.currency, locale: p.locale, languages: p.languages, timezone: p.timezone, taxName: p.tax.name, pricesIncludeTax: p.tax.pricesIncludeTaxDefault,
}]))) + '\n';

function validateAll(packs) {
  let bad = 0;
  for (const [code, pack] of Object.entries(packs)) {
    const problems = validatePack(pack, `${code}.json`);
    if (problems.length) { bad++; console.log(`${code}: ${problems.length} problem(s)`); for (const p of problems) console.log(`   - ${p}`); }
  }
  return bad;
}

const command = args[0];
const packs = loadPacks();

if (command === 'validate') {
  const bad = validateAll(packs);
  console.log(bad ? `\n${bad} pack(s) have problems.` : `All ${Object.keys(packs).length} packs are sound.`);
  process.exit(bad ? 1 : 0);
} else if (command === 'list') {
  for (const [code, p] of Object.entries(packs)) {
    console.log(`${code}  ${p.name.padEnd(22)} ${p.currency.code}  ${p.tax.name.padEnd(16)} ${p.tax.rates.filter((r) => r.percent && !r.legacy).map((r) => r.percent + '%').join(' ').padEnd(26)} ${p.review ? 'reviewed by ' + p.review.by + ' on ' + p.review.on : 'starter (not reviewed by a local adviser)'}`);
  }
} else if (command === 'new') {
  const code = (args[1] ?? '').toUpperCase();
  if (!/^[A-Z]{2}$/.test(code)) { console.error('Give the two-letter country code, for example: new ZZ --name Zedland --currency ZZD --symbol "Z$" --tax VAT --rate 15'); process.exit(1); }
  const file = join(packsDir, `${code}.json`);
  if (existsSync(file)) { console.error(`${code}.json already exists. Edit it, or choose another code.`); process.exit(1); }
  const pack = JSON.parse(JSON.stringify(packs.GB));
  const rate = flag('rate', '10');
  pack.country = code;
  pack.name = flag('name', code);
  pack.asOf = new Date().toISOString().slice(0, 10);
  pack.review = null;
  Object.assign(pack.currency, { code: flag('currency', 'XXX').toUpperCase(), symbol: flag('symbol', flag('currency', 'XXX')), decimals: Number(flag('decimals', '2')), symbolPosition: 'before', symbolSpace: false, grouping: 'standard', decimalSeparator: '.', groupSeparator: ',' });
  pack.locale = flag('locale', 'en');
  pack.languages = [pack.locale.split('-')[0]];
  pack.timezone = flag('timezone', 'UTC/UTC');
  pack.phoneCode = flag('phone', '+0');
  pack.tax.name = flag('tax', 'VAT');
  const key = pack.tax.name.replace(/[^A-Za-z]/g, '').toUpperCase().slice(0, 4) || 'TAX';
  pack.tax.rates = [{ code: `${key}${rate.replace('.', 'P')}`, label: `${pack.tax.name} ${rate}%`, percent: rate }, { code: `${key}0`, label: `${pack.tax.name} 0% (zero-rated)`, zero: true }, { code: `${key}EX`, label: 'Exempt', exempt: true }];
  delete pack.tax.businessId;
  pack.tax.rounding = { total: 'none', increment: '1', defaultOn: false };
  pack.invoice = { title: 'Tax Invoice', requiredFields: ['Seller name and address', 'Tax number', 'Invoice number and date', 'Description, quantity and price of each item', 'Tax amount'], eInvoice: null, retentionYears: 5 };
  pack.notes = ['Written from the template of the "new" command. Replace every value with what the tax office of the country says, then have a local adviser check it and record that with: review ' + code + ' --by "..." --on YYYY-MM-DD'];
  const problems = validatePack(pack, `${code}.json`);
  if (problems.length) { console.error(problems.join('\n')); process.exit(1); }
  writeFileSync(file, JSON.stringify(pack, null, 2) + '\n');
  console.log(`Made ${file}. Open it, check every value, then run: node country-packs/tools/cli.mjs vectors && node country-packs/tools/cli.mjs sync`);
} else if (command === 'review') {
  const code = (args[1] ?? '').toUpperCase();
  const file = join(packsDir, `${code}.json`);
  if (!existsSync(file)) { console.error(`There is no pack ${code}.`); process.exit(1); }
  const by = flag('by'); const on = flag('on');
  if (!by || !on) { console.error('Give --by "name, firm" and --on YYYY-MM-DD'); process.exit(1); }
  const pack = JSON.parse(readFileSync(file, 'utf8'));
  pack.review = { by, on, notes: flag('notes', '') };
  const problems = validatePack(pack, `${code}.json`);
  if (problems.length) { console.error(problems.join('\n')); process.exit(1); }
  writeFileSync(file, JSON.stringify(pack, null, 2) + '\n');
  console.log(`${code} is now recorded as reviewed by ${by} on ${on}.`);
} else if (command === 'vectors') {
  mkdirSync(dirname(vectorsFile), { recursive: true });
  writeFileSync(vectorsFile, vectorText(packs));
  console.log(`Wrote ${cases.length} calculation vectors and ${formats.length} format vectors to ${vectorsFile}`);
} else if (command === 'sync') {
  mkdirSync(storefrontGenerated, { recursive: true });
  writeFileSync(join(storefrontGenerated, 'packs.json'), bundleText(packs));
  writeFileSync(join(storefrontGenerated, 'lite.json'), liteText(packs));
  writeFileSync(join(storefrontGenerated, 'tax-vectors.json'), readFileSync(vectorsFile, 'utf8'));
  console.log(`Copied ${Object.keys(packs).length} packs and the vectors to ${storefrontGenerated}`);
} else if (command === 'check') {
  const problems = [];
  if (validateAll(packs)) problems.push('some packs have problems (run validate)');
  if (!existsSync(vectorsFile) || readFileSync(vectorsFile, 'utf8') !== vectorText(packs)) problems.push('vectors/tax-vectors.json is out of date (run vectors)');
  const bundle = join(storefrontGenerated, 'packs.json');
  if (!existsSync(bundle) || readFileSync(bundle, 'utf8') !== bundleText(packs)) problems.push('the storefront copy of the packs is out of date (run sync)');
  const lite = join(storefrontGenerated, 'lite.json');
  if (!existsSync(lite) || readFileSync(lite, 'utf8') !== liteText(packs)) problems.push('the storefront copy of the country facts is out of date (run sync)');
  const vcopy = join(storefrontGenerated, 'tax-vectors.json');
  if (!existsSync(vcopy) || !existsSync(vectorsFile) || readFileSync(vcopy, 'utf8') !== readFileSync(vectorsFile, 'utf8')) problems.push('the storefront copy of the vectors is out of date (run sync)');
  if (problems.length) { console.log(problems.join('\n')); process.exit(1); }
  console.log(`Country packs are consistent: ${Object.keys(packs).length} packs, ${cases.length} vectors, copies current.`);
} else {
  console.log('Commands: validate | list | new | review | vectors | sync | check');
  process.exit(command ? 1 : 0);
}
