// The Setup Studio in a real browser, as the people who use it would: first-time welcome, signing in, adding a customer, filling in the details, seeing the look in a real
// preview, preparing the setup, a second person approving it, the website and app made by the build service, and the hand-over. A stand-in AI tool answers when asked, and a stand-in
// build service makes the website and app. Nothing leaves this PC.
import assert from 'node:assert';
import { createRequire } from 'node:module';
import { mkdtempSync, rmSync, writeFileSync, chmodSync, mkdirSync, readFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, dirname, resolve, delimiter } from 'node:path';
import { fileURLToPath } from 'node:url';
import { startStudio } from '../lib/server.mjs';
import { listZip } from '../lib/zip.mjs';
import { makeBaseKit } from '../../../scripts/make-base-kit.mjs';
import { standInGitHub } from './stand-in-github.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const { chromium } = createRequire(resolve(here, '..', '..', '..', 'apps', 'business-hub', 'e2e', 'package.json'))('playwright');
const PNG = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChwGA60e6kgAAAABJRU5ErkJggg==', 'base64');
const shots = process.env.STUDIO_SHOTS || join(tmpdir(), 'studio-shots');
mkdirSync(shots, { recursive: true });

const root = mkdtempSync(join(tmpdir(), 'studio-e2e-'));
process.env.SETUP_STUDIO_HOME = join(root, 'home');
writeFileSync(join(root, 'logo.png'), PNG);
const tools = join(root, 'tools'); mkdirSync(tools);
const answer = JSON.stringify({ setup: { schema: 1, settings: { receiptFooter: 'Salamat po!', paymentMethods: ['cash', 'gcash', 'card'] }, vocabulary: { customer: ['Suki', 'Sukis'] } }, theme: { depth: 'lifted' }, explanation: 'Local words and wallets for a Philippine shop.' });
writeFileSync(join(tools, 'claude'), `#!/usr/bin/env node\nprocess.stdin.resume();process.stdin.on('end',()=>console.log(JSON.stringify({is_error:false,result:${JSON.stringify(answer)},modelUsage:{'claude-opus-5-5':{}}})))\n`);
chmodSync(join(tools, 'claude'), 0o755);
const oldPath = process.env.PATH;
process.env.PATH = tools + delimiter + oldPath;
process.env.ANTHROPIC_API_KEY = 'sk-ant-test-123456';

const github = await standInGitHub({ stepMs: 80 });
const studio = await startStudio({ folder: join(root, 'ws'), env: process.env, kitFolder: join(root, 'no-built-in-kit'), build: { api: github.url, pollMs: 100, ceilingMs: 60_000, requestTimeoutMs: 3000 } });
const browser = await chromium.launch();
const problems = [];
const step = (s) => console.log('✓ ' + s);
const shot = (page, name) => page.screenshot({ path: join(shots, `studio-${name}.png`), fullPage: true });
// A message appears when the page has its answer (a wrong password is answered by the Studio, not by the page itself), so the test waits for it to show: reading the line at once reads it before the answer.
const sees = async (page, pattern) => { await page.locator('.err', { hasText: pattern }).first().waitFor({ state: 'visible', timeout: 10000 }); };
const newPage = async (width = 1360, height = 900) => {
  const page = await (await browser.newContext({ viewport: { width, height }, reducedMotion: 'reduce' })).newPage();
  page.on('console', (m) => { if (m.type() === 'error' && !/status of (400|401|403|409)/.test(m.text())) problems.push('console: ' + m.text()); });
  page.on('pageerror', (e) => problems.push('pageerror: ' + e.message));
  page.on('requestfailed', (r) => { if (r.failure()?.errorText !== 'net::ERR_ABORTED') problems.push('requestfailed: ' + r.url() + ' ' + r.failure()?.errorText); });
  return page;
};
const signIn = async (page, name, password) => {
  await page.goto(studio.url);
  await page.locator(`[data-person="${name}"]`).click();
  await page.locator('#s-pass').fill(password);
  await page.locator('#s-go').click();
  await page.locator('nav[aria-label="Main"]').waitFor();
};

try {
  const page = await newPage();
  // ---- first use ------------------------------------------------------------------------------------------------------------------------
  await page.goto(studio.url);
  await page.getByRole('heading', { name: 'Welcome to the Setup Studio' }).waitFor();
  await shot(page, '01-welcome');
  await page.locator('#w-name').fill('Asha Admin');
  await page.locator('#w-pass').fill('a-long-password');
  await page.locator('#w-pass2').fill('different-password');
  await page.locator('#w-go').click();
  await sees(page, /not the same/);
  await page.locator('#w-pass2').fill('a-long-password');
  await page.locator('#w-go').click();
  await page.locator('nav[aria-label="Main"]').waitFor();
  assert.ok(!page.url().includes('k='), 'the secret is not left in the address bar');
  step('the first person makes the administrator account; a mistyped password is explained, and the secret leaves the address bar');
  await page.getByRole('heading', { name: 'Customers', exact: true }).waitFor();
  assert.ok(await page.getByRole('heading', { name: 'No customers yet' }).isVisible());
  await shot(page, '02-empty');

  // ---- the team ---------------------------------------------------------------------------------------------------------------------------
  await page.locator('[data-nav="team"]').click();
  await page.locator('#add-member').click();
  await page.locator('#m-name').fill('Sam Sales'); await page.locator('#m-role').selectOption('sales'); await page.locator('#m-pass').fill('sam-long-password'); await page.locator('#m-save').click();
  await page.locator('[data-member="Sam Sales"]').waitFor();
  await page.locator('#add-member').click();
  await page.locator('#m-name').fill('Rita Reviewer'); await page.locator('#m-role').selectOption('reviewer'); await page.locator('#m-pass').fill('rita-long-password'); await page.locator('#m-save').click();
  await page.locator('[data-member="Rita Reviewer"]').waitFor();
  await shot(page, '03-team');
  step('the administrator adds a salesperson and a reviewer');
  await page.locator('#signout').click();
  await page.locator('[data-person="Sam Sales"]').waitFor();
  await shot(page, '04-signin');

  // ---- a salesperson adds a customer ------------------------------------------------------------------------------------------------------
  await page.locator('[data-person="Sam Sales"]').click();
  await page.locator('#s-pass').fill('wrong-password'); await page.locator('#s-go').click();
  await sees(page, /not right/);
  await page.locator('#s-pass').fill('sam-long-password'); await page.locator('#s-go').click();
  await page.locator('[data-nav="customers"]').click();
  await page.locator('#new-customer').waitFor();
  await page.locator('#new-customer').click();
  await page.locator('#nc-name').fill('Luzon Fresh Mart');
  await page.locator('#nc-create').click();
  await sees(page, /choose the country/);
  await page.locator('#nc-country').selectOption({ label: 'Philippines' });
  await page.locator('#nc-create').click();
  await sees(page, /kind of business/);
  await page.locator('#nc-kind').selectOption({ label: 'Retail store' });
  await page.locator('#nc-create').click();
  await page.waitForURL(/#\/customers\/luzon-fresh-mart\/details/);
  await page.locator('#customer-name').waitFor();
  assert.strictEqual(await page.locator('#customer-name').innerText(), 'Luzon Fresh Mart');
  await page.locator('.pill', { hasText: 'Details' }).first().waitFor();
  await shot(page, '05-details');
  step('a salesperson adds a customer with three answers and lands on its page');

  // details: business, bills, words
  await page.locator('[data-tab="money"]').click();
  await page.locator('input[data-path="business.contact.phone"]').fill('+63 2 5555 0100');
  await page.locator('input[data-path="business.contact.email"]').fill('help@luzonfresh.example');
  await page.locator('#pay-add').fill('gcash'); await page.locator('#pay-add').press('Enter');
  await page.locator('#pay-chips .chip.on', { hasText: 'gcash' }).waitFor();
  await page.locator('#savebar').waitFor();
  await shot(page, '06-money');
  await page.locator('[data-tab="data"]').click();
  await page.locator('[data-import="items"]').click();
  await page.locator('#import-text').fill('Item,Rate,EAN\n"Rice, 5 kg","₱ 285.00",4800000000011\nGift wrapping,20,\nBroken line,,\n');
  await page.locator('#import-check').click();
  await page.locator('#import-result .notice.ok').waitFor();
  assert.match(await page.locator('#import-result').innerText(), /2 items understood/);
  assert.match(await page.locator('#import-result').innerText(), /Line 4/);
  await shot(page, '07-import');
  await page.locator('#import-add').click();
  await page.locator('input[data-word="customer-one"]').fill('Suki'); await page.locator('input[data-word="customer-many"]').fill('Sukis');
  await page.locator('#save').click();
  await page.locator('.toast', { hasText: 'Saved' }).last().waitFor();
  step('the details are written in plain screens: bills and money, a list brought in from a spreadsheet (with the bad line named), their own words');

  // look
  await page.locator('[data-step="look"]').click();
  await page.locator('#preview-frame').waitFor();
  const frame = page.frameLocator('#preview-frame');
  await frame.locator('.shell').waitFor();
  // a new customer opens in the top menu look; each look is one card, and the picture follows it
  assert.strictEqual(await frame.locator('html').getAttribute('data-look'), 'top');
  assert.strictEqual(await frame.locator('html').getAttribute('data-nav'), 'top');
  assert.strictEqual(await frame.locator('html').getAttribute('data-density'), 'touch');
  await page.locator('[data-path="look.layout"] [data-value="list"]').click();
  await frame.locator('html[data-look="list"]').waitFor();
  assert.strictEqual(await frame.locator('html').getAttribute('data-density'), 'comfortable');
  await page.locator('[data-path="look.layout"] [data-value="counter"]').click();
  await frame.locator('html[data-nav="left"]').waitFor();
  await page.locator('[data-path="look.layout"] [data-value="standard"]').click();
  await frame.locator('html[data-look="standard"]').waitFor();
  assert.strictEqual(await frame.locator('html').getAttribute('data-density'), 'comfortable');
  await page.locator('[data-path="device.kind"] [data-value="touch-pos"]').click();
  await page.locator('[data-path="look.style"] [data-value="friendly"]').click();
  await page.locator('#c-look\\.primaryColor').fill('#0a7d4b');
  await page.waitForTimeout(500);
  await frame.locator('html[data-density="touch"]').waitFor();
  assert.strictEqual(await frame.locator('html').getAttribute('data-shape'), 'pill' === 'pill' ? await frame.locator('html').getAttribute('data-shape') : '');
  await shot(page, '08-look-fixed');
  step('the look page shows the real program in the chosen machine layout, as a picture that follows each choice');
  await page.locator('[data-step="details"]').click();
  await page.locator('[data-tab="extras"]').click();
  // the AI assistant's own settings (who the model photos show, festivals, a second language) appear only when the customer gets the assistant, and stay neutral until typed
  assert.strictEqual(await page.locator('#ai-profile-holder').isHidden(), true, 'no AI settings before the assistant is ordered');
  await page.locator('label.switch', { hasText: 'A website' }).click();
  await page.locator('input[data-path="ecosystem.website.domain"]').fill('luzonfresh.example');
  await page.locator('label.switch', { hasText: 'An Android app' }).click();
  await page.locator('input[data-path="ecosystem.android.appId"]').fill('com.luzonfresh.shop');
  await page.locator('label.switch', { hasText: 'The AI assistant (Windows)' }).click();
  await page.locator('#ai-profile').waitFor();
  const said = async (id) => page.locator(`#ai-explain [data-line="${id}"]`).innerText();
  assert.strictEqual(await said('business'), 'Pictures and posters are made for a retail shop in Philippines.');
  assert.match(await said('model-1'), /No look is asked for/);
  assert.match(await said('festivals'), /No festival is named/);
  assert.strictEqual(await said('language'), 'Posters are in one language.');
  await page.locator('input[data-path="images.countryName"]').fill('the Philippines');
  await page.locator('input[data-path="images.models.1.title"]').fill('Visayan model');
  await page.locator('input[data-path="images.models.1.looks"]').fill('Visayan, in his forties');
  for (const f of ['Sinulog', 'Christmas', 'sinulog']) { await page.locator('#ai-festival-add').fill(f); await page.locator('#ai-festival-add').press('Enter'); }
  assert.strictEqual(await page.locator('#ai-festival-chips .chip').count(), 2, 'a repeat in other letters is one festival');
  await page.locator('#ai-language-offers [data-language="fil"]').click();
  assert.strictEqual(await page.locator('input[data-path="images.localLanguage.name"]').inputValue(), 'Filipino');
  assert.strictEqual(await page.locator('input[data-path="images.localLanguage.tag"]').inputValue(), 'fil');
  await page.locator('input[data-path="images.localLanguage.lines.clearance"]').fill('Malaking bawas');
  assert.strictEqual(await said('business'), 'Pictures and posters are made for a retail shop in the Philippines.');
  assert.match(await said('model-0'), /called "Model 1"\. No look is asked for/);
  assert.match(await said('model-1'), /called "Visayan model"\. The person looks like this: Visayan, in his forties\./);
  assert.match(await said('festivals'), /Sinulog, Christmas/);
  assert.match(await said('language'), /second line in Filipino \(fil\)\. Ready-made lines for: clearance\./);
  await shot(page, '09a-ai-profile');
  // a mistake is named next to the place it was typed, stays in front of the person, and is gone once it is taken out
  await page.locator('#ai-festival-add').fill('<b>Eid</b>'); await page.locator('#ai-festival-add').press('Enter');
  await page.locator('#save').click();
  await page.locator('.toast', { hasText: 'Saved' }).last().waitFor();
  await page.locator('[data-error-for="images.festivals"] .err', { hasText: 'cannot have' }).waitFor();
  assert.strictEqual(await page.locator('#ai-festival-chips .chip').count(), 3, 'the festival that cannot be used stays, with its problem');
  await page.locator('#ai-festival-chips button[aria-label="Take out <b>Eid</b>"]').click();
  await page.locator('#save').click();
  await page.locator('.toast', { hasText: 'Saved' }).last().waitFor();
  await page.locator('[data-error-for="images.festivals"] .err').waitFor({ state: 'detached' });
  assert.strictEqual(await page.locator('#ai-festival-chips .chip').count(), 2);
  step('the AI assistant\'s own settings appear when it is ordered, stay neutral until typed, explain live what they change, offer the country\'s languages, and a mistake is named where it was typed');
  await page.locator('[data-path="licence.whiteLabel"] [data-value="theme"]').click();
  await page.locator('#save').click();
  await page.locator('.toast', { hasText: 'Saved' }).last().waitFor();
  await page.locator('[data-step="look"]').click();
  await frame.locator('html[data-shape="pill"]').waitFor({ timeout: 10000 });
  let cssFrame = '';
  for (let i = 0; i < 40 && cssFrame !== 'rgb(10, 125, 75)'; i += 1) { cssFrame = await frame.locator('.btn.primary').first().evaluate((b) => getComputedStyle(b).backgroundColor).catch(() => ''); if (cssFrame !== 'rgb(10, 125, 75)') await page.waitForTimeout(250); }
  assert.strictEqual(cssFrame, 'rgb(10, 125, 75)', 'with a style licence the preview button is the chosen colour: ' + cssFrame);
  assert.strictEqual(await frame.locator('html').getAttribute('data-nav'), 'left');
  await shot(page, '09-look-theme');
  step('with a style licence the preview takes the customer\'s colour and shapes; with a fixed look it does not');
  const logoInput = page.locator('#logo-file');
  await logoInput.setInputFiles(join(root, 'logo.png'));
  await page.locator('#logo-box img').waitFor();
  step('a logo is added and shows');

  // prepare
  await page.locator('#next-action').click();
  await page.waitForURL(/\/prepare/);
  await page.locator('#make-proposal').click();
  await page.locator('#explain').waitFor();
  assert.match(await page.locator('#explain').innerText(), /Luzon Fresh Mart is set up as Retail store in Philippines/);
  await shot(page, '10-prepared');
  step('the setup is prepared from the details and explained in plain words');

  // AI
  await page.locator('[data-nav="settings"]').click();
  await page.locator('#ai-settings').waitFor();
  await page.waitForTimeout(300);
  await page.locator('[data-nav="customers"]').click();
  await page.getByRole('link', { name: /Luzon Fresh Mart/ }).click();
  step('(the salesperson can look at Settings but not change them)');
  assert.strictEqual(await page.locator('#ai-save').count(), 0);
  await page.locator('#signout').click();
  await signIn(page, 'Asha Admin', 'a-long-password');
  await page.locator('[data-nav="settings"]').click();
  await page.locator('#ai-settings').waitFor();
  await page.locator('[data-tool="claude-code"]').click();
  await page.locator('#model-select').waitFor();
  const modelOptions = await page.locator('#model-select option').allInnerTexts();
  assert.ok(modelOptions.some((t) => /Claude Opus 5\.5/.test(t)), 'the models are listed');
  assert.ok(modelOptions.some((t) => /Another model/.test(t)));
  await page.locator('#model-select').selectOption('claude-opus-5-5');
  const levels = await page.locator('#effort-seg button').allInnerTexts();
  assert.ok(levels.some((t) => /Extra high/.test(t)) && levels.some((t) => /Maximum/.test(t)) && levels.some((t) => /Low/.test(t)), 'every thinking level is offered: ' + levels.join(' | '));
  await page.locator('#effort-seg [data-effort="high"]').click();
  await page.locator('#model-select').selectOption('claude-haiku-4-5');
  assert.strictEqual(await page.locator('#effort-seg').count(), 0, 'a model with no thinking level shows none');
  await page.locator('#model-select').selectOption('claude-opus-5-5');
  await page.locator('#effort-seg [data-effort="medium"]').click();
  await shot(page, '11-settings-ai');
  await page.locator('#ai-save').click();
  await page.locator('.toast', { hasText: 'Saved' }).last().waitFor();
  await page.locator('details:has(summary:has-text("Version and updates")) summary').click();
  await page.locator('#health-claude-code dl.kv, #health-claude-code .notice').first().waitFor({ timeout: 30000 });
  step('the administrator chooses an AI tool, sees every model and every thinking level, and can look at the tool\'s version and updates');
  await page.locator('#signout').click();
  await signIn(page, 'Sam Sales', 'sam-long-password');
  await page.goto(studio.url.replace(/\?k=.*/, '') + '#/customers/luzon-fresh-mart/prepare');
  await page.locator('#ai-run').waitFor();
  await page.locator('#ai-card summary', { hasText: 'Show exactly what would be sent' }).click();
  await page.locator('#sent-box', { hasText: 'Stays on this PC' }).waitFor();
  assert.ok(!(await page.locator('#sent-box').innerText()).includes('help@luzonfresh'));
  await page.locator('#ai-run').click();
  await page.locator('#ai-changes').waitFor({ timeout: 30000 });
  assert.match(await page.locator('#ai-changes').innerText(), /Suki|gcash|Words at the bottom of a bill/);
  assert.match(await page.locator('#ai-explanation').innerText(), /Local words and wallets/);
  await shot(page, '12-ai-changes');
  await page.locator('#ai-accept').click();
  await page.locator('#explain').waitFor();
  step('the AI tool is asked, its answer is checked and shown as a list of changes, and kept only when the salesperson accepts');

  // review
  await page.locator('#next-action').click();
  await page.waitForURL(/\/review/);
  await page.locator('#checklist').waitFor();
  await shot(page, '13-review');
  await page.locator('#submit').click();
  await page.locator('.toast', { hasText: 'Sent for approval' }).last().waitFor();
  await page.waitForLoadState();
  await page.locator('.notice', { hasText: 'Waiting for a reviewer' }).waitFor();
  assert.strictEqual(await page.locator('#approve').count(), 0, 'a salesperson cannot approve');
  step('the salesperson sends it for approval, and has no way to approve it');
  await page.locator('#signout').click();

  // approval
  await signIn(page, 'Rita Reviewer', 'rita-long-password');
  await page.goto(studio.url.replace(/\?k=.*/, '') + '#/customers/luzon-fresh-mart/review');
  await page.locator('#approve').waitFor();
  await page.locator('#reject').click();
  await page.locator('#reject-reason').fill('Please add the second payment way');
  await page.locator('#reject-yes').click();
  await page.locator('.toast', { hasText: 'Sent back' }).last().waitFor();
  step('the reviewer can send it back with a note');
  await page.locator('#signout').click();
  await signIn(page, 'Sam Sales', 'sam-long-password');
  await page.goto(studio.url.replace(/\?k=.*/, '') + '#/customers/luzon-fresh-mart/prepare');
  await page.locator('#rejection').waitFor();
  assert.match(await page.locator('#rejection').innerText(), /Please add the second payment way/);
  await page.goto(studio.url.replace(/\?k=.*/, '') + '#/customers/luzon-fresh-mart/review');
  await page.locator('#submit').click();
  await page.locator('.notice', { hasText: 'Waiting for a reviewer' }).waitFor();
  await page.locator('#signout').click();
  await signIn(page, 'Rita Reviewer', 'rita-long-password');
  await page.goto(studio.url.replace(/\?k=.*/, '') + '#/customers/luzon-fresh-mart/review');
  await page.locator('#approve').click();
  await page.locator('#approve-yes').click();
  await page.locator('.toast', { hasText: 'Approved' }).last().waitFor();
  await page.locator('#releases').waitFor();
  assert.match(await page.locator('#approved-by').innerText(), /Rita Reviewer/);
  const [download] = await Promise.all([page.waitForEvent('download'), page.locator('[data-download="1"]').click()]);
  assert.match(download.suggestedFilename(), /luzon-fresh-mart-profile-1\.zip/);
  await shot(page, '14-approved');
  step('the reviewer approves it as a second person; the approved release has a fingerprint and its setup files can be downloaded');

  // the website and the app: an administrator connects the build service, a salesperson sees what would be sent, a reviewer starts the build and watches it
  const siteUrl = studio.url.replace(/\?k=.*/, '') + '#/customers/luzon-fresh-mart/site';
  await page.goto(siteUrl);
  await page.locator('#site-step').waitFor();
  await page.locator('#site-not-connected').waitFor();
  assert.strictEqual(await page.locator('#site-build').isDisabled(), true, 'no build before the build service is connected');
  await page.locator('#site-parts [data-part="website-linux"][data-state="missing"]').waitFor();
  await page.locator('#site-parts [data-part="android"][data-state="missing"]').waitFor();
  await shot(page, '14f-site-not-connected');
  await page.locator('#signout').click();
  await signIn(page, 'Sam Sales', 'sam-long-password');
  await page.goto(siteUrl);
  await page.locator('#site-role-note').waitFor();
  assert.strictEqual(await page.locator('#site-build').isDisabled(), true, 'a salesperson cannot start a build');
  await page.locator('#site-sent summary', { hasText: 'brand.json' }).click();
  assert.match(await page.locator('#site-sent').innerText(), /Luzon Fresh Mart/);
  await page.locator('#site-sent summary', { hasText: 'website-settings.env' }).click();
  assert.match(await page.locator('#site-sent').innerText(), /NEXT_PUBLIC_SITE_URL=https:\/\/luzonfresh\.example/);
  assert.doesNotMatch(await page.locator('#site-sent').innerText(), /AIza|sk-[a-z]|PRIVATE KEY|postgres:/, 'nothing that looks like a key is sent');
  await shot(page, '14g-site-salesperson');
  step('the website and app step shows a salesperson what is to be made and exactly what would be sent (public details only), and does not let them start a build');
  await page.locator('#signout').click();
  await signIn(page, 'Asha Admin', 'a-long-password');
  await page.goto(studio.url.replace(/\?k=.*/, '') + '#/settings');
  await page.locator('#build-settings').waitFor();
  await page.locator('#build-source').fill(github.source);
  await page.locator('#build-results').fill(github.source);
  await page.locator('#build-save').click();
  await page.locator('.toast.bad', { hasText: 'different place' }).last().waitFor();
  await page.locator('#build-results').fill(github.results);
  await page.locator('#build-save').click();
  await page.locator('.toast', { hasText: 'Saved' }).last().waitFor();
  await page.locator('#code-start').fill('wrong-access-code-for-the-test-0000');
  await page.locator('[data-save-code="start"]').click();
  await page.locator('.toast', { hasText: 'Access code saved' }).last().waitFor();
  await page.locator('#code-results').fill(github.tokens.results);
  await page.locator('[data-save-code="results"]').click();
  await page.locator('#build-connected .notice.ok').waitFor();
  await page.locator('#build-test').click();
  await page.locator('#build-test-summary.warn').waitFor();
  assert.match(await page.locator('[data-check="start-code"]').innerText(), /did not accept the access code for starting builds/);
  assert.doesNotMatch(await page.locator('#build-settings').innerText(), /wrong-access-code-for-the-test|test-results-access-code/, 'a code is never shown again');
  await shot(page, '14h-settings-build-wrong-code');
  await page.locator('#code-start').fill(github.tokens.start);
  await page.locator('[data-save-code="start"]').click();
  await page.locator('.toast', { hasText: 'Access code saved' }).last().waitFor();
  await page.locator('#build-test').click();
  await page.locator('#build-test-summary.ok').waitFor();
  assert.strictEqual(await page.locator('#build-test-result [data-check]').count(), 9);
  assert.strictEqual(await page.locator('#build-test-result [data-ok="false"]').count(), 0);
  await shot(page, '14i-settings-build-connected');
  step('an administrator connects the build service: a wrong access code is explained in plain words, a right one passes every check, and a code is never shown again');
  await page.locator('#signout').click();
  await signIn(page, 'Rita Reviewer', 'rita-long-password');
  await page.goto(siteUrl);
  await page.locator('#site-step').waitFor();
  assert.strictEqual(await page.locator('#site-build').isDisabled(), false);
  github.options.holdPublish = true;
  await page.locator('#site-build').click();
  await page.locator('#site-current').waitFor();
  await page.locator('#site-steps li', { hasText: 'Building the website for Linux' }).waitFor({ timeout: 15000 });
  await page.locator('#site-steps li', { hasText: 'Building the Android app' }).waitFor();
  assert.match(await page.locator('#site-state').innerText(), /Going on/);
  assert.match(await page.locator('#site-current').innerText(), /Build 1/);
  assert.strictEqual(await page.locator('#site-build').isDisabled(), true, 'one build at a time');
  await shot(page, '14j-site-building');
  github.options.holdPublish = false;
  await page.locator('#site-ready').waitFor({ timeout: 30000 });
  assert.match(await page.locator('#site-state').innerText(), /Finished/);
  assert.strictEqual(await page.locator('#site-steps li[data-step-state="done"]').count() >= 8, true);
  assert.strictEqual(await page.locator('#site-parts [data-state="built"]').count(), 3);
  await shot(page, '14k-site-done');
  step('a reviewer starts the build, sees each step in plain words while it goes on, and is told when the website and the app are ready');
  await page.locator('#site-to-installer').click();
  await page.waitForURL(/\/installer/);
  const phoneSite = await newPage(420, 860);
  await signIn(phoneSite, 'Rita Reviewer', 'rita-long-password');
  await phoneSite.goto(siteUrl);
  await phoneSite.locator('#site-current').waitFor();
  assert.strictEqual(await phoneSite.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1), true, 'the step fits a narrow window without sideways scrolling');
  await shot(phoneSite, '14l-site-narrow');
  step('the step fits a narrow window too');

  // the installer: an administrator tells the Studio where the released programs are; a reviewer makes the customer's pack
  const programs = join(root, 'programs'); mkdirSync(programs);
  writeFileSync(join(programs, 'SmartRetailPOS-Hub-Setup-1.4.0.exe'), Buffer.alloc(20000, 5));
  writeFileSync(join(programs, 'smart-retail-pos-hub_1.4.0-1_amd64.deb'), Buffer.alloc(12000, 6));
  writeFileSync(join(programs, 'SmartRetailAI-Setup.exe'), Buffer.alloc(9000, 7));
  writeFileSync(join(programs, 'base-kit.json'), JSON.stringify((await makeBaseKit(programs)).manifest));
  await page.goto(studio.url.replace(/\?k=.*/, '') + '#/customers/luzon-fresh-mart/installer');
  await page.locator('#programs-card').waitFor();
  await page.locator('#programs-card .notice', { hasText: 'Ask an administrator' }).waitFor();
  assert.strictEqual(await page.locator('#make-pack').isDisabled(), true, 'no pack without the programs');
  await shot(page, '14b-installer-no-programs');
  await page.locator('#signout').click();
  await signIn(page, 'Asha Admin', 'a-long-password');
  await page.goto(studio.url.replace(/\?k=.*/, '') + '#/settings');
  await page.locator('#programs-settings').waitFor();
  await page.locator('#programs-folder').fill(join(root, 'nowhere'));
  await page.locator('#programs-save').click();
  await page.locator('#programs-say .notice.warn', { hasText: 'not found' }).waitFor();
  await page.locator('#programs-folder').fill(programs);
  await page.locator('#programs-save').click();
  await page.locator('#programs-say .notice.ok', { hasText: 'Version 1.4.0: 3 files checked' }).waitFor();
  await shot(page, '14c-settings-programs');
  await page.locator('#signout').click();
  await signIn(page, 'Rita Reviewer', 'rita-long-password');
  await page.goto(studio.url.replace(/\?k=.*/, '') + '#/customers/luzon-fresh-mart/installer');
  await page.locator('#programs-ok').waitFor();
  await page.locator('#pack-items [data-part="shop-pc"][data-status="ready"]').waitFor();
  await page.locator('#pack-items [data-part="ai"][data-status="ready"]').waitFor();
  await page.locator('#pack-items [data-part="website"][data-status="ready"]').waitFor();
  await page.locator('#pack-items [data-part="android"][data-status="ready"]').waitFor();
  await shot(page, '14d-installer-ready');
  await page.locator('#make-pack').click();
  await page.locator('.toast', { hasText: 'The pack is made' }).last().waitFor({ timeout: 60000 });
  await page.locator('#packs').waitFor();
  await page.locator('#last-pack').waitFor();
  const [packDownload] = await Promise.all([page.waitForEvent('download'), page.locator('[data-download-pack="1"]').click()]);
  assert.match(packDownload.suggestedFilename(), /^luzon-fresh-mart-pack-release-1\.zip$/);
  const packPath = join(root, 'downloaded-pack.zip');
  await packDownload.saveAs(packPath);
  const inPack = listZip(readFileSync(packPath));
  for (const want of ['Luzon Fresh Mart/START HERE.html', 'Luzon Fresh Mart/1 - Shop PC (Windows)/SmartRetailPOS-Hub-Setup-1.4.0.exe', 'Luzon Fresh Mart/1 - Shop PC (Windows)/profile/setup.json', 'Luzon Fresh Mart/1 - Shop PC (Windows)/profile/install.ini', 'Luzon Fresh Mart/2 - AI assistant (Windows)/SmartRetailAI-Setup.exe', 'Luzon Fresh Mart/2 - AI assistant (Windows)/profile/ai.json', 'Luzon Fresh Mart/3 - Website/website-luzon-fresh-mart-linux.zip', 'Luzon Fresh Mart/3 - Website/website-luzon-fresh-mart-windows.zip', 'Luzon Fresh Mart/4 - Android app/SmartRetailPOS-luzon-fresh-mart-1.0.1.apk']) assert.ok(inPack.includes(want), want + ' is in the pack');
  await shot(page, '14e-pack-made');
  step('an administrator chooses the programs folder (a wrong folder is explained); a reviewer sees what goes in the pack, makes it, and downloads the zip with the setup and the customer\'s profile beside it');

  // hand over
  await page.goto(studio.url.replace(/\?k=.*/, '') + '#/customers/luzon-fresh-mart/handover');
  await page.locator('#handover-sheet').waitFor();
  assert.match(await page.locator('#handover-sheet').innerText(), /Luzon Fresh Mart: your Smart Retail POS/);
  assert.match(await page.locator('#handover-sheet').innerText(), /Their own colours and logo/);
  assert.match(await page.locator('#handover-sheet').innerText(), /1 - Shop PC \(Windows\)/, 'the sheet names the pack\'s folder');
  assert.match(await page.locator('#handover-sheet').innerText(), /2 - AI assistant \(Windows\)/, 'and the AI assistant\'s folder');
  await shot(page, '15-handover');
  await page.locator('#deliver-note').fill('Given to the owner, Ana.');
  await page.locator('#deliver').click();
  await page.locator('#delivered-note').waitFor();
  step('the hand-over sheet is made and the hand-over is recorded');

  // activity, narrow window
  await page.locator('[data-nav="activity"]').click();
  await page.locator('#integrity').waitFor();
  assert.match(await page.locator('#integrity').innerText(), /none changed/);
  await shot(page, '16-activity');
  const phone = await newPage(420, 860);
  await phone.goto(studio.url);
  await phone.locator('[data-person="Sam Sales"]').waitFor();
  await shot(phone, '17-narrow-signin');
  step('every action is in the activity record, which proves itself unchanged; the screens fit a narrow window too');

  assert.deepStrictEqual(problems, [], 'the browser saw problems');
  console.log('\nThe Setup Studio works the way its people use it.');
} catch (e) {
  console.error(e);
  console.error('problems seen by the browser:', problems);
  process.exitCode = 1;
} finally {
  process.env.PATH = oldPath;
  await browser.close();
  await studio.close();
  await github.close();
  rmSync(root, { recursive: true, force: true });
}
