Namespace BillPoint
	' Token: 0x020000C5 RID: 197
		Public Partial Class frmCustomerSupportForm_Dashboard
		Inherits Global.System.Windows.Forms.Form

		' Token: 0x06001FBB RID: 8123 RVA: 0x001497A0 File Offset: 0x001479A0
		<Global.System.Diagnostics.DebuggerNonUserCode()>
		Protected Overrides Sub Dispose(disposing As Boolean)
			Try
				Dim flag As Boolean = disposing AndAlso Me.components IsNot Nothing
				If flag Then
					Me.components.Dispose()
				End If
			Finally
				MyBase.Dispose(disposing)
			End Try
		End Sub

		' Token: 0x06001FBC RID: 8124 RVA: 0x001497F0 File Offset: 0x001479F0
		<Global.System.Diagnostics.DebuggerStepThrough()>
		Private Sub InitializeComponent()
			Dim dataGridViewCellStyle As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle2 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle3 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim componentResourceManager As Global.System.ComponentModel.ComponentResourceManager = New Global.System.ComponentModel.ComponentResourceManager(GetType(Global.BillPoint.frmCustomerSupportForm_Dashboard))
			Dim dataGridViewCellStyle4 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle5 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle6 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle7 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle8 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle9 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle10 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle11 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle12 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle13 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle14 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle15 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle16 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle17 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle18 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle19 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle20 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle21 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle22 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle23 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle24 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle25 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle26 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle27 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle28 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle29 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle30 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle31 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle32 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle33 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle34 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle35 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle36 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle37 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle38 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle39 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle40 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle41 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle42 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle43 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle44 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle45 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle46 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle47 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle48 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle49 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle50 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle51 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle52 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle53 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle54 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle55 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle56 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle57 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle58 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Me.DataGridView1 = New Global.System.Windows.Forms.DataGridView()
			Me.Column1 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column2 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column3 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column4 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column5 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column6 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column7 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column8 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column9 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column10 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column11 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column12 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column13 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column15 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column14 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column16 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column17 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.btnJoin = New Global.System.Windows.Forms.DataGridViewButtonColumn()
			Me.btnFollow = New Global.System.Windows.Forms.DataGridViewButtonColumn()
			Me.Panel3 = New Global.System.Windows.Forms.Panel()
			Me.txtTokenNo = New Global.System.Windows.Forms.TextBox()
			Me.Label3 = New Global.System.Windows.Forms.Label()
			Me.Panel6 = New Global.System.Windows.Forms.Panel()
			Me.rdo_Closed = New Global.System.Windows.Forms.RadioButton()
			Me.rdo_Process = New Global.System.Windows.Forms.RadioButton()
			Me.rdo_Open = New Global.System.Windows.Forms.RadioButton()
			Me.Label4 = New Global.System.Windows.Forms.Label()
			Me.GroupBox2 = New Global.System.Windows.Forms.GroupBox()
			Me.btnGetData = New Global.GelButtons.GelButton()
			Me.dtpDateTo = New Global.System.Windows.Forms.DateTimePicker()
			Me.Label2 = New Global.System.Windows.Forms.Label()
			Me.Label1 = New Global.System.Windows.Forms.Label()
			Me.dtpDateFrom = New Global.System.Windows.Forms.DateTimePicker()
			Me.btnShowAll = New Global.GelButtons.GelButton()
			Me.Panel1 = New Global.System.Windows.Forms.Panel()
			Me.btnOffline_Online = New Global.GelButtons.GelButton()
			Me.Panel4 = New Global.System.Windows.Forms.Panel()
			Me.txtMobile = New Global.System.Windows.Forms.TextBox()
			Me.Label7 = New Global.System.Windows.Forms.Label()
			Me.lblUserType = New Global.System.Windows.Forms.Label()
			Me.btnRefresh = New Global.GelButtons.GelButton()
			Me.lblUser = New Global.System.Windows.Forms.Label()
			Me.Panel7 = New Global.System.Windows.Forms.Panel()
			Me.Label18 = New Global.System.Windows.Forms.Label()
			Me.Label21 = New Global.System.Windows.Forms.Label()
			Me.txtTopResult = New Global.System.Windows.Forms.TextBox()
			Me.Label5 = New Global.System.Windows.Forms.Label()
			Me.Panel2 = New Global.System.Windows.Forms.Panel()
			Me.pnl_FollowUp = New Global.System.Windows.Forms.Panel()
			Me.GroupBox3 = New Global.System.Windows.Forms.GroupBox()
			Me.lnkPanle_CLose = New Global.System.Windows.Forms.LinkLabel()
			Me.Label8 = New Global.System.Windows.Forms.Label()
			Me.DataGridView3 = New Global.System.Windows.Forms.DataGridView()
			Me.DataGridViewTextBoxColumn8 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn9 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn13 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn14 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn16 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn17 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn18 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn19 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn20 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn21 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn22 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn23 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn24 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column18 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column19 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn25 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column21 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column22 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column23 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column24 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column25 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column26 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn26 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn27 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn28 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn29 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column27 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column28 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column29 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column30 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column31 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column32 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column33 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column34 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column35 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column36 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column37 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column38 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column39 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column40 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column41 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column42 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column43 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column44 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column45 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column46 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column47 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn30 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column49 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.GelButton1 = New Global.GelButtons.GelButton()
			Me.GroupBox4 = New Global.System.Windows.Forms.GroupBox()
			Me.dgw = New Global.System.Windows.Forms.DataGridView()
			Me.DataGridViewTextBoxColumn31 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn32 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn33 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn34 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn35 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn36 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn37 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn38 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn39 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn40 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn41 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn42 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn43 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn44 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn45 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column20 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn46 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn47 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn48 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn49 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn50 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn51 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn52 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn53 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn54 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn55 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn56 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn57 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn58 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn59 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn60 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn61 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn62 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn63 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn64 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn65 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn66 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn67 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn68 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn69 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn70 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn71 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn72 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn73 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn74 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn75 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridView2 = New Global.System.Windows.Forms.DataGridView()
			Me.DataGridViewTextBoxColumn1 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn2 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn7 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn5 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn6 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn3 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn4 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn10 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn15 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn11 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn12 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.GroupBox1 = New Global.System.Windows.Forms.GroupBox()
			Me.lbl_CustomerID = New Global.System.Windows.Forms.Label()
			Me.lblCurrentIssue = New Global.System.Windows.Forms.Label()
			Me.lblNumbers = New Global.System.Windows.Forms.Label()
			Me.lblCount = New Global.System.Windows.Forms.Label()
			Me.lbl_tokenid = New Global.System.Windows.Forms.Label()
			Me.btnClosed = New Global.GelButtons.GelButton()
			Me.lbl_Id = New Global.System.Windows.Forms.Label()
			Me.btnTokenUpdate = New Global.GelButtons.GelButton()
			Me.txtRemarks = New Global.System.Windows.Forms.TextBox()
			Me.Label6 = New Global.System.Windows.Forms.Label()
			Me.lblTokenNo = New Global.System.Windows.Forms.Label()
			CType(Me.DataGridView1, Global.System.ComponentModel.ISupportInitialize).BeginInit()
			Me.Panel3.SuspendLayout()
			Me.Panel6.SuspendLayout()
			Me.GroupBox2.SuspendLayout()
			Me.Panel1.SuspendLayout()
			Me.Panel4.SuspendLayout()
			Me.Panel7.SuspendLayout()
			Me.Panel2.SuspendLayout()
			Me.pnl_FollowUp.SuspendLayout()
			Me.GroupBox3.SuspendLayout()
			CType(Me.DataGridView3, Global.System.ComponentModel.ISupportInitialize).BeginInit()
			Me.GroupBox4.SuspendLayout()
			CType(Me.dgw, Global.System.ComponentModel.ISupportInitialize).BeginInit()
			CType(Me.DataGridView2, Global.System.ComponentModel.ISupportInitialize).BeginInit()
			Me.GroupBox1.SuspendLayout()
			MyBase.SuspendLayout()
			Me.DataGridView1.AllowUserToAddRows = False
			Me.DataGridView1.AllowUserToDeleteRows = False
			Me.DataGridView1.BackgroundColor = Global.System.Drawing.Color.White
			Me.DataGridView1.ColumnHeadersBorderStyle = Global.System.Windows.Forms.DataGridViewHeaderBorderStyle.[Single]
			dataGridViewCellStyle.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft
			dataGridViewCellStyle.BackColor = Global.System.Drawing.SystemColors.Control
			dataGridViewCellStyle.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 8.25F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			dataGridViewCellStyle.ForeColor = Global.System.Drawing.SystemColors.WindowText
			dataGridViewCellStyle.SelectionBackColor = Global.System.Drawing.SystemColors.Highlight
			dataGridViewCellStyle.SelectionForeColor = Global.System.Drawing.SystemColors.HighlightText
			dataGridViewCellStyle.WrapMode = Global.System.Windows.Forms.DataGridViewTriState.[True]
			Me.DataGridView1.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle
			Me.DataGridView1.ColumnHeadersHeight = 30
			Me.DataGridView1.Columns.AddRange(New Global.System.Windows.Forms.DataGridViewColumn() { Me.Column1, Me.Column2, Me.Column3, Me.Column4, Me.Column5, Me.Column6, Me.Column7, Me.Column8, Me.Column9, Me.Column10, Me.Column11, Me.Column12, Me.Column13, Me.Column15, Me.Column14, Me.Column16, Me.Column17, Me.btnJoin, Me.btnFollow })
			Me.DataGridView1.Cursor = Global.System.Windows.Forms.Cursors.Hand
			dataGridViewCellStyle2.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft
			dataGridViewCellStyle2.BackColor = Global.System.Drawing.SystemColors.Window
			dataGridViewCellStyle2.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 8.25F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			dataGridViewCellStyle2.ForeColor = Global.System.Drawing.SystemColors.ControlText
			dataGridViewCellStyle2.SelectionBackColor = Global.System.Drawing.SystemColors.Highlight
			dataGridViewCellStyle2.SelectionForeColor = Global.System.Drawing.SystemColors.HighlightText
			dataGridViewCellStyle2.WrapMode = Global.System.Windows.Forms.DataGridViewTriState.[False]
			Me.DataGridView1.DefaultCellStyle = dataGridViewCellStyle2
			Me.DataGridView1.Dock = Global.System.Windows.Forms.DockStyle.Fill
			Me.DataGridView1.EnableHeadersVisualStyles = False
			Me.DataGridView1.GridColor = Global.System.Drawing.Color.White
			Me.DataGridView1.Location = New Global.System.Drawing.Point(0, 0)
			Me.DataGridView1.MultiSelect = False
			Me.DataGridView1.Name = "DataGridView1"
			Me.DataGridView1.[ReadOnly] = True
			dataGridViewCellStyle3.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft
			dataGridViewCellStyle3.BackColor = Global.System.Drawing.SystemColors.Control
			dataGridViewCellStyle3.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 8.25F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			dataGridViewCellStyle3.ForeColor = Global.System.Drawing.SystemColors.WindowText
			dataGridViewCellStyle3.SelectionBackColor = Global.System.Drawing.SystemColors.Highlight
			dataGridViewCellStyle3.SelectionForeColor = Global.System.Drawing.SystemColors.HighlightText
			dataGridViewCellStyle3.WrapMode = Global.System.Windows.Forms.DataGridViewTriState.[True]
			Me.DataGridView1.RowHeadersDefaultCellStyle = dataGridViewCellStyle3
			Me.DataGridView1.SelectionMode = Global.System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect
			Me.DataGridView1.Size = New Global.System.Drawing.Size(1803, 573)
			Me.DataGridView1.TabIndex = 0
			Me.Column1.HeaderText = "LogID"
			Me.Column1.Name = "Column1"
			Me.Column1.[ReadOnly] = True
			Me.Column1.Visible = False
			Me.Column2.HeaderText = "support_token_no"
			Me.Column2.Name = "Column2"
			Me.Column2.[ReadOnly] = True
			Me.Column3.HeaderText = "Date"
			Me.Column3.Name = "Column3"
			Me.Column3.[ReadOnly] = True
			Me.Column4.HeaderText = "CurrentIssue"
			Me.Column4.Name = "Column4"
			Me.Column4.[ReadOnly] = True
			Me.Column5.HeaderText = "CustomerName"
			Me.Column5.Name = "Column5"
			Me.Column5.[ReadOnly] = True
			Me.Column6.HeaderText = "Registered Mobile"
			Me.Column6.Name = "Column6"
			Me.Column6.[ReadOnly] = True
			Me.Column7.HeaderText = "Software Name"
			Me.Column7.Name = "Column7"
			Me.Column7.[ReadOnly] = True
			Me.Column7.Visible = False
			Me.Column8.HeaderText = "SoftwareValidity"
			Me.Column8.Name = "Column8"
			Me.Column8.[ReadOnly] = True
			Me.Column8.Visible = False
			Me.Column9.HeaderText = "Status"
			Me.Column9.Name = "Column9"
			Me.Column9.[ReadOnly] = True
			Me.Column10.HeaderText = "Remarks"
			Me.Column10.Name = "Column10"
			Me.Column10.[ReadOnly] = True
			Me.Column11.HeaderText = "Feedback"
			Me.Column11.Name = "Column11"
			Me.Column11.[ReadOnly] = True
			Me.Column12.HeaderText = "Rating"
			Me.Column12.Name = "Column12"
			Me.Column12.[ReadOnly] = True
			Me.Column13.HeaderText = "Join_date"
			Me.Column13.Name = "Column13"
			Me.Column13.[ReadOnly] = True
			Me.Column13.Visible = False
			Me.Column15.HeaderText = "Join_user"
			Me.Column15.Name = "Column15"
			Me.Column15.[ReadOnly] = True
			Me.Column14.HeaderText = "Close_date"
			Me.Column14.Name = "Column14"
			Me.Column14.[ReadOnly] = True
			Me.Column16.HeaderText = "Postpone_Days"
			Me.Column16.Name = "Column16"
			Me.Column16.[ReadOnly] = True
			Me.Column17.HeaderText = "Calling Number"
			Me.Column17.Name = "Column17"
			Me.Column17.[ReadOnly] = True
			Me.Column17.Visible = False
			Me.btnJoin.HeaderText = "Join"
			Me.btnJoin.Name = "btnJoin"
			Me.btnJoin.[ReadOnly] = True
			Me.btnJoin.Resizable = Global.System.Windows.Forms.DataGridViewTriState.[True]
			Me.btnJoin.SortMode = Global.System.Windows.Forms.DataGridViewColumnSortMode.Automatic
			Me.btnJoin.Text = "Join"
			Me.btnJoin.UseColumnTextForButtonValue = True
			Me.btnJoin.Visible = False
			Me.btnFollow.HeaderText = "Follow"
			Me.btnFollow.Name = "btnFollow"
			Me.btnFollow.[ReadOnly] = True
			Me.btnFollow.Text = "Follow"
			Me.btnFollow.UseColumnTextForButtonValue = True
			Me.Panel3.BorderStyle = Global.System.Windows.Forms.BorderStyle.FixedSingle
			Me.Panel3.Controls.Add(Me.txtTokenNo)
			Me.Panel3.Controls.Add(Me.Label3)
			Me.Panel3.Location = New Global.System.Drawing.Point(22, 12)
			Me.Panel3.Name = "Panel3"
			Me.Panel3.Size = New Global.System.Drawing.Size(206, 70)
			Me.Panel3.TabIndex = 518
			Me.txtTokenNo.BackColor = Global.System.Drawing.Color.White
			Me.txtTokenNo.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 9F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			Me.txtTokenNo.Location = New Global.System.Drawing.Point(13, 30)
			Me.txtTokenNo.Name = "txtTokenNo"
			Me.txtTokenNo.Size = New Global.System.Drawing.Size(183, 21)
			Me.txtTokenNo.TabIndex = 13
			Me.Label3.AutoSize = True
			Me.Label3.Location = New Global.System.Drawing.Point(10, 10)
			Me.Label3.Name = "Label3"
			Me.Label3.Size = New Global.System.Drawing.Size(116, 13)
			Me.Label3.TabIndex = 12
			Me.Label3.Text = "Search By Token No. :"
			Me.Panel6.BorderStyle = Global.System.Windows.Forms.BorderStyle.FixedSingle
			Me.Panel6.Controls.Add(Me.rdo_Closed)
			Me.Panel6.Controls.Add(Me.rdo_Process)
			Me.Panel6.Controls.Add(Me.rdo_Open)
			Me.Panel6.Controls.Add(Me.Label4)
			Me.Panel6.Location = New Global.System.Drawing.Point(228, 12)
			Me.Panel6.Name = "Panel6"
			Me.Panel6.Size = New Global.System.Drawing.Size(206, 70)
			Me.Panel6.TabIndex = 519
			Me.rdo_Closed.AutoSize = True
			Me.rdo_Closed.Location = New Global.System.Drawing.Point(134, 33)
			Me.rdo_Closed.Name = "rdo_Closed"
			Me.rdo_Closed.Size = New Global.System.Drawing.Size(57, 17)
			Me.rdo_Closed.TabIndex = 15
			Me.rdo_Closed.TabStop = True
			Me.rdo_Closed.Text = "Closed"
			Me.rdo_Closed.UseVisualStyleBackColor = True
			Me.rdo_Process.AutoSize = True
			Me.rdo_Process.Location = New Global.System.Drawing.Point(66, 33)
			Me.rdo_Process.Name = "rdo_Process"
			Me.rdo_Process.Size = New Global.System.Drawing.Size(63, 17)
			Me.rdo_Process.TabIndex = 14
			Me.rdo_Process.TabStop = True
			Me.rdo_Process.Text = "Process"
			Me.rdo_Process.UseVisualStyleBackColor = True
			Me.rdo_Open.AutoSize = True
			Me.rdo_Open.Location = New Global.System.Drawing.Point(9, 33)
			Me.rdo_Open.Name = "rdo_Open"
			Me.rdo_Open.Size = New Global.System.Drawing.Size(51, 17)
			Me.rdo_Open.TabIndex = 13
			Me.rdo_Open.TabStop = True
			Me.rdo_Open.Text = "Open"
			Me.rdo_Open.UseVisualStyleBackColor = True
			Me.Label4.AutoSize = True
			Me.Label4.Location = New Global.System.Drawing.Point(10, 10)
			Me.Label4.Name = "Label4"
			Me.Label4.Size = New Global.System.Drawing.Size(95, 13)
			Me.Label4.TabIndex = 12
			Me.Label4.Text = "Search By Status :"
			Me.GroupBox2.Controls.Add(Me.btnGetData)
			Me.GroupBox2.Controls.Add(Me.dtpDateTo)
			Me.GroupBox2.Controls.Add(Me.Label2)
			Me.GroupBox2.Controls.Add(Me.Label1)
			Me.GroupBox2.Controls.Add(Me.dtpDateFrom)
			Me.GroupBox2.Location = New Global.System.Drawing.Point(440, 12)
			Me.GroupBox2.Name = "GroupBox2"
			Me.GroupBox2.Size = New Global.System.Drawing.Size(337, 70)
			Me.GroupBox2.TabIndex = 520
			Me.GroupBox2.TabStop = False
			Me.GroupBox2.Text = "Search by Date"
			Me.btnGetData.Anchor = Global.System.Windows.Forms.AnchorStyles.Top Or Global.System.Windows.Forms.AnchorStyles.Right
			Me.btnGetData.BackColor = Global.System.Drawing.Color.MediumVioletRed
			Me.btnGetData.FlatAppearance.BorderSize = 0
			Me.btnGetData.FlatStyle = Global.System.Windows.Forms.FlatStyle.Flat
			Me.btnGetData.Font = New Global.System.Drawing.Font("Segoe UI Semibold", 12F, Global.System.Drawing.FontStyle.Bold, Global.System.Drawing.GraphicsUnit.Point, 0)
			Me.btnGetData.ForeColor = Global.System.Drawing.Color.White
			Me.btnGetData.GradientBottom = Global.System.Drawing.Color.FromArgb(45, 63, 83)
			Me.btnGetData.GradientTop = Global.System.Drawing.Color.RoyalBlue
			Me.btnGetData.Image = CType(componentResourceManager.GetObject("btnGetData.Image"), Global.System.Drawing.Image)
			Me.btnGetData.ImageAlign = Global.System.Drawing.ContentAlignment.MiddleLeft
			Me.btnGetData.Location = New Global.System.Drawing.Point(256, 30)
			Me.btnGetData.Name = "btnGetData"
			Me.btnGetData.Size = New Global.System.Drawing.Size(74, 30)
			Me.btnGetData.TabIndex = 516
			Me.btnGetData.Text = "Get Data"
			Me.btnGetData.TextAlign = Global.System.Drawing.ContentAlignment.MiddleRight
			Me.btnGetData.UseVisualStyleBackColor = False
			Me.dtpDateTo.CustomFormat = "dd/MM/yyyy"
			Me.dtpDateTo.Format = Global.System.Windows.Forms.DateTimePickerFormat.Custom
			Me.dtpDateTo.Location = New Global.System.Drawing.Point(131, 39)
			Me.dtpDateTo.Name = "dtpDateTo"
			Me.dtpDateTo.Size = New Global.System.Drawing.Size(119, 20)
			Me.dtpDateTo.TabIndex = 1
			Me.Label2.AutoSize = True
			Me.Label2.Location = New Global.System.Drawing.Point(128, 20)
			Me.Label2.Name = "Label2"
			Me.Label2.Size = New Global.System.Drawing.Size(26, 13)
			Me.Label2.TabIndex = 13
			Me.Label2.Text = "To :"
			Me.Label1.AutoSize = True
			Me.Label1.Location = New Global.System.Drawing.Point(3, 20)
			Me.Label1.Name = "Label1"
			Me.Label1.Size = New Global.System.Drawing.Size(36, 13)
			Me.Label1.TabIndex = 12
			Me.Label1.Text = "From :"
			Me.dtpDateFrom.CustomFormat = "dd/MM/yyyy"
			Me.dtpDateFrom.Format = Global.System.Windows.Forms.DateTimePickerFormat.Custom
			Me.dtpDateFrom.Location = New Global.System.Drawing.Point(6, 39)
			Me.dtpDateFrom.Name = "dtpDateFrom"
			Me.dtpDateFrom.Size = New Global.System.Drawing.Size(119, 20)
			Me.dtpDateFrom.TabIndex = 0
			Me.btnShowAll.Anchor = Global.System.Windows.Forms.AnchorStyles.Top Or Global.System.Windows.Forms.AnchorStyles.Right
			Me.btnShowAll.BackColor = Global.System.Drawing.Color.MediumVioletRed
			Me.btnShowAll.FlatAppearance.BorderSize = 0
			Me.btnShowAll.FlatStyle = Global.System.Windows.Forms.FlatStyle.Flat
			Me.btnShowAll.Font = New Global.System.Drawing.Font("Segoe UI Semibold", 12F, Global.System.Drawing.FontStyle.Bold, Global.System.Drawing.GraphicsUnit.Point, 0)
			Me.btnShowAll.ForeColor = Global.System.Drawing.Color.White
			Me.btnShowAll.GradientBottom = Global.System.Drawing.Color.LimeGreen
			Me.btnShowAll.GradientTop = Global.System.Drawing.Color.FromArgb(255, 128, 128)
			Me.btnShowAll.Image = CType(componentResourceManager.GetObject("btnShowAll.Image"), Global.System.Drawing.Image)
			Me.btnShowAll.ImageAlign = Global.System.Drawing.ContentAlignment.MiddleLeft
			Me.btnShowAll.Location = New Global.System.Drawing.Point(1294, 51)
			Me.btnShowAll.Name = "btnShowAll"
			Me.btnShowAll.Size = New Global.System.Drawing.Size(177, 31)
			Me.btnShowAll.TabIndex = 517
			Me.btnShowAll.Text = "Show All"
			Me.btnShowAll.TextAlign = Global.System.Drawing.ContentAlignment.MiddleRight
			Me.btnShowAll.UseVisualStyleBackColor = False
			Me.Panel1.BackColor = Global.System.Drawing.Color.FromArgb(255, 224, 192)
			Me.Panel1.Controls.Add(Me.btnOffline_Online)
			Me.Panel1.Controls.Add(Me.Panel4)
			Me.Panel1.Controls.Add(Me.lblUserType)
			Me.Panel1.Controls.Add(Me.btnRefresh)
			Me.Panel1.Controls.Add(Me.lblUser)
			Me.Panel1.Controls.Add(Me.Panel7)
			Me.Panel1.Controls.Add(Me.Label5)
			Me.Panel1.Controls.Add(Me.Panel6)
			Me.Panel1.Controls.Add(Me.btnShowAll)
			Me.Panel1.Controls.Add(Me.GroupBox2)
			Me.Panel1.Controls.Add(Me.Panel3)
			Me.Panel1.Dock = Global.System.Windows.Forms.DockStyle.Top
			Me.Panel1.Location = New Global.System.Drawing.Point(0, 0)
			Me.Panel1.Name = "Panel1"
			Me.Panel1.Size = New Global.System.Drawing.Size(1803, 100)
			Me.Panel1.TabIndex = 521
			Me.btnOffline_Online.Anchor = Global.System.Windows.Forms.AnchorStyles.Top Or Global.System.Windows.Forms.AnchorStyles.Right
			Me.btnOffline_Online.BackColor = Global.System.Drawing.Color.MediumVioletRed
			Me.btnOffline_Online.FlatAppearance.BorderSize = 0
			Me.btnOffline_Online.FlatStyle = Global.System.Windows.Forms.FlatStyle.Flat
			Me.btnOffline_Online.Font = New Global.System.Drawing.Font("Segoe UI Semibold", 12F, Global.System.Drawing.FontStyle.Bold, Global.System.Drawing.GraphicsUnit.Point, 0)
			Me.btnOffline_Online.ForeColor = Global.System.Drawing.Color.White
			Me.btnOffline_Online.GradientBottom = Global.System.Drawing.Color.FromArgb(0, 0, 192)
			Me.btnOffline_Online.GradientTop = Global.System.Drawing.Color.FromArgb(255, 128, 128)
			Me.btnOffline_Online.Image = CType(componentResourceManager.GetObject("btnOffline_Online.Image"), Global.System.Drawing.Image)
			Me.btnOffline_Online.ImageAlign = Global.System.Drawing.ContentAlignment.MiddleLeft
			Me.btnOffline_Online.Location = New Global.System.Drawing.Point(1477, 51)
			Me.btnOffline_Online.Name = "btnOffline_Online"
			Me.btnOffline_Online.Size = New Global.System.Drawing.Size(254, 31)
			Me.btnOffline_Online.TabIndex = 1863
			Me.btnOffline_Online.Text = "Generate Support Token"
			Me.btnOffline_Online.TextAlign = Global.System.Drawing.ContentAlignment.MiddleRight
			Me.btnOffline_Online.UseVisualStyleBackColor = False
			Me.Panel4.BorderStyle = Global.System.Windows.Forms.BorderStyle.FixedSingle
			Me.Panel4.Controls.Add(Me.txtMobile)
			Me.Panel4.Controls.Add(Me.Label7)
			Me.Panel4.Location = New Global.System.Drawing.Point(783, 13)
			Me.Panel4.Name = "Panel4"
			Me.Panel4.Size = New Global.System.Drawing.Size(206, 70)
			Me.Panel4.TabIndex = 519
			Me.txtMobile.BackColor = Global.System.Drawing.Color.White
			Me.txtMobile.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 9F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			Me.txtMobile.Location = New Global.System.Drawing.Point(13, 30)
			Me.txtMobile.Name = "txtMobile"
			Me.txtMobile.Size = New Global.System.Drawing.Size(183, 21)
			Me.txtMobile.TabIndex = 13
			Me.Label7.AutoSize = True
			Me.Label7.Location = New Global.System.Drawing.Point(10, 10)
			Me.Label7.Name = "Label7"
			Me.Label7.Size = New Global.System.Drawing.Size(116, 13)
			Me.Label7.TabIndex = 12
			Me.Label7.Text = "Search By Mobile No. :"
			Me.lblUserType.AutoSize = True
			Me.lblUserType.Location = New Global.System.Drawing.Point(1013, 16)
			Me.lblUserType.Name = "lblUserType"
			Me.lblUserType.Size = New Global.System.Drawing.Size(63, 13)
			Me.lblUserType.TabIndex = 1862
			Me.lblUserType.Text = "lblUserType"
			Me.lblUserType.Visible = False
			Me.btnRefresh.Anchor = Global.System.Windows.Forms.AnchorStyles.Top Or Global.System.Windows.Forms.AnchorStyles.Right
			Me.btnRefresh.BackColor = Global.System.Drawing.Color.MediumVioletRed
			Me.btnRefresh.FlatAppearance.BorderSize = 0
			Me.btnRefresh.FlatStyle = Global.System.Windows.Forms.FlatStyle.Flat
			Me.btnRefresh.Font = New Global.System.Drawing.Font("Segoe UI Semibold", 12F, Global.System.Drawing.FontStyle.Bold, Global.System.Drawing.GraphicsUnit.Point, 0)
			Me.btnRefresh.ForeColor = Global.System.Drawing.Color.White
			Me.btnRefresh.GradientBottom = Global.System.Drawing.Color.LimeGreen
			Me.btnRefresh.GradientTop = Global.System.Drawing.Color.FromArgb(255, 128, 128)
			Me.btnRefresh.Image = CType(componentResourceManager.GetObject("btnRefresh.Image"), Global.System.Drawing.Image)
			Me.btnRefresh.ImageAlign = Global.System.Drawing.ContentAlignment.MiddleLeft
			Me.btnRefresh.Location = New Global.System.Drawing.Point(1294, 14)
			Me.btnRefresh.Name = "btnRefresh"
			Me.btnRefresh.Size = New Global.System.Drawing.Size(89, 33)
			Me.btnRefresh.TabIndex = 516
			Me.btnRefresh.Text = "Refresh"
			Me.btnRefresh.TextAlign = Global.System.Drawing.ContentAlignment.MiddleRight
			Me.btnRefresh.UseVisualStyleBackColor = False
			Me.btnRefresh.Visible = False
			Me.lblUser.AutoSize = True
			Me.lblUser.Location = New Global.System.Drawing.Point(1101, 16)
			Me.lblUser.Name = "lblUser"
			Me.lblUser.Size = New Global.System.Drawing.Size(39, 13)
			Me.lblUser.TabIndex = 1861
			Me.lblUser.Text = "lblUser"
			Me.lblUser.Visible = False
			Me.Panel7.BackColor = Global.System.Drawing.Color.FromArgb(229, 233, 219)
			Me.Panel7.Controls.Add(Me.Label18)
			Me.Panel7.Controls.Add(Me.Label21)
			Me.Panel7.Controls.Add(Me.txtTopResult)
			Me.Panel7.Location = New Global.System.Drawing.Point(991, 36)
			Me.Panel7.Name = "Panel7"
			Me.Panel7.Size = New Global.System.Drawing.Size(242, 47)
			Me.Panel7.TabIndex = 1824
			Me.Label18.Font = New Global.System.Drawing.Font("Microsoft Tai Le", 15F, Global.System.Drawing.FontStyle.Bold)
			Me.Label18.ForeColor = Global.System.Drawing.Color.FromArgb(64, 64, 0)
			Me.Label18.Location = New Global.System.Drawing.Point(131, 10)
			Me.Label18.Name = "Label18"
			Me.Label18.Size = New Global.System.Drawing.Size(107, 30)
			Me.Label18.TabIndex = 1806
			Me.Label18.Text = "RECORDS"
			Me.Label18.TextAlign = Global.System.Drawing.ContentAlignment.MiddleCenter
			Me.Label21.Font = New Global.System.Drawing.Font("Microsoft Tai Le", 15F, Global.System.Drawing.FontStyle.Bold)
			Me.Label21.ForeColor = Global.System.Drawing.Color.FromArgb(64, 64, 0)
			Me.Label21.Location = New Global.System.Drawing.Point(13, 10)
			Me.Label21.Name = "Label21"
			Me.Label21.Size = New Global.System.Drawing.Size(64, 30)
			Me.Label21.TabIndex = 51
			Me.Label21.Text = "TOP :"
			Me.Label21.TextAlign = Global.System.Drawing.ContentAlignment.MiddleCenter
			Me.txtTopResult.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 12F)
			Me.txtTopResult.Location = New Global.System.Drawing.Point(76, 10)
			Me.txtTopResult.Name = "txtTopResult"
			Me.txtTopResult.Size = New Global.System.Drawing.Size(53, 26)
			Me.txtTopResult.TabIndex = 433
			Me.txtTopResult.TabStop = False
			Me.txtTopResult.Text = "15"
			Me.txtTopResult.TextAlign = Global.System.Windows.Forms.HorizontalAlignment.Center
			Me.Label5.Anchor = Global.System.Windows.Forms.AnchorStyles.Top Or Global.System.Windows.Forms.AnchorStyles.Right
			Me.Label5.BackColor = Global.System.Drawing.Color.RoyalBlue
			Me.Label5.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 15.75F, Global.System.Drawing.FontStyle.Bold, Global.System.Drawing.GraphicsUnit.Point, 0)
			Me.Label5.ForeColor = Global.System.Drawing.Color.White
			Me.Label5.Location = New Global.System.Drawing.Point(1389, 3)
			Me.Label5.Name = "Label5"
			Me.Label5.Size = New Global.System.Drawing.Size(411, 33)
			Me.Label5.TabIndex = 521
			Me.Label5.Text = "Customer Support Form- Dashboard"
			Me.Label5.TextAlign = Global.System.Drawing.ContentAlignment.MiddleCenter
			Me.Panel2.BackColor = Global.System.Drawing.Color.FromArgb(255, 255, 192)
			Me.Panel2.Controls.Add(Me.pnl_FollowUp)
			Me.Panel2.Controls.Add(Me.DataGridView1)
			Me.Panel2.Dock = Global.System.Windows.Forms.DockStyle.Fill
			Me.Panel2.Location = New Global.System.Drawing.Point(0, 100)
			Me.Panel2.Name = "Panel2"
			Me.Panel2.Size = New Global.System.Drawing.Size(1803, 573)
			Me.Panel2.TabIndex = 522
			Me.pnl_FollowUp.Anchor = Global.System.Windows.Forms.AnchorStyles.Bottom Or Global.System.Windows.Forms.AnchorStyles.Right
			Me.pnl_FollowUp.Controls.Add(Me.GroupBox3)
			Me.pnl_FollowUp.Controls.Add(Me.DataGridView2)
			Me.pnl_FollowUp.Controls.Add(Me.GroupBox1)
			Me.pnl_FollowUp.Location = New Global.System.Drawing.Point(261, 166)
			Me.pnl_FollowUp.Name = "pnl_FollowUp"
			Me.pnl_FollowUp.Size = New Global.System.Drawing.Size(1325, 379)
			Me.pnl_FollowUp.TabIndex = 1
			Me.pnl_FollowUp.Visible = False
			Me.GroupBox3.Controls.Add(Me.lnkPanle_CLose)
			Me.GroupBox3.Controls.Add(Me.Label8)
			Me.GroupBox3.Controls.Add(Me.DataGridView3)
			Me.GroupBox3.Controls.Add(Me.GelButton1)
			Me.GroupBox3.Controls.Add(Me.GroupBox4)
			Me.GroupBox3.Location = New Global.System.Drawing.Point(730, 6)
			Me.GroupBox3.Name = "GroupBox3"
			Me.GroupBox3.Size = New Global.System.Drawing.Size(592, 370)
			Me.GroupBox3.TabIndex = 525
			Me.GroupBox3.TabStop = False
			Me.GroupBox3.Text = "Quotation List:"
			Me.lnkPanle_CLose.AutoSize = True
			Me.lnkPanle_CLose.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 13F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			Me.lnkPanle_CLose.LinkColor = Global.System.Drawing.Color.Red
			Me.lnkPanle_CLose.Location = New Global.System.Drawing.Point(564, 11)
			Me.lnkPanle_CLose.Name = "lnkPanle_CLose"
			Me.lnkPanle_CLose.Size = New Global.System.Drawing.Size(22, 22)
			Me.lnkPanle_CLose.TabIndex = 524
			Me.lnkPanle_CLose.TabStop = True
			Me.lnkPanle_CLose.Text = "X"
			Me.Label8.Anchor = Global.System.Windows.Forms.AnchorStyles.Top Or Global.System.Windows.Forms.AnchorStyles.Left Or Global.System.Windows.Forms.AnchorStyles.Right
			Me.Label8.BackColor = Global.System.Drawing.Color.RoyalBlue
			Me.Label8.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 14.25F, Global.System.Drawing.FontStyle.Bold, Global.System.Drawing.GraphicsUnit.Point, 0)
			Me.Label8.ForeColor = Global.System.Drawing.Color.White
			Me.Label8.Location = New Global.System.Drawing.Point(7, 16)
			Me.Label8.Name = "Label8"
			Me.Label8.Size = New Global.System.Drawing.Size(396, 26)
			Me.Label8.TabIndex = 1752
			Me.Label8.Text = "List of Quotations"
			Me.Label8.TextAlign = Global.System.Drawing.ContentAlignment.MiddleCenter
			Me.DataGridView3.AllowUserToAddRows = False
			Me.DataGridView3.AllowUserToDeleteRows = False
			dataGridViewCellStyle4.BackColor = Global.System.Drawing.Color.FloralWhite
			Me.DataGridView3.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle4
			Me.DataGridView3.Anchor = Global.System.Windows.Forms.AnchorStyles.Top Or Global.System.Windows.Forms.AnchorStyles.Bottom Or Global.System.Windows.Forms.AnchorStyles.Left Or Global.System.Windows.Forms.AnchorStyles.Right
			Me.DataGridView3.BackgroundColor = Global.System.Drawing.Color.White
			Me.DataGridView3.ColumnHeadersBorderStyle = Global.System.Windows.Forms.DataGridViewHeaderBorderStyle.[Single]
			dataGridViewCellStyle5.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter
			dataGridViewCellStyle5.BackColor = Global.System.Drawing.Color.DarkViolet
			dataGridViewCellStyle5.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 8.25F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			dataGridViewCellStyle5.ForeColor = Global.System.Drawing.Color.White
			dataGridViewCellStyle5.SelectionBackColor = Global.System.Drawing.Color.LightSteelBlue
			dataGridViewCellStyle5.SelectionForeColor = Global.System.Drawing.SystemColors.HighlightText
			dataGridViewCellStyle5.WrapMode = Global.System.Windows.Forms.DataGridViewTriState.[True]
			Me.DataGridView3.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle5
			Me.DataGridView3.ColumnHeadersHeight = 30
			Me.DataGridView3.Columns.AddRange(New Global.System.Windows.Forms.DataGridViewColumn() { Me.DataGridViewTextBoxColumn8, Me.DataGridViewTextBoxColumn9, Me.DataGridViewTextBoxColumn13, Me.DataGridViewTextBoxColumn14, Me.DataGridViewTextBoxColumn16, Me.DataGridViewTextBoxColumn17, Me.DataGridViewTextBoxColumn18, Me.DataGridViewTextBoxColumn19, Me.DataGridViewTextBoxColumn20, Me.DataGridViewTextBoxColumn21, Me.DataGridViewTextBoxColumn22, Me.DataGridViewTextBoxColumn23, Me.DataGridViewTextBoxColumn24, Me.Column18, Me.Column19, Me.DataGridViewTextBoxColumn25, Me.Column21, Me.Column22, Me.Column23, Me.Column24, Me.Column25, Me.Column26, Me.DataGridViewTextBoxColumn26, Me.DataGridViewTextBoxColumn27, Me.DataGridViewTextBoxColumn28, Me.DataGridViewTextBoxColumn29, Me.Column27, Me.Column28, Me.Column29, Me.Column30, Me.Column31, Me.Column32, Me.Column33, Me.Column34, Me.Column35, Me.Column36, Me.Column37, Me.Column38, Me.Column39, Me.Column40, Me.Column41, Me.Column42, Me.Column43, Me.Column44, Me.Column45, Me.Column46, Me.Column47, Me.DataGridViewTextBoxColumn30, Me.Column49 })
			Me.DataGridView3.Cursor = Global.System.Windows.Forms.Cursors.Hand
			dataGridViewCellStyle6.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft
			dataGridViewCellStyle6.BackColor = Global.System.Drawing.SystemColors.Window
			dataGridViewCellStyle6.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 8.25F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			dataGridViewCellStyle6.ForeColor = Global.System.Drawing.SystemColors.ControlText
			dataGridViewCellStyle6.SelectionBackColor = Global.System.Drawing.SystemColors.Highlight
			dataGridViewCellStyle6.SelectionForeColor = Global.System.Drawing.SystemColors.HighlightText
			dataGridViewCellStyle6.WrapMode = Global.System.Windows.Forms.DataGridViewTriState.[False]
			Me.DataGridView3.DefaultCellStyle = dataGridViewCellStyle6
			Me.DataGridView3.EnableHeadersVisualStyles = False
			Me.DataGridView3.GridColor = Global.System.Drawing.Color.White
			Me.DataGridView3.Location = New Global.System.Drawing.Point(6, 46)
			Me.DataGridView3.MultiSelect = False
			Me.DataGridView3.Name = "DataGridView3"
			Me.DataGridView3.[ReadOnly] = True
			Me.DataGridView3.RowHeadersBorderStyle = Global.System.Windows.Forms.DataGridViewHeaderBorderStyle.[Single]
			dataGridViewCellStyle7.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft
			dataGridViewCellStyle7.BackColor = Global.System.Drawing.Color.DarkViolet
			dataGridViewCellStyle7.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 8.25F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			dataGridViewCellStyle7.ForeColor = Global.System.Drawing.Color.White
			dataGridViewCellStyle7.SelectionBackColor = Global.System.Drawing.Color.OrangeRed
			dataGridViewCellStyle7.SelectionForeColor = Global.System.Drawing.Color.White
			dataGridViewCellStyle7.WrapMode = Global.System.Windows.Forms.DataGridViewTriState.[True]
			Me.DataGridView3.RowHeadersDefaultCellStyle = dataGridViewCellStyle7
			Me.DataGridView3.RowHeadersWidth = 25
			Me.DataGridView3.RowHeadersWidthSizeMode = Global.System.Windows.Forms.DataGridViewRowHeadersWidthSizeMode.DisableResizing
			dataGridViewCellStyle8.BackColor = Global.System.Drawing.Color.White
			dataGridViewCellStyle8.Font = New Global.System.Drawing.Font("Tahoma", 8.25F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			dataGridViewCellStyle8.SelectionBackColor = Global.System.Drawing.Color.DarkSlateGray
			dataGridViewCellStyle8.SelectionForeColor = Global.System.Drawing.Color.White
			Me.DataGridView3.RowsDefaultCellStyle = dataGridViewCellStyle8
			Me.DataGridView3.RowTemplate.Height = 25
			Me.DataGridView3.RowTemplate.Resizable = Global.System.Windows.Forms.DataGridViewTriState.[False]
			Me.DataGridView3.SelectionMode = Global.System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect
			Me.DataGridView3.Size = New Global.System.Drawing.Size(580, 148)
			Me.DataGridView3.TabIndex = 1751
			Me.DataGridView3.TabStop = False
			Me.DataGridViewTextBoxColumn8.HeaderText = "Quotation ID"
			Me.DataGridViewTextBoxColumn8.Name = "DataGridViewTextBoxColumn8"
			Me.DataGridViewTextBoxColumn8.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn8.Visible = False
			Me.DataGridViewTextBoxColumn9.HeaderText = "Quotation No."
			Me.DataGridViewTextBoxColumn9.Name = "DataGridViewTextBoxColumn9"
			Me.DataGridViewTextBoxColumn9.[ReadOnly] = True
			dataGridViewCellStyle9.Format = "dd/MM/yyyy"
			Me.DataGridViewTextBoxColumn13.DefaultCellStyle = dataGridViewCellStyle9
			Me.DataGridViewTextBoxColumn13.HeaderText = "Quotation Date"
			Me.DataGridViewTextBoxColumn13.Name = "DataGridViewTextBoxColumn13"
			Me.DataGridViewTextBoxColumn13.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn14.HeaderText = "Tax Type"
			Me.DataGridViewTextBoxColumn14.Name = "DataGridViewTextBoxColumn14"
			Me.DataGridViewTextBoxColumn14.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn16.HeaderText = "CID"
			Me.DataGridViewTextBoxColumn16.Name = "DataGridViewTextBoxColumn16"
			Me.DataGridViewTextBoxColumn16.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn16.Visible = False
			Me.DataGridViewTextBoxColumn17.HeaderText = "Customer ID"
			Me.DataGridViewTextBoxColumn17.Name = "DataGridViewTextBoxColumn17"
			Me.DataGridViewTextBoxColumn17.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn18.HeaderText = "Customer Name"
			Me.DataGridViewTextBoxColumn18.Name = "DataGridViewTextBoxColumn18"
			Me.DataGridViewTextBoxColumn18.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn19.HeaderText = "Contact No."
			Me.DataGridViewTextBoxColumn19.Name = "DataGridViewTextBoxColumn19"
			Me.DataGridViewTextBoxColumn19.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn20.HeaderText = "State"
			Me.DataGridViewTextBoxColumn20.Name = "DataGridViewTextBoxColumn20"
			Me.DataGridViewTextBoxColumn20.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn21.HeaderText = "GSTIN"
			Me.DataGridViewTextBoxColumn21.Name = "DataGridViewTextBoxColumn21"
			Me.DataGridViewTextBoxColumn21.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn22.HeaderText = "SM_ID"
			Me.DataGridViewTextBoxColumn22.Name = "DataGridViewTextBoxColumn22"
			Me.DataGridViewTextBoxColumn22.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn22.Visible = False
			Me.DataGridViewTextBoxColumn23.HeaderText = "Salesman ID"
			Me.DataGridViewTextBoxColumn23.Name = "DataGridViewTextBoxColumn23"
			Me.DataGridViewTextBoxColumn23.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn24.HeaderText = "Salesman"
			Me.DataGridViewTextBoxColumn24.Name = "DataGridViewTextBoxColumn24"
			Me.DataGridViewTextBoxColumn24.[ReadOnly] = True
			dataGridViewCellStyle10.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.Column18.DefaultCellStyle = dataGridViewCellStyle10
			Me.Column18.HeaderText = "(Taxable + Tax) Amt"
			Me.Column18.Name = "Column18"
			Me.Column18.[ReadOnly] = True
			dataGridViewCellStyle11.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.Column19.DefaultCellStyle = dataGridViewCellStyle11
			Me.Column19.HeaderText = "CGST"
			Me.Column19.Name = "Column19"
			Me.Column19.[ReadOnly] = True
			dataGridViewCellStyle12.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn25.DefaultCellStyle = dataGridViewCellStyle12
			Me.DataGridViewTextBoxColumn25.HeaderText = "SGST/UTGST"
			Me.DataGridViewTextBoxColumn25.Name = "DataGridViewTextBoxColumn25"
			Me.DataGridViewTextBoxColumn25.[ReadOnly] = True
			dataGridViewCellStyle13.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.Column21.DefaultCellStyle = dataGridViewCellStyle13
			Me.Column21.HeaderText = "IGST"
			Me.Column21.Name = "Column21"
			Me.Column21.[ReadOnly] = True
			dataGridViewCellStyle14.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.Column22.DefaultCellStyle = dataGridViewCellStyle14
			Me.Column22.HeaderText = "CESS"
			Me.Column22.Name = "Column22"
			Me.Column22.[ReadOnly] = True
			dataGridViewCellStyle15.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.Column23.DefaultCellStyle = dataGridViewCellStyle15
			Me.Column23.HeaderText = "Bill Sundry Charges"
			Me.Column23.Name = "Column23"
			Me.Column23.[ReadOnly] = True
			dataGridViewCellStyle16.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.Column24.DefaultCellStyle = dataGridViewCellStyle16
			Me.Column24.HeaderText = "Total Bill Discount"
			Me.Column24.Name = "Column24"
			Me.Column24.[ReadOnly] = True
			dataGridViewCellStyle17.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.Column25.DefaultCellStyle = dataGridViewCellStyle17
			Me.Column25.HeaderText = "Total"
			Me.Column25.Name = "Column25"
			Me.Column25.[ReadOnly] = True
			dataGridViewCellStyle18.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.Column26.DefaultCellStyle = dataGridViewCellStyle18
			Me.Column26.HeaderText = "Round Off"
			Me.Column26.Name = "Column26"
			Me.Column26.[ReadOnly] = True
			dataGridViewCellStyle19.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn26.DefaultCellStyle = dataGridViewCellStyle19
			Me.DataGridViewTextBoxColumn26.HeaderText = "Grand Total"
			Me.DataGridViewTextBoxColumn26.Name = "DataGridViewTextBoxColumn26"
			Me.DataGridViewTextBoxColumn26.[ReadOnly] = True
			dataGridViewCellStyle20.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn27.DefaultCellStyle = dataGridViewCellStyle20
			Me.DataGridViewTextBoxColumn27.HeaderText = "Total Payment"
			Me.DataGridViewTextBoxColumn27.Name = "DataGridViewTextBoxColumn27"
			Me.DataGridViewTextBoxColumn27.[ReadOnly] = True
			dataGridViewCellStyle21.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn28.DefaultCellStyle = dataGridViewCellStyle21
			Me.DataGridViewTextBoxColumn28.HeaderText = "Payment Due"
			Me.DataGridViewTextBoxColumn28.Name = "DataGridViewTextBoxColumn28"
			Me.DataGridViewTextBoxColumn28.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn29.HeaderText = "Transport Details"
			Me.DataGridViewTextBoxColumn29.Name = "DataGridViewTextBoxColumn29"
			Me.DataGridViewTextBoxColumn29.[ReadOnly] = True
			Me.Column27.HeaderText = "Narration"
			Me.Column27.Name = "Column27"
			Me.Column27.[ReadOnly] = True
			Me.Column28.HeaderText = "E-Way No"
			Me.Column28.Name = "Column28"
			Me.Column28.[ReadOnly] = True
			Me.Column29.HeaderText = "Till ID"
			Me.Column29.Name = "Column29"
			Me.Column29.[ReadOnly] = True
			Me.Column30.HeaderText = "Operator"
			Me.Column30.Name = "Column30"
			Me.Column30.[ReadOnly] = True
			Me.Column31.HeaderText = "Bill Sundy Type"
			Me.Column31.Name = "Column31"
			Me.Column31.[ReadOnly] = True
			dataGridViewCellStyle22.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.Column32.DefaultCellStyle = dataGridViewCellStyle22
			Me.Column32.HeaderText = "Offer Discount"
			Me.Column32.Name = "Column32"
			Me.Column32.[ReadOnly] = True
			dataGridViewCellStyle23.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.Column33.DefaultCellStyle = dataGridViewCellStyle23
			Me.Column33.HeaderText = "Loyalty Discount"
			Me.Column33.Name = "Column33"
			Me.Column33.[ReadOnly] = True
			dataGridViewCellStyle24.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.Column34.DefaultCellStyle = dataGridViewCellStyle24
			Me.Column34.HeaderText = "Writeoff Bill Discount"
			Me.Column34.Name = "Column34"
			Me.Column34.[ReadOnly] = True
			Me.Column35.HeaderText = "Customer City"
			Me.Column35.Name = "Column35"
			Me.Column35.[ReadOnly] = True
			dataGridViewCellStyle25.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			dataGridViewCellStyle25.Format = "N2"
			Me.Column36.DefaultCellStyle = dataGridViewCellStyle25
			Me.Column36.HeaderText = "Cash Tendered"
			Me.Column36.Name = "Column36"
			Me.Column36.[ReadOnly] = True
			dataGridViewCellStyle26.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			dataGridViewCellStyle26.Format = "N2"
			Me.Column37.DefaultCellStyle = dataGridViewCellStyle26
			Me.Column37.HeaderText = "Cash Refund"
			Me.Column37.Name = "Column37"
			Me.Column37.[ReadOnly] = True
			dataGridViewCellStyle27.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			dataGridViewCellStyle27.Format = "N2"
			Me.Column38.DefaultCellStyle = dataGridViewCellStyle27
			Me.Column38.HeaderText = "Bill Cash Amt"
			Me.Column38.Name = "Column38"
			Me.Column38.[ReadOnly] = True
			dataGridViewCellStyle28.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			dataGridViewCellStyle28.Format = "N2"
			Me.Column39.DefaultCellStyle = dataGridViewCellStyle28
			Me.Column39.HeaderText = "Coupon Discount"
			Me.Column39.Name = "Column39"
			Me.Column39.[ReadOnly] = True
			dataGridViewCellStyle29.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			dataGridViewCellStyle29.Format = "N2"
			Me.Column40.DefaultCellStyle = dataGridViewCellStyle29
			Me.Column40.HeaderText = "Gift Discount"
			Me.Column40.Name = "Column40"
			Me.Column40.[ReadOnly] = True
			Me.Column41.HeaderText = "Cus Address"
			Me.Column41.Name = "Column41"
			Me.Column41.[ReadOnly] = True
			Me.Column42.HeaderText = "ReturnNo"
			Me.Column42.Name = "Column42"
			Me.Column42.[ReadOnly] = True
			Me.Column43.HeaderText = "ByReturn"
			Me.Column43.Name = "Column43"
			Me.Column43.[ReadOnly] = True
			Me.Column44.HeaderText = "Loyality Points"
			Me.Column44.Name = "Column44"
			Me.Column44.[ReadOnly] = True
			Me.Column45.HeaderText = "Loyality Reedem Points"
			Me.Column45.Name = "Column45"
			Me.Column45.[ReadOnly] = True
			Me.Column46.HeaderText = "Loyality Reedem Amt"
			Me.Column46.Name = "Column46"
			Me.Column46.[ReadOnly] = True
			Me.Column47.HeaderText = "Status"
			Me.Column47.Name = "Column47"
			Me.Column47.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn30.HeaderText = "Bill_Invoice_Id"
			Me.DataGridViewTextBoxColumn30.Name = "DataGridViewTextBoxColumn30"
			Me.DataGridViewTextBoxColumn30.[ReadOnly] = True
			Me.Column49.HeaderText = "Lead_Id"
			Me.Column49.Name = "Column49"
			Me.Column49.[ReadOnly] = True
			Me.GelButton1.Anchor = Global.System.Windows.Forms.AnchorStyles.Top Or Global.System.Windows.Forms.AnchorStyles.Right
			Me.GelButton1.BackColor = Global.System.Drawing.Color.MediumVioletRed
			Me.GelButton1.FlatAppearance.BorderSize = 0
			Me.GelButton1.FlatStyle = Global.System.Windows.Forms.FlatStyle.Flat
			Me.GelButton1.Font = New Global.System.Drawing.Font("Segoe UI Semibold", 12F, Global.System.Drawing.FontStyle.Bold, Global.System.Drawing.GraphicsUnit.Point, 0)
			Me.GelButton1.ForeColor = Global.System.Drawing.Color.White
			Me.GelButton1.GradientBottom = Global.System.Drawing.Color.FromArgb(45, 63, 83)
			Me.GelButton1.GradientTop = Global.System.Drawing.Color.RoyalBlue
			Me.GelButton1.Image = CType(componentResourceManager.GetObject("GelButton1.Image"), Global.System.Drawing.Image)
			Me.GelButton1.ImageAlign = Global.System.Drawing.ContentAlignment.MiddleLeft
			Me.GelButton1.Location = New Global.System.Drawing.Point(409, 14)
			Me.GelButton1.Name = "GelButton1"
			Me.GelButton1.Size = New Global.System.Drawing.Size(129, 30)
			Me.GelButton1.TabIndex = 527
			Me.GelButton1.Text = "New Quotation"
			Me.GelButton1.TextAlign = Global.System.Drawing.ContentAlignment.MiddleRight
			Me.GelButton1.UseVisualStyleBackColor = False
			Me.GroupBox4.Controls.Add(Me.dgw)
			Me.GroupBox4.Location = New Global.System.Drawing.Point(6, 200)
			Me.GroupBox4.Name = "GroupBox4"
			Me.GroupBox4.Size = New Global.System.Drawing.Size(580, 161)
			Me.GroupBox4.TabIndex = 526
			Me.GroupBox4.TabStop = False
			Me.GroupBox4.Text = "Bill List:"
			Me.dgw.AllowUserToAddRows = False
			Me.dgw.AllowUserToDeleteRows = False
			dataGridViewCellStyle30.BackColor = Global.System.Drawing.Color.FloralWhite
			Me.dgw.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle30
			Me.dgw.Anchor = Global.System.Windows.Forms.AnchorStyles.Top Or Global.System.Windows.Forms.AnchorStyles.Bottom Or Global.System.Windows.Forms.AnchorStyles.Left Or Global.System.Windows.Forms.AnchorStyles.Right
			Me.dgw.BackgroundColor = Global.System.Drawing.Color.White
			Me.dgw.ColumnHeadersBorderStyle = Global.System.Windows.Forms.DataGridViewHeaderBorderStyle.[Single]
			dataGridViewCellStyle31.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter
			dataGridViewCellStyle31.BackColor = Global.System.Drawing.Color.DarkViolet
			dataGridViewCellStyle31.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 8.25F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			dataGridViewCellStyle31.ForeColor = Global.System.Drawing.Color.White
			dataGridViewCellStyle31.SelectionBackColor = Global.System.Drawing.Color.LightSteelBlue
			dataGridViewCellStyle31.SelectionForeColor = Global.System.Drawing.SystemColors.HighlightText
			dataGridViewCellStyle31.WrapMode = Global.System.Windows.Forms.DataGridViewTriState.[True]
			Me.dgw.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle31
			Me.dgw.ColumnHeadersHeight = 30
			Me.dgw.Columns.AddRange(New Global.System.Windows.Forms.DataGridViewColumn() { Me.DataGridViewTextBoxColumn31, Me.DataGridViewTextBoxColumn32, Me.DataGridViewTextBoxColumn33, Me.DataGridViewTextBoxColumn34, Me.DataGridViewTextBoxColumn35, Me.DataGridViewTextBoxColumn36, Me.DataGridViewTextBoxColumn37, Me.DataGridViewTextBoxColumn38, Me.DataGridViewTextBoxColumn39, Me.DataGridViewTextBoxColumn40, Me.DataGridViewTextBoxColumn41, Me.DataGridViewTextBoxColumn42, Me.DataGridViewTextBoxColumn43, Me.DataGridViewTextBoxColumn44, Me.DataGridViewTextBoxColumn45, Me.Column20, Me.DataGridViewTextBoxColumn46, Me.DataGridViewTextBoxColumn47, Me.DataGridViewTextBoxColumn48, Me.DataGridViewTextBoxColumn49, Me.DataGridViewTextBoxColumn50, Me.DataGridViewTextBoxColumn51, Me.DataGridViewTextBoxColumn52, Me.DataGridViewTextBoxColumn53, Me.DataGridViewTextBoxColumn54, Me.DataGridViewTextBoxColumn55, Me.DataGridViewTextBoxColumn56, Me.DataGridViewTextBoxColumn57, Me.DataGridViewTextBoxColumn58, Me.DataGridViewTextBoxColumn59, Me.DataGridViewTextBoxColumn60, Me.DataGridViewTextBoxColumn61, Me.DataGridViewTextBoxColumn62, Me.DataGridViewTextBoxColumn63, Me.DataGridViewTextBoxColumn64, Me.DataGridViewTextBoxColumn65, Me.DataGridViewTextBoxColumn66, Me.DataGridViewTextBoxColumn67, Me.DataGridViewTextBoxColumn68, Me.DataGridViewTextBoxColumn69, Me.DataGridViewTextBoxColumn70, Me.DataGridViewTextBoxColumn71, Me.DataGridViewTextBoxColumn72, Me.DataGridViewTextBoxColumn73, Me.DataGridViewTextBoxColumn74, Me.DataGridViewTextBoxColumn75 })
			Me.dgw.Cursor = Global.System.Windows.Forms.Cursors.Hand
			dataGridViewCellStyle32.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft
			dataGridViewCellStyle32.BackColor = Global.System.Drawing.SystemColors.Window
			dataGridViewCellStyle32.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 8.25F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			dataGridViewCellStyle32.ForeColor = Global.System.Drawing.SystemColors.ControlText
			dataGridViewCellStyle32.SelectionBackColor = Global.System.Drawing.SystemColors.Highlight
			dataGridViewCellStyle32.SelectionForeColor = Global.System.Drawing.SystemColors.HighlightText
			dataGridViewCellStyle32.WrapMode = Global.System.Windows.Forms.DataGridViewTriState.[False]
			Me.dgw.DefaultCellStyle = dataGridViewCellStyle32
			Me.dgw.EnableHeadersVisualStyles = False
			Me.dgw.GridColor = Global.System.Drawing.Color.White
			Me.dgw.Location = New Global.System.Drawing.Point(6, 19)
			Me.dgw.MultiSelect = False
			Me.dgw.Name = "dgw"
			Me.dgw.[ReadOnly] = True
			Me.dgw.RowHeadersBorderStyle = Global.System.Windows.Forms.DataGridViewHeaderBorderStyle.[Single]
			dataGridViewCellStyle33.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft
			dataGridViewCellStyle33.BackColor = Global.System.Drawing.Color.DarkViolet
			dataGridViewCellStyle33.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 8.25F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			dataGridViewCellStyle33.ForeColor = Global.System.Drawing.Color.White
			dataGridViewCellStyle33.SelectionBackColor = Global.System.Drawing.Color.OrangeRed
			dataGridViewCellStyle33.SelectionForeColor = Global.System.Drawing.Color.White
			dataGridViewCellStyle33.WrapMode = Global.System.Windows.Forms.DataGridViewTriState.[True]
			Me.dgw.RowHeadersDefaultCellStyle = dataGridViewCellStyle33
			Me.dgw.RowHeadersWidth = 25
			Me.dgw.RowHeadersWidthSizeMode = Global.System.Windows.Forms.DataGridViewRowHeadersWidthSizeMode.DisableResizing
			dataGridViewCellStyle34.BackColor = Global.System.Drawing.Color.White
			dataGridViewCellStyle34.Font = New Global.System.Drawing.Font("Tahoma", 8.25F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			dataGridViewCellStyle34.SelectionBackColor = Global.System.Drawing.Color.DarkSlateGray
			dataGridViewCellStyle34.SelectionForeColor = Global.System.Drawing.Color.White
			Me.dgw.RowsDefaultCellStyle = dataGridViewCellStyle34
			Me.dgw.RowTemplate.Height = 25
			Me.dgw.RowTemplate.Resizable = Global.System.Windows.Forms.DataGridViewTriState.[False]
			Me.dgw.SelectionMode = Global.System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect
			Me.dgw.Size = New Global.System.Drawing.Size(568, 136)
			Me.dgw.TabIndex = 44
			Me.dgw.TabStop = False
			Me.DataGridViewTextBoxColumn31.HeaderText = "Invoice ID"
			Me.DataGridViewTextBoxColumn31.Name = "DataGridViewTextBoxColumn31"
			Me.DataGridViewTextBoxColumn31.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn31.Visible = False
			Me.DataGridViewTextBoxColumn32.HeaderText = "Invoice No."
			Me.DataGridViewTextBoxColumn32.Name = "DataGridViewTextBoxColumn32"
			Me.DataGridViewTextBoxColumn32.[ReadOnly] = True
			dataGridViewCellStyle35.Format = "dd/MM/yyyy"
			Me.DataGridViewTextBoxColumn33.DefaultCellStyle = dataGridViewCellStyle35
			Me.DataGridViewTextBoxColumn33.HeaderText = "Invoice Date"
			Me.DataGridViewTextBoxColumn33.Name = "DataGridViewTextBoxColumn33"
			Me.DataGridViewTextBoxColumn33.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn34.HeaderText = "Tax Type"
			Me.DataGridViewTextBoxColumn34.Name = "DataGridViewTextBoxColumn34"
			Me.DataGridViewTextBoxColumn34.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn35.HeaderText = "CID"
			Me.DataGridViewTextBoxColumn35.Name = "DataGridViewTextBoxColumn35"
			Me.DataGridViewTextBoxColumn35.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn35.Visible = False
			Me.DataGridViewTextBoxColumn36.HeaderText = "Customer ID"
			Me.DataGridViewTextBoxColumn36.Name = "DataGridViewTextBoxColumn36"
			Me.DataGridViewTextBoxColumn36.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn37.HeaderText = "Customer Name"
			Me.DataGridViewTextBoxColumn37.Name = "DataGridViewTextBoxColumn37"
			Me.DataGridViewTextBoxColumn37.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn38.HeaderText = "Contact No."
			Me.DataGridViewTextBoxColumn38.Name = "DataGridViewTextBoxColumn38"
			Me.DataGridViewTextBoxColumn38.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn39.HeaderText = "State"
			Me.DataGridViewTextBoxColumn39.Name = "DataGridViewTextBoxColumn39"
			Me.DataGridViewTextBoxColumn39.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn40.HeaderText = "GSTIN"
			Me.DataGridViewTextBoxColumn40.Name = "DataGridViewTextBoxColumn40"
			Me.DataGridViewTextBoxColumn40.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn41.HeaderText = "SM_ID"
			Me.DataGridViewTextBoxColumn41.Name = "DataGridViewTextBoxColumn41"
			Me.DataGridViewTextBoxColumn41.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn41.Visible = False
			Me.DataGridViewTextBoxColumn42.HeaderText = "Salesman ID"
			Me.DataGridViewTextBoxColumn42.Name = "DataGridViewTextBoxColumn42"
			Me.DataGridViewTextBoxColumn42.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn43.HeaderText = "Salesman"
			Me.DataGridViewTextBoxColumn43.Name = "DataGridViewTextBoxColumn43"
			Me.DataGridViewTextBoxColumn43.[ReadOnly] = True
			dataGridViewCellStyle36.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn44.DefaultCellStyle = dataGridViewCellStyle36
			Me.DataGridViewTextBoxColumn44.HeaderText = "(Taxable + Tax) Amt"
			Me.DataGridViewTextBoxColumn44.Name = "DataGridViewTextBoxColumn44"
			Me.DataGridViewTextBoxColumn44.[ReadOnly] = True
			dataGridViewCellStyle37.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn45.DefaultCellStyle = dataGridViewCellStyle37
			Me.DataGridViewTextBoxColumn45.HeaderText = "CGST"
			Me.DataGridViewTextBoxColumn45.Name = "DataGridViewTextBoxColumn45"
			Me.DataGridViewTextBoxColumn45.[ReadOnly] = True
			dataGridViewCellStyle38.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.Column20.DefaultCellStyle = dataGridViewCellStyle38
			Me.Column20.HeaderText = "SGST/UTGST"
			Me.Column20.Name = "Column20"
			Me.Column20.[ReadOnly] = True
			dataGridViewCellStyle39.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn46.DefaultCellStyle = dataGridViewCellStyle39
			Me.DataGridViewTextBoxColumn46.HeaderText = "IGST"
			Me.DataGridViewTextBoxColumn46.Name = "DataGridViewTextBoxColumn46"
			Me.DataGridViewTextBoxColumn46.[ReadOnly] = True
			dataGridViewCellStyle40.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn47.DefaultCellStyle = dataGridViewCellStyle40
			Me.DataGridViewTextBoxColumn47.HeaderText = "CESS"
			Me.DataGridViewTextBoxColumn47.Name = "DataGridViewTextBoxColumn47"
			Me.DataGridViewTextBoxColumn47.[ReadOnly] = True
			dataGridViewCellStyle41.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn48.DefaultCellStyle = dataGridViewCellStyle41
			Me.DataGridViewTextBoxColumn48.HeaderText = "Bill Sundry Charges"
			Me.DataGridViewTextBoxColumn48.Name = "DataGridViewTextBoxColumn48"
			Me.DataGridViewTextBoxColumn48.[ReadOnly] = True
			dataGridViewCellStyle42.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn49.DefaultCellStyle = dataGridViewCellStyle42
			Me.DataGridViewTextBoxColumn49.HeaderText = "Total Bill Discount"
			Me.DataGridViewTextBoxColumn49.Name = "DataGridViewTextBoxColumn49"
			Me.DataGridViewTextBoxColumn49.[ReadOnly] = True
			dataGridViewCellStyle43.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn50.DefaultCellStyle = dataGridViewCellStyle43
			Me.DataGridViewTextBoxColumn50.HeaderText = "Total"
			Me.DataGridViewTextBoxColumn50.Name = "DataGridViewTextBoxColumn50"
			Me.DataGridViewTextBoxColumn50.[ReadOnly] = True
			dataGridViewCellStyle44.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn51.DefaultCellStyle = dataGridViewCellStyle44
			Me.DataGridViewTextBoxColumn51.HeaderText = "Round Off"
			Me.DataGridViewTextBoxColumn51.Name = "DataGridViewTextBoxColumn51"
			Me.DataGridViewTextBoxColumn51.[ReadOnly] = True
			dataGridViewCellStyle45.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn52.DefaultCellStyle = dataGridViewCellStyle45
			Me.DataGridViewTextBoxColumn52.HeaderText = "Grand Total"
			Me.DataGridViewTextBoxColumn52.Name = "DataGridViewTextBoxColumn52"
			Me.DataGridViewTextBoxColumn52.[ReadOnly] = True
			dataGridViewCellStyle46.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn53.DefaultCellStyle = dataGridViewCellStyle46
			Me.DataGridViewTextBoxColumn53.HeaderText = "Total Payment"
			Me.DataGridViewTextBoxColumn53.Name = "DataGridViewTextBoxColumn53"
			Me.DataGridViewTextBoxColumn53.[ReadOnly] = True
			dataGridViewCellStyle47.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn54.DefaultCellStyle = dataGridViewCellStyle47
			Me.DataGridViewTextBoxColumn54.HeaderText = "Payment Due"
			Me.DataGridViewTextBoxColumn54.Name = "DataGridViewTextBoxColumn54"
			Me.DataGridViewTextBoxColumn54.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn55.HeaderText = "Transport Details"
			Me.DataGridViewTextBoxColumn55.Name = "DataGridViewTextBoxColumn55"
			Me.DataGridViewTextBoxColumn55.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn56.HeaderText = "Narration"
			Me.DataGridViewTextBoxColumn56.Name = "DataGridViewTextBoxColumn56"
			Me.DataGridViewTextBoxColumn56.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn57.HeaderText = "E-Way No"
			Me.DataGridViewTextBoxColumn57.Name = "DataGridViewTextBoxColumn57"
			Me.DataGridViewTextBoxColumn57.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn58.HeaderText = "Till ID"
			Me.DataGridViewTextBoxColumn58.Name = "DataGridViewTextBoxColumn58"
			Me.DataGridViewTextBoxColumn58.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn59.HeaderText = "Operator"
			Me.DataGridViewTextBoxColumn59.Name = "DataGridViewTextBoxColumn59"
			Me.DataGridViewTextBoxColumn59.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn60.HeaderText = "Bill Sundy Type"
			Me.DataGridViewTextBoxColumn60.Name = "DataGridViewTextBoxColumn60"
			Me.DataGridViewTextBoxColumn60.[ReadOnly] = True
			dataGridViewCellStyle48.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn61.DefaultCellStyle = dataGridViewCellStyle48
			Me.DataGridViewTextBoxColumn61.HeaderText = "Offer Discount"
			Me.DataGridViewTextBoxColumn61.Name = "DataGridViewTextBoxColumn61"
			Me.DataGridViewTextBoxColumn61.[ReadOnly] = True
			dataGridViewCellStyle49.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn62.DefaultCellStyle = dataGridViewCellStyle49
			Me.DataGridViewTextBoxColumn62.HeaderText = "Loyalty Discount"
			Me.DataGridViewTextBoxColumn62.Name = "DataGridViewTextBoxColumn62"
			Me.DataGridViewTextBoxColumn62.[ReadOnly] = True
			dataGridViewCellStyle50.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn63.DefaultCellStyle = dataGridViewCellStyle50
			Me.DataGridViewTextBoxColumn63.HeaderText = "Writeoff Bill Discount"
			Me.DataGridViewTextBoxColumn63.Name = "DataGridViewTextBoxColumn63"
			Me.DataGridViewTextBoxColumn63.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn64.HeaderText = "Customer City"
			Me.DataGridViewTextBoxColumn64.Name = "DataGridViewTextBoxColumn64"
			Me.DataGridViewTextBoxColumn64.[ReadOnly] = True
			dataGridViewCellStyle51.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			dataGridViewCellStyle51.Format = "N2"
			Me.DataGridViewTextBoxColumn65.DefaultCellStyle = dataGridViewCellStyle51
			Me.DataGridViewTextBoxColumn65.HeaderText = "Cash Tendered"
			Me.DataGridViewTextBoxColumn65.Name = "DataGridViewTextBoxColumn65"
			Me.DataGridViewTextBoxColumn65.[ReadOnly] = True
			dataGridViewCellStyle52.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			dataGridViewCellStyle52.Format = "N2"
			Me.DataGridViewTextBoxColumn66.DefaultCellStyle = dataGridViewCellStyle52
			Me.DataGridViewTextBoxColumn66.HeaderText = "Cash Refund"
			Me.DataGridViewTextBoxColumn66.Name = "DataGridViewTextBoxColumn66"
			Me.DataGridViewTextBoxColumn66.[ReadOnly] = True
			dataGridViewCellStyle53.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			dataGridViewCellStyle53.Format = "N2"
			Me.DataGridViewTextBoxColumn67.DefaultCellStyle = dataGridViewCellStyle53
			Me.DataGridViewTextBoxColumn67.HeaderText = "Bill Cash Amt"
			Me.DataGridViewTextBoxColumn67.Name = "DataGridViewTextBoxColumn67"
			Me.DataGridViewTextBoxColumn67.[ReadOnly] = True
			dataGridViewCellStyle54.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			dataGridViewCellStyle54.Format = "N2"
			Me.DataGridViewTextBoxColumn68.DefaultCellStyle = dataGridViewCellStyle54
			Me.DataGridViewTextBoxColumn68.HeaderText = "Coupon Discount"
			Me.DataGridViewTextBoxColumn68.Name = "DataGridViewTextBoxColumn68"
			Me.DataGridViewTextBoxColumn68.[ReadOnly] = True
			dataGridViewCellStyle55.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			dataGridViewCellStyle55.Format = "N2"
			Me.DataGridViewTextBoxColumn69.DefaultCellStyle = dataGridViewCellStyle55
			Me.DataGridViewTextBoxColumn69.HeaderText = "Gift Discount"
			Me.DataGridViewTextBoxColumn69.Name = "DataGridViewTextBoxColumn69"
			Me.DataGridViewTextBoxColumn69.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn70.HeaderText = "Cus Address"
			Me.DataGridViewTextBoxColumn70.Name = "DataGridViewTextBoxColumn70"
			Me.DataGridViewTextBoxColumn70.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn71.HeaderText = "ReturnNo"
			Me.DataGridViewTextBoxColumn71.Name = "DataGridViewTextBoxColumn71"
			Me.DataGridViewTextBoxColumn71.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn72.HeaderText = "ByReturn"
			Me.DataGridViewTextBoxColumn72.Name = "DataGridViewTextBoxColumn72"
			Me.DataGridViewTextBoxColumn72.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn73.HeaderText = "Loyality Points"
			Me.DataGridViewTextBoxColumn73.Name = "DataGridViewTextBoxColumn73"
			Me.DataGridViewTextBoxColumn73.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn74.HeaderText = "Loyality Reedem Points"
			Me.DataGridViewTextBoxColumn74.Name = "DataGridViewTextBoxColumn74"
			Me.DataGridViewTextBoxColumn74.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn75.HeaderText = "Loyality Reedem Amt"
			Me.DataGridViewTextBoxColumn75.Name = "DataGridViewTextBoxColumn75"
			Me.DataGridViewTextBoxColumn75.[ReadOnly] = True
			Me.DataGridView2.AllowUserToAddRows = False
			Me.DataGridView2.AllowUserToDeleteRows = False
			Me.DataGridView2.BackgroundColor = Global.System.Drawing.Color.White
			Me.DataGridView2.ColumnHeadersBorderStyle = Global.System.Windows.Forms.DataGridViewHeaderBorderStyle.[Single]
			dataGridViewCellStyle56.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft
			dataGridViewCellStyle56.BackColor = Global.System.Drawing.SystemColors.Control
			dataGridViewCellStyle56.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 8.25F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			dataGridViewCellStyle56.ForeColor = Global.System.Drawing.SystemColors.WindowText
			dataGridViewCellStyle56.SelectionBackColor = Global.System.Drawing.SystemColors.Highlight
			dataGridViewCellStyle56.SelectionForeColor = Global.System.Drawing.SystemColors.HighlightText
			dataGridViewCellStyle56.WrapMode = Global.System.Windows.Forms.DataGridViewTriState.[True]
			Me.DataGridView2.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle56
			Me.DataGridView2.ColumnHeadersHeight = 30
			Me.DataGridView2.Columns.AddRange(New Global.System.Windows.Forms.DataGridViewColumn() { Me.DataGridViewTextBoxColumn1, Me.DataGridViewTextBoxColumn2, Me.DataGridViewTextBoxColumn7, Me.DataGridViewTextBoxColumn5, Me.DataGridViewTextBoxColumn6, Me.DataGridViewTextBoxColumn3, Me.DataGridViewTextBoxColumn4, Me.DataGridViewTextBoxColumn10, Me.DataGridViewTextBoxColumn15, Me.DataGridViewTextBoxColumn11, Me.DataGridViewTextBoxColumn12 })
			Me.DataGridView2.Cursor = Global.System.Windows.Forms.Cursors.Hand
			dataGridViewCellStyle57.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft
			dataGridViewCellStyle57.BackColor = Global.System.Drawing.SystemColors.Window
			dataGridViewCellStyle57.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 8.25F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			dataGridViewCellStyle57.ForeColor = Global.System.Drawing.SystemColors.ControlText
			dataGridViewCellStyle57.SelectionBackColor = Global.System.Drawing.SystemColors.Highlight
			dataGridViewCellStyle57.SelectionForeColor = Global.System.Drawing.SystemColors.HighlightText
			dataGridViewCellStyle57.WrapMode = Global.System.Windows.Forms.DataGridViewTriState.[False]
			Me.DataGridView2.DefaultCellStyle = dataGridViewCellStyle57
			Me.DataGridView2.EnableHeadersVisualStyles = False
			Me.DataGridView2.GridColor = Global.System.Drawing.Color.White
			Me.DataGridView2.Location = New Global.System.Drawing.Point(10, 170)
			Me.DataGridView2.MultiSelect = False
			Me.DataGridView2.Name = "DataGridView2"
			Me.DataGridView2.[ReadOnly] = True
			dataGridViewCellStyle58.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft
			dataGridViewCellStyle58.BackColor = Global.System.Drawing.SystemColors.Control
			dataGridViewCellStyle58.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 8.25F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			dataGridViewCellStyle58.ForeColor = Global.System.Drawing.SystemColors.WindowText
			dataGridViewCellStyle58.SelectionBackColor = Global.System.Drawing.SystemColors.Highlight
			dataGridViewCellStyle58.SelectionForeColor = Global.System.Drawing.SystemColors.HighlightText
			dataGridViewCellStyle58.WrapMode = Global.System.Windows.Forms.DataGridViewTriState.[True]
			Me.DataGridView2.RowHeadersDefaultCellStyle = dataGridViewCellStyle58
			Me.DataGridView2.SelectionMode = Global.System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect
			Me.DataGridView2.Size = New Global.System.Drawing.Size(712, 206)
			Me.DataGridView2.TabIndex = 1
			Me.DataGridViewTextBoxColumn1.HeaderText = "LogID"
			Me.DataGridViewTextBoxColumn1.Name = "DataGridViewTextBoxColumn1"
			Me.DataGridViewTextBoxColumn1.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn1.Visible = False
			Me.DataGridViewTextBoxColumn2.HeaderText = "support_token_no"
			Me.DataGridViewTextBoxColumn2.Name = "DataGridViewTextBoxColumn2"
			Me.DataGridViewTextBoxColumn2.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn7.HeaderText = "Software Name"
			Me.DataGridViewTextBoxColumn7.Name = "DataGridViewTextBoxColumn7"
			Me.DataGridViewTextBoxColumn7.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn5.HeaderText = "CustomerName"
			Me.DataGridViewTextBoxColumn5.Name = "DataGridViewTextBoxColumn5"
			Me.DataGridViewTextBoxColumn5.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn6.HeaderText = "Registered Mobile"
			Me.DataGridViewTextBoxColumn6.Name = "DataGridViewTextBoxColumn6"
			Me.DataGridViewTextBoxColumn6.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn3.HeaderText = "Date"
			Me.DataGridViewTextBoxColumn3.Name = "DataGridViewTextBoxColumn3"
			Me.DataGridViewTextBoxColumn3.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn4.HeaderText = "CurrentIssue"
			Me.DataGridViewTextBoxColumn4.Name = "DataGridViewTextBoxColumn4"
			Me.DataGridViewTextBoxColumn4.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn10.HeaderText = "Remarks"
			Me.DataGridViewTextBoxColumn10.Name = "DataGridViewTextBoxColumn10"
			Me.DataGridViewTextBoxColumn10.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn15.HeaderText = "Close_date"
			Me.DataGridViewTextBoxColumn15.Name = "DataGridViewTextBoxColumn15"
			Me.DataGridViewTextBoxColumn15.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn11.HeaderText = "Feedback"
			Me.DataGridViewTextBoxColumn11.Name = "DataGridViewTextBoxColumn11"
			Me.DataGridViewTextBoxColumn11.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn12.HeaderText = "Rating"
			Me.DataGridViewTextBoxColumn12.Name = "DataGridViewTextBoxColumn12"
			Me.DataGridViewTextBoxColumn12.[ReadOnly] = True
			Me.GroupBox1.Controls.Add(Me.lbl_CustomerID)
			Me.GroupBox1.Controls.Add(Me.lblCurrentIssue)
			Me.GroupBox1.Controls.Add(Me.lblNumbers)
			Me.GroupBox1.Controls.Add(Me.lblCount)
			Me.GroupBox1.Controls.Add(Me.lbl_tokenid)
			Me.GroupBox1.Controls.Add(Me.btnClosed)
			Me.GroupBox1.Controls.Add(Me.lbl_Id)
			Me.GroupBox1.Controls.Add(Me.btnTokenUpdate)
			Me.GroupBox1.Controls.Add(Me.txtRemarks)
			Me.GroupBox1.Controls.Add(Me.Label6)
			Me.GroupBox1.Controls.Add(Me.lblTokenNo)
			Me.GroupBox1.Location = New Global.System.Drawing.Point(10, 6)
			Me.GroupBox1.Name = "GroupBox1"
			Me.GroupBox1.Size = New Global.System.Drawing.Size(712, 158)
			Me.GroupBox1.TabIndex = 0
			Me.GroupBox1.TabStop = False
			Me.GroupBox1.Text = "Token Follow-Up"
			Me.lbl_CustomerID.AutoSize = True
			Me.lbl_CustomerID.Location = New Global.System.Drawing.Point(404, 43)
			Me.lbl_CustomerID.Name = "lbl_CustomerID"
			Me.lbl_CustomerID.Size = New Global.System.Drawing.Size(78, 13)
			Me.lbl_CustomerID.TabIndex = 527
			Me.lbl_CustomerID.Text = "lbl_CustomerID"
			Me.lbl_CustomerID.Visible = False
			Me.lblCurrentIssue.AutoSize = True
			Me.lblCurrentIssue.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 9.75F, Global.System.Drawing.FontStyle.Bold, Global.System.Drawing.GraphicsUnit.Point, 0)
			Me.lblCurrentIssue.ForeColor = Global.System.Drawing.Color.Red
			Me.lblCurrentIssue.Location = New Global.System.Drawing.Point(17, 122)
			Me.lblCurrentIssue.Name = "lblCurrentIssue"
			Me.lblCurrentIssue.Size = New Global.System.Drawing.Size(110, 16)
			Me.lblCurrentIssue.TabIndex = 526
			Me.lblCurrentIssue.Text = "lblCurrentIssue"
			Me.lblNumbers.AutoSize = True
			Me.lblNumbers.Location = New Global.System.Drawing.Point(349, 22)
			Me.lblNumbers.Name = "lblNumbers"
			Me.lblNumbers.Size = New Global.System.Drawing.Size(59, 13)
			Me.lblNumbers.TabIndex = 525
			Me.lblNumbers.Text = "lblNumbers"
			Me.lblCount.AutoSize = True
			Me.lblCount.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 9.75F, Global.System.Drawing.FontStyle.Bold, Global.System.Drawing.GraphicsUnit.Point, 0)
			Me.lblCount.Location = New Global.System.Drawing.Point(528, 39)
			Me.lblCount.Name = "lblCount"
			Me.lblCount.Size = New Global.System.Drawing.Size(152, 16)
			Me.lblCount.TabIndex = 523
			Me.lblCount.Text = "Total Support Log : X"
			Me.lbl_tokenid.AutoSize = True
			Me.lbl_tokenid.Location = New Global.System.Drawing.Point(323, 44)
			Me.lbl_tokenid.Name = "lbl_tokenid"
			Me.lbl_tokenid.Size = New Global.System.Drawing.Size(58, 13)
			Me.lbl_tokenid.TabIndex = 522
			Me.lbl_tokenid.Text = "lbl_tokenid"
			Me.lbl_tokenid.Visible = False
			Me.btnClosed.Anchor = Global.System.Windows.Forms.AnchorStyles.Top Or Global.System.Windows.Forms.AnchorStyles.Right
			Me.btnClosed.BackColor = Global.System.Drawing.Color.MediumVioletRed
			Me.btnClosed.FlatAppearance.BorderSize = 0
			Me.btnClosed.FlatStyle = Global.System.Windows.Forms.FlatStyle.Flat
			Me.btnClosed.Font = New Global.System.Drawing.Font("Segoe UI Semibold", 12F, Global.System.Drawing.FontStyle.Bold, Global.System.Drawing.GraphicsUnit.Point, 0)
			Me.btnClosed.ForeColor = Global.System.Drawing.Color.White
			Me.btnClosed.GradientBottom = Global.System.Drawing.Color.FromArgb(255, 192, 192)
			Me.btnClosed.GradientTop = Global.System.Drawing.Color.Red
			Me.btnClosed.Image = CType(componentResourceManager.GetObject("btnClosed.Image"), Global.System.Drawing.Image)
			Me.btnClosed.ImageAlign = Global.System.Drawing.ContentAlignment.MiddleLeft
			Me.btnClosed.Location = New Global.System.Drawing.Point(562, 122)
			Me.btnClosed.Name = "btnClosed"
			Me.btnClosed.Size = New Global.System.Drawing.Size(129, 30)
			Me.btnClosed.TabIndex = 521
			Me.btnClosed.Text = "Token Closed"
			Me.btnClosed.TextAlign = Global.System.Drawing.ContentAlignment.MiddleRight
			Me.btnClosed.UseVisualStyleBackColor = False
			Me.lbl_Id.AutoSize = True
			Me.lbl_Id.Location = New Global.System.Drawing.Point(285, 43)
			Me.lbl_Id.Name = "lbl_Id"
			Me.lbl_Id.Size = New Global.System.Drawing.Size(32, 13)
			Me.lbl_Id.TabIndex = 518
			Me.lbl_Id.Text = "lbl_Id"
			Me.lbl_Id.Visible = False
			Me.btnTokenUpdate.Anchor = Global.System.Windows.Forms.AnchorStyles.Top Or Global.System.Windows.Forms.AnchorStyles.Right
			Me.btnTokenUpdate.BackColor = Global.System.Drawing.Color.MediumVioletRed
			Me.btnTokenUpdate.FlatAppearance.BorderSize = 0
			Me.btnTokenUpdate.FlatStyle = Global.System.Windows.Forms.FlatStyle.Flat
			Me.btnTokenUpdate.Font = New Global.System.Drawing.Font("Segoe UI Semibold", 12F, Global.System.Drawing.FontStyle.Bold, Global.System.Drawing.GraphicsUnit.Point, 0)
			Me.btnTokenUpdate.ForeColor = Global.System.Drawing.Color.White
			Me.btnTokenUpdate.GradientBottom = Global.System.Drawing.Color.FromArgb(45, 63, 83)
			Me.btnTokenUpdate.GradientTop = Global.System.Drawing.Color.RoyalBlue
			Me.btnTokenUpdate.Image = CType(componentResourceManager.GetObject("btnTokenUpdate.Image"), Global.System.Drawing.Image)
			Me.btnTokenUpdate.ImageAlign = Global.System.Drawing.ContentAlignment.MiddleLeft
			Me.btnTokenUpdate.Location = New Global.System.Drawing.Point(427, 122)
			Me.btnTokenUpdate.Name = "btnTokenUpdate"
			Me.btnTokenUpdate.Size = New Global.System.Drawing.Size(129, 30)
			Me.btnTokenUpdate.TabIndex = 517
			Me.btnTokenUpdate.Text = "Token Update"
			Me.btnTokenUpdate.TextAlign = Global.System.Drawing.ContentAlignment.MiddleRight
			Me.btnTokenUpdate.UseVisualStyleBackColor = False
			Me.txtRemarks.BackColor = Global.System.Drawing.Color.White
			Me.txtRemarks.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 9F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			Me.txtRemarks.Location = New Global.System.Drawing.Point(18, 60)
			Me.txtRemarks.Multiline = True
			Me.txtRemarks.Name = "txtRemarks"
			Me.txtRemarks.Size = New Global.System.Drawing.Size(673, 56)
			Me.txtRemarks.TabIndex = 15
			Me.Label6.AutoSize = True
			Me.Label6.Location = New Global.System.Drawing.Point(17, 43)
			Me.Label6.Name = "Label6"
			Me.Label6.Size = New Global.System.Drawing.Size(55, 13)
			Me.Label6.TabIndex = 14
			Me.Label6.Text = "Remarks :"
			Me.lblTokenNo.AutoSize = True
			Me.lblTokenNo.Location = New Global.System.Drawing.Point(17, 22)
			Me.lblTokenNo.Name = "lblTokenNo"
			Me.lblTokenNo.Size = New Global.System.Drawing.Size(58, 13)
			Me.lblTokenNo.TabIndex = 13
			Me.lblTokenNo.Text = "Token No."
			MyBase.AutoScaleDimensions = New Global.System.Drawing.SizeF(6F, 13F)
			MyBase.AutoScaleMode = Global.System.Windows.Forms.AutoScaleMode.Font
			MyBase.ClientSize = New Global.System.Drawing.Size(1803, 673)
			MyBase.Controls.Add(Me.Panel2)
			MyBase.Controls.Add(Me.Panel1)
			MyBase.Name = "frmCustomerSupportForm_Dashboard"
			MyBase.StartPosition = Global.System.Windows.Forms.FormStartPosition.CenterParent
			Me.Text = "Customer Support Form - Dashboard"
			CType(Me.DataGridView1, Global.System.ComponentModel.ISupportInitialize).EndInit()
			Me.Panel3.ResumeLayout(False)
			Me.Panel3.PerformLayout()
			Me.Panel6.ResumeLayout(False)
			Me.Panel6.PerformLayout()
			Me.GroupBox2.ResumeLayout(False)
			Me.GroupBox2.PerformLayout()
			Me.Panel1.ResumeLayout(False)
			Me.Panel1.PerformLayout()
			Me.Panel4.ResumeLayout(False)
			Me.Panel4.PerformLayout()
			Me.Panel7.ResumeLayout(False)
			Me.Panel7.PerformLayout()
			Me.Panel2.ResumeLayout(False)
			Me.pnl_FollowUp.ResumeLayout(False)
			Me.GroupBox3.ResumeLayout(False)
			Me.GroupBox3.PerformLayout()
			CType(Me.DataGridView3, Global.System.ComponentModel.ISupportInitialize).EndInit()
			Me.GroupBox4.ResumeLayout(False)
			CType(Me.dgw, Global.System.ComponentModel.ISupportInitialize).EndInit()
			CType(Me.DataGridView2, Global.System.ComponentModel.ISupportInitialize).EndInit()
			Me.GroupBox1.ResumeLayout(False)
			Me.GroupBox1.PerformLayout()
			MyBase.ResumeLayout(False)
		End Sub

		' Token: 0x04000CD9 RID: 3289
		Private components As Global.System.ComponentModel.IContainer
	End Class
End Namespace
