Namespace BillPoint
	' Token: 0x020004C9 RID: 1225
		Public Partial Class frmGSTR1
		Inherits Global.System.Windows.Forms.Form

		' Token: 0x0600F65E RID: 63070 RVA: 0x00939F4C File Offset: 0x0093814C
		<Global.System.Diagnostics.DebuggerNonUserCode()>
		Protected Overrides Sub Dispose(disposing As Boolean)
			Try
				Dim flag As Boolean = disposing AndAlso Me.components IsNot Nothing
				If flag Then
					Me.components.Dispose()
				End If
			Finally
				MyBase.Dispose(disposing)
			End Try
		End Sub

		' Token: 0x0600F65F RID: 63071 RVA: 0x00939F9C File Offset: 0x0093819C
		<Global.System.Diagnostics.DebuggerStepThrough()>
		Private Sub InitializeComponent()
			Dim dataGridViewCellStyle As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle2 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle3 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle4 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle5 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle6 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle7 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle8 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle9 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle10 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle11 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle12 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle13 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle14 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle15 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle16 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle17 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle18 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle19 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle20 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle21 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle22 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle23 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle24 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle25 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle26 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle27 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle28 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle29 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle30 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle31 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle32 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle33 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle34 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle35 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle36 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle37 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle38 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle39 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle40 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle41 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle42 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle43 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle44 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle45 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle46 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle47 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle48 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle49 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle50 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle51 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle52 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle53 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle54 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle55 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle56 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle57 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle58 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle59 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle60 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle61 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle62 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle63 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle64 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle65 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle66 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle67 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle68 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle69 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle70 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle71 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle72 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle73 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle74 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle75 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle76 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle77 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle78 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle79 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle80 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle81 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle82 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle83 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle84 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle85 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle86 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle87 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle88 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle89 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle90 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle91 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle92 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle93 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle94 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle95 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle96 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle97 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle98 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle99 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle100 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle101 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim componentResourceManager As Global.System.ComponentModel.ComponentResourceManager = New Global.System.ComponentModel.ComponentResourceManager(GetType(Global.BillPoint.frmGSTR1))
			Me.TabControl1 = New Global.System.Windows.Forms.TabControl()
			Me.TabPage1 = New Global.System.Windows.Forms.TabPage()
			Me.LinkLabel2 = New Global.System.Windows.Forms.LinkLabel()
			Me.dgw = New Global.System.Windows.Forms.DataGridView()
			Me.Column2 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column3 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column14 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column6 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column16 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column17 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column18 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column19 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column20 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column21 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column22 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column23 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column24 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column25 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column26 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column7 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.TabPage2 = New Global.System.Windows.Forms.TabPage()
			Me.dgw1 = New Global.System.Windows.Forms.DataGridView()
			Me.DataGridViewTextBoxColumn2 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn3 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn4 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn7 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn9 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn10 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn14 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn15 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn16 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn17 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn18 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn19 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn20 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn21 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn22 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn23 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.LinkLabel1 = New Global.System.Windows.Forms.LinkLabel()
			Me.TabPage3 = New Global.System.Windows.Forms.TabPage()
			Me.LinkLabel3 = New Global.System.Windows.Forms.LinkLabel()
			Me.dgw2 = New Global.System.Windows.Forms.DataGridView()
			Me.DataGridViewTextBoxColumn29 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn30 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn31 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn34 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn36 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn37 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn41 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn42 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn43 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn44 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn45 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn46 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn47 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn48 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn49 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn50 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.TabPage4 = New Global.System.Windows.Forms.TabPage()
			Me.LinkLabel4 = New Global.System.Windows.Forms.LinkLabel()
			Me.dgw3 = New Global.System.Windows.Forms.DataGridView()
			Me.Column28 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn56 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn57 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn59 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn60 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn62 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column29 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column30 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn63 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn64 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn65 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn66 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn67 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn68 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn69 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn70 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn71 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn72 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.TabPage5 = New Global.System.Windows.Forms.TabPage()
			Me.LinkLabel5 = New Global.System.Windows.Forms.LinkLabel()
			Me.dgw4 = New Global.System.Windows.Forms.DataGridView()
			Me.DataGridViewTextBoxColumn74 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn75 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn76 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn78 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn79 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn81 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn82 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn83 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn84 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn85 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn86 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn87 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn88 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn89 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn90 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn91 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn92 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn93 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.TabPage6 = New Global.System.Windows.Forms.TabPage()
			Me.LinkLabel6 = New Global.System.Windows.Forms.LinkLabel()
			Me.dgw5 = New Global.System.Windows.Forms.DataGridView()
			Me.DataGridViewTextBoxColumn101 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn94 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn95 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn96 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn97 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn98 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn99 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn100 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn102 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn103 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn104 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn105 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn106 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn107 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn108 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn109 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn110 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn111 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn112 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn113 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn114 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn115 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.GroupBox2 = New Global.System.Windows.Forms.GroupBox()
			Me.btnReset = New Global.System.Windows.Forms.Button()
			Me.dtpDateTo = New Global.System.Windows.Forms.DateTimePicker()
			Me.Label2 = New Global.System.Windows.Forms.Label()
			Me.btnGetData = New Global.System.Windows.Forms.Button()
			Me.Label4 = New Global.System.Windows.Forms.Label()
			Me.dtpDateFrom = New Global.System.Windows.Forms.DateTimePicker()
			Me.Label1 = New Global.System.Windows.Forms.Label()
			Me.SaveFileDialog1 = New Global.System.Windows.Forms.SaveFileDialog()
			Me.TabControl1.SuspendLayout()
			Me.TabPage1.SuspendLayout()
			CType(Me.dgw, Global.System.ComponentModel.ISupportInitialize).BeginInit()
			Me.TabPage2.SuspendLayout()
			CType(Me.dgw1, Global.System.ComponentModel.ISupportInitialize).BeginInit()
			Me.TabPage3.SuspendLayout()
			CType(Me.dgw2, Global.System.ComponentModel.ISupportInitialize).BeginInit()
			Me.TabPage4.SuspendLayout()
			CType(Me.dgw3, Global.System.ComponentModel.ISupportInitialize).BeginInit()
			Me.TabPage5.SuspendLayout()
			CType(Me.dgw4, Global.System.ComponentModel.ISupportInitialize).BeginInit()
			Me.TabPage6.SuspendLayout()
			CType(Me.dgw5, Global.System.ComponentModel.ISupportInitialize).BeginInit()
			Me.GroupBox2.SuspendLayout()
			MyBase.SuspendLayout()
			Me.TabControl1.Controls.Add(Me.TabPage1)
			Me.TabControl1.Controls.Add(Me.TabPage2)
			Me.TabControl1.Controls.Add(Me.TabPage3)
			Me.TabControl1.Controls.Add(Me.TabPage4)
			Me.TabControl1.Controls.Add(Me.TabPage5)
			Me.TabControl1.Controls.Add(Me.TabPage6)
			Me.TabControl1.Cursor = Global.System.Windows.Forms.Cursors.Hand
			Me.TabControl1.Location = New Global.System.Drawing.Point(7, 69)
			Me.TabControl1.Name = "TabControl1"
			Me.TabControl1.SelectedIndex = 0
			Me.TabControl1.Size = New Global.System.Drawing.Size(1146, 567)
			Me.TabControl1.TabIndex = 0
			Me.TabControl1.TabStop = False
			Me.TabPage1.Controls.Add(Me.LinkLabel2)
			Me.TabPage1.Controls.Add(Me.dgw)
			Me.TabPage1.Location = New Global.System.Drawing.Point(4, 22)
			Me.TabPage1.Name = "TabPage1"
			Me.TabPage1.Padding = New Global.System.Windows.Forms.Padding(3)
			Me.TabPage1.Size = New Global.System.Drawing.Size(1138, 541)
			Me.TabPage1.TabIndex = 0
			Me.TabPage1.Text = "B2B"
			Me.TabPage1.UseVisualStyleBackColor = True
			Me.LinkLabel2.AutoSize = True
			Me.LinkLabel2.Cursor = Global.System.Windows.Forms.Cursors.Hand
			Me.LinkLabel2.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 9.75F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			Me.LinkLabel2.Location = New Global.System.Drawing.Point(1036, 522)
			Me.LinkLabel2.Name = "LinkLabel2"
			Me.LinkLabel2.Size = New Global.System.Drawing.Size(102, 16)
			Me.LinkLabel2.TabIndex = 54
			Me.LinkLabel2.TabStop = True
			Me.LinkLabel2.Text = "Export To Excel"
			Me.dgw.AllowUserToAddRows = False
			Me.dgw.AllowUserToDeleteRows = False
			dataGridViewCellStyle.BackColor = Global.System.Drawing.Color.FloralWhite
			Me.dgw.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle
			Me.dgw.BackgroundColor = Global.System.Drawing.Color.White
			Me.dgw.ColumnHeadersBorderStyle = Global.System.Windows.Forms.DataGridViewHeaderBorderStyle.[Single]
			dataGridViewCellStyle2.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter
			dataGridViewCellStyle2.BackColor = Global.System.Drawing.Color.DarkViolet
			dataGridViewCellStyle2.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 8.25F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			dataGridViewCellStyle2.ForeColor = Global.System.Drawing.Color.White
			dataGridViewCellStyle2.SelectionBackColor = Global.System.Drawing.Color.LightSteelBlue
			dataGridViewCellStyle2.SelectionForeColor = Global.System.Drawing.SystemColors.HighlightText
			dataGridViewCellStyle2.WrapMode = Global.System.Windows.Forms.DataGridViewTriState.[True]
			Me.dgw.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2
			Me.dgw.ColumnHeadersHeight = 30
			Me.dgw.Columns.AddRange(New Global.System.Windows.Forms.DataGridViewColumn() { Me.Column2, Me.Column3, Me.Column14, Me.Column6, Me.Column16, Me.Column17, Me.Column18, Me.Column19, Me.Column20, Me.Column21, Me.Column22, Me.Column23, Me.Column24, Me.Column25, Me.Column26, Me.Column7 })
			Me.dgw.Cursor = Global.System.Windows.Forms.Cursors.Hand
			dataGridViewCellStyle3.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft
			dataGridViewCellStyle3.BackColor = Global.System.Drawing.SystemColors.Window
			dataGridViewCellStyle3.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 8.25F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			dataGridViewCellStyle3.ForeColor = Global.System.Drawing.Color.Black
			dataGridViewCellStyle3.SelectionBackColor = Global.System.Drawing.SystemColors.Highlight
			dataGridViewCellStyle3.SelectionForeColor = Global.System.Drawing.SystemColors.HighlightText
			dataGridViewCellStyle3.WrapMode = Global.System.Windows.Forms.DataGridViewTriState.[False]
			Me.dgw.DefaultCellStyle = dataGridViewCellStyle3
			Me.dgw.EnableHeadersVisualStyles = False
			Me.dgw.GridColor = Global.System.Drawing.Color.White
			Me.dgw.Location = New Global.System.Drawing.Point(3, 3)
			Me.dgw.MultiSelect = False
			Me.dgw.Name = "dgw"
			Me.dgw.[ReadOnly] = True
			Me.dgw.RowHeadersBorderStyle = Global.System.Windows.Forms.DataGridViewHeaderBorderStyle.[Single]
			dataGridViewCellStyle4.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft
			dataGridViewCellStyle4.BackColor = Global.System.Drawing.Color.DarkViolet
			dataGridViewCellStyle4.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 8.25F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			dataGridViewCellStyle4.ForeColor = Global.System.Drawing.Color.White
			dataGridViewCellStyle4.SelectionBackColor = Global.System.Drawing.Color.OrangeRed
			dataGridViewCellStyle4.SelectionForeColor = Global.System.Drawing.Color.White
			dataGridViewCellStyle4.WrapMode = Global.System.Windows.Forms.DataGridViewTriState.[True]
			Me.dgw.RowHeadersDefaultCellStyle = dataGridViewCellStyle4
			Me.dgw.RowHeadersWidth = 25
			Me.dgw.RowHeadersWidthSizeMode = Global.System.Windows.Forms.DataGridViewRowHeadersWidthSizeMode.DisableResizing
			dataGridViewCellStyle5.BackColor = Global.System.Drawing.Color.White
			dataGridViewCellStyle5.Font = New Global.System.Drawing.Font("Tahoma", 8.25F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			dataGridViewCellStyle5.SelectionBackColor = Global.System.Drawing.Color.DarkSlateGray
			dataGridViewCellStyle5.SelectionForeColor = Global.System.Drawing.Color.White
			Me.dgw.RowsDefaultCellStyle = dataGridViewCellStyle5
			Me.dgw.RowTemplate.Height = 25
			Me.dgw.RowTemplate.Resizable = Global.System.Windows.Forms.DataGridViewTriState.[False]
			Me.dgw.SelectionMode = Global.System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect
			Me.dgw.Size = New Global.System.Drawing.Size(1132, 516)
			Me.dgw.TabIndex = 44
			Me.dgw.TabStop = False
			Me.Column2.HeaderText = "Invoice No."
			Me.Column2.Name = "Column2"
			Me.Column2.[ReadOnly] = True
			dataGridViewCellStyle6.Format = "dd/MM/yyyy"
			Me.Column3.DefaultCellStyle = dataGridViewCellStyle6
			Me.Column3.HeaderText = "Invoice Date"
			Me.Column3.Name = "Column3"
			Me.Column3.[ReadOnly] = True
			Me.Column14.HeaderText = "Tax Type"
			Me.Column14.Name = "Column14"
			Me.Column14.[ReadOnly] = True
			Me.Column6.HeaderText = "Customer Name"
			Me.Column6.Name = "Column6"
			Me.Column6.[ReadOnly] = True
			Me.Column16.HeaderText = "State"
			Me.Column16.Name = "Column16"
			Me.Column16.[ReadOnly] = True
			Me.Column17.HeaderText = "GSTIN"
			Me.Column17.Name = "Column17"
			Me.Column17.[ReadOnly] = True
			dataGridViewCellStyle7.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.Column18.DefaultCellStyle = dataGridViewCellStyle7
			Me.Column18.HeaderText = "Taxable Amount"
			Me.Column18.Name = "Column18"
			Me.Column18.[ReadOnly] = True
			dataGridViewCellStyle8.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.Column19.DefaultCellStyle = dataGridViewCellStyle8
			Me.Column19.HeaderText = "CGST"
			Me.Column19.Name = "Column19"
			Me.Column19.[ReadOnly] = True
			dataGridViewCellStyle9.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.Column20.DefaultCellStyle = dataGridViewCellStyle9
			Me.Column20.HeaderText = "SGST/UTGST"
			Me.Column20.Name = "Column20"
			Me.Column20.[ReadOnly] = True
			dataGridViewCellStyle10.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.Column21.DefaultCellStyle = dataGridViewCellStyle10
			Me.Column21.HeaderText = "IGST"
			Me.Column21.Name = "Column21"
			Me.Column21.[ReadOnly] = True
			dataGridViewCellStyle11.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.Column22.DefaultCellStyle = dataGridViewCellStyle11
			Me.Column22.HeaderText = "CESS"
			Me.Column22.Name = "Column22"
			Me.Column22.[ReadOnly] = True
			dataGridViewCellStyle12.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.Column23.DefaultCellStyle = dataGridViewCellStyle12
			Me.Column23.HeaderText = "Bill Sundry Charges"
			Me.Column23.Name = "Column23"
			Me.Column23.[ReadOnly] = True
			dataGridViewCellStyle13.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.Column24.DefaultCellStyle = dataGridViewCellStyle13
			Me.Column24.HeaderText = "Total Bill Discount"
			Me.Column24.Name = "Column24"
			Me.Column24.[ReadOnly] = True
			dataGridViewCellStyle14.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.Column25.DefaultCellStyle = dataGridViewCellStyle14
			Me.Column25.HeaderText = "Total"
			Me.Column25.Name = "Column25"
			Me.Column25.[ReadOnly] = True
			dataGridViewCellStyle15.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.Column26.DefaultCellStyle = dataGridViewCellStyle15
			Me.Column26.HeaderText = "Round Off"
			Me.Column26.Name = "Column26"
			Me.Column26.[ReadOnly] = True
			dataGridViewCellStyle16.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.Column7.DefaultCellStyle = dataGridViewCellStyle16
			Me.Column7.HeaderText = "Grand Total"
			Me.Column7.Name = "Column7"
			Me.Column7.[ReadOnly] = True
			Me.TabPage2.Controls.Add(Me.dgw1)
			Me.TabPage2.Controls.Add(Me.LinkLabel1)
			Me.TabPage2.Location = New Global.System.Drawing.Point(4, 22)
			Me.TabPage2.Name = "TabPage2"
			Me.TabPage2.Padding = New Global.System.Windows.Forms.Padding(3)
			Me.TabPage2.Size = New Global.System.Drawing.Size(1138, 541)
			Me.TabPage2.TabIndex = 1
			Me.TabPage2.Text = "B2CL"
			Me.TabPage2.UseVisualStyleBackColor = True
			Me.dgw1.AllowUserToAddRows = False
			Me.dgw1.AllowUserToDeleteRows = False
			dataGridViewCellStyle17.BackColor = Global.System.Drawing.Color.FloralWhite
			Me.dgw1.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle17
			Me.dgw1.BackgroundColor = Global.System.Drawing.Color.White
			Me.dgw1.ColumnHeadersBorderStyle = Global.System.Windows.Forms.DataGridViewHeaderBorderStyle.[Single]
			dataGridViewCellStyle18.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter
			dataGridViewCellStyle18.BackColor = Global.System.Drawing.Color.DarkViolet
			dataGridViewCellStyle18.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 8.25F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			dataGridViewCellStyle18.ForeColor = Global.System.Drawing.Color.White
			dataGridViewCellStyle18.SelectionBackColor = Global.System.Drawing.Color.LightSteelBlue
			dataGridViewCellStyle18.SelectionForeColor = Global.System.Drawing.SystemColors.HighlightText
			dataGridViewCellStyle18.WrapMode = Global.System.Windows.Forms.DataGridViewTriState.[True]
			Me.dgw1.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle18
			Me.dgw1.ColumnHeadersHeight = 30
			Me.dgw1.Columns.AddRange(New Global.System.Windows.Forms.DataGridViewColumn() { Me.DataGridViewTextBoxColumn2, Me.DataGridViewTextBoxColumn3, Me.DataGridViewTextBoxColumn4, Me.DataGridViewTextBoxColumn7, Me.DataGridViewTextBoxColumn9, Me.DataGridViewTextBoxColumn10, Me.DataGridViewTextBoxColumn14, Me.DataGridViewTextBoxColumn15, Me.DataGridViewTextBoxColumn16, Me.DataGridViewTextBoxColumn17, Me.DataGridViewTextBoxColumn18, Me.DataGridViewTextBoxColumn19, Me.DataGridViewTextBoxColumn20, Me.DataGridViewTextBoxColumn21, Me.DataGridViewTextBoxColumn22, Me.DataGridViewTextBoxColumn23 })
			Me.dgw1.Cursor = Global.System.Windows.Forms.Cursors.Hand
			dataGridViewCellStyle19.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft
			dataGridViewCellStyle19.BackColor = Global.System.Drawing.SystemColors.Window
			dataGridViewCellStyle19.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 8.25F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			dataGridViewCellStyle19.ForeColor = Global.System.Drawing.Color.Black
			dataGridViewCellStyle19.SelectionBackColor = Global.System.Drawing.SystemColors.Highlight
			dataGridViewCellStyle19.SelectionForeColor = Global.System.Drawing.SystemColors.HighlightText
			dataGridViewCellStyle19.WrapMode = Global.System.Windows.Forms.DataGridViewTriState.[False]
			Me.dgw1.DefaultCellStyle = dataGridViewCellStyle19
			Me.dgw1.EnableHeadersVisualStyles = False
			Me.dgw1.GridColor = Global.System.Drawing.Color.White
			Me.dgw1.Location = New Global.System.Drawing.Point(3, 3)
			Me.dgw1.MultiSelect = False
			Me.dgw1.Name = "dgw1"
			Me.dgw1.[ReadOnly] = True
			Me.dgw1.RowHeadersBorderStyle = Global.System.Windows.Forms.DataGridViewHeaderBorderStyle.[Single]
			dataGridViewCellStyle20.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft
			dataGridViewCellStyle20.BackColor = Global.System.Drawing.Color.DarkViolet
			dataGridViewCellStyle20.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 8.25F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			dataGridViewCellStyle20.ForeColor = Global.System.Drawing.Color.White
			dataGridViewCellStyle20.SelectionBackColor = Global.System.Drawing.Color.OrangeRed
			dataGridViewCellStyle20.SelectionForeColor = Global.System.Drawing.Color.White
			dataGridViewCellStyle20.WrapMode = Global.System.Windows.Forms.DataGridViewTriState.[True]
			Me.dgw1.RowHeadersDefaultCellStyle = dataGridViewCellStyle20
			Me.dgw1.RowHeadersWidth = 25
			Me.dgw1.RowHeadersWidthSizeMode = Global.System.Windows.Forms.DataGridViewRowHeadersWidthSizeMode.DisableResizing
			dataGridViewCellStyle21.BackColor = Global.System.Drawing.Color.White
			dataGridViewCellStyle21.Font = New Global.System.Drawing.Font("Tahoma", 8.25F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			dataGridViewCellStyle21.SelectionBackColor = Global.System.Drawing.Color.DarkSlateGray
			dataGridViewCellStyle21.SelectionForeColor = Global.System.Drawing.Color.White
			Me.dgw1.RowsDefaultCellStyle = dataGridViewCellStyle21
			Me.dgw1.RowTemplate.Height = 25
			Me.dgw1.RowTemplate.Resizable = Global.System.Windows.Forms.DataGridViewTriState.[False]
			Me.dgw1.SelectionMode = Global.System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect
			Me.dgw1.Size = New Global.System.Drawing.Size(1132, 516)
			Me.dgw1.TabIndex = 54
			Me.dgw1.TabStop = False
			Me.DataGridViewTextBoxColumn2.HeaderText = "Invoice No."
			Me.DataGridViewTextBoxColumn2.Name = "DataGridViewTextBoxColumn2"
			Me.DataGridViewTextBoxColumn2.[ReadOnly] = True
			dataGridViewCellStyle22.Format = "dd/MM/yyyy"
			Me.DataGridViewTextBoxColumn3.DefaultCellStyle = dataGridViewCellStyle22
			Me.DataGridViewTextBoxColumn3.HeaderText = "Invoice Date"
			Me.DataGridViewTextBoxColumn3.Name = "DataGridViewTextBoxColumn3"
			Me.DataGridViewTextBoxColumn3.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn4.HeaderText = "Tax Type"
			Me.DataGridViewTextBoxColumn4.Name = "DataGridViewTextBoxColumn4"
			Me.DataGridViewTextBoxColumn4.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn7.HeaderText = "Customer Name"
			Me.DataGridViewTextBoxColumn7.Name = "DataGridViewTextBoxColumn7"
			Me.DataGridViewTextBoxColumn7.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn9.HeaderText = "State"
			Me.DataGridViewTextBoxColumn9.Name = "DataGridViewTextBoxColumn9"
			Me.DataGridViewTextBoxColumn9.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn10.HeaderText = "GSTIN"
			Me.DataGridViewTextBoxColumn10.Name = "DataGridViewTextBoxColumn10"
			Me.DataGridViewTextBoxColumn10.[ReadOnly] = True
			dataGridViewCellStyle23.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn14.DefaultCellStyle = dataGridViewCellStyle23
			Me.DataGridViewTextBoxColumn14.HeaderText = "Taxable Amount"
			Me.DataGridViewTextBoxColumn14.Name = "DataGridViewTextBoxColumn14"
			Me.DataGridViewTextBoxColumn14.[ReadOnly] = True
			dataGridViewCellStyle24.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn15.DefaultCellStyle = dataGridViewCellStyle24
			Me.DataGridViewTextBoxColumn15.HeaderText = "CGST"
			Me.DataGridViewTextBoxColumn15.Name = "DataGridViewTextBoxColumn15"
			Me.DataGridViewTextBoxColumn15.[ReadOnly] = True
			dataGridViewCellStyle25.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn16.DefaultCellStyle = dataGridViewCellStyle25
			Me.DataGridViewTextBoxColumn16.HeaderText = "SGST/UTGST"
			Me.DataGridViewTextBoxColumn16.Name = "DataGridViewTextBoxColumn16"
			Me.DataGridViewTextBoxColumn16.[ReadOnly] = True
			dataGridViewCellStyle26.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn17.DefaultCellStyle = dataGridViewCellStyle26
			Me.DataGridViewTextBoxColumn17.HeaderText = "IGST"
			Me.DataGridViewTextBoxColumn17.Name = "DataGridViewTextBoxColumn17"
			Me.DataGridViewTextBoxColumn17.[ReadOnly] = True
			dataGridViewCellStyle27.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn18.DefaultCellStyle = dataGridViewCellStyle27
			Me.DataGridViewTextBoxColumn18.HeaderText = "CESS"
			Me.DataGridViewTextBoxColumn18.Name = "DataGridViewTextBoxColumn18"
			Me.DataGridViewTextBoxColumn18.[ReadOnly] = True
			dataGridViewCellStyle28.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn19.DefaultCellStyle = dataGridViewCellStyle28
			Me.DataGridViewTextBoxColumn19.HeaderText = "Bill Sundry Charges"
			Me.DataGridViewTextBoxColumn19.Name = "DataGridViewTextBoxColumn19"
			Me.DataGridViewTextBoxColumn19.[ReadOnly] = True
			dataGridViewCellStyle29.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn20.DefaultCellStyle = dataGridViewCellStyle29
			Me.DataGridViewTextBoxColumn20.HeaderText = "Total Bill Discount"
			Me.DataGridViewTextBoxColumn20.Name = "DataGridViewTextBoxColumn20"
			Me.DataGridViewTextBoxColumn20.[ReadOnly] = True
			dataGridViewCellStyle30.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn21.DefaultCellStyle = dataGridViewCellStyle30
			Me.DataGridViewTextBoxColumn21.HeaderText = "Total"
			Me.DataGridViewTextBoxColumn21.Name = "DataGridViewTextBoxColumn21"
			Me.DataGridViewTextBoxColumn21.[ReadOnly] = True
			dataGridViewCellStyle31.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn22.DefaultCellStyle = dataGridViewCellStyle31
			Me.DataGridViewTextBoxColumn22.HeaderText = "Round Off"
			Me.DataGridViewTextBoxColumn22.Name = "DataGridViewTextBoxColumn22"
			Me.DataGridViewTextBoxColumn22.[ReadOnly] = True
			dataGridViewCellStyle32.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn23.DefaultCellStyle = dataGridViewCellStyle32
			Me.DataGridViewTextBoxColumn23.HeaderText = "Grand Total"
			Me.DataGridViewTextBoxColumn23.Name = "DataGridViewTextBoxColumn23"
			Me.DataGridViewTextBoxColumn23.[ReadOnly] = True
			Me.LinkLabel1.AutoSize = True
			Me.LinkLabel1.Cursor = Global.System.Windows.Forms.Cursors.Hand
			Me.LinkLabel1.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 9.75F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			Me.LinkLabel1.Location = New Global.System.Drawing.Point(1036, 522)
			Me.LinkLabel1.Name = "LinkLabel1"
			Me.LinkLabel1.Size = New Global.System.Drawing.Size(102, 16)
			Me.LinkLabel1.TabIndex = 53
			Me.LinkLabel1.TabStop = True
			Me.LinkLabel1.Text = "Export To Excel"
			Me.TabPage3.Controls.Add(Me.LinkLabel3)
			Me.TabPage3.Controls.Add(Me.dgw2)
			Me.TabPage3.Location = New Global.System.Drawing.Point(4, 22)
			Me.TabPage3.Name = "TabPage3"
			Me.TabPage3.Padding = New Global.System.Windows.Forms.Padding(3)
			Me.TabPage3.Size = New Global.System.Drawing.Size(1138, 541)
			Me.TabPage3.TabIndex = 2
			Me.TabPage3.Text = "B2CS"
			Me.TabPage3.UseVisualStyleBackColor = True
			Me.LinkLabel3.AutoSize = True
			Me.LinkLabel3.Cursor = Global.System.Windows.Forms.Cursors.Hand
			Me.LinkLabel3.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 9.75F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			Me.LinkLabel3.Location = New Global.System.Drawing.Point(1036, 522)
			Me.LinkLabel3.Name = "LinkLabel3"
			Me.LinkLabel3.Size = New Global.System.Drawing.Size(102, 16)
			Me.LinkLabel3.TabIndex = 56
			Me.LinkLabel3.TabStop = True
			Me.LinkLabel3.Text = "Export To Excel"
			Me.dgw2.AllowUserToAddRows = False
			Me.dgw2.AllowUserToDeleteRows = False
			dataGridViewCellStyle33.BackColor = Global.System.Drawing.Color.FloralWhite
			Me.dgw2.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle33
			Me.dgw2.BackgroundColor = Global.System.Drawing.Color.White
			Me.dgw2.ColumnHeadersBorderStyle = Global.System.Windows.Forms.DataGridViewHeaderBorderStyle.[Single]
			dataGridViewCellStyle34.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter
			dataGridViewCellStyle34.BackColor = Global.System.Drawing.Color.DarkViolet
			dataGridViewCellStyle34.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 8.25F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			dataGridViewCellStyle34.ForeColor = Global.System.Drawing.Color.White
			dataGridViewCellStyle34.SelectionBackColor = Global.System.Drawing.Color.LightSteelBlue
			dataGridViewCellStyle34.SelectionForeColor = Global.System.Drawing.SystemColors.HighlightText
			dataGridViewCellStyle34.WrapMode = Global.System.Windows.Forms.DataGridViewTriState.[True]
			Me.dgw2.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle34
			Me.dgw2.ColumnHeadersHeight = 30
			Me.dgw2.Columns.AddRange(New Global.System.Windows.Forms.DataGridViewColumn() { Me.DataGridViewTextBoxColumn29, Me.DataGridViewTextBoxColumn30, Me.DataGridViewTextBoxColumn31, Me.DataGridViewTextBoxColumn34, Me.DataGridViewTextBoxColumn36, Me.DataGridViewTextBoxColumn37, Me.DataGridViewTextBoxColumn41, Me.DataGridViewTextBoxColumn42, Me.DataGridViewTextBoxColumn43, Me.DataGridViewTextBoxColumn44, Me.DataGridViewTextBoxColumn45, Me.DataGridViewTextBoxColumn46, Me.DataGridViewTextBoxColumn47, Me.DataGridViewTextBoxColumn48, Me.DataGridViewTextBoxColumn49, Me.DataGridViewTextBoxColumn50 })
			Me.dgw2.Cursor = Global.System.Windows.Forms.Cursors.Hand
			dataGridViewCellStyle35.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft
			dataGridViewCellStyle35.BackColor = Global.System.Drawing.SystemColors.Window
			dataGridViewCellStyle35.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 8.25F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			dataGridViewCellStyle35.ForeColor = Global.System.Drawing.Color.Black
			dataGridViewCellStyle35.SelectionBackColor = Global.System.Drawing.SystemColors.Highlight
			dataGridViewCellStyle35.SelectionForeColor = Global.System.Drawing.SystemColors.HighlightText
			dataGridViewCellStyle35.WrapMode = Global.System.Windows.Forms.DataGridViewTriState.[False]
			Me.dgw2.DefaultCellStyle = dataGridViewCellStyle35
			Me.dgw2.EnableHeadersVisualStyles = False
			Me.dgw2.GridColor = Global.System.Drawing.Color.White
			Me.dgw2.Location = New Global.System.Drawing.Point(3, 3)
			Me.dgw2.MultiSelect = False
			Me.dgw2.Name = "dgw2"
			Me.dgw2.[ReadOnly] = True
			Me.dgw2.RowHeadersBorderStyle = Global.System.Windows.Forms.DataGridViewHeaderBorderStyle.[Single]
			dataGridViewCellStyle36.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft
			dataGridViewCellStyle36.BackColor = Global.System.Drawing.Color.DarkViolet
			dataGridViewCellStyle36.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 8.25F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			dataGridViewCellStyle36.ForeColor = Global.System.Drawing.Color.White
			dataGridViewCellStyle36.SelectionBackColor = Global.System.Drawing.Color.OrangeRed
			dataGridViewCellStyle36.SelectionForeColor = Global.System.Drawing.Color.White
			dataGridViewCellStyle36.WrapMode = Global.System.Windows.Forms.DataGridViewTriState.[True]
			Me.dgw2.RowHeadersDefaultCellStyle = dataGridViewCellStyle36
			Me.dgw2.RowHeadersWidth = 25
			Me.dgw2.RowHeadersWidthSizeMode = Global.System.Windows.Forms.DataGridViewRowHeadersWidthSizeMode.DisableResizing
			dataGridViewCellStyle37.BackColor = Global.System.Drawing.Color.White
			dataGridViewCellStyle37.Font = New Global.System.Drawing.Font("Tahoma", 8.25F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			dataGridViewCellStyle37.SelectionBackColor = Global.System.Drawing.Color.DarkSlateGray
			dataGridViewCellStyle37.SelectionForeColor = Global.System.Drawing.Color.White
			Me.dgw2.RowsDefaultCellStyle = dataGridViewCellStyle37
			Me.dgw2.RowTemplate.Height = 25
			Me.dgw2.RowTemplate.Resizable = Global.System.Windows.Forms.DataGridViewTriState.[False]
			Me.dgw2.SelectionMode = Global.System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect
			Me.dgw2.Size = New Global.System.Drawing.Size(1132, 516)
			Me.dgw2.TabIndex = 55
			Me.dgw2.TabStop = False
			Me.DataGridViewTextBoxColumn29.HeaderText = "Invoice No."
			Me.DataGridViewTextBoxColumn29.Name = "DataGridViewTextBoxColumn29"
			Me.DataGridViewTextBoxColumn29.[ReadOnly] = True
			dataGridViewCellStyle38.Format = "dd/MM/yyyy"
			Me.DataGridViewTextBoxColumn30.DefaultCellStyle = dataGridViewCellStyle38
			Me.DataGridViewTextBoxColumn30.HeaderText = "Invoice Date"
			Me.DataGridViewTextBoxColumn30.Name = "DataGridViewTextBoxColumn30"
			Me.DataGridViewTextBoxColumn30.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn31.HeaderText = "Tax Type"
			Me.DataGridViewTextBoxColumn31.Name = "DataGridViewTextBoxColumn31"
			Me.DataGridViewTextBoxColumn31.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn34.HeaderText = "Customer Name"
			Me.DataGridViewTextBoxColumn34.Name = "DataGridViewTextBoxColumn34"
			Me.DataGridViewTextBoxColumn34.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn36.HeaderText = "State"
			Me.DataGridViewTextBoxColumn36.Name = "DataGridViewTextBoxColumn36"
			Me.DataGridViewTextBoxColumn36.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn37.HeaderText = "GSTIN"
			Me.DataGridViewTextBoxColumn37.Name = "DataGridViewTextBoxColumn37"
			Me.DataGridViewTextBoxColumn37.[ReadOnly] = True
			dataGridViewCellStyle39.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn41.DefaultCellStyle = dataGridViewCellStyle39
			Me.DataGridViewTextBoxColumn41.HeaderText = "Taxable Amount"
			Me.DataGridViewTextBoxColumn41.Name = "DataGridViewTextBoxColumn41"
			Me.DataGridViewTextBoxColumn41.[ReadOnly] = True
			dataGridViewCellStyle40.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn42.DefaultCellStyle = dataGridViewCellStyle40
			Me.DataGridViewTextBoxColumn42.HeaderText = "CGST"
			Me.DataGridViewTextBoxColumn42.Name = "DataGridViewTextBoxColumn42"
			Me.DataGridViewTextBoxColumn42.[ReadOnly] = True
			dataGridViewCellStyle41.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn43.DefaultCellStyle = dataGridViewCellStyle41
			Me.DataGridViewTextBoxColumn43.HeaderText = "SGST/UTGST"
			Me.DataGridViewTextBoxColumn43.Name = "DataGridViewTextBoxColumn43"
			Me.DataGridViewTextBoxColumn43.[ReadOnly] = True
			dataGridViewCellStyle42.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn44.DefaultCellStyle = dataGridViewCellStyle42
			Me.DataGridViewTextBoxColumn44.HeaderText = "IGST"
			Me.DataGridViewTextBoxColumn44.Name = "DataGridViewTextBoxColumn44"
			Me.DataGridViewTextBoxColumn44.[ReadOnly] = True
			dataGridViewCellStyle43.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn45.DefaultCellStyle = dataGridViewCellStyle43
			Me.DataGridViewTextBoxColumn45.HeaderText = "CESS"
			Me.DataGridViewTextBoxColumn45.Name = "DataGridViewTextBoxColumn45"
			Me.DataGridViewTextBoxColumn45.[ReadOnly] = True
			dataGridViewCellStyle44.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn46.DefaultCellStyle = dataGridViewCellStyle44
			Me.DataGridViewTextBoxColumn46.HeaderText = "Bill Sundry Charges"
			Me.DataGridViewTextBoxColumn46.Name = "DataGridViewTextBoxColumn46"
			Me.DataGridViewTextBoxColumn46.[ReadOnly] = True
			dataGridViewCellStyle45.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn47.DefaultCellStyle = dataGridViewCellStyle45
			Me.DataGridViewTextBoxColumn47.HeaderText = "Total Bill Discount"
			Me.DataGridViewTextBoxColumn47.Name = "DataGridViewTextBoxColumn47"
			Me.DataGridViewTextBoxColumn47.[ReadOnly] = True
			dataGridViewCellStyle46.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn48.DefaultCellStyle = dataGridViewCellStyle46
			Me.DataGridViewTextBoxColumn48.HeaderText = "Total"
			Me.DataGridViewTextBoxColumn48.Name = "DataGridViewTextBoxColumn48"
			Me.DataGridViewTextBoxColumn48.[ReadOnly] = True
			dataGridViewCellStyle47.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn49.DefaultCellStyle = dataGridViewCellStyle47
			Me.DataGridViewTextBoxColumn49.HeaderText = "Round Off"
			Me.DataGridViewTextBoxColumn49.Name = "DataGridViewTextBoxColumn49"
			Me.DataGridViewTextBoxColumn49.[ReadOnly] = True
			dataGridViewCellStyle48.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn50.DefaultCellStyle = dataGridViewCellStyle48
			Me.DataGridViewTextBoxColumn50.HeaderText = "Grand Total"
			Me.DataGridViewTextBoxColumn50.Name = "DataGridViewTextBoxColumn50"
			Me.DataGridViewTextBoxColumn50.[ReadOnly] = True
			Me.TabPage4.Controls.Add(Me.LinkLabel4)
			Me.TabPage4.Controls.Add(Me.dgw3)
			Me.TabPage4.Location = New Global.System.Drawing.Point(4, 22)
			Me.TabPage4.Name = "TabPage4"
			Me.TabPage4.Padding = New Global.System.Windows.Forms.Padding(3)
			Me.TabPage4.Size = New Global.System.Drawing.Size(1138, 541)
			Me.TabPage4.TabIndex = 3
			Me.TabPage4.Text = "CDNR"
			Me.TabPage4.UseVisualStyleBackColor = True
			Me.LinkLabel4.AutoSize = True
			Me.LinkLabel4.Cursor = Global.System.Windows.Forms.Cursors.Hand
			Me.LinkLabel4.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 9.75F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			Me.LinkLabel4.Location = New Global.System.Drawing.Point(1036, 522)
			Me.LinkLabel4.Name = "LinkLabel4"
			Me.LinkLabel4.Size = New Global.System.Drawing.Size(102, 16)
			Me.LinkLabel4.TabIndex = 54
			Me.LinkLabel4.TabStop = True
			Me.LinkLabel4.Text = "Export To Excel"
			Me.dgw3.AllowUserToAddRows = False
			Me.dgw3.AllowUserToDeleteRows = False
			dataGridViewCellStyle49.BackColor = Global.System.Drawing.Color.FloralWhite
			Me.dgw3.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle49
			Me.dgw3.BackgroundColor = Global.System.Drawing.Color.White
			Me.dgw3.ColumnHeadersBorderStyle = Global.System.Windows.Forms.DataGridViewHeaderBorderStyle.[Single]
			dataGridViewCellStyle50.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter
			dataGridViewCellStyle50.BackColor = Global.System.Drawing.Color.DarkViolet
			dataGridViewCellStyle50.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 8.25F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			dataGridViewCellStyle50.ForeColor = Global.System.Drawing.Color.White
			dataGridViewCellStyle50.SelectionBackColor = Global.System.Drawing.Color.LightSteelBlue
			dataGridViewCellStyle50.SelectionForeColor = Global.System.Drawing.SystemColors.HighlightText
			dataGridViewCellStyle50.WrapMode = Global.System.Windows.Forms.DataGridViewTriState.[True]
			Me.dgw3.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle50
			Me.dgw3.ColumnHeadersHeight = 30
			Me.dgw3.Columns.AddRange(New Global.System.Windows.Forms.DataGridViewColumn() { Me.Column28, Me.DataGridViewTextBoxColumn56, Me.DataGridViewTextBoxColumn57, Me.DataGridViewTextBoxColumn59, Me.DataGridViewTextBoxColumn60, Me.DataGridViewTextBoxColumn62, Me.Column29, Me.Column30, Me.DataGridViewTextBoxColumn63, Me.DataGridViewTextBoxColumn64, Me.DataGridViewTextBoxColumn65, Me.DataGridViewTextBoxColumn66, Me.DataGridViewTextBoxColumn67, Me.DataGridViewTextBoxColumn68, Me.DataGridViewTextBoxColumn69, Me.DataGridViewTextBoxColumn70, Me.DataGridViewTextBoxColumn71, Me.DataGridViewTextBoxColumn72 })
			Me.dgw3.Cursor = Global.System.Windows.Forms.Cursors.Hand
			dataGridViewCellStyle51.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft
			dataGridViewCellStyle51.BackColor = Global.System.Drawing.SystemColors.Window
			dataGridViewCellStyle51.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 8.25F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			dataGridViewCellStyle51.ForeColor = Global.System.Drawing.Color.Black
			dataGridViewCellStyle51.SelectionBackColor = Global.System.Drawing.SystemColors.Highlight
			dataGridViewCellStyle51.SelectionForeColor = Global.System.Drawing.SystemColors.HighlightText
			dataGridViewCellStyle51.WrapMode = Global.System.Windows.Forms.DataGridViewTriState.[False]
			Me.dgw3.DefaultCellStyle = dataGridViewCellStyle51
			Me.dgw3.EnableHeadersVisualStyles = False
			Me.dgw3.GridColor = Global.System.Drawing.Color.White
			Me.dgw3.Location = New Global.System.Drawing.Point(3, 3)
			Me.dgw3.MultiSelect = False
			Me.dgw3.Name = "dgw3"
			Me.dgw3.[ReadOnly] = True
			Me.dgw3.RowHeadersBorderStyle = Global.System.Windows.Forms.DataGridViewHeaderBorderStyle.[Single]
			dataGridViewCellStyle52.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft
			dataGridViewCellStyle52.BackColor = Global.System.Drawing.Color.DarkViolet
			dataGridViewCellStyle52.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 8.25F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			dataGridViewCellStyle52.ForeColor = Global.System.Drawing.Color.White
			dataGridViewCellStyle52.SelectionBackColor = Global.System.Drawing.Color.OrangeRed
			dataGridViewCellStyle52.SelectionForeColor = Global.System.Drawing.Color.White
			dataGridViewCellStyle52.WrapMode = Global.System.Windows.Forms.DataGridViewTriState.[True]
			Me.dgw3.RowHeadersDefaultCellStyle = dataGridViewCellStyle52
			Me.dgw3.RowHeadersWidth = 25
			Me.dgw3.RowHeadersWidthSizeMode = Global.System.Windows.Forms.DataGridViewRowHeadersWidthSizeMode.DisableResizing
			dataGridViewCellStyle53.BackColor = Global.System.Drawing.Color.White
			dataGridViewCellStyle53.Font = New Global.System.Drawing.Font("Tahoma", 8.25F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			dataGridViewCellStyle53.SelectionBackColor = Global.System.Drawing.Color.DarkSlateGray
			dataGridViewCellStyle53.SelectionForeColor = Global.System.Drawing.Color.White
			Me.dgw3.RowsDefaultCellStyle = dataGridViewCellStyle53
			Me.dgw3.RowTemplate.Height = 25
			Me.dgw3.RowTemplate.Resizable = Global.System.Windows.Forms.DataGridViewTriState.[False]
			Me.dgw3.SelectionMode = Global.System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect
			Me.dgw3.Size = New Global.System.Drawing.Size(1132, 516)
			Me.dgw3.TabIndex = 44
			Me.Column28.HeaderText = "Sale Return No."
			Me.Column28.Name = "Column28"
			Me.Column28.[ReadOnly] = True
			dataGridViewCellStyle54.Format = "dd/MM/yyyy"
			Me.DataGridViewTextBoxColumn56.DefaultCellStyle = dataGridViewCellStyle54
			Me.DataGridViewTextBoxColumn56.HeaderText = "Sale Return Date"
			Me.DataGridViewTextBoxColumn56.Name = "DataGridViewTextBoxColumn56"
			Me.DataGridViewTextBoxColumn56.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn57.HeaderText = "Tax Type"
			Me.DataGridViewTextBoxColumn57.Name = "DataGridViewTextBoxColumn57"
			Me.DataGridViewTextBoxColumn57.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn59.HeaderText = "Sales Invoice No."
			Me.DataGridViewTextBoxColumn59.Name = "DataGridViewTextBoxColumn59"
			Me.DataGridViewTextBoxColumn59.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn59.Width = 150
			dataGridViewCellStyle55.Format = "dd/MM/yyyy"
			Me.DataGridViewTextBoxColumn60.DefaultCellStyle = dataGridViewCellStyle55
			Me.DataGridViewTextBoxColumn60.HeaderText = "Sales Date"
			Me.DataGridViewTextBoxColumn60.Name = "DataGridViewTextBoxColumn60"
			Me.DataGridViewTextBoxColumn60.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn62.HeaderText = "Customer Name"
			Me.DataGridViewTextBoxColumn62.Name = "DataGridViewTextBoxColumn62"
			Me.DataGridViewTextBoxColumn62.[ReadOnly] = True
			Me.Column29.HeaderText = "Customer State"
			Me.Column29.Name = "Column29"
			Me.Column29.[ReadOnly] = True
			Me.Column30.HeaderText = "Customer GSTIN"
			Me.Column30.Name = "Column30"
			Me.Column30.[ReadOnly] = True
			dataGridViewCellStyle56.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn63.DefaultCellStyle = dataGridViewCellStyle56
			Me.DataGridViewTextBoxColumn63.HeaderText = "Taxable Amount"
			Me.DataGridViewTextBoxColumn63.Name = "DataGridViewTextBoxColumn63"
			Me.DataGridViewTextBoxColumn63.[ReadOnly] = True
			dataGridViewCellStyle57.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn64.DefaultCellStyle = dataGridViewCellStyle57
			Me.DataGridViewTextBoxColumn64.HeaderText = "CGST"
			Me.DataGridViewTextBoxColumn64.Name = "DataGridViewTextBoxColumn64"
			Me.DataGridViewTextBoxColumn64.[ReadOnly] = True
			dataGridViewCellStyle58.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn65.DefaultCellStyle = dataGridViewCellStyle58
			Me.DataGridViewTextBoxColumn65.HeaderText = "SGST/UTGST"
			Me.DataGridViewTextBoxColumn65.Name = "DataGridViewTextBoxColumn65"
			Me.DataGridViewTextBoxColumn65.[ReadOnly] = True
			dataGridViewCellStyle59.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn66.DefaultCellStyle = dataGridViewCellStyle59
			Me.DataGridViewTextBoxColumn66.HeaderText = "IGST"
			Me.DataGridViewTextBoxColumn66.Name = "DataGridViewTextBoxColumn66"
			Me.DataGridViewTextBoxColumn66.[ReadOnly] = True
			dataGridViewCellStyle60.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn67.DefaultCellStyle = dataGridViewCellStyle60
			Me.DataGridViewTextBoxColumn67.HeaderText = "CESS"
			Me.DataGridViewTextBoxColumn67.Name = "DataGridViewTextBoxColumn67"
			Me.DataGridViewTextBoxColumn67.[ReadOnly] = True
			dataGridViewCellStyle61.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn68.DefaultCellStyle = dataGridViewCellStyle61
			Me.DataGridViewTextBoxColumn68.HeaderText = "Bill Sundry Charges"
			Me.DataGridViewTextBoxColumn68.Name = "DataGridViewTextBoxColumn68"
			Me.DataGridViewTextBoxColumn68.[ReadOnly] = True
			dataGridViewCellStyle62.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn69.DefaultCellStyle = dataGridViewCellStyle62
			Me.DataGridViewTextBoxColumn69.HeaderText = "Total Bill Discount"
			Me.DataGridViewTextBoxColumn69.Name = "DataGridViewTextBoxColumn69"
			Me.DataGridViewTextBoxColumn69.[ReadOnly] = True
			dataGridViewCellStyle63.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn70.DefaultCellStyle = dataGridViewCellStyle63
			Me.DataGridViewTextBoxColumn70.HeaderText = "Total"
			Me.DataGridViewTextBoxColumn70.Name = "DataGridViewTextBoxColumn70"
			Me.DataGridViewTextBoxColumn70.[ReadOnly] = True
			dataGridViewCellStyle64.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn71.DefaultCellStyle = dataGridViewCellStyle64
			Me.DataGridViewTextBoxColumn71.HeaderText = "Round Off"
			Me.DataGridViewTextBoxColumn71.Name = "DataGridViewTextBoxColumn71"
			Me.DataGridViewTextBoxColumn71.[ReadOnly] = True
			dataGridViewCellStyle65.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn72.DefaultCellStyle = dataGridViewCellStyle65
			Me.DataGridViewTextBoxColumn72.HeaderText = "Grand Total"
			Me.DataGridViewTextBoxColumn72.Name = "DataGridViewTextBoxColumn72"
			Me.DataGridViewTextBoxColumn72.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn72.Width = 150
			Me.TabPage5.Controls.Add(Me.LinkLabel5)
			Me.TabPage5.Controls.Add(Me.dgw4)
			Me.TabPage5.Location = New Global.System.Drawing.Point(4, 22)
			Me.TabPage5.Name = "TabPage5"
			Me.TabPage5.Padding = New Global.System.Windows.Forms.Padding(3)
			Me.TabPage5.Size = New Global.System.Drawing.Size(1138, 541)
			Me.TabPage5.TabIndex = 4
			Me.TabPage5.Text = "CDNUR"
			Me.TabPage5.UseVisualStyleBackColor = True
			Me.LinkLabel5.AutoSize = True
			Me.LinkLabel5.Cursor = Global.System.Windows.Forms.Cursors.Hand
			Me.LinkLabel5.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 9.75F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			Me.LinkLabel5.Location = New Global.System.Drawing.Point(1035, 522)
			Me.LinkLabel5.Name = "LinkLabel5"
			Me.LinkLabel5.Size = New Global.System.Drawing.Size(102, 16)
			Me.LinkLabel5.TabIndex = 54
			Me.LinkLabel5.TabStop = True
			Me.LinkLabel5.Text = "Export To Excel"
			Me.dgw4.AllowUserToAddRows = False
			Me.dgw4.AllowUserToDeleteRows = False
			dataGridViewCellStyle66.BackColor = Global.System.Drawing.Color.FloralWhite
			Me.dgw4.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle66
			Me.dgw4.BackgroundColor = Global.System.Drawing.Color.White
			Me.dgw4.ColumnHeadersBorderStyle = Global.System.Windows.Forms.DataGridViewHeaderBorderStyle.[Single]
			dataGridViewCellStyle67.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter
			dataGridViewCellStyle67.BackColor = Global.System.Drawing.Color.DarkViolet
			dataGridViewCellStyle67.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 8.25F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			dataGridViewCellStyle67.ForeColor = Global.System.Drawing.Color.White
			dataGridViewCellStyle67.SelectionBackColor = Global.System.Drawing.Color.LightSteelBlue
			dataGridViewCellStyle67.SelectionForeColor = Global.System.Drawing.SystemColors.HighlightText
			dataGridViewCellStyle67.WrapMode = Global.System.Windows.Forms.DataGridViewTriState.[True]
			Me.dgw4.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle67
			Me.dgw4.ColumnHeadersHeight = 30
			Me.dgw4.Columns.AddRange(New Global.System.Windows.Forms.DataGridViewColumn() { Me.DataGridViewTextBoxColumn74, Me.DataGridViewTextBoxColumn75, Me.DataGridViewTextBoxColumn76, Me.DataGridViewTextBoxColumn78, Me.DataGridViewTextBoxColumn79, Me.DataGridViewTextBoxColumn81, Me.DataGridViewTextBoxColumn82, Me.DataGridViewTextBoxColumn83, Me.DataGridViewTextBoxColumn84, Me.DataGridViewTextBoxColumn85, Me.DataGridViewTextBoxColumn86, Me.DataGridViewTextBoxColumn87, Me.DataGridViewTextBoxColumn88, Me.DataGridViewTextBoxColumn89, Me.DataGridViewTextBoxColumn90, Me.DataGridViewTextBoxColumn91, Me.DataGridViewTextBoxColumn92, Me.DataGridViewTextBoxColumn93 })
			Me.dgw4.Cursor = Global.System.Windows.Forms.Cursors.Hand
			dataGridViewCellStyle68.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft
			dataGridViewCellStyle68.BackColor = Global.System.Drawing.SystemColors.Window
			dataGridViewCellStyle68.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 8.25F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			dataGridViewCellStyle68.ForeColor = Global.System.Drawing.Color.Black
			dataGridViewCellStyle68.SelectionBackColor = Global.System.Drawing.SystemColors.Highlight
			dataGridViewCellStyle68.SelectionForeColor = Global.System.Drawing.SystemColors.HighlightText
			dataGridViewCellStyle68.WrapMode = Global.System.Windows.Forms.DataGridViewTriState.[False]
			Me.dgw4.DefaultCellStyle = dataGridViewCellStyle68
			Me.dgw4.EnableHeadersVisualStyles = False
			Me.dgw4.GridColor = Global.System.Drawing.Color.White
			Me.dgw4.Location = New Global.System.Drawing.Point(3, 3)
			Me.dgw4.MultiSelect = False
			Me.dgw4.Name = "dgw4"
			Me.dgw4.[ReadOnly] = True
			Me.dgw4.RowHeadersBorderStyle = Global.System.Windows.Forms.DataGridViewHeaderBorderStyle.[Single]
			dataGridViewCellStyle69.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft
			dataGridViewCellStyle69.BackColor = Global.System.Drawing.Color.DarkViolet
			dataGridViewCellStyle69.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 8.25F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			dataGridViewCellStyle69.ForeColor = Global.System.Drawing.Color.White
			dataGridViewCellStyle69.SelectionBackColor = Global.System.Drawing.Color.OrangeRed
			dataGridViewCellStyle69.SelectionForeColor = Global.System.Drawing.Color.White
			dataGridViewCellStyle69.WrapMode = Global.System.Windows.Forms.DataGridViewTriState.[True]
			Me.dgw4.RowHeadersDefaultCellStyle = dataGridViewCellStyle69
			Me.dgw4.RowHeadersWidth = 25
			Me.dgw4.RowHeadersWidthSizeMode = Global.System.Windows.Forms.DataGridViewRowHeadersWidthSizeMode.DisableResizing
			dataGridViewCellStyle70.BackColor = Global.System.Drawing.Color.White
			dataGridViewCellStyle70.Font = New Global.System.Drawing.Font("Tahoma", 8.25F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			dataGridViewCellStyle70.SelectionBackColor = Global.System.Drawing.Color.DarkSlateGray
			dataGridViewCellStyle70.SelectionForeColor = Global.System.Drawing.Color.White
			Me.dgw4.RowsDefaultCellStyle = dataGridViewCellStyle70
			Me.dgw4.RowTemplate.Height = 25
			Me.dgw4.RowTemplate.Resizable = Global.System.Windows.Forms.DataGridViewTriState.[False]
			Me.dgw4.SelectionMode = Global.System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect
			Me.dgw4.Size = New Global.System.Drawing.Size(1132, 516)
			Me.dgw4.TabIndex = 45
			Me.DataGridViewTextBoxColumn74.HeaderText = "Sale Return No."
			Me.DataGridViewTextBoxColumn74.Name = "DataGridViewTextBoxColumn74"
			Me.DataGridViewTextBoxColumn74.[ReadOnly] = True
			dataGridViewCellStyle71.Format = "dd/MM/yyyy"
			Me.DataGridViewTextBoxColumn75.DefaultCellStyle = dataGridViewCellStyle71
			Me.DataGridViewTextBoxColumn75.HeaderText = "Sale Return Date"
			Me.DataGridViewTextBoxColumn75.Name = "DataGridViewTextBoxColumn75"
			Me.DataGridViewTextBoxColumn75.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn76.HeaderText = "Tax Type"
			Me.DataGridViewTextBoxColumn76.Name = "DataGridViewTextBoxColumn76"
			Me.DataGridViewTextBoxColumn76.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn78.HeaderText = "Sales Invoice No."
			Me.DataGridViewTextBoxColumn78.Name = "DataGridViewTextBoxColumn78"
			Me.DataGridViewTextBoxColumn78.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn78.Width = 150
			dataGridViewCellStyle72.Format = "dd/MM/yyyy"
			Me.DataGridViewTextBoxColumn79.DefaultCellStyle = dataGridViewCellStyle72
			Me.DataGridViewTextBoxColumn79.HeaderText = "Sales Date"
			Me.DataGridViewTextBoxColumn79.Name = "DataGridViewTextBoxColumn79"
			Me.DataGridViewTextBoxColumn79.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn81.HeaderText = "Customer Name"
			Me.DataGridViewTextBoxColumn81.Name = "DataGridViewTextBoxColumn81"
			Me.DataGridViewTextBoxColumn81.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn82.HeaderText = "Customer State"
			Me.DataGridViewTextBoxColumn82.Name = "DataGridViewTextBoxColumn82"
			Me.DataGridViewTextBoxColumn82.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn83.HeaderText = "Customer GSTIN"
			Me.DataGridViewTextBoxColumn83.Name = "DataGridViewTextBoxColumn83"
			Me.DataGridViewTextBoxColumn83.[ReadOnly] = True
			dataGridViewCellStyle73.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn84.DefaultCellStyle = dataGridViewCellStyle73
			Me.DataGridViewTextBoxColumn84.HeaderText = "Taxable Amount"
			Me.DataGridViewTextBoxColumn84.Name = "DataGridViewTextBoxColumn84"
			Me.DataGridViewTextBoxColumn84.[ReadOnly] = True
			dataGridViewCellStyle74.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn85.DefaultCellStyle = dataGridViewCellStyle74
			Me.DataGridViewTextBoxColumn85.HeaderText = "CGST"
			Me.DataGridViewTextBoxColumn85.Name = "DataGridViewTextBoxColumn85"
			Me.DataGridViewTextBoxColumn85.[ReadOnly] = True
			dataGridViewCellStyle75.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn86.DefaultCellStyle = dataGridViewCellStyle75
			Me.DataGridViewTextBoxColumn86.HeaderText = "SGST/UTGST"
			Me.DataGridViewTextBoxColumn86.Name = "DataGridViewTextBoxColumn86"
			Me.DataGridViewTextBoxColumn86.[ReadOnly] = True
			dataGridViewCellStyle76.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn87.DefaultCellStyle = dataGridViewCellStyle76
			Me.DataGridViewTextBoxColumn87.HeaderText = "IGST"
			Me.DataGridViewTextBoxColumn87.Name = "DataGridViewTextBoxColumn87"
			Me.DataGridViewTextBoxColumn87.[ReadOnly] = True
			dataGridViewCellStyle77.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn88.DefaultCellStyle = dataGridViewCellStyle77
			Me.DataGridViewTextBoxColumn88.HeaderText = "CESS"
			Me.DataGridViewTextBoxColumn88.Name = "DataGridViewTextBoxColumn88"
			Me.DataGridViewTextBoxColumn88.[ReadOnly] = True
			dataGridViewCellStyle78.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn89.DefaultCellStyle = dataGridViewCellStyle78
			Me.DataGridViewTextBoxColumn89.HeaderText = "Bill Sundry Charges"
			Me.DataGridViewTextBoxColumn89.Name = "DataGridViewTextBoxColumn89"
			Me.DataGridViewTextBoxColumn89.[ReadOnly] = True
			dataGridViewCellStyle79.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn90.DefaultCellStyle = dataGridViewCellStyle79
			Me.DataGridViewTextBoxColumn90.HeaderText = "Total Bill Discount"
			Me.DataGridViewTextBoxColumn90.Name = "DataGridViewTextBoxColumn90"
			Me.DataGridViewTextBoxColumn90.[ReadOnly] = True
			dataGridViewCellStyle80.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn91.DefaultCellStyle = dataGridViewCellStyle80
			Me.DataGridViewTextBoxColumn91.HeaderText = "Total"
			Me.DataGridViewTextBoxColumn91.Name = "DataGridViewTextBoxColumn91"
			Me.DataGridViewTextBoxColumn91.[ReadOnly] = True
			dataGridViewCellStyle81.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn92.DefaultCellStyle = dataGridViewCellStyle81
			Me.DataGridViewTextBoxColumn92.HeaderText = "Round Off"
			Me.DataGridViewTextBoxColumn92.Name = "DataGridViewTextBoxColumn92"
			Me.DataGridViewTextBoxColumn92.[ReadOnly] = True
			dataGridViewCellStyle82.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn93.DefaultCellStyle = dataGridViewCellStyle82
			Me.DataGridViewTextBoxColumn93.HeaderText = "Grand Total"
			Me.DataGridViewTextBoxColumn93.Name = "DataGridViewTextBoxColumn93"
			Me.DataGridViewTextBoxColumn93.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn93.Width = 150
			Me.TabPage6.Controls.Add(Me.LinkLabel6)
			Me.TabPage6.Controls.Add(Me.dgw5)
			Me.TabPage6.Location = New Global.System.Drawing.Point(4, 22)
			Me.TabPage6.Name = "TabPage6"
			Me.TabPage6.Padding = New Global.System.Windows.Forms.Padding(3)
			Me.TabPage6.Size = New Global.System.Drawing.Size(1138, 541)
			Me.TabPage6.TabIndex = 5
			Me.TabPage6.Text = "HSN"
			Me.TabPage6.UseVisualStyleBackColor = True
			Me.LinkLabel6.AutoSize = True
			Me.LinkLabel6.Cursor = Global.System.Windows.Forms.Cursors.Hand
			Me.LinkLabel6.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 9.75F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			Me.LinkLabel6.Location = New Global.System.Drawing.Point(1035, 522)
			Me.LinkLabel6.Name = "LinkLabel6"
			Me.LinkLabel6.Size = New Global.System.Drawing.Size(102, 16)
			Me.LinkLabel6.TabIndex = 54
			Me.LinkLabel6.TabStop = True
			Me.LinkLabel6.Text = "Export To Excel"
			Me.dgw5.AllowUserToAddRows = False
			Me.dgw5.AllowUserToDeleteRows = False
			dataGridViewCellStyle83.BackColor = Global.System.Drawing.Color.FloralWhite
			Me.dgw5.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle83
			Me.dgw5.BackgroundColor = Global.System.Drawing.Color.White
			Me.dgw5.ColumnHeadersBorderStyle = Global.System.Windows.Forms.DataGridViewHeaderBorderStyle.[Single]
			dataGridViewCellStyle84.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter
			dataGridViewCellStyle84.BackColor = Global.System.Drawing.Color.DarkViolet
			dataGridViewCellStyle84.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 8.25F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			dataGridViewCellStyle84.ForeColor = Global.System.Drawing.Color.White
			dataGridViewCellStyle84.SelectionBackColor = Global.System.Drawing.Color.LightSteelBlue
			dataGridViewCellStyle84.SelectionForeColor = Global.System.Drawing.SystemColors.HighlightText
			dataGridViewCellStyle84.WrapMode = Global.System.Windows.Forms.DataGridViewTriState.[True]
			Me.dgw5.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle84
			Me.dgw5.ColumnHeadersHeight = 30
			Me.dgw5.Columns.AddRange(New Global.System.Windows.Forms.DataGridViewColumn() { Me.DataGridViewTextBoxColumn101, Me.DataGridViewTextBoxColumn94, Me.DataGridViewTextBoxColumn95, Me.DataGridViewTextBoxColumn96, Me.DataGridViewTextBoxColumn97, Me.DataGridViewTextBoxColumn98, Me.DataGridViewTextBoxColumn99, Me.DataGridViewTextBoxColumn100, Me.DataGridViewTextBoxColumn102, Me.DataGridViewTextBoxColumn103, Me.DataGridViewTextBoxColumn104, Me.DataGridViewTextBoxColumn105, Me.DataGridViewTextBoxColumn106, Me.DataGridViewTextBoxColumn107, Me.DataGridViewTextBoxColumn108, Me.DataGridViewTextBoxColumn109, Me.DataGridViewTextBoxColumn110, Me.DataGridViewTextBoxColumn111, Me.DataGridViewTextBoxColumn112, Me.DataGridViewTextBoxColumn113, Me.DataGridViewTextBoxColumn114, Me.DataGridViewTextBoxColumn115 })
			Me.dgw5.Cursor = Global.System.Windows.Forms.Cursors.Hand
			dataGridViewCellStyle85.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft
			dataGridViewCellStyle85.BackColor = Global.System.Drawing.SystemColors.Window
			dataGridViewCellStyle85.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 8.25F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			dataGridViewCellStyle85.ForeColor = Global.System.Drawing.Color.Black
			dataGridViewCellStyle85.SelectionBackColor = Global.System.Drawing.SystemColors.Highlight
			dataGridViewCellStyle85.SelectionForeColor = Global.System.Drawing.SystemColors.HighlightText
			dataGridViewCellStyle85.WrapMode = Global.System.Windows.Forms.DataGridViewTriState.[False]
			Me.dgw5.DefaultCellStyle = dataGridViewCellStyle85
			Me.dgw5.EnableHeadersVisualStyles = False
			Me.dgw5.GridColor = Global.System.Drawing.Color.White
			Me.dgw5.Location = New Global.System.Drawing.Point(3, 3)
			Me.dgw5.MultiSelect = False
			Me.dgw5.Name = "dgw5"
			Me.dgw5.[ReadOnly] = True
			Me.dgw5.RowHeadersBorderStyle = Global.System.Windows.Forms.DataGridViewHeaderBorderStyle.[Single]
			dataGridViewCellStyle86.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft
			dataGridViewCellStyle86.BackColor = Global.System.Drawing.Color.DarkViolet
			dataGridViewCellStyle86.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 8.25F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			dataGridViewCellStyle86.ForeColor = Global.System.Drawing.Color.White
			dataGridViewCellStyle86.SelectionBackColor = Global.System.Drawing.Color.OrangeRed
			dataGridViewCellStyle86.SelectionForeColor = Global.System.Drawing.Color.White
			dataGridViewCellStyle86.WrapMode = Global.System.Windows.Forms.DataGridViewTriState.[True]
			Me.dgw5.RowHeadersDefaultCellStyle = dataGridViewCellStyle86
			Me.dgw5.RowHeadersWidth = 25
			Me.dgw5.RowHeadersWidthSizeMode = Global.System.Windows.Forms.DataGridViewRowHeadersWidthSizeMode.DisableResizing
			dataGridViewCellStyle87.BackColor = Global.System.Drawing.Color.White
			dataGridViewCellStyle87.Font = New Global.System.Drawing.Font("Tahoma", 8.25F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			dataGridViewCellStyle87.SelectionBackColor = Global.System.Drawing.Color.DarkSlateGray
			dataGridViewCellStyle87.SelectionForeColor = Global.System.Drawing.Color.White
			Me.dgw5.RowsDefaultCellStyle = dataGridViewCellStyle87
			Me.dgw5.RowTemplate.Height = 25
			Me.dgw5.RowTemplate.Resizable = Global.System.Windows.Forms.DataGridViewTriState.[False]
			Me.dgw5.SelectionMode = Global.System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect
			Me.dgw5.Size = New Global.System.Drawing.Size(1132, 516)
			Me.dgw5.TabIndex = 44
			Me.DataGridViewTextBoxColumn101.HeaderText = "HSN Code"
			Me.DataGridViewTextBoxColumn101.Name = "DataGridViewTextBoxColumn101"
			Me.DataGridViewTextBoxColumn101.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn94.HeaderText = "Invoice No."
			Me.DataGridViewTextBoxColumn94.Name = "DataGridViewTextBoxColumn94"
			Me.DataGridViewTextBoxColumn94.[ReadOnly] = True
			dataGridViewCellStyle88.Format = "dd/MM/yyyy"
			Me.DataGridViewTextBoxColumn95.DefaultCellStyle = dataGridViewCellStyle88
			Me.DataGridViewTextBoxColumn95.HeaderText = "Invoice Date"
			Me.DataGridViewTextBoxColumn95.Name = "DataGridViewTextBoxColumn95"
			Me.DataGridViewTextBoxColumn95.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn96.HeaderText = "Tax Type"
			Me.DataGridViewTextBoxColumn96.Name = "DataGridViewTextBoxColumn96"
			Me.DataGridViewTextBoxColumn96.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn97.HeaderText = "Customer Name"
			Me.DataGridViewTextBoxColumn97.Name = "DataGridViewTextBoxColumn97"
			Me.DataGridViewTextBoxColumn97.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn98.HeaderText = "State"
			Me.DataGridViewTextBoxColumn98.Name = "DataGridViewTextBoxColumn98"
			Me.DataGridViewTextBoxColumn98.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn99.HeaderText = "GSTIN/UID"
			Me.DataGridViewTextBoxColumn99.Name = "DataGridViewTextBoxColumn99"
			Me.DataGridViewTextBoxColumn99.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn100.HeaderText = "Product Name"
			Me.DataGridViewTextBoxColumn100.Name = "DataGridViewTextBoxColumn100"
			Me.DataGridViewTextBoxColumn100.[ReadOnly] = True
			dataGridViewCellStyle89.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			dataGridViewCellStyle89.Format = "N2"
			Me.DataGridViewTextBoxColumn102.DefaultCellStyle = dataGridViewCellStyle89
			Me.DataGridViewTextBoxColumn102.HeaderText = "Sales Rate"
			Me.DataGridViewTextBoxColumn102.Name = "DataGridViewTextBoxColumn102"
			Me.DataGridViewTextBoxColumn102.[ReadOnly] = True
			dataGridViewCellStyle90.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn103.DefaultCellStyle = dataGridViewCellStyle90
			Me.DataGridViewTextBoxColumn103.HeaderText = "Qty."
			Me.DataGridViewTextBoxColumn103.Name = "DataGridViewTextBoxColumn103"
			Me.DataGridViewTextBoxColumn103.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn104.HeaderText = "UOM"
			Me.DataGridViewTextBoxColumn104.Name = "DataGridViewTextBoxColumn104"
			Me.DataGridViewTextBoxColumn104.[ReadOnly] = True
			dataGridViewCellStyle91.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn105.DefaultCellStyle = dataGridViewCellStyle91
			Me.DataGridViewTextBoxColumn105.HeaderText = "Discount %"
			Me.DataGridViewTextBoxColumn105.Name = "DataGridViewTextBoxColumn105"
			Me.DataGridViewTextBoxColumn105.[ReadOnly] = True
			dataGridViewCellStyle92.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn106.DefaultCellStyle = dataGridViewCellStyle92
			Me.DataGridViewTextBoxColumn106.HeaderText = "Discount"
			Me.DataGridViewTextBoxColumn106.Name = "DataGridViewTextBoxColumn106"
			Me.DataGridViewTextBoxColumn106.[ReadOnly] = True
			dataGridViewCellStyle93.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn107.DefaultCellStyle = dataGridViewCellStyle93
			Me.DataGridViewTextBoxColumn107.HeaderText = "CGST %"
			Me.DataGridViewTextBoxColumn107.Name = "DataGridViewTextBoxColumn107"
			Me.DataGridViewTextBoxColumn107.[ReadOnly] = True
			dataGridViewCellStyle94.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn108.DefaultCellStyle = dataGridViewCellStyle94
			Me.DataGridViewTextBoxColumn108.HeaderText = "CGST"
			Me.DataGridViewTextBoxColumn108.Name = "DataGridViewTextBoxColumn108"
			Me.DataGridViewTextBoxColumn108.[ReadOnly] = True
			dataGridViewCellStyle95.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn109.DefaultCellStyle = dataGridViewCellStyle95
			Me.DataGridViewTextBoxColumn109.HeaderText = "SGST %"
			Me.DataGridViewTextBoxColumn109.Name = "DataGridViewTextBoxColumn109"
			Me.DataGridViewTextBoxColumn109.[ReadOnly] = True
			dataGridViewCellStyle96.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn110.DefaultCellStyle = dataGridViewCellStyle96
			Me.DataGridViewTextBoxColumn110.HeaderText = "SGST/UTGST"
			Me.DataGridViewTextBoxColumn110.Name = "DataGridViewTextBoxColumn110"
			Me.DataGridViewTextBoxColumn110.[ReadOnly] = True
			dataGridViewCellStyle97.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn111.DefaultCellStyle = dataGridViewCellStyle97
			Me.DataGridViewTextBoxColumn111.HeaderText = "IGST %"
			Me.DataGridViewTextBoxColumn111.Name = "DataGridViewTextBoxColumn111"
			Me.DataGridViewTextBoxColumn111.[ReadOnly] = True
			dataGridViewCellStyle98.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn112.DefaultCellStyle = dataGridViewCellStyle98
			Me.DataGridViewTextBoxColumn112.HeaderText = "IGST"
			Me.DataGridViewTextBoxColumn112.Name = "DataGridViewTextBoxColumn112"
			Me.DataGridViewTextBoxColumn112.[ReadOnly] = True
			dataGridViewCellStyle99.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn113.DefaultCellStyle = dataGridViewCellStyle99
			Me.DataGridViewTextBoxColumn113.HeaderText = "CESS %"
			Me.DataGridViewTextBoxColumn113.Name = "DataGridViewTextBoxColumn113"
			Me.DataGridViewTextBoxColumn113.[ReadOnly] = True
			dataGridViewCellStyle100.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn114.DefaultCellStyle = dataGridViewCellStyle100
			Me.DataGridViewTextBoxColumn114.HeaderText = "CESS"
			Me.DataGridViewTextBoxColumn114.Name = "DataGridViewTextBoxColumn114"
			Me.DataGridViewTextBoxColumn114.[ReadOnly] = True
			dataGridViewCellStyle101.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn115.DefaultCellStyle = dataGridViewCellStyle101
			Me.DataGridViewTextBoxColumn115.HeaderText = "Total Amount"
			Me.DataGridViewTextBoxColumn115.Name = "DataGridViewTextBoxColumn115"
			Me.DataGridViewTextBoxColumn115.[ReadOnly] = True
			Me.GroupBox2.BackColor = Global.System.Drawing.Color.White
			Me.GroupBox2.Controls.Add(Me.btnReset)
			Me.GroupBox2.Controls.Add(Me.dtpDateTo)
			Me.GroupBox2.Controls.Add(Me.Label2)
			Me.GroupBox2.Controls.Add(Me.btnGetData)
			Me.GroupBox2.Controls.Add(Me.Label4)
			Me.GroupBox2.Controls.Add(Me.dtpDateFrom)
			Me.GroupBox2.ForeColor = Global.System.Drawing.Color.Black
			Me.GroupBox2.Location = New Global.System.Drawing.Point(313, 43)
			Me.GroupBox2.Name = "GroupBox2"
			Me.GroupBox2.Size = New Global.System.Drawing.Size(553, 43)
			Me.GroupBox2.TabIndex = 50
			Me.GroupBox2.TabStop = False
			Me.GroupBox2.Text = "Search by Date :"
			Me.btnReset.BackColor = Global.System.Drawing.Color.FromArgb(45, 63, 83)
			Me.btnReset.BackgroundImageLayout = Global.System.Windows.Forms.ImageLayout.Stretch
			Me.btnReset.Cursor = Global.System.Windows.Forms.Cursors.Hand
			Me.btnReset.FlatStyle = Global.System.Windows.Forms.FlatStyle.Flat
			Me.btnReset.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 9F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			Me.btnReset.ForeColor = Global.System.Drawing.Color.White
			Me.btnReset.Image = CType(componentResourceManager.GetObject("btnReset.Image"), Global.System.Drawing.Image)
			Me.btnReset.ImageAlign = Global.System.Drawing.ContentAlignment.MiddleLeft
			Me.btnReset.Location = New Global.System.Drawing.Point(444, 8)
			Me.btnReset.Name = "btnReset"
			Me.btnReset.Size = New Global.System.Drawing.Size(101, 32)
			Me.btnReset.TabIndex = 3
			Me.btnReset.Text = "&Reset"
			Me.btnReset.TextAlign = Global.System.Drawing.ContentAlignment.MiddleRight
			Me.btnReset.UseVisualStyleBackColor = False
			Me.dtpDateTo.CustomFormat = "dd/MM/yyyy"
			Me.dtpDateTo.Format = Global.System.Windows.Forms.DateTimePickerFormat.Custom
			Me.dtpDateTo.Location = New Global.System.Drawing.Point(210, 15)
			Me.dtpDateTo.Name = "dtpDateTo"
			Me.dtpDateTo.Size = New Global.System.Drawing.Size(119, 20)
			Me.dtpDateTo.TabIndex = 1
			Me.Label2.AutoSize = True
			Me.Label2.Location = New Global.System.Drawing.Point(179, 18)
			Me.Label2.Name = "Label2"
			Me.Label2.Size = New Global.System.Drawing.Size(26, 13)
			Me.Label2.TabIndex = 13
			Me.Label2.Text = "To :"
			Me.btnGetData.BackColor = Global.System.Drawing.Color.FromArgb(45, 63, 83)
			Me.btnGetData.BackgroundImageLayout = Global.System.Windows.Forms.ImageLayout.Stretch
			Me.btnGetData.Cursor = Global.System.Windows.Forms.Cursors.Hand
			Me.btnGetData.FlatStyle = Global.System.Windows.Forms.FlatStyle.Flat
			Me.btnGetData.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 8.25F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			Me.btnGetData.ForeColor = Global.System.Drawing.Color.White
			Me.btnGetData.Image = CType(componentResourceManager.GetObject("btnGetData.Image"), Global.System.Drawing.Image)
			Me.btnGetData.ImageAlign = Global.System.Drawing.ContentAlignment.MiddleLeft
			Me.btnGetData.Location = New Global.System.Drawing.Point(335, 8)
			Me.btnGetData.Name = "btnGetData"
			Me.btnGetData.Size = New Global.System.Drawing.Size(101, 32)
			Me.btnGetData.TabIndex = 2
			Me.btnGetData.Text = "Get Data"
			Me.btnGetData.TextAlign = Global.System.Drawing.ContentAlignment.MiddleRight
			Me.btnGetData.UseVisualStyleBackColor = False
			Me.Label4.AutoSize = True
			Me.Label4.Location = New Global.System.Drawing.Point(13, 18)
			Me.Label4.Name = "Label4"
			Me.Label4.Size = New Global.System.Drawing.Size(36, 13)
			Me.Label4.TabIndex = 12
			Me.Label4.Text = "From :"
			Me.dtpDateFrom.CustomFormat = "dd/MM/yyyy"
			Me.dtpDateFrom.Format = Global.System.Windows.Forms.DateTimePickerFormat.Custom
			Me.dtpDateFrom.Location = New Global.System.Drawing.Point(55, 15)
			Me.dtpDateFrom.Name = "dtpDateFrom"
			Me.dtpDateFrom.Size = New Global.System.Drawing.Size(119, 20)
			Me.dtpDateFrom.TabIndex = 0
			Me.Label1.BackColor = Global.System.Drawing.Color.FromArgb(45, 63, 83)
			Me.Label1.Dock = Global.System.Windows.Forms.DockStyle.Top
			Me.Label1.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 14.25F, Global.System.Drawing.FontStyle.Bold, Global.System.Drawing.GraphicsUnit.Point, 0)
			Me.Label1.ForeColor = Global.System.Drawing.Color.White
			Me.Label1.Location = New Global.System.Drawing.Point(0, 0)
			Me.Label1.Name = "Label1"
			Me.Label1.Size = New Global.System.Drawing.Size(1160, 31)
			Me.Label1.TabIndex = 51
			Me.Label1.Text = "GSTR-1 Returns"
			Me.Label1.TextAlign = Global.System.Drawing.ContentAlignment.MiddleCenter
			MyBase.AutoScaleDimensions = New Global.System.Drawing.SizeF(6F, 13F)
			MyBase.AutoScaleMode = Global.System.Windows.Forms.AutoScaleMode.Font
			Me.BackColor = Global.System.Drawing.Color.Coral
			MyBase.ClientSize = New Global.System.Drawing.Size(1160, 643)
			MyBase.Controls.Add(Me.Label1)
			MyBase.Controls.Add(Me.GroupBox2)
			MyBase.Controls.Add(Me.TabControl1)
			Me.ForeColor = Global.System.Drawing.Color.Black
			MyBase.FormBorderStyle = Global.System.Windows.Forms.FormBorderStyle.FixedSingle
			MyBase.KeyPreview = True
			MyBase.MaximizeBox = False
			MyBase.Name = "frmGSTR1"
			MyBase.ShowIcon = False
			MyBase.ShowInTaskbar = False
			MyBase.StartPosition = Global.System.Windows.Forms.FormStartPosition.CenterParent
			Me.TabControl1.ResumeLayout(False)
			Me.TabPage1.ResumeLayout(False)
			Me.TabPage1.PerformLayout()
			CType(Me.dgw, Global.System.ComponentModel.ISupportInitialize).EndInit()
			Me.TabPage2.ResumeLayout(False)
			Me.TabPage2.PerformLayout()
			CType(Me.dgw1, Global.System.ComponentModel.ISupportInitialize).EndInit()
			Me.TabPage3.ResumeLayout(False)
			Me.TabPage3.PerformLayout()
			CType(Me.dgw2, Global.System.ComponentModel.ISupportInitialize).EndInit()
			Me.TabPage4.ResumeLayout(False)
			Me.TabPage4.PerformLayout()
			CType(Me.dgw3, Global.System.ComponentModel.ISupportInitialize).EndInit()
			Me.TabPage5.ResumeLayout(False)
			Me.TabPage5.PerformLayout()
			CType(Me.dgw4, Global.System.ComponentModel.ISupportInitialize).EndInit()
			Me.TabPage6.ResumeLayout(False)
			Me.TabPage6.PerformLayout()
			CType(Me.dgw5, Global.System.ComponentModel.ISupportInitialize).EndInit()
			Me.GroupBox2.ResumeLayout(False)
			Me.GroupBox2.PerformLayout()
			MyBase.ResumeLayout(False)
		End Sub

		' Token: 0x04005E1F RID: 24095
		Private components As Global.System.ComponentModel.IContainer
	End Class
End Namespace
