Namespace BillPoint
	' Token: 0x020001E1 RID: 481
		Public Partial Class frmProductRec_variant
		Inherits Global.System.Windows.Forms.Form

		' Token: 0x0600809D RID: 32925 RVA: 0x005F40D0 File Offset: 0x005F22D0
		<Global.System.Diagnostics.DebuggerNonUserCode()>
		Protected Overrides Sub Dispose(disposing As Boolean)
			Try
				Dim flag As Boolean = disposing AndAlso Me.components IsNot Nothing
				If flag Then
					Me.components.Dispose()
				End If
			Finally
				MyBase.Dispose(disposing)
			End Try
		End Sub

		' Token: 0x0600809E RID: 32926 RVA: 0x005F4120 File Offset: 0x005F2320
		<Global.System.Diagnostics.DebuggerStepThrough()>
		Private Sub InitializeComponent()
			Dim componentResourceManager As Global.System.ComponentModel.ComponentResourceManager = New Global.System.ComponentModel.ComponentResourceManager(GetType(Global.BillPoint.frmProductRec_variant))
			Dim dataGridViewCellStyle As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle2 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle3 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle4 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle5 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle6 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle7 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle8 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle9 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle10 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle11 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle12 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle13 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle14 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle15 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle16 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Me.txtBar = New Global.System.Windows.Forms.TextBox()
			Me.txtBarcodeTempStock = New Global.System.Windows.Forms.TextBox()
			Me.txtID = New Global.System.Windows.Forms.TextBox()
			Me.pbgiftqr = New Global.System.Windows.Forms.PictureBox()
			Me.txtProductCode = New Global.System.Windows.Forms.TextBox()
			Me.txtNP = New Global.System.Windows.Forms.TextBox()
			Me.txtBarcode = New Global.System.Windows.Forms.TextBox()
			Me.cmbNP = New Global.System.Windows.Forms.ComboBox()
			Me.GelButtonNewRecord = New Global.GelButtons.GelButton()
			Me.GelButton1 = New Global.GelButtons.GelButton()
			Me.DataGridView2 = New Global.System.Windows.Forms.DataGridView()
			Me.PID2 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn2 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn3 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.CategoryName = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewButtonColumn1 = New Global.System.Windows.Forms.DataGridViewButtonColumn()
			Me.SubCategoryName = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewButtonColumn2 = New Global.System.Windows.Forms.DataGridViewButtonColumn()
			Me.DataGridViewTextBoxColumn4 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn5 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn6 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn7 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.CostPrice = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn9 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn10 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.cmbGST1 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewButtonColumn3 = New Global.System.Windows.Forms.DataGridViewButtonColumn()
			Me.DataGridViewTextBoxColumn11 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn12 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn13 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn14 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn15 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn16 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn17 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.cmbPurchaseUnit2 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.cmbSalesUnit2 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.cmbAltunit2 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn18 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn19 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn20 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn21 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.cmbSalesTaxType2 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.cmbPurchaseTaxType2 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.ddlGdown2 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.ddlRack2 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn22 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.txtOpeningStock2 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn24 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.txtMRP = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.txtRSP1 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn27 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn28 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn29 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn30 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.cmbSize2 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.cmbColour2 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn31 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn32 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn33 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Photo = New Global.System.Windows.Forms.DataGridViewImageColumn()
			Me.btnAddNew = New Global.System.Windows.Forms.DataGridViewButtonColumn()
			Me.Label14 = New Global.System.Windows.Forms.Label()
			Me.Label13 = New Global.System.Windows.Forms.Label()
			CType(Me.pbgiftqr, Global.System.ComponentModel.ISupportInitialize).BeginInit()
			CType(Me.DataGridView2, Global.System.ComponentModel.ISupportInitialize).BeginInit()
			MyBase.SuspendLayout()
			Me.txtBar.Location = New Global.System.Drawing.Point(526, 35)
			Me.txtBar.Name = "txtBar"
			Me.txtBar.Size = New Global.System.Drawing.Size(100, 20)
			Me.txtBar.TabIndex = 438
			Me.txtBar.Visible = False
			Me.txtBarcodeTempStock.Location = New Global.System.Drawing.Point(729, 5)
			Me.txtBarcodeTempStock.Name = "txtBarcodeTempStock"
			Me.txtBarcodeTempStock.Size = New Global.System.Drawing.Size(100, 20)
			Me.txtBarcodeTempStock.TabIndex = 439
			Me.txtBarcodeTempStock.Visible = False
			Me.txtID.Location = New Global.System.Drawing.Point(470, 5)
			Me.txtID.Name = "txtID"
			Me.txtID.Size = New Global.System.Drawing.Size(100, 20)
			Me.txtID.TabIndex = 440
			Me.txtID.Visible = False
			Me.pbgiftqr.BorderStyle = Global.System.Windows.Forms.BorderStyle.FixedSingle
			Me.pbgiftqr.Image = Global.BillPoint.My.Resources.Resources.Noimage
			Me.pbgiftqr.Location = New Global.System.Drawing.Point(552, 272)
			Me.pbgiftqr.Name = "pbgiftqr"
			Me.pbgiftqr.Size = New Global.System.Drawing.Size(45, 28)
			Me.pbgiftqr.TabIndex = 1800
			Me.pbgiftqr.TabStop = False
			Me.pbgiftqr.Visible = False
			Me.txtProductCode.Location = New Global.System.Drawing.Point(350, 5)
			Me.txtProductCode.Name = "txtProductCode"
			Me.txtProductCode.Size = New Global.System.Drawing.Size(100, 20)
			Me.txtProductCode.TabIndex = 1801
			Me.txtProductCode.Visible = False
			Me.txtNP.Location = New Global.System.Drawing.Point(228, 5)
			Me.txtNP.Name = "txtNP"
			Me.txtNP.Size = New Global.System.Drawing.Size(100, 20)
			Me.txtNP.TabIndex = 1802
			Me.txtNP.Visible = False
			Me.txtBarcode.Location = New Global.System.Drawing.Point(940, 5)
			Me.txtBarcode.Name = "txtBarcode"
			Me.txtBarcode.Size = New Global.System.Drawing.Size(100, 20)
			Me.txtBarcode.TabIndex = 1803
			Me.txtBarcode.Visible = False
			Me.cmbNP.FormattingEnabled = True
			Me.cmbNP.Location = New Global.System.Drawing.Point(91, 4)
			Me.cmbNP.Name = "cmbNP"
			Me.cmbNP.Size = New Global.System.Drawing.Size(121, 21)
			Me.cmbNP.TabIndex = 1804
			Me.cmbNP.Visible = False
			Me.GelButtonNewRecord.Anchor = Global.System.Windows.Forms.AnchorStyles.Top Or Global.System.Windows.Forms.AnchorStyles.Right
			Me.GelButtonNewRecord.BackColor = Global.System.Drawing.Color.MediumVioletRed
			Me.GelButtonNewRecord.FlatAppearance.BorderSize = 0
			Me.GelButtonNewRecord.FlatStyle = Global.System.Windows.Forms.FlatStyle.Flat
			Me.GelButtonNewRecord.Font = New Global.System.Drawing.Font("Segoe UI Semibold", 12F, Global.System.Drawing.FontStyle.Bold, Global.System.Drawing.GraphicsUnit.Point, 0)
			Me.GelButtonNewRecord.ForeColor = Global.System.Drawing.Color.White
			Me.GelButtonNewRecord.GradientBottom = Global.System.Drawing.Color.LimeGreen
			Me.GelButtonNewRecord.GradientTop = Global.System.Drawing.Color.FromArgb(255, 128, 128)
			Me.GelButtonNewRecord.Image = CType(componentResourceManager.GetObject("GelButtonNewRecord.Image"), Global.System.Drawing.Image)
			Me.GelButtonNewRecord.ImageAlign = Global.System.Drawing.ContentAlignment.MiddleLeft
			Me.GelButtonNewRecord.Location = New Global.System.Drawing.Point(839, 272)
			Me.GelButtonNewRecord.Name = "GelButtonNewRecord"
			Me.GelButtonNewRecord.Size = New Global.System.Drawing.Size(108, 33)
			Me.GelButtonNewRecord.TabIndex = 1805
			Me.GelButtonNewRecord.Text = "New"
			Me.GelButtonNewRecord.TextAlign = Global.System.Drawing.ContentAlignment.MiddleRight
			Me.GelButtonNewRecord.UseVisualStyleBackColor = False
			Me.GelButtonNewRecord.Visible = False
			Me.GelButton1.Anchor = Global.System.Windows.Forms.AnchorStyles.Top Or Global.System.Windows.Forms.AnchorStyles.Right
			Me.GelButton1.BackColor = Global.System.Drawing.Color.MediumVioletRed
			Me.GelButton1.FlatAppearance.BorderSize = 0
			Me.GelButton1.FlatStyle = Global.System.Windows.Forms.FlatStyle.Flat
			Me.GelButton1.Font = New Global.System.Drawing.Font("Segoe UI Semibold", 12F, Global.System.Drawing.FontStyle.Bold, Global.System.Drawing.GraphicsUnit.Point, 0)
			Me.GelButton1.ForeColor = Global.System.Drawing.Color.White
			Me.GelButton1.GradientBottom = Global.System.Drawing.Color.LimeGreen
			Me.GelButton1.GradientTop = Global.System.Drawing.Color.FromArgb(255, 128, 128)
			Me.GelButton1.Image = CType(componentResourceManager.GetObject("GelButton1.Image"), Global.System.Drawing.Image)
			Me.GelButton1.ImageAlign = Global.System.Drawing.ContentAlignment.MiddleLeft
			Me.GelButton1.Location = New Global.System.Drawing.Point(962, 272)
			Me.GelButton1.Name = "GelButton1"
			Me.GelButton1.Size = New Global.System.Drawing.Size(144, 33)
			Me.GelButton1.TabIndex = 1806
			Me.GelButton1.Text = "Variant Sattle"
			Me.GelButton1.TextAlign = Global.System.Drawing.ContentAlignment.MiddleRight
			Me.GelButton1.UseVisualStyleBackColor = False
			dataGridViewCellStyle.BackColor = Global.System.Drawing.Color.FloralWhite
			dataGridViewCellStyle.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 12F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			Me.DataGridView2.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle
			Me.DataGridView2.Anchor = Global.System.Windows.Forms.AnchorStyles.Top Or Global.System.Windows.Forms.AnchorStyles.Bottom Or Global.System.Windows.Forms.AnchorStyles.Left Or Global.System.Windows.Forms.AnchorStyles.Right
			Me.DataGridView2.AutoSizeColumnsMode = Global.System.Windows.Forms.DataGridViewAutoSizeColumnsMode.DisplayedCells
			Me.DataGridView2.BackgroundColor = Global.System.Drawing.Color.FromArgb(128, 128, 255)
			Me.DataGridView2.ColumnHeadersBorderStyle = Global.System.Windows.Forms.DataGridViewHeaderBorderStyle.[Single]
			dataGridViewCellStyle2.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter
			dataGridViewCellStyle2.BackColor = Global.System.Drawing.Color.DarkViolet
			dataGridViewCellStyle2.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 12F, Global.System.Drawing.FontStyle.Bold, Global.System.Drawing.GraphicsUnit.Point, 0)
			dataGridViewCellStyle2.ForeColor = Global.System.Drawing.Color.White
			dataGridViewCellStyle2.SelectionBackColor = Global.System.Drawing.Color.LightSteelBlue
			dataGridViewCellStyle2.SelectionForeColor = Global.System.Drawing.SystemColors.HighlightText
			dataGridViewCellStyle2.WrapMode = Global.System.Windows.Forms.DataGridViewTriState.[True]
			Me.DataGridView2.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2
			Me.DataGridView2.ColumnHeadersHeight = 40
			Me.DataGridView2.Columns.AddRange(New Global.System.Windows.Forms.DataGridViewColumn() { Me.PID2, Me.DataGridViewTextBoxColumn2, Me.DataGridViewTextBoxColumn3, Me.CategoryName, Me.DataGridViewButtonColumn1, Me.SubCategoryName, Me.DataGridViewButtonColumn2, Me.DataGridViewTextBoxColumn4, Me.DataGridViewTextBoxColumn5, Me.DataGridViewTextBoxColumn6, Me.DataGridViewTextBoxColumn7, Me.CostPrice, Me.DataGridViewTextBoxColumn9, Me.DataGridViewTextBoxColumn10, Me.cmbGST1, Me.DataGridViewButtonColumn3, Me.DataGridViewTextBoxColumn11, Me.DataGridViewTextBoxColumn12, Me.DataGridViewTextBoxColumn13, Me.DataGridViewTextBoxColumn14, Me.DataGridViewTextBoxColumn15, Me.DataGridViewTextBoxColumn16, Me.DataGridViewTextBoxColumn17, Me.cmbPurchaseUnit2, Me.cmbSalesUnit2, Me.cmbAltunit2, Me.DataGridViewTextBoxColumn18, Me.DataGridViewTextBoxColumn19, Me.DataGridViewTextBoxColumn20, Me.DataGridViewTextBoxColumn21, Me.cmbSalesTaxType2, Me.cmbPurchaseTaxType2, Me.ddlGdown2, Me.ddlRack2, Me.DataGridViewTextBoxColumn22, Me.txtOpeningStock2, Me.DataGridViewTextBoxColumn24, Me.txtMRP, Me.txtRSP1, Me.DataGridViewTextBoxColumn27, Me.DataGridViewTextBoxColumn28, Me.DataGridViewTextBoxColumn29, Me.DataGridViewTextBoxColumn30, Me.cmbSize2, Me.cmbColour2, Me.DataGridViewTextBoxColumn31, Me.DataGridViewTextBoxColumn32, Me.DataGridViewTextBoxColumn33, Me.Photo, Me.btnAddNew })
			Me.DataGridView2.Cursor = Global.System.Windows.Forms.Cursors.Hand
			dataGridViewCellStyle3.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft
			dataGridViewCellStyle3.BackColor = Global.System.Drawing.SystemColors.Window
			dataGridViewCellStyle3.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 11.25F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			dataGridViewCellStyle3.ForeColor = Global.System.Drawing.SystemColors.ControlText
			dataGridViewCellStyle3.SelectionBackColor = Global.System.Drawing.SystemColors.Highlight
			dataGridViewCellStyle3.SelectionForeColor = Global.System.Drawing.Color.Black
			dataGridViewCellStyle3.WrapMode = Global.System.Windows.Forms.DataGridViewTriState.[False]
			Me.DataGridView2.DefaultCellStyle = dataGridViewCellStyle3
			Me.DataGridView2.EnableHeadersVisualStyles = False
			Me.DataGridView2.GridColor = Global.System.Drawing.Color.White
			Me.DataGridView2.Location = New Global.System.Drawing.Point(3, 2)
			Me.DataGridView2.MultiSelect = False
			Me.DataGridView2.Name = "DataGridView2"
			Me.DataGridView2.RowHeadersBorderStyle = Global.System.Windows.Forms.DataGridViewHeaderBorderStyle.[Single]
			dataGridViewCellStyle4.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft
			dataGridViewCellStyle4.BackColor = Global.System.Drawing.Color.DarkViolet
			dataGridViewCellStyle4.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 11.25F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			dataGridViewCellStyle4.ForeColor = Global.System.Drawing.Color.White
			dataGridViewCellStyle4.SelectionBackColor = Global.System.Drawing.Color.OrangeRed
			dataGridViewCellStyle4.SelectionForeColor = Global.System.Drawing.Color.White
			dataGridViewCellStyle4.WrapMode = Global.System.Windows.Forms.DataGridViewTriState.[True]
			Me.DataGridView2.RowHeadersDefaultCellStyle = dataGridViewCellStyle4
			Me.DataGridView2.RowHeadersWidth = 25
			Me.DataGridView2.RowHeadersWidthSizeMode = Global.System.Windows.Forms.DataGridViewRowHeadersWidthSizeMode.DisableResizing
			dataGridViewCellStyle5.BackColor = Global.System.Drawing.Color.White
			dataGridViewCellStyle5.Font = New Global.System.Drawing.Font("Tahoma", 11.25F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			dataGridViewCellStyle5.SelectionBackColor = Global.System.Drawing.Color.DarkSlateGray
			dataGridViewCellStyle5.SelectionForeColor = Global.System.Drawing.Color.White
			Me.DataGridView2.RowsDefaultCellStyle = dataGridViewCellStyle5
			Me.DataGridView2.RowTemplate.Height = 30
			Me.DataGridView2.RowTemplate.Resizable = Global.System.Windows.Forms.DataGridViewTriState.[False]
			Me.DataGridView2.SelectionMode = Global.System.Windows.Forms.DataGridViewSelectionMode.CellSelect
			Me.DataGridView2.Size = New Global.System.Drawing.Size(1115, 264)
			Me.DataGridView2.TabIndex = 1807
			Me.DataGridView2.TabStop = False
			Me.PID2.DataPropertyName = "PID"
			Me.PID2.HeaderText = "PID"
			Me.PID2.Name = "PID2"
			Me.PID2.Visible = False
			Me.DataGridViewTextBoxColumn2.DataPropertyName = "ProductCode"
			Me.DataGridViewTextBoxColumn2.FillWeight = 284.084F
			Me.DataGridViewTextBoxColumn2.HeaderText = "Product Code"
			Me.DataGridViewTextBoxColumn2.Name = "DataGridViewTextBoxColumn2"
			Me.DataGridViewTextBoxColumn2.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn2.Width = 142
			Me.DataGridViewTextBoxColumn3.DataPropertyName = "Productname"
			Me.DataGridViewTextBoxColumn3.FillWeight = 275.771F
			Me.DataGridViewTextBoxColumn3.HeaderText = "Product Name"
			Me.DataGridViewTextBoxColumn3.Name = "DataGridViewTextBoxColumn3"
			Me.DataGridViewTextBoxColumn3.Resizable = Global.System.Windows.Forms.DataGridViewTriState.[True]
			Me.DataGridViewTextBoxColumn3.Width = 146
			Me.CategoryName.DataPropertyName = "CategoryName"
			dataGridViewCellStyle6.BackColor = Global.System.Drawing.Color.Red
			dataGridViewCellStyle6.ForeColor = Global.System.Drawing.Color.White
			dataGridViewCellStyle6.Padding = New Global.System.Windows.Forms.Padding(2)
			Me.CategoryName.DefaultCellStyle = dataGridViewCellStyle6
			Me.CategoryName.FillWeight = 153.3014F
			Me.CategoryName.HeaderText = "Category"
			Me.CategoryName.Name = "CategoryName"
			Me.CategoryName.SortMode = Global.System.Windows.Forms.DataGridViewColumnSortMode.NotSortable
			Me.CategoryName.Visible = False
			Me.DataGridViewButtonColumn1.DataPropertyName = "Category_plus"
			dataGridViewCellStyle7.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter
			dataGridViewCellStyle7.ForeColor = Global.System.Drawing.Color.Purple
			Me.DataGridViewButtonColumn1.DefaultCellStyle = dataGridViewCellStyle7
			Me.DataGridViewButtonColumn1.FillWeight = 65.74377F
			Me.DataGridViewButtonColumn1.HeaderText = "+"
			Me.DataGridViewButtonColumn1.Name = "DataGridViewButtonColumn1"
			Me.DataGridViewButtonColumn1.Text = "+"
			Me.DataGridViewButtonColumn1.UseColumnTextForButtonValue = True
			Me.DataGridViewButtonColumn1.Visible = False
			Me.DataGridViewButtonColumn1.Width = 30
			Me.SubCategoryName.DataPropertyName = "SubCategoryName"
			dataGridViewCellStyle8.Padding = New Global.System.Windows.Forms.Padding(2)
			Me.SubCategoryName.DefaultCellStyle = dataGridViewCellStyle8
			Me.SubCategoryName.FillWeight = 211.0264F
			Me.SubCategoryName.HeaderText = "Sub Category / Brand"
			Me.SubCategoryName.Name = "SubCategoryName"
			Me.SubCategoryName.Resizable = Global.System.Windows.Forms.DataGridViewTriState.[True]
			Me.SubCategoryName.SortMode = Global.System.Windows.Forms.DataGridViewColumnSortMode.NotSortable
			Me.SubCategoryName.Visible = False
			Me.DataGridViewButtonColumn2.DataPropertyName = "Subcategory_plus"
			dataGridViewCellStyle9.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter
			dataGridViewCellStyle9.ForeColor = Global.System.Drawing.Color.Purple
			Me.DataGridViewButtonColumn2.DefaultCellStyle = dataGridViewCellStyle9
			Me.DataGridViewButtonColumn2.FillWeight = 61.50089F
			Me.DataGridViewButtonColumn2.HeaderText = "+"
			Me.DataGridViewButtonColumn2.Name = "DataGridViewButtonColumn2"
			Me.DataGridViewButtonColumn2.Text = "+"
			Me.DataGridViewButtonColumn2.Visible = False
			Me.DataGridViewButtonColumn2.Width = 30
			Me.DataGridViewTextBoxColumn4.HeaderText = "SubCategoryID"
			Me.DataGridViewTextBoxColumn4.Name = "DataGridViewTextBoxColumn4"
			Me.DataGridViewTextBoxColumn4.Visible = False
			Me.DataGridViewTextBoxColumn5.DataPropertyName = "HSNCode"
			Me.DataGridViewTextBoxColumn5.FillWeight = 192.4218F
			Me.DataGridViewTextBoxColumn5.HeaderText = "HSN Code"
			Me.DataGridViewTextBoxColumn5.Name = "DataGridViewTextBoxColumn5"
			Me.DataGridViewTextBoxColumn5.Visible = False
			Me.DataGridViewTextBoxColumn6.DataPropertyName = "PartNo"
			Me.DataGridViewTextBoxColumn6.FillWeight = 199.441F
			Me.DataGridViewTextBoxColumn6.HeaderText = "Part / Group"
			Me.DataGridViewTextBoxColumn6.Name = "DataGridViewTextBoxColumn6"
			Me.DataGridViewTextBoxColumn6.Visible = False
			Me.DataGridViewTextBoxColumn7.DataPropertyName = "Description"
			dataGridViewCellStyle10.WrapMode = Global.System.Windows.Forms.DataGridViewTriState.[False]
			Me.DataGridViewTextBoxColumn7.DefaultCellStyle = dataGridViewCellStyle10
			Me.DataGridViewTextBoxColumn7.FillWeight = 190.5685F
			Me.DataGridViewTextBoxColumn7.HeaderText = "Description"
			Me.DataGridViewTextBoxColumn7.Name = "DataGridViewTextBoxColumn7"
			Me.DataGridViewTextBoxColumn7.Visible = False
			Me.DataGridViewTextBoxColumn7.Width = 167
			Me.CostPrice.DataPropertyName = "CostPrice"
			Me.CostPrice.FillWeight = 203.4047F
			Me.CostPrice.HeaderText = "Purchase Price"
			Me.CostPrice.Name = "CostPrice"
			Me.CostPrice.Width = 153
			Me.DataGridViewTextBoxColumn9.DataPropertyName = "SellingPrice"
			Me.DataGridViewTextBoxColumn9.HeaderText = "Retail Sale Price"
			Me.DataGridViewTextBoxColumn9.Name = "DataGridViewTextBoxColumn9"
			Me.DataGridViewTextBoxColumn9.Visible = False
			Me.DataGridViewTextBoxColumn10.DataPropertyName = "Discount"
			Me.DataGridViewTextBoxColumn10.FillWeight = 156.3039F
			Me.DataGridViewTextBoxColumn10.HeaderText = "Discount %"
			Me.DataGridViewTextBoxColumn10.Name = "DataGridViewTextBoxColumn10"
			Me.DataGridViewTextBoxColumn10.Visible = False
			Me.cmbGST1.FillWeight = 74.17998F
			Me.cmbGST1.HeaderText = "GSt %"
			Me.cmbGST1.Name = "cmbGST1"
			Me.cmbGST1.Resizable = Global.System.Windows.Forms.DataGridViewTriState.[True]
			Me.cmbGST1.SortMode = Global.System.Windows.Forms.DataGridViewColumnSortMode.NotSortable
			Me.cmbGST1.Visible = False
			Me.DataGridViewButtonColumn3.DataPropertyName = "Gst_plus"
			dataGridViewCellStyle11.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter
			dataGridViewCellStyle11.ForeColor = Global.System.Drawing.Color.Purple
			Me.DataGridViewButtonColumn3.DefaultCellStyle = dataGridViewCellStyle11
			Me.DataGridViewButtonColumn3.FillWeight = 68.8888F
			Me.DataGridViewButtonColumn3.HeaderText = "+"
			Me.DataGridViewButtonColumn3.Name = "DataGridViewButtonColumn3"
			Me.DataGridViewButtonColumn3.Resizable = Global.System.Windows.Forms.DataGridViewTriState.[True]
			Me.DataGridViewButtonColumn3.SortMode = Global.System.Windows.Forms.DataGridViewColumnSortMode.Automatic
			Me.DataGridViewButtonColumn3.Text = "+"
			Me.DataGridViewButtonColumn3.UseColumnTextForButtonValue = True
			Me.DataGridViewButtonColumn3.Visible = False
			Me.DataGridViewButtonColumn3.Width = 30
			Me.DataGridViewTextBoxColumn11.DataPropertyName = "CGST"
			Me.DataGridViewTextBoxColumn11.FillWeight = 120.4923F
			Me.DataGridViewTextBoxColumn11.HeaderText = "CGST %"
			Me.DataGridViewTextBoxColumn11.Name = "DataGridViewTextBoxColumn11"
			Me.DataGridViewTextBoxColumn11.Visible = False
			Me.DataGridViewTextBoxColumn12.DataPropertyName = "SGST"
			Me.DataGridViewTextBoxColumn12.FillWeight = 182.0708F
			Me.DataGridViewTextBoxColumn12.HeaderText = "SGST/UTGST %"
			Me.DataGridViewTextBoxColumn12.Name = "DataGridViewTextBoxColumn12"
			Me.DataGridViewTextBoxColumn12.Visible = False
			Me.DataGridViewTextBoxColumn13.DataPropertyName = "IGST"
			Me.DataGridViewTextBoxColumn13.FillWeight = 101.0284F
			Me.DataGridViewTextBoxColumn13.HeaderText = "IGST %"
			Me.DataGridViewTextBoxColumn13.Name = "DataGridViewTextBoxColumn13"
			Me.DataGridViewTextBoxColumn13.Visible = False
			Me.DataGridViewTextBoxColumn14.DataPropertyName = "Cess"
			Me.DataGridViewTextBoxColumn14.FillWeight = 101.9943F
			Me.DataGridViewTextBoxColumn14.HeaderText = "CESS %"
			Me.DataGridViewTextBoxColumn14.Name = "DataGridViewTextBoxColumn14"
			Me.DataGridViewTextBoxColumn14.Visible = False
			Me.DataGridViewTextBoxColumn15.DataPropertyName = "ReorderPoint"
			Me.DataGridViewTextBoxColumn15.HeaderText = "Wholesale Sale Price"
			Me.DataGridViewTextBoxColumn15.Name = "DataGridViewTextBoxColumn15"
			Me.DataGridViewTextBoxColumn15.Visible = False
			Me.DataGridViewTextBoxColumn16.DataPropertyName = "Barcode"
			Me.DataGridViewTextBoxColumn16.HeaderText = "Barcode"
			Me.DataGridViewTextBoxColumn16.Name = "DataGridViewTextBoxColumn16"
			Me.DataGridViewTextBoxColumn16.Visible = False
			Me.DataGridViewTextBoxColumn17.HeaderText = "Opening Stock"
			Me.DataGridViewTextBoxColumn17.Name = "DataGridViewTextBoxColumn17"
			Me.DataGridViewTextBoxColumn17.Visible = False
			Me.cmbPurchaseUnit2.DataPropertyName = "PurchaseUnit"
			dataGridViewCellStyle12.Padding = New Global.System.Windows.Forms.Padding(2)
			Me.cmbPurchaseUnit2.DefaultCellStyle = dataGridViewCellStyle12
			Me.cmbPurchaseUnit2.FillWeight = 116.1214F
			Me.cmbPurchaseUnit2.HeaderText = "Purchase Main Unit"
			Me.cmbPurchaseUnit2.Name = "cmbPurchaseUnit2"
			Me.cmbPurchaseUnit2.Resizable = Global.System.Windows.Forms.DataGridViewTriState.[True]
			Me.cmbPurchaseUnit2.SortMode = Global.System.Windows.Forms.DataGridViewColumnSortMode.NotSortable
			Me.cmbPurchaseUnit2.Visible = False
			Me.cmbSalesUnit2.DataPropertyName = "SalesUnit"
			dataGridViewCellStyle13.Padding = New Global.System.Windows.Forms.Padding(2)
			Me.cmbSalesUnit2.DefaultCellStyle = dataGridViewCellStyle13
			Me.cmbSalesUnit2.FillWeight = 77.56514F
			Me.cmbSalesUnit2.HeaderText = "Sales Unit"
			Me.cmbSalesUnit2.Name = "cmbSalesUnit2"
			Me.cmbSalesUnit2.Resizable = Global.System.Windows.Forms.DataGridViewTriState.[True]
			Me.cmbSalesUnit2.SortMode = Global.System.Windows.Forms.DataGridViewColumnSortMode.NotSortable
			Me.cmbSalesUnit2.Visible = False
			Me.cmbAltunit2.DataPropertyName = "SalesAltUnit"
			dataGridViewCellStyle14.Padding = New Global.System.Windows.Forms.Padding(2)
			Me.cmbAltunit2.DefaultCellStyle = dataGridViewCellStyle14
			Me.cmbAltunit2.FillWeight = 69.68296F
			Me.cmbAltunit2.HeaderText = "Alter Unit"
			Me.cmbAltunit2.Name = "cmbAltunit2"
			Me.cmbAltunit2.Resizable = Global.System.Windows.Forms.DataGridViewTriState.[True]
			Me.cmbAltunit2.SortMode = Global.System.Windows.Forms.DataGridViewColumnSortMode.NotSortable
			Me.cmbAltunit2.Visible = False
			Me.DataGridViewTextBoxColumn18.DataPropertyName = "Conv"
			Me.DataGridViewTextBoxColumn18.FillWeight = 142.4686F
			Me.DataGridViewTextBoxColumn18.HeaderText = "Conversion Value"
			Me.DataGridViewTextBoxColumn18.Name = "DataGridViewTextBoxColumn18"
			Me.DataGridViewTextBoxColumn18.Visible = False
			Me.DataGridViewTextBoxColumn19.DataPropertyName = "MinStock"
			Me.DataGridViewTextBoxColumn19.FillWeight = 92.37314F
			Me.DataGridViewTextBoxColumn19.HeaderText = "Min Stock"
			Me.DataGridViewTextBoxColumn19.Name = "DataGridViewTextBoxColumn19"
			Me.DataGridViewTextBoxColumn19.Visible = False
			Me.DataGridViewTextBoxColumn20.DataPropertyName = "MRP"
			Me.DataGridViewTextBoxColumn20.HeaderText = "MRP"
			Me.DataGridViewTextBoxColumn20.Name = "DataGridViewTextBoxColumn20"
			Me.DataGridViewTextBoxColumn20.Visible = False
			Me.DataGridViewTextBoxColumn21.DataPropertyName = "Status"
			Me.DataGridViewTextBoxColumn21.HeaderText = "Active"
			Me.DataGridViewTextBoxColumn21.Name = "DataGridViewTextBoxColumn21"
			Me.DataGridViewTextBoxColumn21.Visible = False
			Me.cmbSalesTaxType2.DataPropertyName = "STax"
			dataGridViewCellStyle15.Padding = New Global.System.Windows.Forms.Padding(2)
			Me.cmbSalesTaxType2.DefaultCellStyle = dataGridViewCellStyle15
			Me.cmbSalesTaxType2.FillWeight = 88.44212F
			Me.cmbSalesTaxType2.HeaderText = "Sale Tax Type"
			Me.cmbSalesTaxType2.Name = "cmbSalesTaxType2"
			Me.cmbSalesTaxType2.Resizable = Global.System.Windows.Forms.DataGridViewTriState.[True]
			Me.cmbSalesTaxType2.SortMode = Global.System.Windows.Forms.DataGridViewColumnSortMode.NotSortable
			Me.cmbSalesTaxType2.Visible = False
			Me.cmbPurchaseTaxType2.DataPropertyName = "PTax"
			dataGridViewCellStyle16.Padding = New Global.System.Windows.Forms.Padding(2)
			Me.cmbPurchaseTaxType2.DefaultCellStyle = dataGridViewCellStyle16
			Me.cmbPurchaseTaxType2.FillWeight = 84.72654F
			Me.cmbPurchaseTaxType2.HeaderText = "Purchase Tax Type"
			Me.cmbPurchaseTaxType2.Name = "cmbPurchaseTaxType2"
			Me.cmbPurchaseTaxType2.Resizable = Global.System.Windows.Forms.DataGridViewTriState.[True]
			Me.cmbPurchaseTaxType2.SortMode = Global.System.Windows.Forms.DataGridViewColumnSortMode.NotSortable
			Me.cmbPurchaseTaxType2.Visible = False
			Me.ddlGdown2.DataPropertyName = "GDown"
			Me.ddlGdown2.FillWeight = 57.85149F
			Me.ddlGdown2.HeaderText = "Godown"
			Me.ddlGdown2.Name = "ddlGdown2"
			Me.ddlGdown2.Resizable = Global.System.Windows.Forms.DataGridViewTriState.[True]
			Me.ddlGdown2.SortMode = Global.System.Windows.Forms.DataGridViewColumnSortMode.NotSortable
			Me.ddlGdown2.Visible = False
			Me.ddlRack2.DataPropertyName = "Rack"
			Me.ddlRack2.FillWeight = 42.29925F
			Me.ddlRack2.HeaderText = "Rack"
			Me.ddlRack2.Name = "ddlRack2"
			Me.ddlRack2.Resizable = Global.System.Windows.Forms.DataGridViewTriState.[True]
			Me.ddlRack2.SortMode = Global.System.Windows.Forms.DataGridViewColumnSortMode.NotSortable
			Me.ddlRack2.Visible = False
			Me.DataGridViewTextBoxColumn22.DataPropertyName = "DefQty"
			Me.DataGridViewTextBoxColumn22.FillWeight = 90.80885F
			Me.DataGridViewTextBoxColumn22.HeaderText = "Default Sale Qty"
			Me.DataGridViewTextBoxColumn22.Name = "DataGridViewTextBoxColumn22"
			Me.DataGridViewTextBoxColumn22.Visible = False
			Me.txtOpeningStock2.DataPropertyName = "Qty"
			Me.txtOpeningStock2.FillWeight = 95.47243F
			Me.txtOpeningStock2.HeaderText = "Opening Stock"
			Me.txtOpeningStock2.Name = "txtOpeningStock2"
			Me.txtOpeningStock2.Width = 151
			Me.DataGridViewTextBoxColumn24.DataPropertyName = "Barcode"
			Me.DataGridViewTextBoxColumn24.FillWeight = 68.12365F
			Me.DataGridViewTextBoxColumn24.HeaderText = "Barcode"
			Me.DataGridViewTextBoxColumn24.Name = "DataGridViewTextBoxColumn24"
			Me.txtMRP.DataPropertyName = "MRP"
			Me.txtMRP.FillWeight = 50.81135F
			Me.txtMRP.HeaderText = "MRP"
			Me.txtMRP.Name = "txtMRP"
			Me.txtMRP.Width = 71
			Me.txtRSP1.DataPropertyName = "SalePrice"
			Me.txtRSP1.FillWeight = 90.11961F
			Me.txtRSP1.HeaderText = "Retail Sale Price"
			Me.txtRSP1.Name = "txtRSP1"
			Me.txtRSP1.Width = 166
			Me.DataGridViewTextBoxColumn27.DataPropertyName = "WSalePrice"
			Me.DataGridViewTextBoxColumn27.FillWeight = 84.05479F
			Me.DataGridViewTextBoxColumn27.HeaderText = "Wholesale Sale Price"
			Me.DataGridViewTextBoxColumn27.Name = "DataGridViewTextBoxColumn27"
			Me.DataGridViewTextBoxColumn27.Visible = False
			Me.DataGridViewTextBoxColumn28.DataPropertyName = "Batch"
			Me.DataGridViewTextBoxColumn28.FillWeight = 47.2846F
			Me.DataGridViewTextBoxColumn28.HeaderText = "Batch"
			Me.DataGridViewTextBoxColumn28.Name = "DataGridViewTextBoxColumn28"
			Me.DataGridViewTextBoxColumn28.Visible = False
			Me.DataGridViewTextBoxColumn29.DataPropertyName = "Mfgdate"
			Me.DataGridViewTextBoxColumn29.FillWeight = 53.91898F
			Me.DataGridViewTextBoxColumn29.HeaderText = "Mfg Date"
			Me.DataGridViewTextBoxColumn29.Name = "DataGridViewTextBoxColumn29"
			Me.DataGridViewTextBoxColumn29.Visible = False
			Me.DataGridViewTextBoxColumn30.DataPropertyName = "ExpDate"
			Me.DataGridViewTextBoxColumn30.FillWeight = 52.19537F
			Me.DataGridViewTextBoxColumn30.HeaderText = "Exp Date"
			Me.DataGridViewTextBoxColumn30.Name = "DataGridViewTextBoxColumn30"
			Me.DataGridViewTextBoxColumn30.Visible = False
			Me.cmbSize2.DataPropertyName = "Size"
			Me.cmbSize2.FillWeight = 28.57796F
			Me.cmbSize2.HeaderText = "Size"
			Me.cmbSize2.Name = "cmbSize2"
			Me.cmbSize2.Resizable = Global.System.Windows.Forms.DataGridViewTriState.[True]
			Me.cmbSize2.Width = 68
			Me.cmbColour2.DataPropertyName = "Colour"
			Me.cmbColour2.FillWeight = 30.52615F
			Me.cmbColour2.HeaderText = "Colour"
			Me.cmbColour2.Name = "cmbColour2"
			Me.cmbColour2.Resizable = Global.System.Windows.Forms.DataGridViewTriState.[True]
			Me.cmbColour2.SortMode = Global.System.Windows.Forms.DataGridViewColumnSortMode.NotSortable
			Me.cmbColour2.Width = 66
			Me.DataGridViewTextBoxColumn31.DataPropertyName = "IMEI1"
			Me.DataGridViewTextBoxColumn31.FillWeight = 40.28614F
			Me.DataGridViewTextBoxColumn31.HeaderText = "IME1"
			Me.DataGridViewTextBoxColumn31.Name = "DataGridViewTextBoxColumn31"
			Me.DataGridViewTextBoxColumn31.Visible = False
			Me.DataGridViewTextBoxColumn32.DataPropertyName = "IMEI2"
			Me.DataGridViewTextBoxColumn32.FillWeight = 39.46039F
			Me.DataGridViewTextBoxColumn32.HeaderText = "IME2"
			Me.DataGridViewTextBoxColumn32.Name = "DataGridViewTextBoxColumn32"
			Me.DataGridViewTextBoxColumn32.Visible = False
			Me.DataGridViewTextBoxColumn33.DataPropertyName = "Kitchen"
			Me.DataGridViewTextBoxColumn33.HeaderText = "Kitchen"
			Me.DataGridViewTextBoxColumn33.Name = "DataGridViewTextBoxColumn33"
			Me.DataGridViewTextBoxColumn33.Visible = False
			Me.Photo.DataPropertyName = "Photo"
			Me.Photo.FillWeight = 27.62098F
			Me.Photo.HeaderText = "Photo"
			Me.Photo.Image = Global.BillPoint.My.Resources.Resources._1__16_
			Me.Photo.ImageLayout = Global.System.Windows.Forms.DataGridViewImageCellLayout.Zoom
			Me.Photo.Name = "Photo"
			Me.Photo.Visible = False
			Me.btnAddNew.DataPropertyName = "btnAddNew"
			Me.btnAddNew.HeaderText = "+"
			Me.btnAddNew.Name = "btnAddNew"
			Me.btnAddNew.Text = "+"
			Me.btnAddNew.UseColumnTextForButtonValue = True
			Me.btnAddNew.Width = 24
			Me.Label14.AutoSize = True
			Me.Label14.Location = New Global.System.Drawing.Point(167, 285)
			Me.Label14.Name = "Label14"
			Me.Label14.Size = New Global.System.Drawing.Size(45, 13)
			Me.Label14.TabIndex = 1808
			Me.Label14.Text = "Label14"
			Me.Label13.AutoSize = True
			Me.Label13.Location = New Global.System.Drawing.Point(88, 285)
			Me.Label13.Name = "Label13"
			Me.Label13.Size = New Global.System.Drawing.Size(45, 13)
			Me.Label13.TabIndex = 1809
			Me.Label13.Text = "Label13"
			MyBase.AutoScaleDimensions = New Global.System.Drawing.SizeF(6F, 13F)
			MyBase.AutoScaleMode = Global.System.Windows.Forms.AutoScaleMode.Font
			Me.BackColor = Global.System.Drawing.Color.RoyalBlue
			MyBase.ClientSize = New Global.System.Drawing.Size(1117, 312)
			MyBase.ControlBox = False
			MyBase.Controls.Add(Me.pbgiftqr)
			MyBase.Controls.Add(Me.Label13)
			MyBase.Controls.Add(Me.Label14)
			MyBase.Controls.Add(Me.DataGridView2)
			MyBase.Controls.Add(Me.GelButton1)
			MyBase.Controls.Add(Me.GelButtonNewRecord)
			MyBase.Controls.Add(Me.cmbNP)
			MyBase.Controls.Add(Me.txtBarcode)
			MyBase.Controls.Add(Me.txtNP)
			MyBase.Controls.Add(Me.txtProductCode)
			MyBase.Controls.Add(Me.txtID)
			MyBase.Controls.Add(Me.txtBarcodeTempStock)
			MyBase.Controls.Add(Me.txtBar)
			MyBase.FormBorderStyle = Global.System.Windows.Forms.FormBorderStyle.Fixed3D
			MyBase.Icon = CType(componentResourceManager.GetObject("$this.Icon"), Global.System.Drawing.Icon)
			MyBase.KeyPreview = True
			MyBase.MaximizeBox = False
			MyBase.MinimizeBox = False
			MyBase.Name = "frmProductRec_variant"
			MyBase.ShowIcon = False
			MyBase.ShowInTaskbar = False
			MyBase.StartPosition = Global.System.Windows.Forms.FormStartPosition.CenterScreen
			CType(Me.pbgiftqr, Global.System.ComponentModel.ISupportInitialize).EndInit()
			CType(Me.DataGridView2, Global.System.ComponentModel.ISupportInitialize).EndInit()
			MyBase.ResumeLayout(False)
			MyBase.PerformLayout()
		End Sub

		' Token: 0x040038C5 RID: 14533
		Private components As Global.System.ComponentModel.IContainer
	End Class
End Namespace
