Namespace BillPoint
	' Token: 0x020001E3 RID: 483
		Public Partial Class frmProductRec1
		Inherits Global.System.Windows.Forms.Form

		' Token: 0x0600813A RID: 33082 RVA: 0x005F9050 File Offset: 0x005F7250
		<Global.System.Diagnostics.DebuggerNonUserCode()>
		Protected Overrides Sub Dispose(disposing As Boolean)
			Try
				Dim flag As Boolean = disposing AndAlso Me.components IsNot Nothing
				If flag Then
					Me.components.Dispose()
				End If
			Finally
				MyBase.Dispose(disposing)
			End Try
		End Sub

		' Token: 0x0600813B RID: 33083 RVA: 0x005F90A0 File Offset: 0x005F72A0
		<Global.System.Diagnostics.DebuggerStepThrough()>
		Private Sub InitializeComponent()
			Dim dataGridViewCellStyle As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle2 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle3 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle4 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle5 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim componentResourceManager As Global.System.ComponentModel.ComponentResourceManager = New Global.System.ComponentModel.ComponentResourceManager(GetType(Global.BillPoint.frmProductRec1))
			Dim dataGridViewCellStyle6 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle7 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle8 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle9 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle10 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle11 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle12 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle13 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle14 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle15 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle16 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Me.DataGridView1 = New Global.System.Windows.Forms.DataGridView()
			Me.txtBar = New Global.System.Windows.Forms.TextBox()
			Me.txtBarcodeTempStock = New Global.System.Windows.Forms.TextBox()
			Me.txtID = New Global.System.Windows.Forms.TextBox()
			Me.pbgiftqr = New Global.System.Windows.Forms.PictureBox()
			Me.txtProductCode = New Global.System.Windows.Forms.TextBox()
			Me.txtNP = New Global.System.Windows.Forms.TextBox()
			Me.txtBarcode = New Global.System.Windows.Forms.TextBox()
			Me.cmbNP = New Global.System.Windows.Forms.ComboBox()
			Me.GelButtonNewRecord = New Global.GelButtons.GelButton()
			Me.PID = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.ProductCode = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.ProductName = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.cmbCategory = New Global.System.Windows.Forms.DataGridViewComboBoxColumn()
			Me.btnAddCategory = New Global.System.Windows.Forms.DataGridViewButtonColumn()
			Me.cmbSubCategory = New Global.System.Windows.Forms.DataGridViewComboBoxColumn()
			Me.btnAddSubCategory = New Global.System.Windows.Forms.DataGridViewButtonColumn()
			Me.txtSubCategoryID = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.txtHSNCode = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.txtPartNo = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.txtFeatures = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.txtCostPrice = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.RSPrice = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.txtDiscount = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.cmbGST = New Global.System.Windows.Forms.DataGridViewComboBoxColumn()
			Me.btnAddGSTPer = New Global.System.Windows.Forms.DataGridViewButtonColumn()
			Me.txtCGST = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.txtSGST = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.txtIGST = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.txtCESS = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.WSPrice = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Barcode = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.OpeningStock = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.cmbPurchaseUnit = New Global.System.Windows.Forms.DataGridViewComboBoxColumn()
			Me.cmbSalesUnit = New Global.System.Windows.Forms.DataGridViewComboBoxColumn()
			Me.cmbAltunit = New Global.System.Windows.Forms.DataGridViewComboBoxColumn()
			Me.Conv = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.txtMinStock = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DefMRP = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Active = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.cmbSalesTaxType = New Global.System.Windows.Forms.DataGridViewComboBoxColumn()
			Me.cmbPurchaseTaxType = New Global.System.Windows.Forms.DataGridViewComboBoxColumn()
			Me.ddlGdown = New Global.System.Windows.Forms.DataGridViewComboBoxColumn()
			Me.ddlRack = New Global.System.Windows.Forms.DataGridViewComboBoxColumn()
			Me.txtSaleQty = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.txtOpeningStock = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.txtBarcode_TempStock = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.txtDefMRP = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.txtRSP = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.txtWSP = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.txtBatch = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.MfgDate = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.ExpDate = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.cmbSize = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.cmbColour = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.txtIMEI1 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.txtIMEI2 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Kitchen = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Photo = New Global.System.Windows.Forms.DataGridViewImageColumn()
			Me.InsertButtonColumn = New Global.System.Windows.Forms.DataGridViewButtonColumn()
			Me.UpdateButtonColumn = New Global.System.Windows.Forms.DataGridViewButtonColumn()
			Me.DeleteButtonColumn = New Global.System.Windows.Forms.DataGridViewButtonColumn()
			Me.PrintBarcodeButton = New Global.System.Windows.Forms.DataGridViewButtonColumn()
			Me.Mark = New Global.System.Windows.Forms.DataGridViewCheckBoxColumn()
			Me.variantName = New Global.System.Windows.Forms.DataGridViewButtonColumn()
			CType(Me.DataGridView1, Global.System.ComponentModel.ISupportInitialize).BeginInit()
			CType(Me.pbgiftqr, Global.System.ComponentModel.ISupportInitialize).BeginInit()
			MyBase.SuspendLayout()
			dataGridViewCellStyle.BackColor = Global.System.Drawing.Color.FloralWhite
			dataGridViewCellStyle.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 9.75F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			Me.DataGridView1.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle
			Me.DataGridView1.Anchor = Global.System.Windows.Forms.AnchorStyles.Top Or Global.System.Windows.Forms.AnchorStyles.Bottom Or Global.System.Windows.Forms.AnchorStyles.Left Or Global.System.Windows.Forms.AnchorStyles.Right
			Me.DataGridView1.AutoSizeColumnsMode = Global.System.Windows.Forms.DataGridViewAutoSizeColumnsMode.DisplayedCells
			Me.DataGridView1.BackgroundColor = Global.System.Drawing.Color.White
			Me.DataGridView1.ColumnHeadersBorderStyle = Global.System.Windows.Forms.DataGridViewHeaderBorderStyle.[Single]
			dataGridViewCellStyle2.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter
			dataGridViewCellStyle2.BackColor = Global.System.Drawing.Color.DarkViolet
			dataGridViewCellStyle2.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 11.25F, Global.System.Drawing.FontStyle.Bold, Global.System.Drawing.GraphicsUnit.Point, 0)
			dataGridViewCellStyle2.ForeColor = Global.System.Drawing.Color.White
			dataGridViewCellStyle2.SelectionBackColor = Global.System.Drawing.Color.LightSteelBlue
			dataGridViewCellStyle2.SelectionForeColor = Global.System.Drawing.SystemColors.HighlightText
			dataGridViewCellStyle2.WrapMode = Global.System.Windows.Forms.DataGridViewTriState.[True]
			Me.DataGridView1.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2
			Me.DataGridView1.ColumnHeadersHeight = 40
			Me.DataGridView1.Columns.AddRange(New Global.System.Windows.Forms.DataGridViewColumn() { Me.PID, Me.ProductCode, Me.ProductName, Me.cmbCategory, Me.btnAddCategory, Me.cmbSubCategory, Me.btnAddSubCategory, Me.txtSubCategoryID, Me.txtHSNCode, Me.txtPartNo, Me.txtFeatures, Me.txtCostPrice, Me.RSPrice, Me.txtDiscount, Me.cmbGST, Me.btnAddGSTPer, Me.txtCGST, Me.txtSGST, Me.txtIGST, Me.txtCESS, Me.WSPrice, Me.Barcode, Me.OpeningStock, Me.cmbPurchaseUnit, Me.cmbSalesUnit, Me.cmbAltunit, Me.Conv, Me.txtMinStock, Me.DefMRP, Me.Active, Me.cmbSalesTaxType, Me.cmbPurchaseTaxType, Me.ddlGdown, Me.ddlRack, Me.txtSaleQty, Me.txtOpeningStock, Me.txtBarcode_TempStock, Me.txtDefMRP, Me.txtRSP, Me.txtWSP, Me.txtBatch, Me.MfgDate, Me.ExpDate, Me.cmbSize, Me.cmbColour, Me.txtIMEI1, Me.txtIMEI2, Me.Kitchen, Me.Photo, Me.InsertButtonColumn, Me.UpdateButtonColumn, Me.DeleteButtonColumn, Me.PrintBarcodeButton, Me.Mark, Me.variantName })
			Me.DataGridView1.Cursor = Global.System.Windows.Forms.Cursors.Hand
			dataGridViewCellStyle3.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft
			dataGridViewCellStyle3.BackColor = Global.System.Drawing.SystemColors.Window
			dataGridViewCellStyle3.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 9.75F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			dataGridViewCellStyle3.ForeColor = Global.System.Drawing.SystemColors.ControlText
			dataGridViewCellStyle3.SelectionBackColor = Global.System.Drawing.SystemColors.Highlight
			dataGridViewCellStyle3.SelectionForeColor = Global.System.Drawing.SystemColors.HighlightText
			dataGridViewCellStyle3.WrapMode = Global.System.Windows.Forms.DataGridViewTriState.[False]
			Me.DataGridView1.DefaultCellStyle = dataGridViewCellStyle3
			Me.DataGridView1.EnableHeadersVisualStyles = False
			Me.DataGridView1.GridColor = Global.System.Drawing.Color.White
			Me.DataGridView1.Location = New Global.System.Drawing.Point(0, 0)
			Me.DataGridView1.MultiSelect = False
			Me.DataGridView1.Name = "DataGridView1"
			Me.DataGridView1.RowHeadersBorderStyle = Global.System.Windows.Forms.DataGridViewHeaderBorderStyle.[Single]
			dataGridViewCellStyle4.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft
			dataGridViewCellStyle4.BackColor = Global.System.Drawing.Color.DarkViolet
			dataGridViewCellStyle4.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 9.75F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			dataGridViewCellStyle4.ForeColor = Global.System.Drawing.Color.White
			dataGridViewCellStyle4.SelectionBackColor = Global.System.Drawing.Color.OrangeRed
			dataGridViewCellStyle4.SelectionForeColor = Global.System.Drawing.Color.White
			dataGridViewCellStyle4.WrapMode = Global.System.Windows.Forms.DataGridViewTriState.[True]
			Me.DataGridView1.RowHeadersDefaultCellStyle = dataGridViewCellStyle4
			Me.DataGridView1.RowHeadersWidth = 25
			Me.DataGridView1.RowHeadersWidthSizeMode = Global.System.Windows.Forms.DataGridViewRowHeadersWidthSizeMode.DisableResizing
			dataGridViewCellStyle5.BackColor = Global.System.Drawing.Color.White
			dataGridViewCellStyle5.Font = New Global.System.Drawing.Font("Tahoma", 9.75F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			dataGridViewCellStyle5.SelectionBackColor = Global.System.Drawing.Color.DarkSlateGray
			dataGridViewCellStyle5.SelectionForeColor = Global.System.Drawing.Color.White
			Me.DataGridView1.RowsDefaultCellStyle = dataGridViewCellStyle5
			Me.DataGridView1.RowTemplate.Height = 30
			Me.DataGridView1.RowTemplate.Resizable = Global.System.Windows.Forms.DataGridViewTriState.[False]
			Me.DataGridView1.SelectionMode = Global.System.Windows.Forms.DataGridViewSelectionMode.CellSelect
			Me.DataGridView1.Size = New Global.System.Drawing.Size(1248, 203)
			Me.DataGridView1.TabIndex = 437
			Me.DataGridView1.TabStop = False
			Me.txtBar.Location = New Global.System.Drawing.Point(596, 5)
			Me.txtBar.Name = "txtBar"
			Me.txtBar.Size = New Global.System.Drawing.Size(100, 20)
			Me.txtBar.TabIndex = 438
			Me.txtBar.Visible = False
			Me.txtBarcodeTempStock.Location = New Global.System.Drawing.Point(729, 5)
			Me.txtBarcodeTempStock.Name = "txtBarcodeTempStock"
			Me.txtBarcodeTempStock.Size = New Global.System.Drawing.Size(100, 20)
			Me.txtBarcodeTempStock.TabIndex = 439
			Me.txtBarcodeTempStock.Visible = False
			Me.txtID.Location = New Global.System.Drawing.Point(470, 5)
			Me.txtID.Name = "txtID"
			Me.txtID.Size = New Global.System.Drawing.Size(100, 20)
			Me.txtID.TabIndex = 440
			Me.txtID.Visible = False
			Me.pbgiftqr.BorderStyle = Global.System.Windows.Forms.BorderStyle.FixedSingle
			Me.pbgiftqr.Image = Global.BillPoint.My.Resources.Resources.Noimage
			Me.pbgiftqr.Location = New Global.System.Drawing.Point(875, 5)
			Me.pbgiftqr.Name = "pbgiftqr"
			Me.pbgiftqr.Size = New Global.System.Drawing.Size(32, 40)
			Me.pbgiftqr.TabIndex = 1800
			Me.pbgiftqr.TabStop = False
			Me.pbgiftqr.Visible = False
			Me.txtProductCode.Location = New Global.System.Drawing.Point(350, 5)
			Me.txtProductCode.Name = "txtProductCode"
			Me.txtProductCode.Size = New Global.System.Drawing.Size(100, 20)
			Me.txtProductCode.TabIndex = 1801
			Me.txtProductCode.Visible = False
			Me.txtNP.Location = New Global.System.Drawing.Point(228, 5)
			Me.txtNP.Name = "txtNP"
			Me.txtNP.Size = New Global.System.Drawing.Size(100, 20)
			Me.txtNP.TabIndex = 1802
			Me.txtNP.Visible = False
			Me.txtBarcode.Location = New Global.System.Drawing.Point(940, 5)
			Me.txtBarcode.Name = "txtBarcode"
			Me.txtBarcode.Size = New Global.System.Drawing.Size(100, 20)
			Me.txtBarcode.TabIndex = 1803
			Me.txtBarcode.Visible = False
			Me.cmbNP.FormattingEnabled = True
			Me.cmbNP.Location = New Global.System.Drawing.Point(1089, 5)
			Me.cmbNP.Name = "cmbNP"
			Me.cmbNP.Size = New Global.System.Drawing.Size(121, 21)
			Me.cmbNP.TabIndex = 1804
			Me.cmbNP.Visible = False
			Me.GelButtonNewRecord.Anchor = Global.System.Windows.Forms.AnchorStyles.Top Or Global.System.Windows.Forms.AnchorStyles.Right
			Me.GelButtonNewRecord.BackColor = Global.System.Drawing.Color.MediumVioletRed
			Me.GelButtonNewRecord.FlatAppearance.BorderSize = 0
			Me.GelButtonNewRecord.FlatStyle = Global.System.Windows.Forms.FlatStyle.Flat
			Me.GelButtonNewRecord.Font = New Global.System.Drawing.Font("Segoe UI Semibold", 12F, Global.System.Drawing.FontStyle.Bold, Global.System.Drawing.GraphicsUnit.Point, 0)
			Me.GelButtonNewRecord.ForeColor = Global.System.Drawing.Color.White
			Me.GelButtonNewRecord.GradientBottom = Global.System.Drawing.Color.LimeGreen
			Me.GelButtonNewRecord.GradientTop = Global.System.Drawing.Color.FromArgb(255, 128, 128)
			Me.GelButtonNewRecord.Image = CType(componentResourceManager.GetObject("GelButtonNewRecord.Image"), Global.System.Drawing.Image)
			Me.GelButtonNewRecord.ImageAlign = Global.System.Drawing.ContentAlignment.MiddleLeft
			Me.GelButtonNewRecord.Location = New Global.System.Drawing.Point(498, 234)
			Me.GelButtonNewRecord.Name = "GelButtonNewRecord"
			Me.GelButtonNewRecord.Size = New Global.System.Drawing.Size(108, 33)
			Me.GelButtonNewRecord.TabIndex = 1805
			Me.GelButtonNewRecord.Text = "New"
			Me.GelButtonNewRecord.TextAlign = Global.System.Drawing.ContentAlignment.MiddleRight
			Me.GelButtonNewRecord.UseVisualStyleBackColor = False
			Me.GelButtonNewRecord.Visible = False
			Me.PID.DataPropertyName = "PID"
			Me.PID.HeaderText = "PID"
			Me.PID.Name = "PID"
			Me.PID.Visible = False
			Me.PID.Width = 59
			Me.ProductCode.DataPropertyName = "ProductCode"
			Me.ProductCode.FillWeight = 284.084F
			Me.ProductCode.HeaderText = "Product Code"
			Me.ProductCode.Name = "ProductCode"
			Me.ProductCode.[ReadOnly] = True
			Me.ProductCode.Width = 124
			Me.ProductName.DataPropertyName = "Productname"
			Me.ProductName.FillWeight = 275.771F
			Me.ProductName.HeaderText = "Product Name"
			Me.ProductName.Name = "ProductName"
			Me.ProductName.Resizable = Global.System.Windows.Forms.DataGridViewTriState.[True]
			Me.ProductName.Width = 128
			Me.cmbCategory.DataPropertyName = "CategoryName"
			dataGridViewCellStyle6.BackColor = Global.System.Drawing.Color.Red
			dataGridViewCellStyle6.ForeColor = Global.System.Drawing.Color.White
			dataGridViewCellStyle6.Padding = New Global.System.Windows.Forms.Padding(2)
			Me.cmbCategory.DefaultCellStyle = dataGridViewCellStyle6
			Me.cmbCategory.FillWeight = 153.3014F
			Me.cmbCategory.HeaderText = "Category"
			Me.cmbCategory.Name = "cmbCategory"
			Me.cmbCategory.Width = 81
			Me.btnAddCategory.DataPropertyName = "Category_plus"
			dataGridViewCellStyle7.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter
			dataGridViewCellStyle7.ForeColor = Global.System.Drawing.Color.Purple
			Me.btnAddCategory.DefaultCellStyle = dataGridViewCellStyle7
			Me.btnAddCategory.FillWeight = 65.74377F
			Me.btnAddCategory.HeaderText = "+"
			Me.btnAddCategory.Name = "btnAddCategory"
			Me.btnAddCategory.Text = "+"
			Me.btnAddCategory.UseColumnTextForButtonValue = True
			Me.btnAddCategory.Width = 23
			Me.cmbSubCategory.DataPropertyName = "SubCategoryName"
			dataGridViewCellStyle8.Padding = New Global.System.Windows.Forms.Padding(2)
			Me.cmbSubCategory.DefaultCellStyle = dataGridViewCellStyle8
			Me.cmbSubCategory.FillWeight = 211.0264F
			Me.cmbSubCategory.HeaderText = "Sub Category / Brand"
			Me.cmbSubCategory.Name = "cmbSubCategory"
			Me.cmbSubCategory.Width = 117
			Me.btnAddSubCategory.DataPropertyName = "Subcategory_plus"
			dataGridViewCellStyle9.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter
			dataGridViewCellStyle9.ForeColor = Global.System.Drawing.Color.Purple
			Me.btnAddSubCategory.DefaultCellStyle = dataGridViewCellStyle9
			Me.btnAddSubCategory.FillWeight = 61.50089F
			Me.btnAddSubCategory.HeaderText = "+"
			Me.btnAddSubCategory.Name = "btnAddSubCategory"
			Me.btnAddSubCategory.Text = "+"
			Me.btnAddSubCategory.UseColumnTextForButtonValue = True
			Me.btnAddSubCategory.Width = 23
			Me.txtSubCategoryID.HeaderText = "SubCategoryID"
			Me.txtSubCategoryID.Name = "txtSubCategoryID"
			Me.txtSubCategoryID.Visible = False
			Me.txtSubCategoryID.Width = 145
			Me.txtHSNCode.DataPropertyName = "HSNCode"
			Me.txtHSNCode.FillWeight = 192.4218F
			Me.txtHSNCode.HeaderText = "HSN Code"
			Me.txtHSNCode.Name = "txtHSNCode"
			Me.txtHSNCode.Width = 103
			Me.txtPartNo.DataPropertyName = "PartNo"
			Me.txtPartNo.FillWeight = 199.441F
			Me.txtPartNo.HeaderText = "Part / Group"
			Me.txtPartNo.Name = "txtPartNo"
			Me.txtPartNo.Width = 114
			Me.txtFeatures.DataPropertyName = "Description"
			dataGridViewCellStyle10.WrapMode = Global.System.Windows.Forms.DataGridViewTriState.[False]
			Me.txtFeatures.DefaultCellStyle = dataGridViewCellStyle10
			Me.txtFeatures.FillWeight = 190.5685F
			Me.txtFeatures.HeaderText = "Description"
			Me.txtFeatures.Name = "txtFeatures"
			Me.txtFeatures.Width = 118
			Me.txtCostPrice.DataPropertyName = "CostPrice"
			Me.txtCostPrice.FillWeight = 203.4047F
			Me.txtCostPrice.HeaderText = "Purchase Price"
			Me.txtCostPrice.Name = "txtCostPrice"
			Me.txtCostPrice.Width = 134
			Me.RSPrice.DataPropertyName = "SellingPrice"
			Me.RSPrice.HeaderText = "Retail Sale Price"
			Me.RSPrice.Name = "RSPrice"
			Me.RSPrice.Visible = False
			Me.RSPrice.Width = 143
			Me.txtDiscount.DataPropertyName = "Discount"
			Me.txtDiscount.FillWeight = 156.3039F
			Me.txtDiscount.HeaderText = "Discount %"
			Me.txtDiscount.Name = "txtDiscount"
			Me.txtDiscount.Width = 108
			Me.cmbGST.DataPropertyName = "cmbGST"
			Me.cmbGST.FillWeight = 74.17998F
			Me.cmbGST.HeaderText = "GSt %"
			Me.cmbGST.Name = "cmbGST"
			Me.cmbGST.Width = 42
			Me.btnAddGSTPer.DataPropertyName = "Gst_plus"
			dataGridViewCellStyle11.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter
			dataGridViewCellStyle11.ForeColor = Global.System.Drawing.Color.Purple
			Me.btnAddGSTPer.DefaultCellStyle = dataGridViewCellStyle11
			Me.btnAddGSTPer.FillWeight = 68.8888F
			Me.btnAddGSTPer.HeaderText = "+"
			Me.btnAddGSTPer.Name = "btnAddGSTPer"
			Me.btnAddGSTPer.Resizable = Global.System.Windows.Forms.DataGridViewTriState.[True]
			Me.btnAddGSTPer.SortMode = Global.System.Windows.Forms.DataGridViewColumnSortMode.Automatic
			Me.btnAddGSTPer.Text = "+"
			Me.btnAddGSTPer.UseColumnTextForButtonValue = True
			Me.btnAddGSTPer.Width = 42
			Me.txtCGST.DataPropertyName = "CGST"
			Me.txtCGST.FillWeight = 120.4923F
			Me.txtCGST.HeaderText = "CGST %"
			Me.txtCGST.Name = "txtCGST"
			Me.txtCGST.Width = 89
			Me.txtSGST.DataPropertyName = "SGST"
			Me.txtSGST.FillWeight = 182.0708F
			Me.txtSGST.HeaderText = "SGST/UTGST %"
			Me.txtSGST.Name = "txtSGST"
			Me.txtSGST.Width = 143
			Me.txtIGST.DataPropertyName = "IGST"
			Me.txtIGST.FillWeight = 101.0284F
			Me.txtIGST.HeaderText = "IGST %"
			Me.txtIGST.Name = "txtIGST"
			Me.txtIGST.Width = 82
			Me.txtCESS.DataPropertyName = "Cess"
			Me.txtCESS.FillWeight = 101.9943F
			Me.txtCESS.HeaderText = "CESS %"
			Me.txtCESS.Name = "txtCESS"
			Me.txtCESS.Width = 88
			Me.WSPrice.DataPropertyName = "ReorderPoint"
			Me.WSPrice.HeaderText = "Wholesale Sale Price"
			Me.WSPrice.Name = "WSPrice"
			Me.WSPrice.Visible = False
			Me.WSPrice.Width = 141
			Me.Barcode.DataPropertyName = "Barcode"
			Me.Barcode.HeaderText = "Barcode"
			Me.Barcode.Name = "Barcode"
			Me.Barcode.Visible = False
			Me.Barcode.Width = 95
			Me.OpeningStock.DataPropertyName = "OpeningStock"
			Me.OpeningStock.HeaderText = "Opening Stock"
			Me.OpeningStock.Name = "OpeningStock"
			Me.OpeningStock.Visible = False
			Me.OpeningStock.Width = 131
			Me.cmbPurchaseUnit.DataPropertyName = "PurchaseUnit"
			dataGridViewCellStyle12.Padding = New Global.System.Windows.Forms.Padding(2)
			Me.cmbPurchaseUnit.DefaultCellStyle = dataGridViewCellStyle12
			Me.cmbPurchaseUnit.FillWeight = 116.1214F
			Me.cmbPurchaseUnit.HeaderText = "Purchase Main Unit"
			Me.cmbPurchaseUnit.Name = "cmbPurchaseUnit"
			Me.cmbPurchaseUnit.Width = 117
			Me.cmbSalesUnit.DataPropertyName = "SalesUnit"
			dataGridViewCellStyle13.Padding = New Global.System.Windows.Forms.Padding(2)
			Me.cmbSalesUnit.DefaultCellStyle = dataGridViewCellStyle13
			Me.cmbSalesUnit.FillWeight = 77.56514F
			Me.cmbSalesUnit.HeaderText = "Sales Unit"
			Me.cmbSalesUnit.Name = "cmbSalesUnit"
			Me.cmbSalesUnit.Width = 81
			Me.cmbAltunit.DataPropertyName = "SalesAltUnit"
			dataGridViewCellStyle14.Padding = New Global.System.Windows.Forms.Padding(2)
			Me.cmbAltunit.DefaultCellStyle = dataGridViewCellStyle14
			Me.cmbAltunit.FillWeight = 69.68296F
			Me.cmbAltunit.HeaderText = "Alter Unit"
			Me.cmbAltunit.Name = "cmbAltunit"
			Me.cmbAltunit.Width = 47
			Me.Conv.DataPropertyName = "Conv"
			Me.Conv.FillWeight = 142.4686F
			Me.Conv.HeaderText = "Conversion Value"
			Me.Conv.Name = "Conv"
			Me.Conv.Width = 150
			Me.txtMinStock.DataPropertyName = "MinStock"
			Me.txtMinStock.FillWeight = 92.37314F
			Me.txtMinStock.HeaderText = "Min Stock"
			Me.txtMinStock.Name = "txtMinStock"
			Me.txtMinStock.Width = 99
			Me.DefMRP.DataPropertyName = "MRP"
			Me.DefMRP.HeaderText = "MRP"
			Me.DefMRP.Name = "DefMRP"
			Me.DefMRP.Visible = False
			Me.DefMRP.Width = 69
			Me.Active.DataPropertyName = "Status"
			Me.Active.HeaderText = "Active"
			Me.Active.Name = "Active"
			Me.Active.Visible = False
			Me.Active.Width = 77
			Me.cmbSalesTaxType.DataPropertyName = "STax"
			dataGridViewCellStyle15.Padding = New Global.System.Windows.Forms.Padding(2)
			Me.cmbSalesTaxType.DefaultCellStyle = dataGridViewCellStyle15
			Me.cmbSalesTaxType.FillWeight = 88.44212F
			Me.cmbSalesTaxType.HeaderText = "Sale Tax Type"
			Me.cmbSalesTaxType.Items.AddRange(New Object() { "Inclusive", "Exclusive", "Exempt GST", "No Taxes" })
			Me.cmbSalesTaxType.Name = "cmbSalesTaxType"
			Me.cmbSalesTaxType.Width = 107
			Me.cmbPurchaseTaxType.DataPropertyName = "PTax"
			dataGridViewCellStyle16.Padding = New Global.System.Windows.Forms.Padding(2)
			Me.cmbPurchaseTaxType.DefaultCellStyle = dataGridViewCellStyle16
			Me.cmbPurchaseTaxType.FillWeight = 84.72654F
			Me.cmbPurchaseTaxType.HeaderText = "Purchase Tax Type"
			Me.cmbPurchaseTaxType.Items.AddRange(New Object() { "Inclusive", "Exclusive", "Exempt GST", "No Taxes" })
			Me.cmbPurchaseTaxType.Name = "cmbPurchaseTaxType"
			Me.cmbPurchaseTaxType.Resizable = Global.System.Windows.Forms.DataGridViewTriState.[True]
			Me.cmbPurchaseTaxType.Width = 109
			Me.ddlGdown.DataPropertyName = "GDown"
			Me.ddlGdown.FillWeight = 57.85149F
			Me.ddlGdown.HeaderText = "Godown"
			Me.ddlGdown.Name = "ddlGdown"
			Me.ddlGdown.Width = 76
			Me.ddlRack.DataPropertyName = "Rack"
			Me.ddlRack.FillWeight = 42.29925F
			Me.ddlRack.HeaderText = "Rack"
			Me.ddlRack.Name = "ddlRack"
			Me.ddlRack.Width = 52
			Me.txtSaleQty.DataPropertyName = "DefQty"
			Me.txtSaleQty.FillWeight = 90.80885F
			Me.txtSaleQty.HeaderText = "Default Sale Qty"
			Me.txtSaleQty.Name = "txtSaleQty"
			Me.txtSaleQty.Width = 117
			Me.txtOpeningStock.DataPropertyName = "Qty"
			Me.txtOpeningStock.FillWeight = 95.47243F
			Me.txtOpeningStock.HeaderText = "Opening Stock"
			Me.txtOpeningStock.Name = "txtOpeningStock"
			Me.txtOpeningStock.Width = 131
			Me.txtBarcode_TempStock.DataPropertyName = "Barcode"
			Me.txtBarcode_TempStock.FillWeight = 68.12365F
			Me.txtBarcode_TempStock.HeaderText = "Barcode"
			Me.txtBarcode_TempStock.Name = "txtBarcode_TempStock"
			Me.txtBarcode_TempStock.Width = 95
			Me.txtDefMRP.DataPropertyName = "MRP"
			Me.txtDefMRP.FillWeight = 50.81135F
			Me.txtDefMRP.HeaderText = "MRP"
			Me.txtDefMRP.Name = "txtDefMRP"
			Me.txtDefMRP.Width = 69
			Me.txtRSP.DataPropertyName = "SalePrice"
			Me.txtRSP.FillWeight = 90.11961F
			Me.txtRSP.HeaderText = "Retail Sale Price"
			Me.txtRSP.Name = "txtRSP"
			Me.txtRSP.Width = 143
			Me.txtWSP.DataPropertyName = "WSalePrice"
			Me.txtWSP.FillWeight = 84.05479F
			Me.txtWSP.HeaderText = "Wholesale Sale Price"
			Me.txtWSP.Name = "txtWSP"
			Me.txtWSP.Width = 141
			Me.txtBatch.DataPropertyName = "Batch"
			Me.txtBatch.FillWeight = 47.2846F
			Me.txtBatch.HeaderText = "Batch"
			Me.txtBatch.Name = "txtBatch"
			Me.txtBatch.Width = 75
			Me.MfgDate.DataPropertyName = "Mfgdate"
			Me.MfgDate.FillWeight = 53.91898F
			Me.MfgDate.HeaderText = "Mfg Date"
			Me.MfgDate.Name = "MfgDate"
			Me.MfgDate.Width = 92
			Me.ExpDate.DataPropertyName = "ExpDate"
			Me.ExpDate.FillWeight = 52.19537F
			Me.ExpDate.HeaderText = "Exp Date"
			Me.ExpDate.Name = "ExpDate"
			Me.ExpDate.Width = 92
			Me.cmbSize.DataPropertyName = "Size"
			Me.cmbSize.FillWeight = 28.57796F
			Me.cmbSize.HeaderText = "Size"
			Me.cmbSize.Name = "cmbSize"
			Me.cmbSize.Resizable = Global.System.Windows.Forms.DataGridViewTriState.[True]
			Me.cmbSize.SortMode = Global.System.Windows.Forms.DataGridViewColumnSortMode.NotSortable
			Me.cmbSize.Width = 46
			Me.cmbColour.DataPropertyName = "Colour"
			Me.cmbColour.FillWeight = 30.52615F
			Me.cmbColour.HeaderText = "Colour"
			Me.cmbColour.Name = "cmbColour"
			Me.cmbColour.Resizable = Global.System.Windows.Forms.DataGridViewTriState.[True]
			Me.cmbColour.SortMode = Global.System.Windows.Forms.DataGridViewColumnSortMode.NotSortable
			Me.cmbColour.Width = 64
			Me.txtIMEI1.DataPropertyName = "IMEI1"
			Me.txtIMEI1.FillWeight = 40.28614F
			Me.txtIMEI1.HeaderText = "IME1"
			Me.txtIMEI1.Name = "txtIMEI1"
			Me.txtIMEI1.Width = 70
			Me.txtIMEI2.DataPropertyName = "IMEI2"
			Me.txtIMEI2.FillWeight = 39.46039F
			Me.txtIMEI2.HeaderText = "IME2"
			Me.txtIMEI2.Name = "txtIMEI2"
			Me.txtIMEI2.Width = 70
			Me.Kitchen.DataPropertyName = "Kitchen"
			Me.Kitchen.HeaderText = "Kitchen"
			Me.Kitchen.Name = "Kitchen"
			Me.Kitchen.Visible = False
			Me.Kitchen.Width = 88
			Me.Photo.DataPropertyName = "Photo"
			Me.Photo.FillWeight = 27.62098F
			Me.Photo.HeaderText = "Photo"
			Me.Photo.Image = Global.BillPoint.My.Resources.Resources._12
			Me.Photo.ImageLayout = Global.System.Windows.Forms.DataGridViewImageCellLayout.Zoom
			Me.Photo.Name = "Photo"
			Me.Photo.Width = 58
			Me.InsertButtonColumn.FillWeight = 26.04096F
			Me.InsertButtonColumn.HeaderText = "Insert"
			Me.InsertButtonColumn.Name = "InsertButtonColumn"
			Me.InsertButtonColumn.Text = "Insert"
			Me.InsertButtonColumn.UseColumnTextForButtonValue = True
			Me.InsertButtonColumn.Width = 55
			Me.UpdateButtonColumn.DataPropertyName = "UpdateButtonColumn"
			Me.UpdateButtonColumn.FillWeight = 32.01813F
			Me.UpdateButtonColumn.HeaderText = "Update"
			Me.UpdateButtonColumn.Name = "UpdateButtonColumn"
			Me.UpdateButtonColumn.Text = "Update"
			Me.UpdateButtonColumn.UseColumnTextForButtonValue = True
			Me.UpdateButtonColumn.Width = 66
			Me.DeleteButtonColumn.DataPropertyName = "DeleteButtonColumn"
			Me.DeleteButtonColumn.FillWeight = 28.92606F
			Me.DeleteButtonColumn.HeaderText = "Delete"
			Me.DeleteButtonColumn.Name = "DeleteButtonColumn"
			Me.DeleteButtonColumn.Text = "Delete"
			Me.DeleteButtonColumn.UseColumnTextForButtonValue = True
			Me.DeleteButtonColumn.Width = 61
			Me.PrintBarcodeButton.DataPropertyName = "PrintBarcodeButton"
			Me.PrintBarcodeButton.HeaderText = "Print"
			Me.PrintBarcodeButton.Name = "PrintBarcodeButton"
			Me.PrintBarcodeButton.Text = "Barcode"
			Me.PrintBarcodeButton.UseColumnTextForButtonValue = True
			Me.PrintBarcodeButton.Width = 48
			Me.Mark.DataPropertyName = "Mark"
			Me.Mark.HeaderText = "Mark / Unmark"
			Me.Mark.Name = "Mark"
			Me.Mark.Width = 113
			Me.variantName.DataPropertyName = "variantName"
			Me.variantName.HeaderText = "Variant"
			Me.variantName.Name = "variantName"
			Me.variantName.Visible = False
			Me.variantName.Width = 65
			MyBase.AutoScaleDimensions = New Global.System.Drawing.SizeF(6F, 13F)
			MyBase.AutoScaleMode = Global.System.Windows.Forms.AutoScaleMode.Font
			Me.BackColor = Global.System.Drawing.Color.RoyalBlue
			MyBase.ClientSize = New Global.System.Drawing.Size(1248, 195)
			MyBase.ControlBox = False
			MyBase.Controls.Add(Me.DataGridView1)
			MyBase.Controls.Add(Me.GelButtonNewRecord)
			MyBase.Controls.Add(Me.cmbNP)
			MyBase.Controls.Add(Me.txtBarcode)
			MyBase.Controls.Add(Me.txtNP)
			MyBase.Controls.Add(Me.txtProductCode)
			MyBase.Controls.Add(Me.pbgiftqr)
			MyBase.Controls.Add(Me.txtID)
			MyBase.Controls.Add(Me.txtBarcodeTempStock)
			MyBase.Controls.Add(Me.txtBar)
			MyBase.FormBorderStyle = Global.System.Windows.Forms.FormBorderStyle.Fixed3D
			MyBase.Icon = CType(componentResourceManager.GetObject("$this.Icon"), Global.System.Drawing.Icon)
			MyBase.KeyPreview = True
			MyBase.MaximizeBox = False
			MyBase.MinimizeBox = False
			MyBase.Name = "frmProductRec1"
			MyBase.ShowIcon = False
			MyBase.ShowInTaskbar = False
			MyBase.StartPosition = Global.System.Windows.Forms.FormStartPosition.CenterScreen
			CType(Me.DataGridView1, Global.System.ComponentModel.ISupportInitialize).EndInit()
			CType(Me.pbgiftqr, Global.System.ComponentModel.ISupportInitialize).EndInit()
			MyBase.ResumeLayout(False)
			MyBase.PerformLayout()
		End Sub

		' Token: 0x0400390D RID: 14605
		Private components As Global.System.ComponentModel.IContainer
	End Class
End Namespace
