Namespace BillPoint
	' Token: 0x020001ED RID: 493
		Public Partial Class frmProductwiseProfit
		Inherits Global.System.Windows.Forms.Form

		' Token: 0x06008417 RID: 33815 RVA: 0x006215FC File Offset: 0x0061F7FC
		<Global.System.Diagnostics.DebuggerNonUserCode()>
		Protected Overrides Sub Dispose(disposing As Boolean)
			Try
				Dim flag As Boolean = disposing AndAlso Me.components IsNot Nothing
				If flag Then
					Me.components.Dispose()
				End If
			Finally
				MyBase.Dispose(disposing)
			End Try
		End Sub

		' Token: 0x06008418 RID: 33816 RVA: 0x0062164C File Offset: 0x0061F84C
		<Global.System.Diagnostics.DebuggerStepThrough()>
		Private Sub InitializeComponent()
			Dim dataGridViewCellStyle As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle2 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle3 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle4 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle5 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle6 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle7 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle8 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle9 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle10 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle11 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle12 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle13 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle14 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle15 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle16 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle17 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle18 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle19 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle20 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle21 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle22 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle23 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle24 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle25 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle26 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle27 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle28 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle29 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle30 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Me.DataGridView1 = New Global.System.Windows.Forms.DataGridView()
			Me.Column1 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column2 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column3 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column7 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column4 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column5 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn1 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column17 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn2 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column9 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column10 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column11 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column12 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column13 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column14 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn3 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column6 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column18 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column19 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column22 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column25 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column26 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column27 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column28 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column30 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column31 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column32 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column33 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column35 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column36 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column37 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column38 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column39 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column40 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column41 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column42 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column52 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column53 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column55 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column56 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column57 = New Global.System.Windows.Forms.DataGridViewImageColumn()
			Me.Column58 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column59 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Status = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			CType(Me.DataGridView1, Global.System.ComponentModel.ISupportInitialize).BeginInit()
			MyBase.SuspendLayout()
			Me.DataGridView1.AllowUserToAddRows = False
			Me.DataGridView1.AllowUserToDeleteRows = False
			Me.DataGridView1.AllowUserToOrderColumns = True
			Me.DataGridView1.AllowUserToResizeColumns = False
			Me.DataGridView1.AllowUserToResizeRows = False
			dataGridViewCellStyle.BackColor = Global.System.Drawing.Color.White
			Me.DataGridView1.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle
			Me.DataGridView1.AutoSizeColumnsMode = Global.System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill
			Me.DataGridView1.AutoSizeRowsMode = Global.System.Windows.Forms.DataGridViewAutoSizeRowsMode.AllCells
			Me.DataGridView1.BackgroundColor = Global.System.Drawing.Color.FromArgb(229, 233, 219)
			Me.DataGridView1.CellBorderStyle = Global.System.Windows.Forms.DataGridViewCellBorderStyle.Raised
			dataGridViewCellStyle2.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter
			dataGridViewCellStyle2.BackColor = Global.System.Drawing.Color.FromArgb(228, 255, 142)
			dataGridViewCellStyle2.Font = New Global.System.Drawing.Font("Segoe UI Semibold", 12F, Global.System.Drawing.FontStyle.Bold, Global.System.Drawing.GraphicsUnit.Point, 0)
			dataGridViewCellStyle2.ForeColor = Global.System.Drawing.Color.Black
			dataGridViewCellStyle2.SelectionBackColor = Global.System.Drawing.Color.FromArgb(228, 255, 142)
			dataGridViewCellStyle2.SelectionForeColor = Global.System.Drawing.Color.Gray
			dataGridViewCellStyle2.WrapMode = Global.System.Windows.Forms.DataGridViewTriState.[True]
			Me.DataGridView1.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2
			Me.DataGridView1.ColumnHeadersHeight = 40
			Me.DataGridView1.ColumnHeadersHeightSizeMode = Global.System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.DisableResizing
			Me.DataGridView1.Columns.AddRange(New Global.System.Windows.Forms.DataGridViewColumn() { Me.Column1, Me.Column2, Me.Column3, Me.Column7, Me.Column4, Me.Column5, Me.DataGridViewTextBoxColumn1, Me.Column17, Me.DataGridViewTextBoxColumn2, Me.Column9, Me.Column10, Me.Column11, Me.Column12, Me.Column13, Me.Column14, Me.DataGridViewTextBoxColumn3, Me.Column6, Me.Column18, Me.Column19, Me.Column22, Me.Column25, Me.Column26, Me.Column27, Me.Column28, Me.Column30, Me.Column31, Me.Column32, Me.Column33, Me.Column35, Me.Column36, Me.Column37, Me.Column38, Me.Column39, Me.Column40, Me.Column41, Me.Column42, Me.Column52, Me.Column53, Me.Column55, Me.Column56, Me.Column57, Me.Column58, Me.Column59, Me.Status })
			Me.DataGridView1.Cursor = Global.System.Windows.Forms.Cursors.Hand
			dataGridViewCellStyle3.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft
			dataGridViewCellStyle3.BackColor = Global.System.Drawing.SystemColors.Window
			dataGridViewCellStyle3.Font = New Global.System.Drawing.Font("Segoe UI Semibold", 12F, Global.System.Drawing.FontStyle.Bold, Global.System.Drawing.GraphicsUnit.Point, 0)
			dataGridViewCellStyle3.ForeColor = Global.System.Drawing.Color.White
			dataGridViewCellStyle3.SelectionBackColor = Global.System.Drawing.SystemColors.Highlight
			dataGridViewCellStyle3.SelectionForeColor = Global.System.Drawing.SystemColors.HighlightText
			dataGridViewCellStyle3.WrapMode = Global.System.Windows.Forms.DataGridViewTriState.[False]
			Me.DataGridView1.DefaultCellStyle = dataGridViewCellStyle3
			Me.DataGridView1.Dock = Global.System.Windows.Forms.DockStyle.Fill
			Me.DataGridView1.EnableHeadersVisualStyles = False
			Me.DataGridView1.GridColor = Global.System.Drawing.Color.White
			Me.DataGridView1.Location = New Global.System.Drawing.Point(0, 0)
			Me.DataGridView1.MultiSelect = False
			Me.DataGridView1.Name = "DataGridView1"
			Me.DataGridView1.[ReadOnly] = True
			Me.DataGridView1.RowHeadersBorderStyle = Global.System.Windows.Forms.DataGridViewHeaderBorderStyle.[Single]
			dataGridViewCellStyle4.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft
			dataGridViewCellStyle4.BackColor = Global.System.Drawing.Color.RoyalBlue
			dataGridViewCellStyle4.Font = New Global.System.Drawing.Font("Segoe UI Semibold", 12F, Global.System.Drawing.FontStyle.Bold, Global.System.Drawing.GraphicsUnit.Point, 0)
			dataGridViewCellStyle4.ForeColor = Global.System.Drawing.Color.White
			dataGridViewCellStyle4.SelectionBackColor = Global.System.Drawing.Color.RoyalBlue
			dataGridViewCellStyle4.SelectionForeColor = Global.System.Drawing.Color.White
			dataGridViewCellStyle4.WrapMode = Global.System.Windows.Forms.DataGridViewTriState.[True]
			Me.DataGridView1.RowHeadersDefaultCellStyle = dataGridViewCellStyle4
			Me.DataGridView1.RowHeadersVisible = False
			Me.DataGridView1.RowHeadersWidth = 29
			Me.DataGridView1.RowHeadersWidthSizeMode = Global.System.Windows.Forms.DataGridViewRowHeadersWidthSizeMode.DisableResizing
			dataGridViewCellStyle5.BackColor = Global.System.Drawing.Color.White
			dataGridViewCellStyle5.Font = New Global.System.Drawing.Font("Segoe UI Semibold", 12F, Global.System.Drawing.FontStyle.Bold)
			dataGridViewCellStyle5.ForeColor = Global.System.Drawing.Color.Black
			dataGridViewCellStyle5.SelectionBackColor = Global.System.Drawing.Color.Khaki
			dataGridViewCellStyle5.SelectionForeColor = Global.System.Drawing.Color.Black
			Me.DataGridView1.RowsDefaultCellStyle = dataGridViewCellStyle5
			Me.DataGridView1.RowTemplate.Height = 20
			Me.DataGridView1.RowTemplate.[ReadOnly] = True
			Me.DataGridView1.RowTemplate.Resizable = Global.System.Windows.Forms.DataGridViewTriState.[False]
			Me.DataGridView1.SelectionMode = Global.System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect
			Me.DataGridView1.Size = New Global.System.Drawing.Size(1069, 484)
			Me.DataGridView1.TabIndex = 409
			Me.DataGridView1.TabStop = False
			Me.Column1.FillWeight = 20F
			Me.Column1.HeaderText = "PID"
			Me.Column1.Name = "Column1"
			Me.Column1.[ReadOnly] = True
			Me.Column1.Visible = False
			Me.Column2.HeaderText = "HSN Code"
			Me.Column2.Name = "Column2"
			Me.Column2.[ReadOnly] = True
			Me.Column2.Visible = False
			Me.Column3.FillWeight = 262.6422F
			Me.Column3.HeaderText = "Product Name"
			Me.Column3.Name = "Column3"
			Me.Column3.[ReadOnly] = True
			dataGridViewCellStyle6.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft
			Me.Column7.DefaultCellStyle = dataGridViewCellStyle6
			Me.Column7.FillWeight = 200F
			Me.Column7.HeaderText = "Barcode"
			Me.Column7.Name = "Column7"
			Me.Column7.[ReadOnly] = True
			dataGridViewCellStyle7.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.Column4.DefaultCellStyle = dataGridViewCellStyle7
			Me.Column4.FillWeight = 63.78453F
			Me.Column4.HeaderText = "Qty"
			Me.Column4.Name = "Column4"
			Me.Column4.[ReadOnly] = True
			dataGridViewCellStyle8.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.Column5.DefaultCellStyle = dataGridViewCellStyle8
			Me.Column5.FillWeight = 60.0325F
			Me.Column5.HeaderText = "Rate"
			Me.Column5.Name = "Column5"
			Me.Column5.[ReadOnly] = True
			dataGridViewCellStyle9.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter
			Me.DataGridViewTextBoxColumn1.DefaultCellStyle = dataGridViewCellStyle9
			Me.DataGridViewTextBoxColumn1.FillWeight = 52.52844F
			Me.DataGridViewTextBoxColumn1.HeaderText = "Disc %"
			Me.DataGridViewTextBoxColumn1.Name = "DataGridViewTextBoxColumn1"
			Me.DataGridViewTextBoxColumn1.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn1.Visible = False
			dataGridViewCellStyle10.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.Column17.DefaultCellStyle = dataGridViewCellStyle10
			Me.Column17.FillWeight = 60.0325F
			Me.Column17.HeaderText = "Disc Amt"
			Me.Column17.Name = "Column17"
			Me.Column17.[ReadOnly] = True
			Me.Column17.Visible = False
			dataGridViewCellStyle11.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn2.DefaultCellStyle = dataGridViewCellStyle11
			Me.DataGridViewTextBoxColumn2.FillWeight = 55F
			Me.DataGridViewTextBoxColumn2.HeaderText = "CGST %"
			Me.DataGridViewTextBoxColumn2.Name = "DataGridViewTextBoxColumn2"
			Me.DataGridViewTextBoxColumn2.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn2.Visible = False
			dataGridViewCellStyle12.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.Column9.DefaultCellStyle = dataGridViewCellStyle12
			Me.Column9.FillWeight = 70F
			Me.Column9.HeaderText = "CGST Amt"
			Me.Column9.Name = "Column9"
			Me.Column9.[ReadOnly] = True
			Me.Column9.Visible = False
			dataGridViewCellStyle13.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.Column10.DefaultCellStyle = dataGridViewCellStyle13
			Me.Column10.FillWeight = 55F
			Me.Column10.HeaderText = "SGST %"
			Me.Column10.Name = "Column10"
			Me.Column10.[ReadOnly] = True
			Me.Column10.Visible = False
			dataGridViewCellStyle14.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.Column11.DefaultCellStyle = dataGridViewCellStyle14
			Me.Column11.FillWeight = 70F
			Me.Column11.HeaderText = "SGST Amt"
			Me.Column11.Name = "Column11"
			Me.Column11.[ReadOnly] = True
			Me.Column11.Visible = False
			dataGridViewCellStyle15.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.Column12.DefaultCellStyle = dataGridViewCellStyle15
			Me.Column12.FillWeight = 50F
			Me.Column12.HeaderText = "IGST %"
			Me.Column12.Name = "Column12"
			Me.Column12.[ReadOnly] = True
			Me.Column12.Visible = False
			dataGridViewCellStyle16.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.Column13.DefaultCellStyle = dataGridViewCellStyle16
			Me.Column13.FillWeight = 70F
			Me.Column13.HeaderText = "IGST Amt"
			Me.Column13.Name = "Column13"
			Me.Column13.[ReadOnly] = True
			Me.Column13.Visible = False
			dataGridViewCellStyle17.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.Column14.DefaultCellStyle = dataGridViewCellStyle17
			Me.Column14.FillWeight = 50F
			Me.Column14.HeaderText = "CESS %"
			Me.Column14.Name = "Column14"
			Me.Column14.[ReadOnly] = True
			Me.Column14.Visible = False
			dataGridViewCellStyle18.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn3.DefaultCellStyle = dataGridViewCellStyle18
			Me.DataGridViewTextBoxColumn3.FillWeight = 70F
			Me.DataGridViewTextBoxColumn3.HeaderText = "CESS Amt"
			Me.DataGridViewTextBoxColumn3.Name = "DataGridViewTextBoxColumn3"
			Me.DataGridViewTextBoxColumn3.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn3.Visible = False
			dataGridViewCellStyle19.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.Column6.DefaultCellStyle = dataGridViewCellStyle19
			Me.Column6.FillWeight = 75.04063F
			Me.Column6.HeaderText = "Total"
			Me.Column6.Name = "Column6"
			Me.Column6.[ReadOnly] = True
			dataGridViewCellStyle20.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.Column18.DefaultCellStyle = dataGridViewCellStyle20
			Me.Column18.FillWeight = 20F
			Me.Column18.HeaderText = "Purchase Rate"
			Me.Column18.Name = "Column18"
			Me.Column18.[ReadOnly] = True
			Me.Column18.Visible = False
			dataGridViewCellStyle21.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.Column19.DefaultCellStyle = dataGridViewCellStyle21
			Me.Column19.HeaderText = "Margin"
			Me.Column19.Name = "Column19"
			Me.Column19.[ReadOnly] = True
			dataGridViewCellStyle22.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft
			Me.Column22.DefaultCellStyle = dataGridViewCellStyle22
			Me.Column22.HeaderText = "Description"
			Me.Column22.Name = "Column22"
			Me.Column22.[ReadOnly] = True
			Me.Column22.Visible = False
			Me.Column25.HeaderText = "Temp Qty"
			Me.Column25.Name = "Column25"
			Me.Column25.[ReadOnly] = True
			Me.Column25.Visible = False
			Me.Column26.HeaderText = "IMEI-1"
			Me.Column26.Name = "Column26"
			Me.Column26.[ReadOnly] = True
			Me.Column26.Visible = False
			Me.Column27.HeaderText = "IMEI-2"
			Me.Column27.Name = "Column27"
			Me.Column27.[ReadOnly] = True
			Me.Column27.Visible = False
			dataGridViewCellStyle23.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			dataGridViewCellStyle23.Format = "N2"
			Me.Column28.DefaultCellStyle = dataGridViewCellStyle23
			Me.Column28.HeaderText = "MRP"
			Me.Column28.Name = "Column28"
			Me.Column28.[ReadOnly] = True
			Me.Column28.Visible = False
			dataGridViewCellStyle24.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			dataGridViewCellStyle24.Format = "N2"
			dataGridViewCellStyle24.NullValue = Nothing
			Me.Column30.DefaultCellStyle = dataGridViewCellStyle24
			Me.Column30.HeaderText = "Taxable Amt"
			Me.Column30.Name = "Column30"
			Me.Column30.[ReadOnly] = True
			Me.Column30.Visible = False
			dataGridViewCellStyle25.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.Column31.DefaultCellStyle = dataGridViewCellStyle25
			Me.Column31.HeaderText = "Alt Qty"
			Me.Column31.Name = "Column31"
			Me.Column31.[ReadOnly] = True
			Me.Column31.Visible = False
			dataGridViewCellStyle26.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter
			Me.Column32.DefaultCellStyle = dataGridViewCellStyle26
			Me.Column32.HeaderText = "Alt Unit"
			Me.Column32.Name = "Column32"
			Me.Column32.[ReadOnly] = True
			Me.Column32.Visible = False
			dataGridViewCellStyle27.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter
			Me.Column33.DefaultCellStyle = dataGridViewCellStyle27
			Me.Column33.HeaderText = "Tax Type"
			Me.Column33.Name = "Column33"
			Me.Column33.[ReadOnly] = True
			Me.Column33.Visible = False
			dataGridViewCellStyle28.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			dataGridViewCellStyle28.Format = "N2"
			Me.Column35.DefaultCellStyle = dataGridViewCellStyle28
			Me.Column35.HeaderText = "Total MRP"
			Me.Column35.Name = "Column35"
			Me.Column35.[ReadOnly] = True
			Me.Column35.Visible = False
			dataGridViewCellStyle29.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter
			Me.Column36.DefaultCellStyle = dataGridViewCellStyle29
			Me.Column36.HeaderText = "Free Offer Qty"
			Me.Column36.Name = "Column36"
			Me.Column36.[ReadOnly] = True
			Me.Column36.Visible = False
			dataGridViewCellStyle30.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter
			Me.Column37.DefaultCellStyle = dataGridViewCellStyle30
			Me.Column37.HeaderText = "Main Unit"
			Me.Column37.Name = "Column37"
			Me.Column37.[ReadOnly] = True
			Me.Column37.Visible = False
			Me.Column38.HeaderText = "Batch/Serial"
			Me.Column38.Name = "Column38"
			Me.Column38.[ReadOnly] = True
			Me.Column38.Visible = False
			Me.Column39.HeaderText = "Mfg Date"
			Me.Column39.Name = "Column39"
			Me.Column39.[ReadOnly] = True
			Me.Column39.Visible = False
			Me.Column40.HeaderText = "Exp Date"
			Me.Column40.Name = "Column40"
			Me.Column40.[ReadOnly] = True
			Me.Column40.Visible = False
			Me.Column41.HeaderText = "Size"
			Me.Column41.Name = "Column41"
			Me.Column41.[ReadOnly] = True
			Me.Column41.Visible = False
			Me.Column42.HeaderText = "Colour"
			Me.Column42.Name = "Column42"
			Me.Column42.[ReadOnly] = True
			Me.Column42.Visible = False
			Me.Column52.FillWeight = 75.04063F
			Me.Column52.HeaderText = "SalesManID"
			Me.Column52.Name = "Column52"
			Me.Column52.[ReadOnly] = True
			Me.Column52.Visible = False
			Me.Column53.FillWeight = 75.04063F
			Me.Column53.HeaderText = "SalesMan"
			Me.Column53.Name = "Column53"
			Me.Column53.[ReadOnly] = True
			Me.Column53.Visible = False
			Me.Column55.FillWeight = 75.04063F
			Me.Column55.HeaderText = "%"
			Me.Column55.Name = "Column55"
			Me.Column55.[ReadOnly] = True
			Me.Column55.Visible = False
			Me.Column56.FillWeight = 75.04063F
			Me.Column56.HeaderText = "Commision"
			Me.Column56.Name = "Column56"
			Me.Column56.[ReadOnly] = True
			Me.Column56.Visible = False
			Me.Column57.FillWeight = 75.04063F
			Me.Column57.HeaderText = "PImage"
			Me.Column57.ImageLayout = Global.System.Windows.Forms.DataGridViewImageCellLayout.Zoom
			Me.Column57.Name = "Column57"
			Me.Column57.[ReadOnly] = True
			Me.Column57.Resizable = Global.System.Windows.Forms.DataGridViewTriState.[False]
			Me.Column57.Visible = False
			Me.Column58.HeaderText = "StockId"
			Me.Column58.Name = "Column58"
			Me.Column58.[ReadOnly] = True
			Me.Column58.Visible = False
			Me.Column59.HeaderText = "Points"
			Me.Column59.Name = "Column59"
			Me.Column59.[ReadOnly] = True
			Me.Column59.Visible = False
			Me.Status.HeaderText = "Profit/Loss"
			Me.Status.Name = "Status"
			Me.Status.[ReadOnly] = True
			MyBase.AutoScaleDimensions = New Global.System.Drawing.SizeF(6F, 13F)
			MyBase.AutoScaleMode = Global.System.Windows.Forms.AutoScaleMode.Font
			MyBase.ClientSize = New Global.System.Drawing.Size(1069, 484)
			MyBase.Controls.Add(Me.DataGridView1)
			MyBase.MaximizeBox = False
			MyBase.MinimizeBox = False
			MyBase.Name = "frmProductwiseProfit"
			MyBase.StartPosition = Global.System.Windows.Forms.FormStartPosition.CenterScreen
			Me.Text = "Productwise Profit Report"
			CType(Me.DataGridView1, Global.System.ComponentModel.ISupportInitialize).EndInit()
			MyBase.ResumeLayout(False)
		End Sub

		' Token: 0x04003A69 RID: 14953
		Private components As Global.System.ComponentModel.IContainer
	End Class
End Namespace
