Namespace BillPoint
	' Token: 0x02000081 RID: 129
		Public Partial Class frmProductSmart
		Inherits Global.System.Windows.Forms.Form

		' Token: 0x06001549 RID: 5449 RVA: 0x000E62A0 File Offset: 0x000E44A0
		<Global.System.Diagnostics.DebuggerNonUserCode()>
		Protected Overrides Sub Dispose(disposing As Boolean)
			Try
				Dim flag As Boolean = disposing AndAlso Me.components IsNot Nothing
				If flag Then
					Me.components.Dispose()
				End If
			Finally
				MyBase.Dispose(disposing)
			End Try
		End Sub

		' Token: 0x0600154A RID: 5450 RVA: 0x000E62F0 File Offset: 0x000E44F0
		<Global.System.Diagnostics.DebuggerStepThrough()>
		Private Sub InitializeComponent()
			Me.components = New Global.System.ComponentModel.Container()
			Dim dataGridViewCellStyle As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle2 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle3 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle4 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle5 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle6 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle7 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle8 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle9 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle10 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle11 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle12 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle13 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle14 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle15 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle16 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim componentResourceManager As Global.System.ComponentModel.ComponentResourceManager = New Global.System.ComponentModel.ComponentResourceManager(GetType(Global.BillPoint.frmProductSmart))
			Dim dataGridViewCellStyle17 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle18 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle19 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle20 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle21 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle22 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle23 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle24 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle25 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle26 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle27 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Me.Panel1 = New Global.System.Windows.Forms.Panel()
			Me.btnWebcam = New Global.System.Windows.Forms.Button()
			Me.pnlVariant = New Global.System.Windows.Forms.Panel()
			Me.DataGridView2 = New Global.System.Windows.Forms.DataGridView()
			Me.PID2 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn2 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn3 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.CategoryName = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewButtonColumn1 = New Global.System.Windows.Forms.DataGridViewButtonColumn()
			Me.SubCategoryName = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewButtonColumn2 = New Global.System.Windows.Forms.DataGridViewButtonColumn()
			Me.DataGridViewTextBoxColumn4 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn5 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn6 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn7 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.CostPrice = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn9 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn10 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.cmbGST1 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewButtonColumn3 = New Global.System.Windows.Forms.DataGridViewButtonColumn()
			Me.DataGridViewTextBoxColumn11 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn12 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn13 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn14 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn15 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn16 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn17 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.cmbPurchaseUnit2 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.cmbSalesUnit2 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.cmbAltunit2 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn18 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn19 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn20 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn21 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.cmbSalesTaxType2 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.cmbPurchaseTaxType2 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.ddlGdown2 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.ddlRack2 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn22 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.txtOpeningStock2 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn24 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.txtMRP = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.txtRSP1 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn27 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn28 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn29 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn30 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.cmbSize2 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.cmbColour2 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn31 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn32 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn33 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewImageColumn1 = New Global.System.Windows.Forms.DataGridViewImageColumn()
			Me.btnAddNew = New Global.System.Windows.Forms.DataGridViewButtonColumn()
			Me.GelButton1 = New Global.System.Windows.Forms.Button()
			Me.GelButton2 = New Global.System.Windows.Forms.Button()
			Me.Label14 = New Global.System.Windows.Forms.Label()
			Me.Label13 = New Global.System.Windows.Forms.Label()
			Me.Panel7 = New Global.System.Windows.Forms.Panel()
			Me.txtbarcodeNocopy = New Global.System.Windows.Forms.TextBox()
			Me.Label20 = New Global.System.Windows.Forms.Label()
			Me.Label19 = New Global.System.Windows.Forms.Label()
			Me.CheckBox1 = New Global.System.Windows.Forms.CheckBox()
			Me.Label18 = New Global.System.Windows.Forms.Label()
			Me.Label21 = New Global.System.Windows.Forms.Label()
			Me.txtTopResult = New Global.System.Windows.Forms.TextBox()
			Me.Panel2 = New Global.System.Windows.Forms.Panel()
			Me.Label12 = New Global.System.Windows.Forms.Label()
			Me.Panel3 = New Global.System.Windows.Forms.Panel()
			Me.ComboBox2 = New Global.System.Windows.Forms.ComboBox()
			Me.txtID_Update = New Global.System.Windows.Forms.TextBox()
			Me.Label9 = New Global.System.Windows.Forms.Label()
			Me.cmbRack = New Global.System.Windows.Forms.ComboBox()
			Me.Label8 = New Global.System.Windows.Forms.Label()
			Me.cmbGDown = New Global.System.Windows.Forms.ComboBox()
			Me.Label7 = New Global.System.Windows.Forms.Label()
			Me.TextBox1 = New Global.System.Windows.Forms.TextBox()
			Me.ComboBox1 = New Global.System.Windows.Forms.ComboBox()
			Me.Label6 = New Global.System.Windows.Forms.Label()
			Me.txtBarcode = New Global.System.Windows.Forms.TextBox()
			Me.Label5 = New Global.System.Windows.Forms.Label()
			Me.Label4 = New Global.System.Windows.Forms.Label()
			Me.txtCategory = New Global.System.Windows.Forms.TextBox()
			Me.Label2 = New Global.System.Windows.Forms.Label()
			Me.txtProductName = New Global.System.Windows.Forms.TextBox()
			Me.Label3 = New Global.System.Windows.Forms.Label()
			Me.lblUser = New Global.System.Windows.Forms.Label()
			Me.lblSet = New Global.System.Windows.Forms.Label()
			Me.Label16 = New Global.System.Windows.Forms.Label()
			Me.txtSearchProduct = New Global.System.Windows.Forms.TextBox()
			Me.btnBulkImageUpdate = New Global.System.Windows.Forms.Button()
			Me.Label15 = New Global.System.Windows.Forms.Label()
			Me.cmbSearchCat = New Global.System.Windows.Forms.ComboBox()
			Me.btnShowAll = New Global.System.Windows.Forms.Button()
			Me.txtCompany = New Global.System.Windows.Forms.TextBox()
			Me.Picture = New Global.System.Windows.Forms.PictureBox()
			Me.txtNP = New Global.System.Windows.Forms.TextBox()
			Me.cmbNP = New Global.System.Windows.Forms.ComboBox()
			Me.pbgiftqr = New Global.System.Windows.Forms.PictureBox()
			Me.txtBar = New Global.System.Windows.Forms.TextBox()
			Me.txtBarcodeTempStock = New Global.System.Windows.Forms.TextBox()
			Me.txtProductCode = New Global.System.Windows.Forms.TextBox()
			Me.txtID = New Global.System.Windows.Forms.TextBox()
			Me.Panel5 = New Global.System.Windows.Forms.Panel()
			Me.GelButton3 = New Global.System.Windows.Forms.Button()
			Me.btnReset = New Global.System.Windows.Forms.Button()
			Me.GelButtonNewRecord = New Global.System.Windows.Forms.Button()
			Me.GelButton5 = New Global.System.Windows.Forms.Button()
			Me.btnExportExcel = New Global.System.Windows.Forms.Button()
			Me.GelButton6 = New Global.System.Windows.Forms.Button()
			Me.Button16 = New Global.System.Windows.Forms.Button()
			Me.btnProductSeting = New Global.System.Windows.Forms.Button()
			Me.DataGridView1 = New Global.System.Windows.Forms.DataGridView()
			Me.DataGridViewTextBoxColumn1 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn26 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn64 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn45 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn48 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.PCode = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.ProductName = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.CatSubCategory = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.HSNCode = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Part_Group = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Description = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.PurchasePrice = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Discount = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.GST = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.CGST = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.SGST_UTGST = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.CESS = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.PurchaseMainUnit = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.SalsesUnit = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.AlterUnit = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Conv = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.MinStock = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Active = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.SaleTaxType = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.PurchaseTaxType = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.GDown = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Rack = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DefQty = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.OpeningStock = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Barcode = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.MRP = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.RSPrice = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.WSPrice = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Batch = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.MfgDate = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.ExpDate = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Size = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Colour = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.IME1 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.IME2 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Kitchen = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Photo = New Global.System.Windows.Forms.DataGridViewImageColumn()
			Me.Mark_Unmark = New Global.System.Windows.Forms.DataGridViewCheckBoxColumn()
			Me.DataGridViewButtonColumn6 = New Global.System.Windows.Forms.DataGridViewButtonColumn()
			Me.DataGridViewButtonColumn7 = New Global.System.Windows.Forms.DataGridViewButtonColumn()
			Me.DataGridViewButtonColumn8 = New Global.System.Windows.Forms.DataGridViewButtonColumn()
			Me.variantName = New Global.System.Windows.Forms.DataGridViewButtonColumn()
			Me.SaveFileDialog1 = New Global.System.Windows.Forms.SaveFileDialog()
			Me.Timer1 = New Global.System.Windows.Forms.Timer(Me.components)
			Me.Panel4 = New Global.System.Windows.Forms.Panel()
			Me.PictureBox1 = New Global.System.Windows.Forms.PictureBox()
			Me.Label17 = New Global.System.Windows.Forms.Label()
			Me.DataGridViewImageColumn2 = New Global.System.Windows.Forms.DataGridViewImageColumn()
			Me.Panel1.SuspendLayout()
			Me.pnlVariant.SuspendLayout()
			CType(Me.DataGridView2, Global.System.ComponentModel.ISupportInitialize).BeginInit()
			Me.Panel7.SuspendLayout()
			Me.Panel2.SuspendLayout()
			Me.Panel3.SuspendLayout()
			CType(Me.Picture, Global.System.ComponentModel.ISupportInitialize).BeginInit()
			CType(Me.pbgiftqr, Global.System.ComponentModel.ISupportInitialize).BeginInit()
			Me.Panel5.SuspendLayout()
			CType(Me.DataGridView1, Global.System.ComponentModel.ISupportInitialize).BeginInit()
			Me.Panel4.SuspendLayout()
			CType(Me.PictureBox1, Global.System.ComponentModel.ISupportInitialize).BeginInit()
			MyBase.SuspendLayout()
			Me.Panel1.Anchor = Global.System.Windows.Forms.AnchorStyles.Top Or Global.System.Windows.Forms.AnchorStyles.Bottom Or Global.System.Windows.Forms.AnchorStyles.Left Or Global.System.Windows.Forms.AnchorStyles.Right
			Me.Panel1.BackColor = Global.System.Drawing.Color.White
			Me.Panel1.BorderStyle = Global.System.Windows.Forms.BorderStyle.FixedSingle
			Me.Panel1.Controls.Add(Me.btnWebcam)
			Me.Panel1.Controls.Add(Me.pnlVariant)
			Me.Panel1.Controls.Add(Me.Panel7)
			Me.Panel1.Controls.Add(Me.Panel2)
			Me.Panel1.Controls.Add(Me.Label16)
			Me.Panel1.Controls.Add(Me.txtSearchProduct)
			Me.Panel1.Controls.Add(Me.btnBulkImageUpdate)
			Me.Panel1.Controls.Add(Me.Label15)
			Me.Panel1.Controls.Add(Me.cmbSearchCat)
			Me.Panel1.Controls.Add(Me.btnShowAll)
			Me.Panel1.Controls.Add(Me.txtCompany)
			Me.Panel1.Controls.Add(Me.Picture)
			Me.Panel1.Controls.Add(Me.txtNP)
			Me.Panel1.Controls.Add(Me.cmbNP)
			Me.Panel1.Controls.Add(Me.pbgiftqr)
			Me.Panel1.Controls.Add(Me.txtBar)
			Me.Panel1.Controls.Add(Me.txtBarcodeTempStock)
			Me.Panel1.Controls.Add(Me.txtProductCode)
			Me.Panel1.Controls.Add(Me.txtID)
			Me.Panel1.Controls.Add(Me.Panel5)
			Me.Panel1.Controls.Add(Me.DataGridView1)
			Me.Panel1.Location = New Global.System.Drawing.Point(4, 12)
			Me.Panel1.Name = "Panel1"
			Me.Panel1.Size = New Global.System.Drawing.Size(1420, 749)
			Me.Panel1.TabIndex = 2
			Me.btnWebcam.Anchor = Global.System.Windows.Forms.AnchorStyles.Top Or Global.System.Windows.Forms.AnchorStyles.Right
			Me.btnWebcam.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 9F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			Me.btnWebcam.Location = New Global.System.Drawing.Point(593, 111)
			Me.btnWebcam.Name = "btnWebcam"
			Me.btnWebcam.Size = New Global.System.Drawing.Size(97, 39)
			Me.btnWebcam.TabIndex = 1841
			Me.btnWebcam.Text = "WebCam " & vbCrLf & "(Ctrl +W)"
			Me.btnWebcam.UseVisualStyleBackColor = True
			Me.btnWebcam.Visible = False
			Me.pnlVariant.Anchor = Global.System.Windows.Forms.AnchorStyles.Bottom Or Global.System.Windows.Forms.AnchorStyles.Left
			Me.pnlVariant.BackColor = Global.System.Drawing.Color.FromArgb(229, 233, 219)
			Me.pnlVariant.Controls.Add(Me.DataGridView2)
			Me.pnlVariant.Controls.Add(Me.GelButton1)
			Me.pnlVariant.Controls.Add(Me.GelButton2)
			Me.pnlVariant.Controls.Add(Me.Label14)
			Me.pnlVariant.Controls.Add(Me.Label13)
			Me.pnlVariant.Location = New Global.System.Drawing.Point(26, 285)
			Me.pnlVariant.Name = "pnlVariant"
			Me.pnlVariant.Size = New Global.System.Drawing.Size(1098, 324)
			Me.pnlVariant.TabIndex = 1807
			Me.pnlVariant.Visible = False
			dataGridViewCellStyle.BackColor = Global.System.Drawing.Color.FloralWhite
			Me.DataGridView2.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle
			Me.DataGridView2.Anchor = Global.System.Windows.Forms.AnchorStyles.Top Or Global.System.Windows.Forms.AnchorStyles.Bottom Or Global.System.Windows.Forms.AnchorStyles.Left Or Global.System.Windows.Forms.AnchorStyles.Right
			Me.DataGridView2.AutoSizeColumnsMode = Global.System.Windows.Forms.DataGridViewAutoSizeColumnsMode.DisplayedCells
			Me.DataGridView2.BackgroundColor = Global.System.Drawing.Color.FromArgb(229, 233, 219)
			Me.DataGridView2.ColumnHeadersBorderStyle = Global.System.Windows.Forms.DataGridViewHeaderBorderStyle.[Single]
			dataGridViewCellStyle2.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter
			dataGridViewCellStyle2.BackColor = Global.System.Drawing.Color.FromArgb(228, 255, 142)
			dataGridViewCellStyle2.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 12F, Global.System.Drawing.FontStyle.Bold, Global.System.Drawing.GraphicsUnit.Point, 0)
			dataGridViewCellStyle2.ForeColor = Global.System.Drawing.Color.Black
			dataGridViewCellStyle2.SelectionBackColor = Global.System.Drawing.Color.FromArgb(228, 255, 142)
			dataGridViewCellStyle2.SelectionForeColor = Global.System.Drawing.SystemColors.ControlDarkDark
			dataGridViewCellStyle2.WrapMode = Global.System.Windows.Forms.DataGridViewTriState.[True]
			Me.DataGridView2.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2
			Me.DataGridView2.ColumnHeadersHeight = 40
			Me.DataGridView2.Columns.AddRange(New Global.System.Windows.Forms.DataGridViewColumn() { Me.PID2, Me.DataGridViewTextBoxColumn2, Me.DataGridViewTextBoxColumn3, Me.CategoryName, Me.DataGridViewButtonColumn1, Me.SubCategoryName, Me.DataGridViewButtonColumn2, Me.DataGridViewTextBoxColumn4, Me.DataGridViewTextBoxColumn5, Me.DataGridViewTextBoxColumn6, Me.DataGridViewTextBoxColumn7, Me.CostPrice, Me.DataGridViewTextBoxColumn9, Me.DataGridViewTextBoxColumn10, Me.cmbGST1, Me.DataGridViewButtonColumn3, Me.DataGridViewTextBoxColumn11, Me.DataGridViewTextBoxColumn12, Me.DataGridViewTextBoxColumn13, Me.DataGridViewTextBoxColumn14, Me.DataGridViewTextBoxColumn15, Me.DataGridViewTextBoxColumn16, Me.DataGridViewTextBoxColumn17, Me.cmbPurchaseUnit2, Me.cmbSalesUnit2, Me.cmbAltunit2, Me.DataGridViewTextBoxColumn18, Me.DataGridViewTextBoxColumn19, Me.DataGridViewTextBoxColumn20, Me.DataGridViewTextBoxColumn21, Me.cmbSalesTaxType2, Me.cmbPurchaseTaxType2, Me.ddlGdown2, Me.ddlRack2, Me.DataGridViewTextBoxColumn22, Me.txtOpeningStock2, Me.DataGridViewTextBoxColumn24, Me.txtMRP, Me.txtRSP1, Me.DataGridViewTextBoxColumn27, Me.DataGridViewTextBoxColumn28, Me.DataGridViewTextBoxColumn29, Me.DataGridViewTextBoxColumn30, Me.cmbSize2, Me.cmbColour2, Me.DataGridViewTextBoxColumn31, Me.DataGridViewTextBoxColumn32, Me.DataGridViewTextBoxColumn33, Me.DataGridViewImageColumn1, Me.btnAddNew })
			Me.DataGridView2.Cursor = Global.System.Windows.Forms.Cursors.Hand
			dataGridViewCellStyle3.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft
			dataGridViewCellStyle3.BackColor = Global.System.Drawing.SystemColors.Window
			dataGridViewCellStyle3.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 11.25F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			dataGridViewCellStyle3.ForeColor = Global.System.Drawing.SystemColors.ControlText
			dataGridViewCellStyle3.SelectionBackColor = Global.System.Drawing.SystemColors.Highlight
			dataGridViewCellStyle3.SelectionForeColor = Global.System.Drawing.Color.Black
			dataGridViewCellStyle3.WrapMode = Global.System.Windows.Forms.DataGridViewTriState.[False]
			Me.DataGridView2.DefaultCellStyle = dataGridViewCellStyle3
			Me.DataGridView2.EnableHeadersVisualStyles = False
			Me.DataGridView2.GridColor = Global.System.Drawing.Color.FromArgb(229, 233, 219)
			Me.DataGridView2.Location = New Global.System.Drawing.Point(4, 4)
			Me.DataGridView2.MultiSelect = False
			Me.DataGridView2.Name = "DataGridView2"
			Me.DataGridView2.RowHeadersBorderStyle = Global.System.Windows.Forms.DataGridViewHeaderBorderStyle.[Single]
			dataGridViewCellStyle4.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft
			dataGridViewCellStyle4.BackColor = Global.System.Drawing.Color.DarkViolet
			dataGridViewCellStyle4.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 11.25F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			dataGridViewCellStyle4.ForeColor = Global.System.Drawing.Color.White
			dataGridViewCellStyle4.SelectionBackColor = Global.System.Drawing.Color.OrangeRed
			dataGridViewCellStyle4.SelectionForeColor = Global.System.Drawing.Color.White
			dataGridViewCellStyle4.WrapMode = Global.System.Windows.Forms.DataGridViewTriState.[True]
			Me.DataGridView2.RowHeadersDefaultCellStyle = dataGridViewCellStyle4
			Me.DataGridView2.RowHeadersWidth = 25
			Me.DataGridView2.RowHeadersWidthSizeMode = Global.System.Windows.Forms.DataGridViewRowHeadersWidthSizeMode.DisableResizing
			dataGridViewCellStyle5.BackColor = Global.System.Drawing.Color.White
			dataGridViewCellStyle5.Font = New Global.System.Drawing.Font("Tahoma", 11.25F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			dataGridViewCellStyle5.SelectionBackColor = Global.System.Drawing.Color.DarkSlateGray
			dataGridViewCellStyle5.SelectionForeColor = Global.System.Drawing.Color.White
			Me.DataGridView2.RowsDefaultCellStyle = dataGridViewCellStyle5
			Me.DataGridView2.RowTemplate.Height = 20
			Me.DataGridView2.RowTemplate.Resizable = Global.System.Windows.Forms.DataGridViewTriState.[False]
			Me.DataGridView2.SelectionMode = Global.System.Windows.Forms.DataGridViewSelectionMode.CellSelect
			Me.DataGridView2.Size = New Global.System.Drawing.Size(1078, 263)
			Me.DataGridView2.TabIndex = 437
			Me.DataGridView2.TabStop = False
			Me.DataGridView2.Visible = False
			Me.PID2.DataPropertyName = "PID"
			Me.PID2.HeaderText = "PID"
			Me.PID2.Name = "PID2"
			Me.PID2.Visible = False
			Me.PID2.Width = 64
			Me.DataGridViewTextBoxColumn2.DataPropertyName = "ProductCode"
			Me.DataGridViewTextBoxColumn2.FillWeight = 284.084F
			Me.DataGridViewTextBoxColumn2.HeaderText = "P - Code"
			Me.DataGridViewTextBoxColumn2.Name = "DataGridViewTextBoxColumn2"
			Me.DataGridViewTextBoxColumn2.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn2.Width = 102
			Me.DataGridViewTextBoxColumn3.DataPropertyName = "Productname"
			Me.DataGridViewTextBoxColumn3.FillWeight = 275.771F
			Me.DataGridViewTextBoxColumn3.HeaderText = "Product Name"
			Me.DataGridViewTextBoxColumn3.Name = "DataGridViewTextBoxColumn3"
			Me.DataGridViewTextBoxColumn3.Resizable = Global.System.Windows.Forms.DataGridViewTriState.[True]
			Me.DataGridViewTextBoxColumn3.Width = 146
			Me.CategoryName.DataPropertyName = "CategoryName"
			dataGridViewCellStyle6.BackColor = Global.System.Drawing.Color.Red
			dataGridViewCellStyle6.ForeColor = Global.System.Drawing.Color.White
			dataGridViewCellStyle6.Padding = New Global.System.Windows.Forms.Padding(2)
			Me.CategoryName.DefaultCellStyle = dataGridViewCellStyle6
			Me.CategoryName.FillWeight = 153.3014F
			Me.CategoryName.HeaderText = "Category"
			Me.CategoryName.Name = "CategoryName"
			Me.CategoryName.SortMode = Global.System.Windows.Forms.DataGridViewColumnSortMode.NotSortable
			Me.CategoryName.Visible = False
			Me.CategoryName.Width = 87
			Me.DataGridViewButtonColumn1.DataPropertyName = "Category_plus"
			dataGridViewCellStyle7.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter
			dataGridViewCellStyle7.ForeColor = Global.System.Drawing.Color.Purple
			Me.DataGridViewButtonColumn1.DefaultCellStyle = dataGridViewCellStyle7
			Me.DataGridViewButtonColumn1.FillWeight = 65.74377F
			Me.DataGridViewButtonColumn1.HeaderText = "+"
			Me.DataGridViewButtonColumn1.Name = "DataGridViewButtonColumn1"
			Me.DataGridViewButtonColumn1.Text = "+"
			Me.DataGridViewButtonColumn1.UseColumnTextForButtonValue = True
			Me.DataGridViewButtonColumn1.Visible = False
			Me.DataGridViewButtonColumn1.Width = 25
			Me.SubCategoryName.DataPropertyName = "SubCategoryName"
			dataGridViewCellStyle8.Padding = New Global.System.Windows.Forms.Padding(2)
			Me.SubCategoryName.DefaultCellStyle = dataGridViewCellStyle8
			Me.SubCategoryName.FillWeight = 211.0264F
			Me.SubCategoryName.HeaderText = "Sub Category / Brand"
			Me.SubCategoryName.Name = "SubCategoryName"
			Me.SubCategoryName.Resizable = Global.System.Windows.Forms.DataGridViewTriState.[True]
			Me.SubCategoryName.SortMode = Global.System.Windows.Forms.DataGridViewColumnSortMode.NotSortable
			Me.SubCategoryName.Visible = False
			Me.SubCategoryName.Width = 187
			Me.DataGridViewButtonColumn2.DataPropertyName = "Subcategory_plus"
			dataGridViewCellStyle9.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter
			dataGridViewCellStyle9.ForeColor = Global.System.Drawing.Color.Purple
			Me.DataGridViewButtonColumn2.DefaultCellStyle = dataGridViewCellStyle9
			Me.DataGridViewButtonColumn2.FillWeight = 61.50089F
			Me.DataGridViewButtonColumn2.HeaderText = "+"
			Me.DataGridViewButtonColumn2.Name = "DataGridViewButtonColumn2"
			Me.DataGridViewButtonColumn2.Text = "+"
			Me.DataGridViewButtonColumn2.Visible = False
			Me.DataGridViewButtonColumn2.Width = 25
			Me.DataGridViewTextBoxColumn4.HeaderText = "SubCategoryID"
			Me.DataGridViewTextBoxColumn4.Name = "DataGridViewTextBoxColumn4"
			Me.DataGridViewTextBoxColumn4.Visible = False
			Me.DataGridViewTextBoxColumn4.Width = 157
			Me.DataGridViewTextBoxColumn5.DataPropertyName = "HSNCode"
			Me.DataGridViewTextBoxColumn5.FillWeight = 192.4218F
			Me.DataGridViewTextBoxColumn5.HeaderText = "HSN Code"
			Me.DataGridViewTextBoxColumn5.Name = "DataGridViewTextBoxColumn5"
			Me.DataGridViewTextBoxColumn5.Visible = False
			Me.DataGridViewTextBoxColumn5.Width = 118
			Me.DataGridViewTextBoxColumn6.DataPropertyName = "PartNo"
			Me.DataGridViewTextBoxColumn6.FillWeight = 199.441F
			Me.DataGridViewTextBoxColumn6.HeaderText = "Part / Group"
			Me.DataGridViewTextBoxColumn6.Name = "DataGridViewTextBoxColumn6"
			Me.DataGridViewTextBoxColumn6.Visible = False
			Me.DataGridViewTextBoxColumn6.Width = 132
			Me.DataGridViewTextBoxColumn7.DataPropertyName = "Description"
			dataGridViewCellStyle10.WrapMode = Global.System.Windows.Forms.DataGridViewTriState.[False]
			Me.DataGridViewTextBoxColumn7.DefaultCellStyle = dataGridViewCellStyle10
			Me.DataGridViewTextBoxColumn7.FillWeight = 190.5685F
			Me.DataGridViewTextBoxColumn7.HeaderText = "Description"
			Me.DataGridViewTextBoxColumn7.Name = "DataGridViewTextBoxColumn7"
			Me.DataGridViewTextBoxColumn7.Visible = False
			Me.DataGridViewTextBoxColumn7.Width = 125
			Me.CostPrice.DataPropertyName = "CostPrice"
			Me.CostPrice.FillWeight = 203.4047F
			Me.CostPrice.HeaderText = "Purchase Price"
			Me.CostPrice.Name = "CostPrice"
			Me.CostPrice.Width = 153
			Me.DataGridViewTextBoxColumn9.DataPropertyName = "SellingPrice"
			Me.DataGridViewTextBoxColumn9.HeaderText = "Retail Sale Price"
			Me.DataGridViewTextBoxColumn9.Name = "DataGridViewTextBoxColumn9"
			Me.DataGridViewTextBoxColumn9.Visible = False
			Me.DataGridViewTextBoxColumn9.Width = 167
			Me.DataGridViewTextBoxColumn10.DataPropertyName = "Discount"
			Me.DataGridViewTextBoxColumn10.FillWeight = 156.3039F
			Me.DataGridViewTextBoxColumn10.HeaderText = "Discount %"
			Me.DataGridViewTextBoxColumn10.Name = "DataGridViewTextBoxColumn10"
			Me.DataGridViewTextBoxColumn10.Visible = False
			Me.DataGridViewTextBoxColumn10.Width = 125
			Me.cmbGST1.FillWeight = 74.17998F
			Me.cmbGST1.HeaderText = "GSt %"
			Me.cmbGST1.Name = "cmbGST1"
			Me.cmbGST1.Resizable = Global.System.Windows.Forms.DataGridViewTriState.[True]
			Me.cmbGST1.SortMode = Global.System.Windows.Forms.DataGridViewColumnSortMode.NotSortable
			Me.cmbGST1.Visible = False
			Me.cmbGST1.Width = 67
			Me.DataGridViewButtonColumn3.DataPropertyName = "Gst_plus"
			dataGridViewCellStyle11.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter
			dataGridViewCellStyle11.ForeColor = Global.System.Drawing.Color.Purple
			Me.DataGridViewButtonColumn3.DefaultCellStyle = dataGridViewCellStyle11
			Me.DataGridViewButtonColumn3.FillWeight = 68.8888F
			Me.DataGridViewButtonColumn3.HeaderText = "+"
			Me.DataGridViewButtonColumn3.Name = "DataGridViewButtonColumn3"
			Me.DataGridViewButtonColumn3.Resizable = Global.System.Windows.Forms.DataGridViewTriState.[True]
			Me.DataGridViewButtonColumn3.SortMode = Global.System.Windows.Forms.DataGridViewColumnSortMode.Automatic
			Me.DataGridViewButtonColumn3.Text = "+"
			Me.DataGridViewButtonColumn3.UseColumnTextForButtonValue = True
			Me.DataGridViewButtonColumn3.Visible = False
			Me.DataGridViewButtonColumn3.Width = 44
			Me.DataGridViewTextBoxColumn11.DataPropertyName = "CGST"
			Me.DataGridViewTextBoxColumn11.FillWeight = 120.4923F
			Me.DataGridViewTextBoxColumn11.HeaderText = "CGST %"
			Me.DataGridViewTextBoxColumn11.Name = "DataGridViewTextBoxColumn11"
			Me.DataGridViewTextBoxColumn11.Visible = False
			Me.DataGridViewTextBoxColumn11.Width = 102
			Me.DataGridViewTextBoxColumn12.DataPropertyName = "SGST"
			Me.DataGridViewTextBoxColumn12.FillWeight = 182.0708F
			Me.DataGridViewTextBoxColumn12.HeaderText = "SGST/UTGST %"
			Me.DataGridViewTextBoxColumn12.Name = "DataGridViewTextBoxColumn12"
			Me.DataGridViewTextBoxColumn12.Visible = False
			Me.DataGridViewTextBoxColumn12.Width = 166
			Me.DataGridViewTextBoxColumn13.DataPropertyName = "IGST"
			Me.DataGridViewTextBoxColumn13.FillWeight = 101.0284F
			Me.DataGridViewTextBoxColumn13.HeaderText = "IGST %"
			Me.DataGridViewTextBoxColumn13.Name = "DataGridViewTextBoxColumn13"
			Me.DataGridViewTextBoxColumn13.Visible = False
			Me.DataGridViewTextBoxColumn13.Width = 96
			Me.DataGridViewTextBoxColumn14.DataPropertyName = "Cess"
			Me.DataGridViewTextBoxColumn14.FillWeight = 101.9943F
			Me.DataGridViewTextBoxColumn14.HeaderText = "CESS %"
			Me.DataGridViewTextBoxColumn14.Name = "DataGridViewTextBoxColumn14"
			Me.DataGridViewTextBoxColumn14.Visible = False
			Me.DataGridViewTextBoxColumn14.Width = 102
			Me.DataGridViewTextBoxColumn15.DataPropertyName = "ReorderPoint"
			Me.DataGridViewTextBoxColumn15.HeaderText = "Wholesale Sale Price"
			Me.DataGridViewTextBoxColumn15.Name = "DataGridViewTextBoxColumn15"
			Me.DataGridViewTextBoxColumn15.Visible = False
			Me.DataGridViewTextBoxColumn15.Width = 203
			Me.DataGridViewTextBoxColumn16.DataPropertyName = "Barcode"
			Me.DataGridViewTextBoxColumn16.HeaderText = "Barcode"
			Me.DataGridViewTextBoxColumn16.Name = "DataGridViewTextBoxColumn16"
			Me.DataGridViewTextBoxColumn16.Visible = False
			Me.DataGridViewTextBoxColumn16.Width = 101
			Me.DataGridViewTextBoxColumn17.HeaderText = "Opening Qty"
			Me.DataGridViewTextBoxColumn17.Name = "DataGridViewTextBoxColumn17"
			Me.DataGridViewTextBoxColumn17.Visible = False
			Me.DataGridViewTextBoxColumn17.Width = 133
			Me.cmbPurchaseUnit2.DataPropertyName = "PurchaseUnit"
			dataGridViewCellStyle12.Padding = New Global.System.Windows.Forms.Padding(2)
			Me.cmbPurchaseUnit2.DefaultCellStyle = dataGridViewCellStyle12
			Me.cmbPurchaseUnit2.FillWeight = 116.1214F
			Me.cmbPurchaseUnit2.HeaderText = "Purchase Main Unit"
			Me.cmbPurchaseUnit2.Name = "cmbPurchaseUnit2"
			Me.cmbPurchaseUnit2.Resizable = Global.System.Windows.Forms.DataGridViewTriState.[True]
			Me.cmbPurchaseUnit2.SortMode = Global.System.Windows.Forms.DataGridViewColumnSortMode.NotSortable
			Me.cmbPurchaseUnit2.Visible = False
			Me.cmbPurchaseUnit2.Width = 171
			Me.cmbSalesUnit2.DataPropertyName = "SalesUnit"
			dataGridViewCellStyle13.Padding = New Global.System.Windows.Forms.Padding(2)
			Me.cmbSalesUnit2.DefaultCellStyle = dataGridViewCellStyle13
			Me.cmbSalesUnit2.FillWeight = 77.56514F
			Me.cmbSalesUnit2.HeaderText = "Sales Unit"
			Me.cmbSalesUnit2.Name = "cmbSalesUnit2"
			Me.cmbSalesUnit2.Resizable = Global.System.Windows.Forms.DataGridViewTriState.[True]
			Me.cmbSalesUnit2.SortMode = Global.System.Windows.Forms.DataGridViewColumnSortMode.NotSortable
			Me.cmbSalesUnit2.Visible = False
			Me.cmbSalesUnit2.Width = 98
			Me.cmbAltunit2.DataPropertyName = "SalesAltUnit"
			dataGridViewCellStyle14.Padding = New Global.System.Windows.Forms.Padding(2)
			Me.cmbAltunit2.DefaultCellStyle = dataGridViewCellStyle14
			Me.cmbAltunit2.FillWeight = 69.68296F
			Me.cmbAltunit2.HeaderText = "Alter Unit"
			Me.cmbAltunit2.Name = "cmbAltunit2"
			Me.cmbAltunit2.Resizable = Global.System.Windows.Forms.DataGridViewTriState.[True]
			Me.cmbAltunit2.SortMode = Global.System.Windows.Forms.DataGridViewColumnSortMode.NotSortable
			Me.cmbAltunit2.Visible = False
			Me.cmbAltunit2.Width = 91
			Me.DataGridViewTextBoxColumn18.DataPropertyName = "Conv"
			Me.DataGridViewTextBoxColumn18.FillWeight = 142.4686F
			Me.DataGridViewTextBoxColumn18.HeaderText = "Conversion Value"
			Me.DataGridViewTextBoxColumn18.Name = "DataGridViewTextBoxColumn18"
			Me.DataGridViewTextBoxColumn18.Visible = False
			Me.DataGridViewTextBoxColumn18.Width = 174
			Me.DataGridViewTextBoxColumn19.DataPropertyName = "MinStock"
			Me.DataGridViewTextBoxColumn19.FillWeight = 92.37314F
			Me.DataGridViewTextBoxColumn19.HeaderText = "Min Stock"
			Me.DataGridViewTextBoxColumn19.Name = "DataGridViewTextBoxColumn19"
			Me.DataGridViewTextBoxColumn19.Visible = False
			Me.DataGridViewTextBoxColumn19.Width = 113
			Me.DataGridViewTextBoxColumn20.DataPropertyName = "MRP"
			Me.DataGridViewTextBoxColumn20.HeaderText = "MRP"
			Me.DataGridViewTextBoxColumn20.Name = "DataGridViewTextBoxColumn20"
			Me.DataGridViewTextBoxColumn20.Visible = False
			Me.DataGridViewTextBoxColumn20.Width = 72
			Me.DataGridViewTextBoxColumn21.DataPropertyName = "Status"
			Me.DataGridViewTextBoxColumn21.HeaderText = "Active"
			Me.DataGridViewTextBoxColumn21.Name = "DataGridViewTextBoxColumn21"
			Me.DataGridViewTextBoxColumn21.Visible = False
			Me.DataGridViewTextBoxColumn21.Width = 83
			Me.cmbSalesTaxType2.DataPropertyName = "STax"
			dataGridViewCellStyle15.Padding = New Global.System.Windows.Forms.Padding(2)
			Me.cmbSalesTaxType2.DefaultCellStyle = dataGridViewCellStyle15
			Me.cmbSalesTaxType2.FillWeight = 88.44212F
			Me.cmbSalesTaxType2.HeaderText = "Sale Tax Type"
			Me.cmbSalesTaxType2.Name = "cmbSalesTaxType2"
			Me.cmbSalesTaxType2.Resizable = Global.System.Windows.Forms.DataGridViewTriState.[True]
			Me.cmbSalesTaxType2.SortMode = Global.System.Windows.Forms.DataGridViewColumnSortMode.NotSortable
			Me.cmbSalesTaxType2.Visible = False
			Me.cmbSalesTaxType2.Width = 127
			Me.cmbPurchaseTaxType2.DataPropertyName = "PTax"
			dataGridViewCellStyle16.Padding = New Global.System.Windows.Forms.Padding(2)
			Me.cmbPurchaseTaxType2.DefaultCellStyle = dataGridViewCellStyle16
			Me.cmbPurchaseTaxType2.FillWeight = 84.72654F
			Me.cmbPurchaseTaxType2.HeaderText = "Purchase Tax Type"
			Me.cmbPurchaseTaxType2.Name = "cmbPurchaseTaxType2"
			Me.cmbPurchaseTaxType2.Resizable = Global.System.Windows.Forms.DataGridViewTriState.[True]
			Me.cmbPurchaseTaxType2.SortMode = Global.System.Windows.Forms.DataGridViewColumnSortMode.NotSortable
			Me.cmbPurchaseTaxType2.Visible = False
			Me.cmbPurchaseTaxType2.Width = 166
			Me.ddlGdown2.DataPropertyName = "GDown"
			Me.ddlGdown2.FillWeight = 57.85149F
			Me.ddlGdown2.HeaderText = "Godown"
			Me.ddlGdown2.Name = "ddlGdown2"
			Me.ddlGdown2.Resizable = Global.System.Windows.Forms.DataGridViewTriState.[True]
			Me.ddlGdown2.SortMode = Global.System.Windows.Forms.DataGridViewColumnSortMode.NotSortable
			Me.ddlGdown2.Visible = False
			Me.ddlGdown2.Width = 81
			Me.ddlRack2.DataPropertyName = "Rack"
			Me.ddlRack2.FillWeight = 42.29925F
			Me.ddlRack2.HeaderText = "Rack"
			Me.ddlRack2.Name = "ddlRack2"
			Me.ddlRack2.Resizable = Global.System.Windows.Forms.DataGridViewTriState.[True]
			Me.ddlRack2.SortMode = Global.System.Windows.Forms.DataGridViewColumnSortMode.NotSortable
			Me.ddlRack2.Visible = False
			Me.ddlRack2.Width = 56
			Me.DataGridViewTextBoxColumn22.DataPropertyName = "DefQty"
			Me.DataGridViewTextBoxColumn22.FillWeight = 90.80885F
			Me.DataGridViewTextBoxColumn22.HeaderText = "Default Sale Qty"
			Me.DataGridViewTextBoxColumn22.Name = "DataGridViewTextBoxColumn22"
			Me.DataGridViewTextBoxColumn22.Visible = False
			Me.DataGridViewTextBoxColumn22.Width = 166
			Me.txtOpeningStock2.DataPropertyName = "Qty"
			Me.txtOpeningStock2.FillWeight = 95.47243F
			Me.txtOpeningStock2.HeaderText = "Opening Stock"
			Me.txtOpeningStock2.Name = "txtOpeningStock2"
			Me.txtOpeningStock2.Width = 151
			Me.DataGridViewTextBoxColumn24.DataPropertyName = "Barcode"
			Me.DataGridViewTextBoxColumn24.FillWeight = 68.12365F
			Me.DataGridViewTextBoxColumn24.HeaderText = "Barcode"
			Me.DataGridViewTextBoxColumn24.Name = "DataGridViewTextBoxColumn24"
			Me.txtMRP.DataPropertyName = "MRP"
			Me.txtMRP.FillWeight = 50.81135F
			Me.txtMRP.HeaderText = "MRP"
			Me.txtMRP.Name = "txtMRP"
			Me.txtMRP.Width = 71
			Me.txtRSP1.DataPropertyName = "SalePrice"
			Me.txtRSP1.FillWeight = 90.11961F
			Me.txtRSP1.HeaderText = "Retail Sale Price"
			Me.txtRSP1.Name = "txtRSP1"
			Me.txtRSP1.Width = 166
			Me.DataGridViewTextBoxColumn27.DataPropertyName = "WSalePrice"
			Me.DataGridViewTextBoxColumn27.FillWeight = 84.05479F
			Me.DataGridViewTextBoxColumn27.HeaderText = "Wholesale Sale Price"
			Me.DataGridViewTextBoxColumn27.Name = "DataGridViewTextBoxColumn27"
			Me.DataGridViewTextBoxColumn27.Visible = False
			Me.DataGridViewTextBoxColumn27.Width = 203
			Me.DataGridViewTextBoxColumn28.DataPropertyName = "Batch"
			Me.DataGridViewTextBoxColumn28.FillWeight = 47.2846F
			Me.DataGridViewTextBoxColumn28.HeaderText = "Batch"
			Me.DataGridViewTextBoxColumn28.Name = "DataGridViewTextBoxColumn28"
			Me.DataGridViewTextBoxColumn28.Visible = False
			Me.DataGridViewTextBoxColumn28.Width = 81
			Me.DataGridViewTextBoxColumn29.DataPropertyName = "Mfgdate"
			Me.DataGridViewTextBoxColumn29.FillWeight = 53.91898F
			Me.DataGridViewTextBoxColumn29.HeaderText = "Mfg Date"
			Me.DataGridViewTextBoxColumn29.Name = "DataGridViewTextBoxColumn29"
			Me.DataGridViewTextBoxColumn29.Visible = False
			Me.DataGridViewTextBoxColumn29.Width = 108
			Me.DataGridViewTextBoxColumn30.DataPropertyName = "ExpDate"
			Me.DataGridViewTextBoxColumn30.FillWeight = 52.19537F
			Me.DataGridViewTextBoxColumn30.HeaderText = "Exp Date"
			Me.DataGridViewTextBoxColumn30.Name = "DataGridViewTextBoxColumn30"
			Me.DataGridViewTextBoxColumn30.Visible = False
			Me.DataGridViewTextBoxColumn30.Width = 108
			Me.cmbSize2.DataPropertyName = "Size"
			Me.cmbSize2.FillWeight = 28.57796F
			Me.cmbSize2.HeaderText = "Size"
			Me.cmbSize2.Name = "cmbSize2"
			Me.cmbSize2.Resizable = Global.System.Windows.Forms.DataGridViewTriState.[True]
			Me.cmbSize2.Width = 68
			Me.cmbColour2.DataPropertyName = "Colour"
			Me.cmbColour2.FillWeight = 30.52615F
			Me.cmbColour2.HeaderText = "Colour"
			Me.cmbColour2.Name = "cmbColour2"
			Me.cmbColour2.Resizable = Global.System.Windows.Forms.DataGridViewTriState.[True]
			Me.cmbColour2.SortMode = Global.System.Windows.Forms.DataGridViewColumnSortMode.NotSortable
			Me.cmbColour2.Width = 66
			Me.DataGridViewTextBoxColumn31.DataPropertyName = "IMEI1"
			Me.DataGridViewTextBoxColumn31.FillWeight = 40.28614F
			Me.DataGridViewTextBoxColumn31.HeaderText = "IME1"
			Me.DataGridViewTextBoxColumn31.Name = "DataGridViewTextBoxColumn31"
			Me.DataGridViewTextBoxColumn31.Visible = False
			Me.DataGridViewTextBoxColumn31.Width = 76
			Me.DataGridViewTextBoxColumn32.DataPropertyName = "IMEI2"
			Me.DataGridViewTextBoxColumn32.FillWeight = 39.46039F
			Me.DataGridViewTextBoxColumn32.HeaderText = "IME2"
			Me.DataGridViewTextBoxColumn32.Name = "DataGridViewTextBoxColumn32"
			Me.DataGridViewTextBoxColumn32.Visible = False
			Me.DataGridViewTextBoxColumn32.Width = 76
			Me.DataGridViewTextBoxColumn33.DataPropertyName = "Kitchen"
			Me.DataGridViewTextBoxColumn33.HeaderText = "Kitchen"
			Me.DataGridViewTextBoxColumn33.Name = "DataGridViewTextBoxColumn33"
			Me.DataGridViewTextBoxColumn33.Visible = False
			Me.DataGridViewTextBoxColumn33.Width = 94
			Me.DataGridViewImageColumn1.DataPropertyName = "Photo"
			Me.DataGridViewImageColumn1.FillWeight = 27.62098F
			Me.DataGridViewImageColumn1.HeaderText = "Photo"
			Me.DataGridViewImageColumn1.Image = CType(componentResourceManager.GetObject("DataGridViewImageColumn1.Image"), Global.System.Drawing.Image)
			Me.DataGridViewImageColumn1.ImageLayout = Global.System.Windows.Forms.DataGridViewImageCellLayout.Zoom
			Me.DataGridViewImageColumn1.Name = "DataGridViewImageColumn1"
			Me.DataGridViewImageColumn1.Visible = False
			Me.DataGridViewImageColumn1.Width = 62
			Me.btnAddNew.DataPropertyName = "btnAddNew"
			Me.btnAddNew.HeaderText = "+"
			Me.btnAddNew.Name = "btnAddNew"
			Me.btnAddNew.Text = "+"
			Me.btnAddNew.UseColumnTextForButtonValue = True
			Me.btnAddNew.Width = 24
			Me.GelButton1.Anchor = Global.System.Windows.Forms.AnchorStyles.Bottom Or Global.System.Windows.Forms.AnchorStyles.Right
			Me.GelButton1.BackgroundImage = CType(componentResourceManager.GetObject("GelButton1.BackgroundImage"), Global.System.Drawing.Image)
			Me.GelButton1.BackgroundImageLayout = Global.System.Windows.Forms.ImageLayout.Stretch
			Me.GelButton1.FlatAppearance.BorderSize = 0
			Me.GelButton1.FlatStyle = Global.System.Windows.Forms.FlatStyle.Flat
			Me.GelButton1.Location = New Global.System.Drawing.Point(670, 273)
			Me.GelButton1.Name = "GelButton1"
			Me.GelButton1.Size = New Global.System.Drawing.Size(203, 41)
			Me.GelButton1.TabIndex = 1836
			Me.GelButton1.UseVisualStyleBackColor = True
			Me.GelButton2.Anchor = Global.System.Windows.Forms.AnchorStyles.Bottom Or Global.System.Windows.Forms.AnchorStyles.Right
			Me.GelButton2.BackgroundImage = CType(componentResourceManager.GetObject("GelButton2.BackgroundImage"), Global.System.Drawing.Image)
			Me.GelButton2.BackgroundImageLayout = Global.System.Windows.Forms.ImageLayout.Stretch
			Me.GelButton2.FlatAppearance.BorderSize = 0
			Me.GelButton2.FlatStyle = Global.System.Windows.Forms.FlatStyle.Flat
			Me.GelButton2.Location = New Global.System.Drawing.Point(879, 273)
			Me.GelButton2.Name = "GelButton2"
			Me.GelButton2.Size = New Global.System.Drawing.Size(203, 41)
			Me.GelButton2.TabIndex = 1835
			Me.GelButton2.UseVisualStyleBackColor = True
			Me.Label14.AutoSize = True
			Me.Label14.Location = New Global.System.Drawing.Point(72, 357)
			Me.Label14.Name = "Label14"
			Me.Label14.Size = New Global.System.Drawing.Size(45, 13)
			Me.Label14.TabIndex = 518
			Me.Label14.Text = "Label14"
			Me.Label14.Visible = False
			Me.Label13.AutoSize = True
			Me.Label13.Location = New Global.System.Drawing.Point(7, 357)
			Me.Label13.Name = "Label13"
			Me.Label13.Size = New Global.System.Drawing.Size(45, 13)
			Me.Label13.TabIndex = 517
			Me.Label13.Text = "Label13"
			Me.Label13.Visible = False
			Me.Panel7.BackColor = Global.System.Drawing.Color.FromArgb(229, 233, 219)
			Me.Panel7.Controls.Add(Me.txtbarcodeNocopy)
			Me.Panel7.Controls.Add(Me.Label20)
			Me.Panel7.Controls.Add(Me.Label19)
			Me.Panel7.Controls.Add(Me.CheckBox1)
			Me.Panel7.Controls.Add(Me.Label18)
			Me.Panel7.Controls.Add(Me.Label21)
			Me.Panel7.Controls.Add(Me.txtTopResult)
			Me.Panel7.Location = New Global.System.Drawing.Point(8, 81)
			Me.Panel7.Name = "Panel7"
			Me.Panel7.Size = New Global.System.Drawing.Size(436, 68)
			Me.Panel7.TabIndex = 1823
			Me.txtbarcodeNocopy.BackColor = Global.System.Drawing.Color.White
			Me.txtbarcodeNocopy.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 12F)
			Me.txtbarcodeNocopy.Location = New Global.System.Drawing.Point(388, 36)
			Me.txtbarcodeNocopy.Name = "txtbarcodeNocopy"
			Me.txtbarcodeNocopy.Size = New Global.System.Drawing.Size(42, 26)
			Me.txtbarcodeNocopy.TabIndex = 1803
			Me.txtbarcodeNocopy.Text = "1"
			Me.txtbarcodeNocopy.Visible = False
			Me.Label20.BackColor = Global.System.Drawing.Color.LightGray
			Me.Label20.Font = New Global.System.Drawing.Font("Microsoft Tai Le", 11F, Global.System.Drawing.FontStyle.Bold)
			Me.Label20.ForeColor = Global.System.Drawing.Color.FromArgb(64, 64, 0)
			Me.Label20.Location = New Global.System.Drawing.Point(191, 37)
			Me.Label20.Name = "Label20"
			Me.Label20.Size = New Global.System.Drawing.Size(206, 25)
			Me.Label20.TabIndex = 1808
			Me.Label20.Text = "BARCODE No. of Copies :"
			Me.Label20.TextAlign = Global.System.Drawing.ContentAlignment.MiddleCenter
			Me.Label20.Visible = False
			Me.Label19.Font = New Global.System.Drawing.Font("Microsoft Tai Le", 15F, Global.System.Drawing.FontStyle.Bold)
			Me.Label19.ForeColor = Global.System.Drawing.Color.FromArgb(64, 64, 0)
			Me.Label19.Location = New Global.System.Drawing.Point(6, 37)
			Me.Label19.Name = "Label19"
			Me.Label19.Size = New Global.System.Drawing.Size(145, 25)
			Me.Label19.TabIndex = 1807
			Me.Label19.Text = "SELECT ALL :"
			Me.Label19.TextAlign = Global.System.Drawing.ContentAlignment.MiddleCenter
			Me.CheckBox1.Anchor = Global.System.Windows.Forms.AnchorStyles.Top Or Global.System.Windows.Forms.AnchorStyles.Right
			Me.CheckBox1.AutoSize = True
			Me.CheckBox1.BackColor = Global.System.Drawing.Color.PaleGreen
			Me.CheckBox1.Cursor = Global.System.Windows.Forms.Cursors.Hand
			Me.CheckBox1.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 8F, Global.System.Drawing.FontStyle.Bold, Global.System.Drawing.GraphicsUnit.Point, 0)
			Me.CheckBox1.Location = New Global.System.Drawing.Point(153, 43)
			Me.CheckBox1.Name = "CheckBox1"
			Me.CheckBox1.Size = New Global.System.Drawing.Size(15, 14)
			Me.CheckBox1.TabIndex = 1805
			Me.CheckBox1.TabStop = False
			Me.CheckBox1.UseVisualStyleBackColor = False
			Me.Label18.Font = New Global.System.Drawing.Font("Microsoft Tai Le", 15F, Global.System.Drawing.FontStyle.Bold)
			Me.Label18.ForeColor = Global.System.Drawing.Color.FromArgb(64, 64, 0)
			Me.Label18.Location = New Global.System.Drawing.Point(183, 5)
			Me.Label18.Name = "Label18"
			Me.Label18.Size = New Global.System.Drawing.Size(107, 30)
			Me.Label18.TabIndex = 1806
			Me.Label18.Text = "RECORDS"
			Me.Label18.TextAlign = Global.System.Drawing.ContentAlignment.MiddleCenter
			Me.Label21.Font = New Global.System.Drawing.Font("Microsoft Tai Le", 15F, Global.System.Drawing.FontStyle.Bold)
			Me.Label21.ForeColor = Global.System.Drawing.Color.FromArgb(64, 64, 0)
			Me.Label21.Location = New Global.System.Drawing.Point(13, 5)
			Me.Label21.Name = "Label21"
			Me.Label21.Size = New Global.System.Drawing.Size(64, 30)
			Me.Label21.TabIndex = 51
			Me.Label21.Text = "TOP :"
			Me.Label21.TextAlign = Global.System.Drawing.ContentAlignment.MiddleCenter
			Me.txtTopResult.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 12F)
			Me.txtTopResult.Location = New Global.System.Drawing.Point(80, 5)
			Me.txtTopResult.Name = "txtTopResult"
			Me.txtTopResult.Size = New Global.System.Drawing.Size(97, 26)
			Me.txtTopResult.TabIndex = 433
			Me.txtTopResult.TabStop = False
			Me.txtTopResult.Text = "5"
			Me.txtTopResult.TextAlign = Global.System.Windows.Forms.HorizontalAlignment.Center
			Me.Panel2.Controls.Add(Me.Label12)
			Me.Panel2.Controls.Add(Me.Panel3)
			Me.Panel2.Controls.Add(Me.lblUser)
			Me.Panel2.Controls.Add(Me.lblSet)
			Me.Panel2.Location = New Global.System.Drawing.Point(363, 538)
			Me.Panel2.Name = "Panel2"
			Me.Panel2.Size = New Global.System.Drawing.Size(128, 68)
			Me.Panel2.TabIndex = 520
			Me.Panel2.Visible = False
			Me.Label12.AutoSize = True
			Me.Label12.Location = New Global.System.Drawing.Point(694, 21)
			Me.Label12.Name = "Label12"
			Me.Label12.Size = New Global.System.Drawing.Size(94, 13)
			Me.Label12.TabIndex = 1804
			Me.Label12.Text = "Barcode NoCopy :"
			Me.Panel3.BorderStyle = Global.System.Windows.Forms.BorderStyle.FixedSingle
			Me.Panel3.Controls.Add(Me.ComboBox2)
			Me.Panel3.Controls.Add(Me.txtID_Update)
			Me.Panel3.Controls.Add(Me.Label9)
			Me.Panel3.Controls.Add(Me.cmbRack)
			Me.Panel3.Controls.Add(Me.Label8)
			Me.Panel3.Controls.Add(Me.cmbGDown)
			Me.Panel3.Controls.Add(Me.Label7)
			Me.Panel3.Controls.Add(Me.TextBox1)
			Me.Panel3.Controls.Add(Me.ComboBox1)
			Me.Panel3.Controls.Add(Me.Label6)
			Me.Panel3.Controls.Add(Me.txtBarcode)
			Me.Panel3.Controls.Add(Me.Label5)
			Me.Panel3.Controls.Add(Me.Label4)
			Me.Panel3.Controls.Add(Me.txtCategory)
			Me.Panel3.Controls.Add(Me.Label2)
			Me.Panel3.Controls.Add(Me.txtProductName)
			Me.Panel3.Controls.Add(Me.Label3)
			Me.Panel3.Location = New Global.System.Drawing.Point(40, 19)
			Me.Panel3.Name = "Panel3"
			Me.Panel3.Size = New Global.System.Drawing.Size(661, 96)
			Me.Panel3.TabIndex = 45
			Me.ComboBox2.Cursor = Global.System.Windows.Forms.Cursors.Hand
			Me.ComboBox2.DropDownStyle = Global.System.Windows.Forms.ComboBoxStyle.Simple
			Me.ComboBox2.FormattingEnabled = True
			Me.ComboBox2.Items.AddRange(New Object() { "Product Name", "Barcode", "Category", "Sub Category" })
			Me.ComboBox2.Location = New Global.System.Drawing.Point(184, 21)
			Me.ComboBox2.Name = "ComboBox2"
			Me.ComboBox2.Size = New Global.System.Drawing.Size(165, 21)
			Me.ComboBox2.TabIndex = 1803
			Me.txtID_Update.Location = New Global.System.Drawing.Point(496, -2)
			Me.txtID_Update.Name = "txtID_Update"
			Me.txtID_Update.Size = New Global.System.Drawing.Size(43, 20)
			Me.txtID_Update.TabIndex = 1802
			Me.txtID_Update.TabStop = False
			Me.txtID_Update.Text = "RowID"
			Me.txtID_Update.TextAlign = Global.System.Windows.Forms.HorizontalAlignment.Center
			Me.txtID_Update.Visible = False
			Me.Label9.AutoSize = True
			Me.Label9.Location = New Global.System.Drawing.Point(546, 48)
			Me.Label9.Name = "Label9"
			Me.Label9.Size = New Global.System.Drawing.Size(91, 13)
			Me.Label9.TabIndex = 56
			Me.Label9.Text = "Search By Rack :"
			Me.Label9.Visible = False
			Me.cmbRack.Cursor = Global.System.Windows.Forms.Cursors.Hand
			Me.cmbRack.DropDownStyle = Global.System.Windows.Forms.ComboBoxStyle.DropDownList
			Me.cmbRack.FormattingEnabled = True
			Me.cmbRack.Items.AddRange(New Object() { "Active", "Deactive" })
			Me.cmbRack.Location = New Global.System.Drawing.Point(549, 68)
			Me.cmbRack.Name = "cmbRack"
			Me.cmbRack.Size = New Global.System.Drawing.Size(102, 21)
			Me.cmbRack.TabIndex = 7
			Me.cmbRack.Visible = False
			Me.Label8.AutoSize = True
			Me.Label8.Location = New Global.System.Drawing.Point(546, 1)
			Me.Label8.Name = "Label8"
			Me.Label8.Size = New Global.System.Drawing.Size(105, 13)
			Me.Label8.TabIndex = 54
			Me.Label8.Text = "Search By Godown :"
			Me.Label8.Visible = False
			Me.cmbGDown.Cursor = Global.System.Windows.Forms.Cursors.Hand
			Me.cmbGDown.DropDownStyle = Global.System.Windows.Forms.ComboBoxStyle.DropDownList
			Me.cmbGDown.FormattingEnabled = True
			Me.cmbGDown.Items.AddRange(New Object() { "Active", "Deactive" })
			Me.cmbGDown.Location = New Global.System.Drawing.Point(549, 21)
			Me.cmbGDown.Name = "cmbGDown"
			Me.cmbGDown.Size = New Global.System.Drawing.Size(102, 21)
			Me.cmbGDown.TabIndex = 3
			Me.cmbGDown.Visible = False
			Me.Label7.AutoSize = True
			Me.Label7.Location = New Global.System.Drawing.Point(363, 48)
			Me.Label7.Name = "Label7"
			Me.Label7.Size = New Global.System.Drawing.Size(95, 13)
			Me.Label7.TabIndex = 14
			Me.Label7.Text = "Search By Status :"
			Me.Label7.Visible = False
			Me.TextBox1.BackColor = Global.System.Drawing.Color.White
			Me.TextBox1.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 9F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			Me.TextBox1.Location = New Global.System.Drawing.Point(366, 21)
			Me.TextBox1.Name = "TextBox1"
			Me.TextBox1.Size = New Global.System.Drawing.Size(159, 21)
			Me.TextBox1.TabIndex = 2
			Me.ComboBox1.Cursor = Global.System.Windows.Forms.Cursors.Hand
			Me.ComboBox1.DropDownStyle = Global.System.Windows.Forms.ComboBoxStyle.DropDownList
			Me.ComboBox1.FormattingEnabled = True
			Me.ComboBox1.Items.AddRange(New Object() { "Active", "Deactive" })
			Me.ComboBox1.Location = New Global.System.Drawing.Point(366, 68)
			Me.ComboBox1.Name = "ComboBox1"
			Me.ComboBox1.Size = New Global.System.Drawing.Size(159, 21)
			Me.ComboBox1.TabIndex = 6
			Me.ComboBox1.Visible = False
			Me.Label6.AutoSize = True
			Me.Label6.Location = New Global.System.Drawing.Point(363, 1)
			Me.Label6.Name = "Label6"
			Me.Label6.Size = New Global.System.Drawing.Size(121, 13)
			Me.Label6.TabIndex = 12
			Me.Label6.Text = "Search By Part /Group :"
			Me.txtBarcode.BackColor = Global.System.Drawing.Color.White
			Me.txtBarcode.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 9F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			Me.txtBarcode.Location = New Global.System.Drawing.Point(184, 68)
			Me.txtBarcode.Name = "txtBarcode"
			Me.txtBarcode.Size = New Global.System.Drawing.Size(159, 21)
			Me.txtBarcode.TabIndex = 5
			Me.Label5.AutoSize = True
			Me.Label5.Location = New Global.System.Drawing.Point(181, 48)
			Me.Label5.Name = "Label5"
			Me.Label5.Size = New Global.System.Drawing.Size(105, 13)
			Me.Label5.TabIndex = 12
			Me.Label5.Text = "Search By Barcode :"
			Me.Label4.AutoSize = True
			Me.Label4.Location = New Global.System.Drawing.Point(181, 1)
			Me.Label4.Name = "Label4"
			Me.Label4.Size = New Global.System.Drawing.Size(168, 13)
			Me.Label4.TabIndex = 12
			Me.Label4.Text = "Search By Sub Category / Brand :"
			Me.txtCategory.BackColor = Global.System.Drawing.Color.White
			Me.txtCategory.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 9F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			Me.txtCategory.Location = New Global.System.Drawing.Point(3, 68)
			Me.txtCategory.Name = "txtCategory"
			Me.txtCategory.Size = New Global.System.Drawing.Size(159, 21)
			Me.txtCategory.TabIndex = 4
			Me.Label2.AutoSize = True
			Me.Label2.Location = New Global.System.Drawing.Point(0, 48)
			Me.Label2.Name = "Label2"
			Me.Label2.Size = New Global.System.Drawing.Size(107, 13)
			Me.Label2.TabIndex = 12
			Me.Label2.Text = "Search By Category :"
			Me.txtProductName.BackColor = Global.System.Drawing.Color.White
			Me.txtProductName.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 9F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			Me.txtProductName.Location = New Global.System.Drawing.Point(3, 21)
			Me.txtProductName.Name = "txtProductName"
			Me.txtProductName.Size = New Global.System.Drawing.Size(159, 21)
			Me.txtProductName.TabIndex = 0
			Me.Label3.AutoSize = True
			Me.Label3.Location = New Global.System.Drawing.Point(0, 1)
			Me.Label3.Name = "Label3"
			Me.Label3.Size = New Global.System.Drawing.Size(133, 13)
			Me.Label3.TabIndex = 12
			Me.Label3.Text = "Search By Product Name :"
			Me.lblUser.AutoSize = True
			Me.lblUser.Location = New Global.System.Drawing.Point(737, 68)
			Me.lblUser.Name = "lblUser"
			Me.lblUser.Size = New Global.System.Drawing.Size(95, 13)
			Me.lblUser.TabIndex = 1804
			Me.lblUser.Text = "Search By Status :"
			Me.lblSet.AutoSize = True
			Me.lblSet.Location = New Global.System.Drawing.Point(765, 102)
			Me.lblSet.Name = "lblSet"
			Me.lblSet.Size = New Global.System.Drawing.Size(23, 13)
			Me.lblSet.TabIndex = 44
			Me.lblSet.Text = "Set"
			Me.lblSet.Visible = False
			Me.Label16.AutoSize = True
			Me.Label16.Location = New Global.System.Drawing.Point(539, 86)
			Me.Label16.Name = "Label16"
			Me.Label16.Size = New Global.System.Drawing.Size(45, 13)
			Me.Label16.TabIndex = 1815
			Me.Label16.Text = "Label16"
			Me.Label16.Visible = False
			Me.txtSearchProduct.BackColor = Global.System.Drawing.Color.White
			Me.txtSearchProduct.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 12F)
			Me.txtSearchProduct.Location = New Global.System.Drawing.Point(177, 47)
			Me.txtSearchProduct.Name = "txtSearchProduct"
			Me.txtSearchProduct.Size = New Global.System.Drawing.Size(424, 26)
			Me.txtSearchProduct.TabIndex = 1821
			Me.btnBulkImageUpdate.Anchor = Global.System.Windows.Forms.AnchorStyles.Top Or Global.System.Windows.Forms.AnchorStyles.Right
			Me.btnBulkImageUpdate.BackgroundImage = CType(componentResourceManager.GetObject("btnBulkImageUpdate.BackgroundImage"), Global.System.Drawing.Image)
			Me.btnBulkImageUpdate.BackgroundImageLayout = Global.System.Windows.Forms.ImageLayout.Stretch
			Me.btnBulkImageUpdate.FlatAppearance.BorderSize = 0
			Me.btnBulkImageUpdate.FlatStyle = Global.System.Windows.Forms.FlatStyle.Flat
			Me.btnBulkImageUpdate.Location = New Global.System.Drawing.Point(510, 41)
			Me.btnBulkImageUpdate.Name = "btnBulkImageUpdate"
			Me.btnBulkImageUpdate.Size = New Global.System.Drawing.Size(258, 41)
			Me.btnBulkImageUpdate.TabIndex = 1832
			Me.btnBulkImageUpdate.UseVisualStyleBackColor = True
			Me.btnBulkImageUpdate.Visible = False
			Me.Label15.AutoSize = True
			Me.Label15.Location = New Global.System.Drawing.Point(475, 86)
			Me.Label15.Name = "Label15"
			Me.Label15.Size = New Global.System.Drawing.Size(45, 13)
			Me.Label15.TabIndex = 1814
			Me.Label15.Text = "Label15"
			Me.Label15.Visible = False
			Me.cmbSearchCat.BackColor = Global.System.Drawing.Color.RoyalBlue
			Me.cmbSearchCat.Cursor = Global.System.Windows.Forms.Cursors.Hand
			Me.cmbSearchCat.DropDownStyle = Global.System.Windows.Forms.ComboBoxStyle.DropDownList
			Me.cmbSearchCat.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 12F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			Me.cmbSearchCat.ForeColor = Global.System.Drawing.Color.White
			Me.cmbSearchCat.FormattingEnabled = True
			Me.cmbSearchCat.Items.AddRange(New Object() { "Product Name", "Sub-Category/Category", "Barcode", "Part / Group" })
			Me.cmbSearchCat.Location = New Global.System.Drawing.Point(8, 47)
			Me.cmbSearchCat.Name = "cmbSearchCat"
			Me.cmbSearchCat.Size = New Global.System.Drawing.Size(163, 28)
			Me.cmbSearchCat.TabIndex = 1822
			Me.cmbSearchCat.TabStop = False
			Me.btnShowAll.Anchor = Global.System.Windows.Forms.AnchorStyles.Top Or Global.System.Windows.Forms.AnchorStyles.Right
			Me.btnShowAll.BackgroundImage = CType(componentResourceManager.GetObject("btnShowAll.BackgroundImage"), Global.System.Drawing.Image)
			Me.btnShowAll.BackgroundImageLayout = Global.System.Windows.Forms.ImageLayout.Stretch
			Me.btnShowAll.FlatAppearance.BorderSize = 0
			Me.btnShowAll.FlatStyle = Global.System.Windows.Forms.FlatStyle.Flat
			Me.btnShowAll.Location = New Global.System.Drawing.Point(742, 100)
			Me.btnShowAll.Name = "btnShowAll"
			Me.btnShowAll.Size = New Global.System.Drawing.Size(128, 41)
			Me.btnShowAll.TabIndex = 1833
			Me.btnShowAll.UseVisualStyleBackColor = True
			Me.btnShowAll.Visible = False
			Me.txtCompany.Font = New Global.System.Drawing.Font("Tahoma", 8.25F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			Me.txtCompany.Location = New Global.System.Drawing.Point(459, 117)
			Me.txtCompany.Name = "txtCompany"
			Me.txtCompany.Size = New Global.System.Drawing.Size(42, 21)
			Me.txtCompany.TabIndex = 1806
			Me.txtCompany.Visible = False
			Me.Picture.Image = CType(componentResourceManager.GetObject("Picture.Image"), Global.System.Drawing.Image)
			Me.Picture.Location = New Global.System.Drawing.Point(150, 270)
			Me.Picture.Name = "Picture"
			Me.Picture.Size = New Global.System.Drawing.Size(209, 229)
			Me.Picture.SizeMode = Global.System.Windows.Forms.PictureBoxSizeMode.StretchImage
			Me.Picture.TabIndex = 1804
			Me.Picture.TabStop = False
			Me.Picture.Visible = False
			Me.txtNP.BackColor = Global.System.Drawing.SystemColors.Control
			Me.txtNP.Location = New Global.System.Drawing.Point(1025, 358)
			Me.txtNP.Name = "txtNP"
			Me.txtNP.RightToLeft = Global.System.Windows.Forms.RightToLeft.Yes
			Me.txtNP.Size = New Global.System.Drawing.Size(35, 20)
			Me.txtNP.TabIndex = 1801
			Me.txtNP.TabStop = False
			Me.txtNP.Visible = False
			Me.cmbNP.DropDownStyle = Global.System.Windows.Forms.ComboBoxStyle.DropDownList
			Me.cmbNP.FormattingEnabled = True
			Me.cmbNP.Location = New Global.System.Drawing.Point(970, 359)
			Me.cmbNP.Name = "cmbNP"
			Me.cmbNP.Size = New Global.System.Drawing.Size(49, 21)
			Me.cmbNP.TabIndex = 1800
			Me.cmbNP.TabStop = False
			Me.cmbNP.Visible = False
			Me.pbgiftqr.Image = CType(componentResourceManager.GetObject("pbgiftqr.Image"), Global.System.Drawing.Image)
			Me.pbgiftqr.Location = New Global.System.Drawing.Point(970, 289)
			Me.pbgiftqr.Name = "pbgiftqr"
			Me.pbgiftqr.Size = New Global.System.Drawing.Size(32, 40)
			Me.pbgiftqr.TabIndex = 1799
			Me.pbgiftqr.TabStop = False
			Me.pbgiftqr.Visible = False
			Me.txtBar.BackColor = Global.System.Drawing.Color.White
			Me.txtBar.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 9F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			Me.txtBar.Location = New Global.System.Drawing.Point(970, 280)
			Me.txtBar.Name = "txtBar"
			Me.txtBar.Size = New Global.System.Drawing.Size(93, 21)
			Me.txtBar.TabIndex = 440
			Me.txtBar.Visible = False
			Me.txtBarcodeTempStock.BackColor = Global.System.Drawing.Color.White
			Me.txtBarcodeTempStock.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 9F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			Me.txtBarcodeTempStock.Location = New Global.System.Drawing.Point(970, 300)
			Me.txtBarcodeTempStock.Name = "txtBarcodeTempStock"
			Me.txtBarcodeTempStock.Size = New Global.System.Drawing.Size(93, 21)
			Me.txtBarcodeTempStock.TabIndex = 439
			Me.txtBarcodeTempStock.Visible = False
			Me.txtProductCode.Location = New Global.System.Drawing.Point(1020, 322)
			Me.txtProductCode.Name = "txtProductCode"
			Me.txtProductCode.Size = New Global.System.Drawing.Size(43, 20)
			Me.txtProductCode.TabIndex = 438
			Me.txtProductCode.TabStop = False
			Me.txtProductCode.Text = "PC"
			Me.txtProductCode.TextAlign = Global.System.Windows.Forms.HorizontalAlignment.Center
			Me.txtProductCode.Visible = False
			Me.txtID.Location = New Global.System.Drawing.Point(970, 322)
			Me.txtID.Name = "txtID"
			Me.txtID.Size = New Global.System.Drawing.Size(43, 20)
			Me.txtID.TabIndex = 437
			Me.txtID.TabStop = False
			Me.txtID.Text = "PID"
			Me.txtID.TextAlign = Global.System.Windows.Forms.HorizontalAlignment.Center
			Me.txtID.Visible = False
			Me.Panel5.Anchor = Global.System.Windows.Forms.AnchorStyles.Top Or Global.System.Windows.Forms.AnchorStyles.Right
			Me.Panel5.BorderStyle = Global.System.Windows.Forms.BorderStyle.FixedSingle
			Me.Panel5.Controls.Add(Me.GelButton3)
			Me.Panel5.Controls.Add(Me.btnReset)
			Me.Panel5.Controls.Add(Me.GelButtonNewRecord)
			Me.Panel5.Controls.Add(Me.GelButton5)
			Me.Panel5.Controls.Add(Me.btnExportExcel)
			Me.Panel5.Controls.Add(Me.GelButton6)
			Me.Panel5.Controls.Add(Me.Button16)
			Me.Panel5.Controls.Add(Me.btnProductSeting)
			Me.Panel5.Location = New Global.System.Drawing.Point(876, 46)
			Me.Panel5.Name = "Panel5"
			Me.Panel5.Size = New Global.System.Drawing.Size(536, 104)
			Me.Panel5.TabIndex = 51
			Me.GelButton3.Anchor = Global.System.Windows.Forms.AnchorStyles.Top Or Global.System.Windows.Forms.AnchorStyles.Right
			Me.GelButton3.BackgroundImage = CType(componentResourceManager.GetObject("GelButton3.BackgroundImage"), Global.System.Drawing.Image)
			Me.GelButton3.BackgroundImageLayout = Global.System.Windows.Forms.ImageLayout.Stretch
			Me.GelButton3.FlatAppearance.BorderSize = 0
			Me.GelButton3.FlatStyle = Global.System.Windows.Forms.FlatStyle.Flat
			Me.GelButton3.Location = New Global.System.Drawing.Point(403, 3)
			Me.GelButton3.Name = "GelButton3"
			Me.GelButton3.Size = New Global.System.Drawing.Size(128, 41)
			Me.GelButton3.TabIndex = 1820
			Me.GelButton3.UseVisualStyleBackColor = True
			Me.btnReset.Anchor = Global.System.Windows.Forms.AnchorStyles.Top Or Global.System.Windows.Forms.AnchorStyles.Right
			Me.btnReset.BackgroundImage = CType(componentResourceManager.GetObject("btnReset.BackgroundImage"), Global.System.Drawing.Image)
			Me.btnReset.BackgroundImageLayout = Global.System.Windows.Forms.ImageLayout.Stretch
			Me.btnReset.FlatAppearance.BorderSize = 0
			Me.btnReset.FlatStyle = Global.System.Windows.Forms.FlatStyle.Flat
			Me.btnReset.Location = New Global.System.Drawing.Point(9, 53)
			Me.btnReset.Name = "btnReset"
			Me.btnReset.Size = New Global.System.Drawing.Size(128, 40)
			Me.btnReset.TabIndex = 1817
			Me.btnReset.UseVisualStyleBackColor = True
			Me.GelButtonNewRecord.Anchor = Global.System.Windows.Forms.AnchorStyles.Top Or Global.System.Windows.Forms.AnchorStyles.Right
			Me.GelButtonNewRecord.BackgroundImage = CType(componentResourceManager.GetObject("GelButtonNewRecord.BackgroundImage"), Global.System.Drawing.Image)
			Me.GelButtonNewRecord.BackgroundImageLayout = Global.System.Windows.Forms.ImageLayout.Stretch
			Me.GelButtonNewRecord.FlatAppearance.BorderSize = 0
			Me.GelButtonNewRecord.FlatStyle = Global.System.Windows.Forms.FlatStyle.Flat
			Me.GelButtonNewRecord.Location = New Global.System.Drawing.Point(403, 52)
			Me.GelButtonNewRecord.Name = "GelButtonNewRecord"
			Me.GelButtonNewRecord.Size = New Global.System.Drawing.Size(128, 41)
			Me.GelButtonNewRecord.TabIndex = 1834
			Me.GelButtonNewRecord.UseVisualStyleBackColor = True
			Me.GelButton5.Anchor = Global.System.Windows.Forms.AnchorStyles.Top Or Global.System.Windows.Forms.AnchorStyles.Right
			Me.GelButton5.BackgroundImage = CType(componentResourceManager.GetObject("GelButton5.BackgroundImage"), Global.System.Drawing.Image)
			Me.GelButton5.BackgroundImageLayout = Global.System.Windows.Forms.ImageLayout.Stretch
			Me.GelButton5.FlatAppearance.BorderSize = 0
			Me.GelButton5.FlatStyle = Global.System.Windows.Forms.FlatStyle.Flat
			Me.GelButton5.Location = New Global.System.Drawing.Point(273, 53)
			Me.GelButton5.Name = "GelButton5"
			Me.GelButton5.Size = New Global.System.Drawing.Size(128, 41)
			Me.GelButton5.TabIndex = 1817
			Me.GelButton5.UseVisualStyleBackColor = True
			Me.btnExportExcel.Anchor = Global.System.Windows.Forms.AnchorStyles.Top Or Global.System.Windows.Forms.AnchorStyles.Right
			Me.btnExportExcel.BackgroundImage = CType(componentResourceManager.GetObject("btnExportExcel.BackgroundImage"), Global.System.Drawing.Image)
			Me.btnExportExcel.BackgroundImageLayout = Global.System.Windows.Forms.ImageLayout.Stretch
			Me.btnExportExcel.FlatAppearance.BorderSize = 0
			Me.btnExportExcel.FlatStyle = Global.System.Windows.Forms.FlatStyle.Flat
			Me.btnExportExcel.Location = New Global.System.Drawing.Point(273, 3)
			Me.btnExportExcel.Name = "btnExportExcel"
			Me.btnExportExcel.Size = New Global.System.Drawing.Size(128, 41)
			Me.btnExportExcel.TabIndex = 1819
			Me.btnExportExcel.UseVisualStyleBackColor = True
			Me.GelButton6.Anchor = Global.System.Windows.Forms.AnchorStyles.Top Or Global.System.Windows.Forms.AnchorStyles.Right
			Me.GelButton6.BackgroundImage = CType(componentResourceManager.GetObject("GelButton6.BackgroundImage"), Global.System.Drawing.Image)
			Me.GelButton6.BackgroundImageLayout = Global.System.Windows.Forms.ImageLayout.Stretch
			Me.GelButton6.FlatAppearance.BorderSize = 0
			Me.GelButton6.FlatStyle = Global.System.Windows.Forms.FlatStyle.Flat
			Me.GelButton6.Location = New Global.System.Drawing.Point(143, 53)
			Me.GelButton6.Name = "GelButton6"
			Me.GelButton6.Size = New Global.System.Drawing.Size(128, 41)
			Me.GelButton6.TabIndex = 1818
			Me.GelButton6.UseVisualStyleBackColor = True
			Me.Button16.Anchor = Global.System.Windows.Forms.AnchorStyles.Top Or Global.System.Windows.Forms.AnchorStyles.Right
			Me.Button16.BackgroundImage = CType(componentResourceManager.GetObject("Button16.BackgroundImage"), Global.System.Drawing.Image)
			Me.Button16.BackgroundImageLayout = Global.System.Windows.Forms.ImageLayout.Stretch
			Me.Button16.FlatAppearance.BorderSize = 0
			Me.Button16.FlatStyle = Global.System.Windows.Forms.FlatStyle.Flat
			Me.Button16.Location = New Global.System.Drawing.Point(9, 3)
			Me.Button16.Name = "Button16"
			Me.Button16.Size = New Global.System.Drawing.Size(128, 41)
			Me.Button16.TabIndex = 1816
			Me.Button16.UseVisualStyleBackColor = True
			Me.btnProductSeting.Anchor = Global.System.Windows.Forms.AnchorStyles.Top Or Global.System.Windows.Forms.AnchorStyles.Right
			Me.btnProductSeting.BackgroundImage = CType(componentResourceManager.GetObject("btnProductSeting.BackgroundImage"), Global.System.Drawing.Image)
			Me.btnProductSeting.BackgroundImageLayout = Global.System.Windows.Forms.ImageLayout.Stretch
			Me.btnProductSeting.FlatAppearance.BorderSize = 0
			Me.btnProductSeting.FlatStyle = Global.System.Windows.Forms.FlatStyle.Flat
			Me.btnProductSeting.Location = New Global.System.Drawing.Point(143, 3)
			Me.btnProductSeting.Name = "btnProductSeting"
			Me.btnProductSeting.Size = New Global.System.Drawing.Size(128, 41)
			Me.btnProductSeting.TabIndex = 1818
			Me.btnProductSeting.UseVisualStyleBackColor = True
			dataGridViewCellStyle17.BackColor = Global.System.Drawing.Color.FloralWhite
			dataGridViewCellStyle17.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 12F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			Me.DataGridView1.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle17
			Me.DataGridView1.Anchor = Global.System.Windows.Forms.AnchorStyles.Top Or Global.System.Windows.Forms.AnchorStyles.Bottom Or Global.System.Windows.Forms.AnchorStyles.Left Or Global.System.Windows.Forms.AnchorStyles.Right
			Me.DataGridView1.AutoSizeColumnsMode = Global.System.Windows.Forms.DataGridViewAutoSizeColumnsMode.DisplayedCells
			Me.DataGridView1.BackgroundColor = Global.System.Drawing.Color.FromArgb(229, 233, 219)
			Me.DataGridView1.ColumnHeadersBorderStyle = Global.System.Windows.Forms.DataGridViewHeaderBorderStyle.[Single]
			dataGridViewCellStyle18.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter
			dataGridViewCellStyle18.BackColor = Global.System.Drawing.Color.FromArgb(238, 238, 242)
			dataGridViewCellStyle18.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 12F, Global.System.Drawing.FontStyle.Bold, Global.System.Drawing.GraphicsUnit.Point, 0)
			dataGridViewCellStyle18.ForeColor = Global.System.Drawing.Color.Black
			dataGridViewCellStyle18.SelectionBackColor = Global.System.Drawing.Color.FromArgb(238, 238, 242)
			dataGridViewCellStyle18.SelectionForeColor = Global.System.Drawing.SystemColors.ControlDarkDark
			dataGridViewCellStyle18.WrapMode = Global.System.Windows.Forms.DataGridViewTriState.[True]
			Me.DataGridView1.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle18
			Me.DataGridView1.ColumnHeadersHeight = 40
			Me.DataGridView1.Columns.AddRange(New Global.System.Windows.Forms.DataGridViewColumn() { Me.DataGridViewTextBoxColumn1, Me.DataGridViewTextBoxColumn26, Me.DataGridViewTextBoxColumn64, Me.DataGridViewTextBoxColumn45, Me.DataGridViewTextBoxColumn48, Me.PCode, Me.ProductName, Me.CatSubCategory, Me.HSNCode, Me.Part_Group, Me.Description, Me.PurchasePrice, Me.Discount, Me.GST, Me.CGST, Me.SGST_UTGST, Me.CESS, Me.PurchaseMainUnit, Me.SalsesUnit, Me.AlterUnit, Me.Conv, Me.MinStock, Me.Active, Me.SaleTaxType, Me.PurchaseTaxType, Me.GDown, Me.Rack, Me.DefQty, Me.OpeningStock, Me.Barcode, Me.MRP, Me.RSPrice, Me.WSPrice, Me.Batch, Me.MfgDate, Me.ExpDate, Me.Size, Me.Colour, Me.IME1, Me.IME2, Me.Kitchen, Me.Photo, Me.Mark_Unmark, Me.DataGridViewButtonColumn6, Me.DataGridViewButtonColumn7, Me.DataGridViewButtonColumn8, Me.variantName })
			Me.DataGridView1.Cursor = Global.System.Windows.Forms.Cursors.Hand
			dataGridViewCellStyle19.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft
			dataGridViewCellStyle19.BackColor = Global.System.Drawing.SystemColors.Window
			dataGridViewCellStyle19.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 12F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			dataGridViewCellStyle19.ForeColor = Global.System.Drawing.SystemColors.ControlText
			dataGridViewCellStyle19.SelectionBackColor = Global.System.Drawing.SystemColors.Highlight
			dataGridViewCellStyle19.SelectionForeColor = Global.System.Drawing.SystemColors.HighlightText
			dataGridViewCellStyle19.WrapMode = Global.System.Windows.Forms.DataGridViewTriState.[False]
			Me.DataGridView1.DefaultCellStyle = dataGridViewCellStyle19
			Me.DataGridView1.EnableHeadersVisualStyles = False
			Me.DataGridView1.GridColor = Global.System.Drawing.Color.FromArgb(229, 233, 219)
			Me.DataGridView1.Location = New Global.System.Drawing.Point(9, 162)
			Me.DataGridView1.MultiSelect = False
			Me.DataGridView1.Name = "DataGridView1"
			Me.DataGridView1.RowHeadersBorderStyle = Global.System.Windows.Forms.DataGridViewHeaderBorderStyle.[Single]
			dataGridViewCellStyle20.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft
			dataGridViewCellStyle20.BackColor = Global.System.Drawing.Color.DarkViolet
			dataGridViewCellStyle20.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 12F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			dataGridViewCellStyle20.ForeColor = Global.System.Drawing.Color.White
			dataGridViewCellStyle20.SelectionBackColor = Global.System.Drawing.Color.OrangeRed
			dataGridViewCellStyle20.SelectionForeColor = Global.System.Drawing.Color.White
			dataGridViewCellStyle20.WrapMode = Global.System.Windows.Forms.DataGridViewTriState.[True]
			Me.DataGridView1.RowHeadersDefaultCellStyle = dataGridViewCellStyle20
			Me.DataGridView1.RowHeadersWidth = 15
			Me.DataGridView1.RowHeadersWidthSizeMode = Global.System.Windows.Forms.DataGridViewRowHeadersWidthSizeMode.DisableResizing
			dataGridViewCellStyle21.BackColor = Global.System.Drawing.Color.White
			dataGridViewCellStyle21.Font = New Global.System.Drawing.Font("Tahoma", 12F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			dataGridViewCellStyle21.SelectionBackColor = Global.System.Drawing.Color.DarkSlateGray
			dataGridViewCellStyle21.SelectionForeColor = Global.System.Drawing.Color.White
			Me.DataGridView1.RowsDefaultCellStyle = dataGridViewCellStyle21
			Me.DataGridView1.RowTemplate.Height = 30
			Me.DataGridView1.RowTemplate.Resizable = Global.System.Windows.Forms.DataGridViewTriState.[False]
			Me.DataGridView1.SelectionMode = Global.System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect
			Me.DataGridView1.Size = New Global.System.Drawing.Size(1403, 550)
			Me.DataGridView1.TabIndex = 1842
			Me.DataGridView1.TabStop = False
			Me.DataGridViewTextBoxColumn1.DataPropertyName = "PID"
			Me.DataGridViewTextBoxColumn1.HeaderText = "PID"
			Me.DataGridViewTextBoxColumn1.Name = "DataGridViewTextBoxColumn1"
			Me.DataGridViewTextBoxColumn1.Visible = False
			Me.DataGridViewTextBoxColumn1.Width = 64
			Me.DataGridViewTextBoxColumn26.HeaderText = "SubCategoryID"
			Me.DataGridViewTextBoxColumn26.Name = "DataGridViewTextBoxColumn26"
			Me.DataGridViewTextBoxColumn26.Visible = False
			Me.DataGridViewTextBoxColumn26.Width = 157
			Me.DataGridViewTextBoxColumn64.HeaderText = "variant_id"
			Me.DataGridViewTextBoxColumn64.Name = "DataGridViewTextBoxColumn64"
			Me.DataGridViewTextBoxColumn64.Visible = False
			Me.DataGridViewTextBoxColumn64.Width = 112
			Me.DataGridViewTextBoxColumn45.DataPropertyName = "OpeningStock"
			Me.DataGridViewTextBoxColumn45.HeaderText = "Opening Stock"
			Me.DataGridViewTextBoxColumn45.Name = "DataGridViewTextBoxColumn45"
			Me.DataGridViewTextBoxColumn45.Visible = False
			Me.DataGridViewTextBoxColumn45.Width = 152
			Me.DataGridViewTextBoxColumn48.DataPropertyName = "MRP"
			Me.DataGridViewTextBoxColumn48.HeaderText = "MRP"
			Me.DataGridViewTextBoxColumn48.Name = "DataGridViewTextBoxColumn48"
			Me.DataGridViewTextBoxColumn48.Visible = False
			Me.DataGridViewTextBoxColumn48.Width = 72
			Me.PCode.DataPropertyName = "ProductCode"
			Me.PCode.FillWeight = 347.1696F
			Me.PCode.HeaderText = "P-Code"
			Me.PCode.Name = "PCode"
			Me.PCode.[ReadOnly] = True
			Me.PCode.Width = 92
			Me.ProductName.DataPropertyName = "ProductName"
			Me.ProductName.FillWeight = 740.0392F
			Me.ProductName.HeaderText = "Product Name"
			Me.ProductName.Name = "ProductName"
			Me.ProductName.Resizable = Global.System.Windows.Forms.DataGridViewTriState.[True]
			Me.ProductName.Width = 146
			Me.CatSubCategory.HeaderText = "Cat , Sub Category"
			Me.CatSubCategory.Name = "CatSubCategory"
			Me.CatSubCategory.[ReadOnly] = True
			Me.CatSubCategory.Width = 185
			Me.HSNCode.DataPropertyName = "HSNCode"
			Me.HSNCode.FillWeight = 219.0145F
			Me.HSNCode.HeaderText = "HSN Code"
			Me.HSNCode.Name = "HSNCode"
			Me.HSNCode.Width = 117
			Me.Part_Group.DataPropertyName = "PartNo"
			Me.Part_Group.FillWeight = 203.019F
			Me.Part_Group.HeaderText = "Part / Group"
			Me.Part_Group.Name = "Part_Group"
			Me.Part_Group.Width = 131
			Me.Description.DataPropertyName = "Description"
			dataGridViewCellStyle22.WrapMode = Global.System.Windows.Forms.DataGridViewTriState.[False]
			Me.Description.DefaultCellStyle = dataGridViewCellStyle22
			Me.Description.FillWeight = 314.3774F
			Me.Description.HeaderText = "Description"
			Me.Description.Name = "Description"
			Me.Description.Width = 124
			Me.PurchasePrice.DataPropertyName = "CostPrice"
			Me.PurchasePrice.FillWeight = 165.0521F
			Me.PurchasePrice.HeaderText = "Purchase Price"
			Me.PurchasePrice.Name = "PurchasePrice"
			Me.PurchasePrice.Width = 153
			Me.Discount.DataPropertyName = "Discount"
			Me.Discount.FillWeight = 153.1596F
			Me.Discount.HeaderText = "Discount %"
			Me.Discount.Name = "Discount"
			Me.Discount.Width = 124
			Me.GST.DataPropertyName = "cmbGST"
			Me.GST.FillWeight = 142.034F
			Me.GST.HeaderText = "GSt %"
			Me.GST.Name = "GST"
			Me.GST.Resizable = Global.System.Windows.Forms.DataGridViewTriState.[True]
			Me.GST.SortMode = Global.System.Windows.Forms.DataGridViewColumnSortMode.NotSortable
			Me.GST.Width = 66
			Me.CGST.DataPropertyName = "CGST"
			Me.CGST.FillWeight = 128.7334F
			Me.CGST.HeaderText = "CGST %"
			Me.CGST.Name = "CGST"
			Me.CGST.[ReadOnly] = True
			Me.CGST.Width = 101
			Me.SGST_UTGST.DataPropertyName = "SGST"
			Me.SGST_UTGST.FillWeight = 119.3519F
			Me.SGST_UTGST.HeaderText = "SGST/UTGST %"
			Me.SGST_UTGST.Name = "SGST_UTGST"
			Me.SGST_UTGST.[ReadOnly] = True
			Me.SGST_UTGST.Width = 165
			Me.CESS.DataPropertyName = "Cess"
			Me.CESS.FillWeight = 102.7636F
			Me.CESS.HeaderText = "CESS %"
			Me.CESS.Name = "CESS"
			Me.CESS.Width = 101
			Me.PurchaseMainUnit.DataPropertyName = "PurchaseUnit"
			dataGridViewCellStyle23.Padding = New Global.System.Windows.Forms.Padding(2)
			Me.PurchaseMainUnit.DefaultCellStyle = dataGridViewCellStyle23
			Me.PurchaseMainUnit.FillWeight = 95.29082F
			Me.PurchaseMainUnit.HeaderText = "Purchase Main Unit"
			Me.PurchaseMainUnit.Name = "PurchaseMainUnit"
			Me.PurchaseMainUnit.Resizable = Global.System.Windows.Forms.DataGridViewTriState.[True]
			Me.PurchaseMainUnit.SortMode = Global.System.Windows.Forms.DataGridViewColumnSortMode.NotSortable
			Me.PurchaseMainUnit.Width = 170
			Me.SalsesUnit.DataPropertyName = "SalesUnit"
			dataGridViewCellStyle24.Padding = New Global.System.Windows.Forms.Padding(2)
			Me.SalsesUnit.DefaultCellStyle = dataGridViewCellStyle24
			Me.SalsesUnit.FillWeight = 88.42116F
			Me.SalsesUnit.HeaderText = "Sales Unit"
			Me.SalsesUnit.Name = "SalsesUnit"
			Me.SalsesUnit.Resizable = Global.System.Windows.Forms.DataGridViewTriState.[True]
			Me.SalsesUnit.SortMode = Global.System.Windows.Forms.DataGridViewColumnSortMode.NotSortable
			Me.SalsesUnit.Width = 97
			Me.AlterUnit.DataPropertyName = "SalesAltUnit"
			dataGridViewCellStyle25.Padding = New Global.System.Windows.Forms.Padding(2)
			Me.AlterUnit.DefaultCellStyle = dataGridViewCellStyle25
			Me.AlterUnit.FillWeight = 81.96306F
			Me.AlterUnit.HeaderText = "Alter Unit"
			Me.AlterUnit.Name = "AlterUnit"
			Me.AlterUnit.Resizable = Global.System.Windows.Forms.DataGridViewTriState.[True]
			Me.AlterUnit.SortMode = Global.System.Windows.Forms.DataGridViewColumnSortMode.NotSortable
			Me.AlterUnit.Width = 90
			Me.Conv.DataPropertyName = "Conv"
			Me.Conv.FillWeight = 75.9705F
			Me.Conv.HeaderText = "Conversion Value"
			Me.Conv.Name = "Conv"
			Me.Conv.Width = 173
			Me.MinStock.DataPropertyName = "MinStock"
			Me.MinStock.FillWeight = 70.63207F
			Me.MinStock.HeaderText = "Min Stock"
			Me.MinStock.Name = "MinStock"
			Me.MinStock.Width = 112
			Me.Active.DataPropertyName = "Status"
			Me.Active.HeaderText = "Active"
			Me.Active.Name = "Active"
			Me.Active.Width = 82
			Me.SaleTaxType.DataPropertyName = "STax"
			dataGridViewCellStyle26.Padding = New Global.System.Windows.Forms.Padding(2)
			Me.SaleTaxType.DefaultCellStyle = dataGridViewCellStyle26
			Me.SaleTaxType.FillWeight = 65.55757F
			Me.SaleTaxType.HeaderText = "Sale Tax Type"
			Me.SaleTaxType.Name = "SaleTaxType"
			Me.SaleTaxType.Resizable = Global.System.Windows.Forms.DataGridViewTriState.[True]
			Me.SaleTaxType.SortMode = Global.System.Windows.Forms.DataGridViewColumnSortMode.NotSortable
			Me.SaleTaxType.Width = 126
			Me.PurchaseTaxType.DataPropertyName = "PTax"
			dataGridViewCellStyle27.Padding = New Global.System.Windows.Forms.Padding(2)
			Me.PurchaseTaxType.DefaultCellStyle = dataGridViewCellStyle27
			Me.PurchaseTaxType.FillWeight = 60.8552F
			Me.PurchaseTaxType.HeaderText = "Purchase Tax Type"
			Me.PurchaseTaxType.Name = "PurchaseTaxType"
			Me.PurchaseTaxType.Resizable = Global.System.Windows.Forms.DataGridViewTriState.[True]
			Me.PurchaseTaxType.SortMode = Global.System.Windows.Forms.DataGridViewColumnSortMode.NotSortable
			Me.PurchaseTaxType.Width = 165
			Me.GDown.DataPropertyName = "GDown"
			Me.GDown.FillWeight = 56.49738F
			Me.GDown.HeaderText = "Godown"
			Me.GDown.Name = "GDown"
			Me.GDown.Resizable = Global.System.Windows.Forms.DataGridViewTriState.[True]
			Me.GDown.SortMode = Global.System.Windows.Forms.DataGridViewColumnSortMode.NotSortable
			Me.GDown.Width = 80
			Me.Rack.DataPropertyName = "Rack"
			Me.Rack.FillWeight = 52.39393F
			Me.Rack.HeaderText = "Rack"
			Me.Rack.Name = "Rack"
			Me.Rack.Resizable = Global.System.Windows.Forms.DataGridViewTriState.[True]
			Me.Rack.SortMode = Global.System.Windows.Forms.DataGridViewColumnSortMode.NotSortable
			Me.Rack.Width = 55
			Me.DefQty.DataPropertyName = "DefQty"
			Me.DefQty.FillWeight = 48.55701F
			Me.DefQty.HeaderText = "Default Sale Qty"
			Me.DefQty.Name = "DefQty"
			Me.DefQty.Width = 165
			Me.OpeningStock.DataPropertyName = "Qty"
			Me.OpeningStock.FillWeight = 45.14423F
			Me.OpeningStock.HeaderText = "Opening Qty"
			Me.OpeningStock.Name = "OpeningStock"
			Me.OpeningStock.Width = 132
			Me.Barcode.DataPropertyName = "Barcode"
			Me.Barcode.FillWeight = 42.00196F
			Me.Barcode.HeaderText = "Barcode"
			Me.Barcode.Name = "Barcode"
			Me.MRP.DataPropertyName = "MRP"
			Me.MRP.FillWeight = 39.02098F
			Me.MRP.HeaderText = "MRP"
			Me.MRP.Name = "MRP"
			Me.MRP.Width = 71
			Me.RSPrice.DataPropertyName = "SalePrice"
			Me.RSPrice.FillWeight = 36.21695F
			Me.RSPrice.HeaderText = "Retail Sale Price"
			Me.RSPrice.Name = "RSPrice"
			Me.RSPrice.Width = 166
			Me.WSPrice.DataPropertyName = "WSalePrice"
			Me.WSPrice.FillWeight = 33.7336F
			Me.WSPrice.HeaderText = "Wholesale Sale Price"
			Me.WSPrice.Name = "WSPrice"
			Me.WSPrice.Width = 202
			Me.Batch.DataPropertyName = "Batch"
			Me.Batch.FillWeight = 31.42084F
			Me.Batch.HeaderText = "Batch"
			Me.Batch.Name = "Batch"
			Me.Batch.Width = 80
			Me.MfgDate.DataPropertyName = "Mfgdate"
			Me.MfgDate.FillWeight = 29.18063F
			Me.MfgDate.HeaderText = "Mfg Date"
			Me.MfgDate.Name = "MfgDate"
			Me.MfgDate.Width = 107
			Me.ExpDate.DataPropertyName = "ExpDate"
			Me.ExpDate.FillWeight = 27.12789F
			Me.ExpDate.HeaderText = "Exp Date"
			Me.ExpDate.Name = "ExpDate"
			Me.ExpDate.Width = 107
			Me.Size.DataPropertyName = "Size"
			Me.Size.FillWeight = 25.22529F
			Me.Size.HeaderText = "Size"
			Me.Size.Name = "Size"
			Me.Size.Resizable = Global.System.Windows.Forms.DataGridViewTriState.[True]
			Me.Size.SortMode = Global.System.Windows.Forms.DataGridViewColumnSortMode.NotSortable
			Me.Size.Width = 49
			Me.Colour.DataPropertyName = "Colour"
			Me.Colour.FillWeight = 23.40078F
			Me.Colour.HeaderText = "Colour"
			Me.Colour.Name = "Colour"
			Me.Colour.Resizable = Global.System.Windows.Forms.DataGridViewTriState.[True]
			Me.Colour.SortMode = Global.System.Windows.Forms.DataGridViewColumnSortMode.NotSortable
			Me.Colour.Width = 66
			Me.IME1.DataPropertyName = "IMEI1"
			Me.IME1.FillWeight = 21.71936F
			Me.IME1.HeaderText = "IME1"
			Me.IME1.Name = "IME1"
			Me.IME1.Width = 75
			Me.IME2.DataPropertyName = "IMEI2"
			Me.IME2.FillWeight = 20.19191F
			Me.IME2.HeaderText = "IME2"
			Me.IME2.Name = "IME2"
			Me.IME2.Width = 75
			Me.Kitchen.DataPropertyName = "Kitchen"
			Me.Kitchen.HeaderText = "Kitchen"
			Me.Kitchen.Name = "Kitchen"
			Me.Kitchen.Width = 93
			Me.Photo.DataPropertyName = "Photo"
			Me.Photo.FillWeight = 18.77747F
			Me.Photo.HeaderText = "Photo"
			Me.Photo.Image = CType(componentResourceManager.GetObject("Photo.Image"), Global.System.Drawing.Image)
			Me.Photo.ImageLayout = Global.System.Windows.Forms.DataGridViewImageCellLayout.Zoom
			Me.Photo.Name = "Photo"
			Me.Photo.Width = 61
			Me.Mark_Unmark.DataPropertyName = "Mark"
			Me.Mark_Unmark.FillWeight = 14.30449F
			Me.Mark_Unmark.HeaderText = "Mark / Unmark"
			Me.Mark_Unmark.Name = "Mark_Unmark"
			Me.Mark_Unmark.Visible = False
			Me.Mark_Unmark.Width = 131
			Me.DataGridViewButtonColumn6.DataPropertyName = "UpdateButtonColumn"
			Me.DataGridViewButtonColumn6.FillWeight = 12.39162F
			Me.DataGridViewButtonColumn6.HeaderText = "Save/Update"
			Me.DataGridViewButtonColumn6.Name = "DataGridViewButtonColumn6"
			Me.DataGridViewButtonColumn6.Text = ""
			Me.DataGridViewButtonColumn6.Width = 118
			Me.DataGridViewButtonColumn7.DataPropertyName = "DeleteButtonColumn"
			Me.DataGridViewButtonColumn7.FillWeight = 11.75682F
			Me.DataGridViewButtonColumn7.HeaderText = "Delete"
			Me.DataGridViewButtonColumn7.Name = "DataGridViewButtonColumn7"
			Me.DataGridViewButtonColumn7.Text = "Delete"
			Me.DataGridViewButtonColumn7.UseColumnTextForButtonValue = True
			Me.DataGridViewButtonColumn7.Width = 67
			Me.DataGridViewButtonColumn8.DataPropertyName = "PrintBarcodeButton"
			Me.DataGridViewButtonColumn8.FillWeight = 11.15153F
			Me.DataGridViewButtonColumn8.HeaderText = "Print"
			Me.DataGridViewButtonColumn8.Name = "DataGridViewButtonColumn8"
			Me.DataGridViewButtonColumn8.Text = "Barcode"
			Me.DataGridViewButtonColumn8.UseColumnTextForButtonValue = True
			Me.DataGridViewButtonColumn8.Visible = False
			Me.DataGridViewButtonColumn8.Width = 52
			Me.variantName.DataPropertyName = "variantName"
			Me.variantName.FillWeight = 13.5023F
			Me.variantName.HeaderText = "Variant"
			Me.variantName.Name = "variantName"
			Me.variantName.Text = "Variant"
			Me.variantName.UseColumnTextForButtonValue = True
			Me.variantName.Visible = False
			Me.variantName.Width = 73
			Me.Panel4.BackColor = Global.System.Drawing.Color.FromArgb(238, 238, 242)
			Me.Panel4.Controls.Add(Me.PictureBox1)
			Me.Panel4.Controls.Add(Me.Label17)
			Me.Panel4.Dock = Global.System.Windows.Forms.DockStyle.Top
			Me.Panel4.Location = New Global.System.Drawing.Point(0, 0)
			Me.Panel4.Name = "Panel4"
			Me.Panel4.Size = New Global.System.Drawing.Size(1426, 51)
			Me.Panel4.TabIndex = 1818
			Me.PictureBox1.Location = New Global.System.Drawing.Point(4, 10)
			Me.PictureBox1.Name = "PictureBox1"
			Me.PictureBox1.Size = New Global.System.Drawing.Size(44, 30)
			Me.PictureBox1.TabIndex = 51
			Me.PictureBox1.TabStop = False
			Me.Label17.BackColor = Global.System.Drawing.Color.FromArgb(238, 238, 242)
			Me.Label17.Font = New Global.System.Drawing.Font("Microsoft Tai Le", 21F, Global.System.Drawing.FontStyle.Bold, Global.System.Drawing.GraphicsUnit.Point, 0)
			Me.Label17.ForeColor = Global.System.Drawing.Color.FromArgb(64, 64, 0)
			Me.Label17.Location = New Global.System.Drawing.Point(39, 8)
			Me.Label17.Name = "Label17"
			Me.Label17.Size = New Global.System.Drawing.Size(287, 35)
			Me.Label17.TabIndex = 50
			Me.Label17.Text = "LIST OF PRODUCTS"
			Me.Label17.TextAlign = Global.System.Drawing.ContentAlignment.MiddleCenter
			Me.DataGridViewImageColumn2.DataPropertyName = "Photo"
			Me.DataGridViewImageColumn2.FillWeight = 27.62098F
			Me.DataGridViewImageColumn2.HeaderText = "Photo"
			Me.DataGridViewImageColumn2.Image = CType(componentResourceManager.GetObject("DataGridViewImageColumn2.Image"), Global.System.Drawing.Image)
			Me.DataGridViewImageColumn2.ImageLayout = Global.System.Windows.Forms.DataGridViewImageCellLayout.Zoom
			Me.DataGridViewImageColumn2.Name = "DataGridViewImageColumn2"
			Me.DataGridViewImageColumn2.Width = 61
			MyBase.AutoScaleDimensions = New Global.System.Drawing.SizeF(6F, 13F)
			MyBase.AutoScaleMode = Global.System.Windows.Forms.AutoScaleMode.Font
			Me.BackColor = Global.System.Drawing.Color.White
			MyBase.ClientSize = New Global.System.Drawing.Size(1426, 737)
			MyBase.Controls.Add(Me.Panel4)
			MyBase.Controls.Add(Me.Panel1)
			MyBase.FormBorderStyle = Global.System.Windows.Forms.FormBorderStyle.FixedSingle
			MyBase.Icon = CType(componentResourceManager.GetObject("$this.Icon"), Global.System.Drawing.Icon)
			MyBase.KeyPreview = True
			MyBase.MaximizeBox = False
			MyBase.Name = "frmProductSmart"
			MyBase.ShowIcon = False
			MyBase.ShowInTaskbar = False
			MyBase.StartPosition = Global.System.Windows.Forms.FormStartPosition.CenterParent
			MyBase.WindowState = Global.System.Windows.Forms.FormWindowState.Maximized
			Me.Panel1.ResumeLayout(False)
			Me.Panel1.PerformLayout()
			Me.pnlVariant.ResumeLayout(False)
			Me.pnlVariant.PerformLayout()
			CType(Me.DataGridView2, Global.System.ComponentModel.ISupportInitialize).EndInit()
			Me.Panel7.ResumeLayout(False)
			Me.Panel7.PerformLayout()
			Me.Panel2.ResumeLayout(False)
			Me.Panel2.PerformLayout()
			Me.Panel3.ResumeLayout(False)
			Me.Panel3.PerformLayout()
			CType(Me.Picture, Global.System.ComponentModel.ISupportInitialize).EndInit()
			CType(Me.pbgiftqr, Global.System.ComponentModel.ISupportInitialize).EndInit()
			Me.Panel5.ResumeLayout(False)
			CType(Me.DataGridView1, Global.System.ComponentModel.ISupportInitialize).EndInit()
			Me.Panel4.ResumeLayout(False)
			CType(Me.PictureBox1, Global.System.ComponentModel.ISupportInitialize).EndInit()
			MyBase.ResumeLayout(False)
		End Sub

		' Token: 0x0400074E RID: 1870
		Private components As Global.System.ComponentModel.IContainer
	End Class
End Namespace
