Namespace BillPoint
	' Token: 0x020001FC RID: 508
		Public Partial Class frmStock_Settlement
		Inherits Global.System.Windows.Forms.Form

		' Token: 0x060091B8 RID: 37304 RVA: 0x0069E904 File Offset: 0x0069CB04
		<Global.System.Diagnostics.DebuggerNonUserCode()>
		Protected Overrides Sub Dispose(disposing As Boolean)
			Try
				Dim flag As Boolean = disposing AndAlso Me.components IsNot Nothing
				If flag Then
					Me.components.Dispose()
				End If
			Finally
				MyBase.Dispose(disposing)
			End Try
		End Sub

		' Token: 0x060091B9 RID: 37305 RVA: 0x0069E954 File Offset: 0x0069CB54
		<Global.System.Diagnostics.DebuggerStepThrough()>
		Private Sub InitializeComponent()
			Dim componentResourceManager As Global.System.ComponentModel.ComponentResourceManager = New Global.System.ComponentModel.ComponentResourceManager(GetType(Global.BillPoint.frmStock_Settlement))
			Dim dataGridViewCellStyle As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle2 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle3 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle4 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle5 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle6 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle7 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle8 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle9 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle10 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle11 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle12 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle13 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle14 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle15 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle16 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle17 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle18 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle19 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle20 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle21 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle22 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle23 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle24 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle25 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle26 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle27 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle28 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle29 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle30 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Me.listView1 = New Global.System.Windows.Forms.ListView()
			Me.ColumnHeader1 = New Global.System.Windows.Forms.ColumnHeader()
			Me.ColumnHeader2 = New Global.System.Windows.Forms.ColumnHeader()
			Me.ColumnHeader31 = New Global.System.Windows.Forms.ColumnHeader()
			Me.ColumnHeader3 = New Global.System.Windows.Forms.ColumnHeader()
			Me.ColumnHeader4 = New Global.System.Windows.Forms.ColumnHeader()
			Me.ColumnHeader5 = New Global.System.Windows.Forms.ColumnHeader()
			Me.ColumnHeader6 = New Global.System.Windows.Forms.ColumnHeader()
			Me.ColumnHeader7 = New Global.System.Windows.Forms.ColumnHeader()
			Me.ColumnHeader19 = New Global.System.Windows.Forms.ColumnHeader()
			Me.ColumnHeader8 = New Global.System.Windows.Forms.ColumnHeader()
			Me.ColumnHeader9 = New Global.System.Windows.Forms.ColumnHeader()
			Me.ColumnHeader10 = New Global.System.Windows.Forms.ColumnHeader()
			Me.ColumnHeader11 = New Global.System.Windows.Forms.ColumnHeader()
			Me.ColumnHeader12 = New Global.System.Windows.Forms.ColumnHeader()
			Me.ColumnHeader13 = New Global.System.Windows.Forms.ColumnHeader()
			Me.ColumnHeader15 = New Global.System.Windows.Forms.ColumnHeader()
			Me.ColumnHeader16 = New Global.System.Windows.Forms.ColumnHeader()
			Me.ColumnHeader17 = New Global.System.Windows.Forms.ColumnHeader()
			Me.ColumnHeader18 = New Global.System.Windows.Forms.ColumnHeader()
			Me.ColumnHeader14 = New Global.System.Windows.Forms.ColumnHeader()
			Me.ColumnHeader20 = New Global.System.Windows.Forms.ColumnHeader()
			Me.ColumnHeader21 = New Global.System.Windows.Forms.ColumnHeader()
			Me.ColumnHeader22 = New Global.System.Windows.Forms.ColumnHeader()
			Me.ColumnHeader23 = New Global.System.Windows.Forms.ColumnHeader()
			Me.ColumnHeader24 = New Global.System.Windows.Forms.ColumnHeader()
			Me.ColumnHeader25 = New Global.System.Windows.Forms.ColumnHeader()
			Me.ColumnHeader26 = New Global.System.Windows.Forms.ColumnHeader()
			Me.ColumnHeader27 = New Global.System.Windows.Forms.ColumnHeader()
			Me.ColumnHeader28 = New Global.System.Windows.Forms.ColumnHeader()
			Me.ColumnHeader29 = New Global.System.Windows.Forms.ColumnHeader()
			Me.ColumnHeader30 = New Global.System.Windows.Forms.ColumnHeader()
			Me.ColumnHeader32 = New Global.System.Windows.Forms.ColumnHeader()
			Me.ColumnHeader33 = New Global.System.Windows.Forms.ColumnHeader()
			Me.ColumnHeader34 = New Global.System.Windows.Forms.ColumnHeader()
			Me.ColumnHeader35 = New Global.System.Windows.Forms.ColumnHeader()
			Me.ColumnHeader36 = New Global.System.Windows.Forms.ColumnHeader()
			Me.ColumnHeader37 = New Global.System.Windows.Forms.ColumnHeader()
			Me.ColumnHeader38 = New Global.System.Windows.Forms.ColumnHeader()
			Me.ColumnHeader40 = New Global.System.Windows.Forms.ColumnHeader()
			Me.ColumnHeader41 = New Global.System.Windows.Forms.ColumnHeader()
			Me.btnDToken = New Global.GelButtons.GelButton()
			Me.GroupBox5 = New Global.System.Windows.Forms.GroupBox()
			Me.txtFrom_company_id = New Global.System.Windows.Forms.TextBox()
			Me.txtProductCode = New Global.System.Windows.Forms.TextBox()
			Me.txtID1 = New Global.System.Windows.Forms.TextBox()
			Me.TextBox2 = New Global.System.Windows.Forms.TextBox()
			Me.TextBox1 = New Global.System.Windows.Forms.TextBox()
			Me.txtID = New Global.System.Windows.Forms.TextBox()
			Me.lblUserType = New Global.System.Windows.Forms.Label()
			Me.lblUser = New Global.System.Windows.Forms.Label()
			Me.txtCompany_to = New Global.System.Windows.Forms.TextBox()
			Me.txtCompany_id_from = New Global.System.Windows.Forms.TextBox()
			Me.Label136 = New Global.System.Windows.Forms.Label()
			Me.Label135 = New Global.System.Windows.Forms.Label()
			Me.cmbToCompany = New Global.System.Windows.Forms.ComboBox()
			Me.DataGridView1 = New Global.System.Windows.Forms.DataGridView()
			Me.Column1 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column2 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column3 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column7 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column4 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column5 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn1 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column17 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn2 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column9 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column10 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column11 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column12 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column13 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column14 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn3 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column6 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column18 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column19 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column22 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column25 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column26 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column27 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column28 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column30 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column31 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column32 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column33 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column35 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column36 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column37 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column38 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column39 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column40 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column41 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column42 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column52 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column53 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column54 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column55 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column56 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column57 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column58 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.pbgiftqr = New Global.System.Windows.Forms.PictureBox()
			Me.Picture = New Global.System.Windows.Forms.PictureBox()
			Me.GroupBox5.SuspendLayout()
			CType(Me.DataGridView1, Global.System.ComponentModel.ISupportInitialize).BeginInit()
			CType(Me.pbgiftqr, Global.System.ComponentModel.ISupportInitialize).BeginInit()
			CType(Me.Picture, Global.System.ComponentModel.ISupportInitialize).BeginInit()
			MyBase.SuspendLayout()
			Me.listView1.Anchor = Global.System.Windows.Forms.AnchorStyles.Top Or Global.System.Windows.Forms.AnchorStyles.Bottom Or Global.System.Windows.Forms.AnchorStyles.Left Or Global.System.Windows.Forms.AnchorStyles.Right
			Me.listView1.BackColor = Global.System.Drawing.Color.FromArgb(255, 255, 128)
			Me.listView1.CheckBoxes = True
			Me.listView1.Columns.AddRange(New Global.System.Windows.Forms.ColumnHeader() { Me.ColumnHeader1, Me.ColumnHeader2, Me.ColumnHeader31, Me.ColumnHeader3, Me.ColumnHeader4, Me.ColumnHeader5, Me.ColumnHeader6, Me.ColumnHeader7, Me.ColumnHeader19, Me.ColumnHeader8, Me.ColumnHeader9, Me.ColumnHeader10, Me.ColumnHeader11, Me.ColumnHeader12, Me.ColumnHeader13, Me.ColumnHeader15, Me.ColumnHeader16, Me.ColumnHeader17, Me.ColumnHeader18, Me.ColumnHeader14, Me.ColumnHeader20, Me.ColumnHeader21, Me.ColumnHeader22, Me.ColumnHeader23, Me.ColumnHeader24, Me.ColumnHeader25, Me.ColumnHeader26, Me.ColumnHeader27, Me.ColumnHeader28, Me.ColumnHeader29, Me.ColumnHeader30, Me.ColumnHeader32, Me.ColumnHeader33, Me.ColumnHeader34, Me.ColumnHeader35, Me.ColumnHeader36, Me.ColumnHeader37, Me.ColumnHeader38, Me.ColumnHeader40, Me.ColumnHeader41 })
			Me.listView1.Cursor = Global.System.Windows.Forms.Cursors.Hand
			Me.listView1.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 9F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			Me.listView1.FullRowSelect = True
			Me.listView1.GridLines = True
			Me.listView1.HeaderStyle = Global.System.Windows.Forms.ColumnHeaderStyle.Nonclickable
			Me.listView1.HideSelection = False
			Me.listView1.Location = New Global.System.Drawing.Point(7, 126)
			Me.listView1.MultiSelect = False
			Me.listView1.Name = "listView1"
			Me.listView1.Size = New Global.System.Drawing.Size(782, 312)
			Me.listView1.TabIndex = 575
			Me.listView1.TabStop = False
			Me.listView1.UseCompatibleStateImageBehavior = False
			Me.listView1.View = Global.System.Windows.Forms.View.Details
			Me.ColumnHeader1.Text = "ID"
			Me.ColumnHeader2.Text = "Product Code"
			Me.ColumnHeader2.Width = 100
			Me.ColumnHeader31.Text = "Barcode"
			Me.ColumnHeader31.Width = 100
			Me.ColumnHeader3.Text = "Product Name"
			Me.ColumnHeader3.Width = 200
			Me.ColumnHeader4.Text = "HSNC"
			Me.ColumnHeader4.Width = 80
			Me.ColumnHeader5.Text = "Part/Group"
			Me.ColumnHeader5.Width = 80
			Me.ColumnHeader6.Text = "Description"
			Me.ColumnHeader6.Width = 100
			Me.ColumnHeader7.Text = "Purchase Price"
			Me.ColumnHeader7.TextAlign = Global.System.Windows.Forms.HorizontalAlignment.Right
			Me.ColumnHeader7.Width = 100
			Me.ColumnHeader19.Text = "MRP"
			Me.ColumnHeader19.TextAlign = Global.System.Windows.Forms.HorizontalAlignment.Right
			Me.ColumnHeader19.Width = 100
			Me.ColumnHeader8.Text = "R.Sale Price"
			Me.ColumnHeader8.TextAlign = Global.System.Windows.Forms.HorizontalAlignment.Right
			Me.ColumnHeader8.Width = 100
			Me.ColumnHeader9.Text = "W.Sale Price"
			Me.ColumnHeader9.TextAlign = Global.System.Windows.Forms.HorizontalAlignment.Right
			Me.ColumnHeader9.Width = 100
			Me.ColumnHeader10.Text = "Disc%"
			Me.ColumnHeader10.TextAlign = Global.System.Windows.Forms.HorizontalAlignment.Center
			Me.ColumnHeader10.Width = 100
			Me.ColumnHeader11.Text = "CGST%"
			Me.ColumnHeader11.TextAlign = Global.System.Windows.Forms.HorizontalAlignment.Center
			Me.ColumnHeader11.Width = 100
			Me.ColumnHeader12.Text = "SGST%"
			Me.ColumnHeader12.TextAlign = Global.System.Windows.Forms.HorizontalAlignment.Center
			Me.ColumnHeader12.Width = 100
			Me.ColumnHeader13.Text = "CESS%"
			Me.ColumnHeader13.TextAlign = Global.System.Windows.Forms.HorizontalAlignment.Center
			Me.ColumnHeader13.Width = 100
			Me.ColumnHeader15.Text = "Purchase Unit"
			Me.ColumnHeader15.TextAlign = Global.System.Windows.Forms.HorizontalAlignment.Center
			Me.ColumnHeader15.Width = 100
			Me.ColumnHeader16.Text = "Sale Unit"
			Me.ColumnHeader16.TextAlign = Global.System.Windows.Forms.HorizontalAlignment.Center
			Me.ColumnHeader16.Width = 100
			Me.ColumnHeader17.Text = "Alter Unit"
			Me.ColumnHeader17.TextAlign = Global.System.Windows.Forms.HorizontalAlignment.Center
			Me.ColumnHeader17.Width = 100
			Me.ColumnHeader18.Text = "Con Value"
			Me.ColumnHeader18.TextAlign = Global.System.Windows.Forms.HorizontalAlignment.Center
			Me.ColumnHeader18.Width = 80
			Me.ColumnHeader14.Text = "Minimum Stock"
			Me.ColumnHeader14.TextAlign = Global.System.Windows.Forms.HorizontalAlignment.Right
			Me.ColumnHeader14.Width = 100
			Me.ColumnHeader20.Text = "Godown"
			Me.ColumnHeader20.Width = 120
			Me.ColumnHeader21.Text = "Rack"
			Me.ColumnHeader21.Width = 100
			Me.ColumnHeader22.Text = "Def Sale Qty"
			Me.ColumnHeader22.Width = 80
			Me.ColumnHeader23.Text = "OS_Purchase Price"
			Me.ColumnHeader23.TextAlign = Global.System.Windows.Forms.HorizontalAlignment.Right
			Me.ColumnHeader23.Width = 100
			Me.ColumnHeader24.Text = "OS_MRP"
			Me.ColumnHeader24.TextAlign = Global.System.Windows.Forms.HorizontalAlignment.Right
			Me.ColumnHeader24.Width = 130
			Me.ColumnHeader25.Text = "OS_R.Sale Price"
			Me.ColumnHeader25.TextAlign = Global.System.Windows.Forms.HorizontalAlignment.Right
			Me.ColumnHeader25.Width = 130
			Me.ColumnHeader26.Text = "OS_W.Sale Price"
			Me.ColumnHeader26.TextAlign = Global.System.Windows.Forms.HorizontalAlignment.Right
			Me.ColumnHeader26.Width = 130
			Me.ColumnHeader27.Text = "Batch"
			Me.ColumnHeader27.Width = 100
			Me.ColumnHeader28.Text = "Mfg Date"
			Me.ColumnHeader28.Width = 100
			Me.ColumnHeader29.Text = "Exp Date"
			Me.ColumnHeader29.Width = 100
			Me.ColumnHeader30.Text = "Colour"
			Me.ColumnHeader30.Width = 100
			Me.ColumnHeader32.Text = "Size"
			Me.ColumnHeader32.Width = 100
			Me.ColumnHeader33.Text = "IMEI-1"
			Me.ColumnHeader34.Text = "IMEI-2"
			Me.ColumnHeader35.Text = "Active"
			Me.ColumnHeader35.TextAlign = Global.System.Windows.Forms.HorizontalAlignment.Center
			Me.ColumnHeader36.Text = "Qr Code"
			Me.ColumnHeader37.Text = "Transfer Quantity"
			Me.ColumnHeader38.Text = "TokenNo"
			Me.ColumnHeader38.Width = 100
			Me.ColumnHeader40.Text = "Category"
			Me.ColumnHeader41.Text = "SubCategoryName"
			Me.btnDToken.Anchor = Global.System.Windows.Forms.AnchorStyles.Top Or Global.System.Windows.Forms.AnchorStyles.Right
			Me.btnDToken.BackColor = Global.System.Drawing.Color.MediumVioletRed
			Me.btnDToken.FlatAppearance.BorderSize = 0
			Me.btnDToken.FlatStyle = Global.System.Windows.Forms.FlatStyle.Flat
			Me.btnDToken.Font = New Global.System.Drawing.Font("Segoe UI Semibold", 12F, Global.System.Drawing.FontStyle.Bold, Global.System.Drawing.GraphicsUnit.Point, 0)
			Me.btnDToken.ForeColor = Global.System.Drawing.Color.White
			Me.btnDToken.GradientBottom = Global.System.Drawing.Color.Green
			Me.btnDToken.GradientTop = Global.System.Drawing.Color.Green
			Me.btnDToken.Image = CType(componentResourceManager.GetObject("btnDToken.Image"), Global.System.Drawing.Image)
			Me.btnDToken.ImageAlign = Global.System.Drawing.ContentAlignment.MiddleLeft
			Me.btnDToken.Location = New Global.System.Drawing.Point(10, 69)
			Me.btnDToken.Name = "btnDToken"
			Me.btnDToken.Size = New Global.System.Drawing.Size(187, 38)
			Me.btnDToken.TabIndex = 580
			Me.btnDToken.Text = "&Settlement Stock"
			Me.btnDToken.TextAlign = Global.System.Drawing.ContentAlignment.MiddleRight
			Me.btnDToken.UseVisualStyleBackColor = False
			Me.GroupBox5.Controls.Add(Me.txtFrom_company_id)
			Me.GroupBox5.Controls.Add(Me.txtProductCode)
			Me.GroupBox5.Controls.Add(Me.txtID1)
			Me.GroupBox5.Controls.Add(Me.TextBox2)
			Me.GroupBox5.Controls.Add(Me.TextBox1)
			Me.GroupBox5.Controls.Add(Me.txtID)
			Me.GroupBox5.Controls.Add(Me.lblUserType)
			Me.GroupBox5.Controls.Add(Me.lblUser)
			Me.GroupBox5.Controls.Add(Me.txtCompany_to)
			Me.GroupBox5.Controls.Add(Me.btnDToken)
			Me.GroupBox5.Controls.Add(Me.txtCompany_id_from)
			Me.GroupBox5.Controls.Add(Me.Label136)
			Me.GroupBox5.Controls.Add(Me.Label135)
			Me.GroupBox5.Controls.Add(Me.cmbToCompany)
			Me.GroupBox5.Location = New Global.System.Drawing.Point(7, 4)
			Me.GroupBox5.Name = "GroupBox5"
			Me.GroupBox5.Size = New Global.System.Drawing.Size(782, 116)
			Me.GroupBox5.TabIndex = 1843
			Me.GroupBox5.TabStop = False
			Me.GroupBox5.Text = "Branch Details"
			Me.txtFrom_company_id.BackColor = Global.System.Drawing.Color.FromArgb(255, 255, 192)
			Me.txtFrom_company_id.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 12F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			Me.txtFrom_company_id.Location = New Global.System.Drawing.Point(139, 9)
			Me.txtFrom_company_id.Name = "txtFrom_company_id"
			Me.txtFrom_company_id.Size = New Global.System.Drawing.Size(288, 26)
			Me.txtFrom_company_id.TabIndex = 1853
			Me.txtProductCode.BackColor = Global.System.Drawing.Color.FromArgb(255, 255, 192)
			Me.txtProductCode.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 9F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			Me.txtProductCode.Location = New Global.System.Drawing.Point(513, 69)
			Me.txtProductCode.Name = "txtProductCode"
			Me.txtProductCode.Size = New Global.System.Drawing.Size(44, 21)
			Me.txtProductCode.TabIndex = 1852
			Me.txtProductCode.TabStop = False
			Me.txtProductCode.Visible = False
			Me.txtID1.BackColor = Global.System.Drawing.Color.FromArgb(255, 255, 192)
			Me.txtID1.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 9F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			Me.txtID1.Location = New Global.System.Drawing.Point(513, 42)
			Me.txtID1.Name = "txtID1"
			Me.txtID1.Size = New Global.System.Drawing.Size(44, 21)
			Me.txtID1.TabIndex = 1851
			Me.txtID1.TabStop = False
			Me.txtID1.Visible = False
			Me.TextBox2.BackColor = Global.System.Drawing.Color.FromArgb(255, 255, 192)
			Me.TextBox2.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 9F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			Me.TextBox2.Location = New Global.System.Drawing.Point(513, 15)
			Me.TextBox2.Name = "TextBox2"
			Me.TextBox2.Size = New Global.System.Drawing.Size(44, 21)
			Me.TextBox2.TabIndex = 1850
			Me.TextBox2.TabStop = False
			Me.TextBox2.Visible = False
			Me.TextBox1.BackColor = Global.System.Drawing.Color.FromArgb(255, 255, 192)
			Me.TextBox1.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 9F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			Me.TextBox1.Location = New Global.System.Drawing.Point(647, 86)
			Me.TextBox1.Name = "TextBox1"
			Me.TextBox1.Size = New Global.System.Drawing.Size(70, 21)
			Me.TextBox1.TabIndex = 1849
			Me.TextBox1.TabStop = False
			Me.TextBox1.Visible = False
			Me.txtID.BackColor = Global.System.Drawing.Color.FromArgb(255, 255, 192)
			Me.txtID.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 9F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			Me.txtID.Location = New Global.System.Drawing.Point(723, 86)
			Me.txtID.Name = "txtID"
			Me.txtID.Size = New Global.System.Drawing.Size(44, 21)
			Me.txtID.TabIndex = 1848
			Me.txtID.TabStop = False
			Me.txtID.Visible = False
			Me.lblUserType.AutoSize = True
			Me.lblUserType.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 9F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			Me.lblUserType.ForeColor = Global.System.Drawing.Color.FromArgb(64, 64, 0)
			Me.lblUserType.Location = New Global.System.Drawing.Point(695, 16)
			Me.lblUserType.Name = "lblUserType"
			Me.lblUserType.Size = New Global.System.Drawing.Size(72, 15)
			Me.lblUserType.TabIndex = 1847
			Me.lblUserType.Text = "lblUserType"
			Me.lblUserType.Visible = False
			Me.lblUser.AutoSize = True
			Me.lblUser.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 9F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			Me.lblUser.ForeColor = Global.System.Drawing.Color.FromArgb(64, 64, 0)
			Me.lblUser.Location = New Global.System.Drawing.Point(633, 16)
			Me.lblUser.Name = "lblUser"
			Me.lblUser.Size = New Global.System.Drawing.Size(46, 15)
			Me.lblUser.TabIndex = 1846
			Me.lblUser.Text = "lblUser"
			Me.lblUser.Visible = False
			Me.txtCompany_to.BackColor = Global.System.Drawing.Color.FromArgb(255, 255, 192)
			Me.txtCompany_to.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 12F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			Me.txtCompany_to.Location = New Global.System.Drawing.Point(11, 37)
			Me.txtCompany_to.Name = "txtCompany_to"
			Me.txtCompany_to.Size = New Global.System.Drawing.Size(418, 26)
			Me.txtCompany_to.TabIndex = 1845
			Me.txtCompany_id_from.BackColor = Global.System.Drawing.Color.FromArgb(255, 255, 192)
			Me.txtCompany_id_from.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 12F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			Me.txtCompany_id_from.Location = New Global.System.Drawing.Point(435, 39)
			Me.txtCompany_id_from.Name = "txtCompany_id_from"
			Me.txtCompany_id_from.Size = New Global.System.Drawing.Size(75, 26)
			Me.txtCompany_id_from.TabIndex = 1844
			Me.txtCompany_id_from.Visible = False
			Me.Label136.AutoSize = True
			Me.Label136.Location = New Global.System.Drawing.Point(8, 19)
			Me.Label136.Name = "Label136"
			Me.Label136.Size = New Global.System.Drawing.Size(30, 13)
			Me.Label136.TabIndex = 3
			Me.Label136.Text = "From"
			Me.Label135.AutoSize = True
			Me.Label135.Location = New Global.System.Drawing.Point(433, 22)
			Me.Label135.Name = "Label135"
			Me.Label135.Size = New Global.System.Drawing.Size(20, 13)
			Me.Label135.TabIndex = 2
			Me.Label135.Text = "To"
			Me.Label135.Visible = False
			Me.cmbToCompany.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 8F)
			Me.cmbToCompany.FormattingEnabled = True
			Me.cmbToCompany.Location = New Global.System.Drawing.Point(12, 39)
			Me.cmbToCompany.Name = "cmbToCompany"
			Me.cmbToCompany.Size = New Global.System.Drawing.Size(224, 21)
			Me.cmbToCompany.TabIndex = 1
			Me.DataGridView1.AllowUserToAddRows = False
			Me.DataGridView1.AllowUserToDeleteRows = False
			Me.DataGridView1.AllowUserToOrderColumns = True
			Me.DataGridView1.AllowUserToResizeColumns = False
			Me.DataGridView1.AllowUserToResizeRows = False
			dataGridViewCellStyle.BackColor = Global.System.Drawing.Color.White
			Me.DataGridView1.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle
			Me.DataGridView1.Anchor = Global.System.Windows.Forms.AnchorStyles.Top Or Global.System.Windows.Forms.AnchorStyles.Bottom Or Global.System.Windows.Forms.AnchorStyles.Left Or Global.System.Windows.Forms.AnchorStyles.Right
			Me.DataGridView1.AutoSizeColumnsMode = Global.System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill
			Me.DataGridView1.AutoSizeRowsMode = Global.System.Windows.Forms.DataGridViewAutoSizeRowsMode.AllCells
			Me.DataGridView1.BackgroundColor = Global.System.Drawing.Color.White
			Me.DataGridView1.CellBorderStyle = Global.System.Windows.Forms.DataGridViewCellBorderStyle.Raised
			dataGridViewCellStyle2.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter
			dataGridViewCellStyle2.BackColor = Global.System.Drawing.Color.RoyalBlue
			dataGridViewCellStyle2.Font = New Global.System.Drawing.Font("Segoe UI Semibold", 12F, Global.System.Drawing.FontStyle.Bold)
			dataGridViewCellStyle2.ForeColor = Global.System.Drawing.Color.White
			dataGridViewCellStyle2.SelectionBackColor = Global.System.Drawing.Color.RoyalBlue
			dataGridViewCellStyle2.SelectionForeColor = Global.System.Drawing.Color.White
			dataGridViewCellStyle2.WrapMode = Global.System.Windows.Forms.DataGridViewTriState.[True]
			Me.DataGridView1.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2
			Me.DataGridView1.ColumnHeadersHeight = 40
			Me.DataGridView1.Columns.AddRange(New Global.System.Windows.Forms.DataGridViewColumn() { Me.Column1, Me.Column2, Me.Column3, Me.Column7, Me.Column4, Me.Column5, Me.DataGridViewTextBoxColumn1, Me.Column17, Me.DataGridViewTextBoxColumn2, Me.Column9, Me.Column10, Me.Column11, Me.Column12, Me.Column13, Me.Column14, Me.DataGridViewTextBoxColumn3, Me.Column6, Me.Column18, Me.Column19, Me.Column22, Me.Column25, Me.Column26, Me.Column27, Me.Column28, Me.Column30, Me.Column31, Me.Column32, Me.Column33, Me.Column35, Me.Column36, Me.Column37, Me.Column38, Me.Column39, Me.Column40, Me.Column41, Me.Column42, Me.Column52, Me.Column53, Me.Column54, Me.Column55, Me.Column56, Me.Column57, Me.Column58 })
			Me.DataGridView1.Cursor = Global.System.Windows.Forms.Cursors.Hand
			dataGridViewCellStyle3.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft
			dataGridViewCellStyle3.BackColor = Global.System.Drawing.SystemColors.Window
			dataGridViewCellStyle3.Font = New Global.System.Drawing.Font("Segoe UI Semibold", 12F, Global.System.Drawing.FontStyle.Bold)
			dataGridViewCellStyle3.ForeColor = Global.System.Drawing.Color.White
			dataGridViewCellStyle3.SelectionBackColor = Global.System.Drawing.SystemColors.Highlight
			dataGridViewCellStyle3.SelectionForeColor = Global.System.Drawing.SystemColors.HighlightText
			dataGridViewCellStyle3.WrapMode = Global.System.Windows.Forms.DataGridViewTriState.[False]
			Me.DataGridView1.DefaultCellStyle = dataGridViewCellStyle3
			Me.DataGridView1.EnableHeadersVisualStyles = False
			Me.DataGridView1.GridColor = Global.System.Drawing.Color.White
			Me.DataGridView1.Location = New Global.System.Drawing.Point(7, 295)
			Me.DataGridView1.MultiSelect = False
			Me.DataGridView1.Name = "DataGridView1"
			Me.DataGridView1.[ReadOnly] = True
			Me.DataGridView1.RowHeadersBorderStyle = Global.System.Windows.Forms.DataGridViewHeaderBorderStyle.[Single]
			dataGridViewCellStyle4.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft
			dataGridViewCellStyle4.BackColor = Global.System.Drawing.Color.RoyalBlue
			dataGridViewCellStyle4.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 12F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			dataGridViewCellStyle4.ForeColor = Global.System.Drawing.Color.White
			dataGridViewCellStyle4.SelectionBackColor = Global.System.Drawing.Color.RoyalBlue
			dataGridViewCellStyle4.SelectionForeColor = Global.System.Drawing.Color.White
			dataGridViewCellStyle4.WrapMode = Global.System.Windows.Forms.DataGridViewTriState.[True]
			Me.DataGridView1.RowHeadersDefaultCellStyle = dataGridViewCellStyle4
			Me.DataGridView1.RowHeadersVisible = False
			Me.DataGridView1.RowHeadersWidth = 29
			Me.DataGridView1.RowHeadersWidthSizeMode = Global.System.Windows.Forms.DataGridViewRowHeadersWidthSizeMode.DisableResizing
			dataGridViewCellStyle5.BackColor = Global.System.Drawing.Color.White
			dataGridViewCellStyle5.Font = New Global.System.Drawing.Font("Segoe UI Semibold", 12F, Global.System.Drawing.FontStyle.Bold)
			dataGridViewCellStyle5.ForeColor = Global.System.Drawing.Color.Black
			dataGridViewCellStyle5.SelectionBackColor = Global.System.Drawing.Color.Khaki
			dataGridViewCellStyle5.SelectionForeColor = Global.System.Drawing.Color.Black
			Me.DataGridView1.RowsDefaultCellStyle = dataGridViewCellStyle5
			Me.DataGridView1.RowTemplate.Height = 20
			Me.DataGridView1.RowTemplate.[ReadOnly] = True
			Me.DataGridView1.RowTemplate.Resizable = Global.System.Windows.Forms.DataGridViewTriState.[False]
			Me.DataGridView1.SelectionMode = Global.System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect
			Me.DataGridView1.Size = New Global.System.Drawing.Size(781, 143)
			Me.DataGridView1.TabIndex = 1844
			Me.DataGridView1.TabStop = False
			Me.Column1.FillWeight = 20F
			Me.Column1.HeaderText = "PID"
			Me.Column1.Name = "Column1"
			Me.Column1.[ReadOnly] = True
			Me.Column1.Visible = False
			Me.Column2.HeaderText = "HSN Code"
			Me.Column2.Name = "Column2"
			Me.Column2.[ReadOnly] = True
			Me.Column2.Visible = False
			Me.Column3.FillWeight = 320F
			Me.Column3.HeaderText = "Product Name"
			Me.Column3.Name = "Column3"
			Me.Column3.[ReadOnly] = True
			dataGridViewCellStyle6.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft
			Me.Column7.DefaultCellStyle = dataGridViewCellStyle6
			Me.Column7.FillWeight = 130F
			Me.Column7.HeaderText = "Barcode"
			Me.Column7.Name = "Column7"
			Me.Column7.[ReadOnly] = True
			dataGridViewCellStyle7.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.Column4.DefaultCellStyle = dataGridViewCellStyle7
			Me.Column4.FillWeight = 85F
			Me.Column4.HeaderText = "Qty"
			Me.Column4.Name = "Column4"
			Me.Column4.[ReadOnly] = True
			dataGridViewCellStyle8.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.Column5.DefaultCellStyle = dataGridViewCellStyle8
			Me.Column5.FillWeight = 80F
			Me.Column5.HeaderText = "Rate"
			Me.Column5.Name = "Column5"
			Me.Column5.[ReadOnly] = True
			dataGridViewCellStyle9.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter
			Me.DataGridViewTextBoxColumn1.DefaultCellStyle = dataGridViewCellStyle9
			Me.DataGridViewTextBoxColumn1.FillWeight = 70F
			Me.DataGridViewTextBoxColumn1.HeaderText = "Disc %"
			Me.DataGridViewTextBoxColumn1.Name = "DataGridViewTextBoxColumn1"
			Me.DataGridViewTextBoxColumn1.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn1.Visible = False
			dataGridViewCellStyle10.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.Column17.DefaultCellStyle = dataGridViewCellStyle10
			Me.Column17.FillWeight = 80F
			Me.Column17.HeaderText = "Disc"
			Me.Column17.Name = "Column17"
			Me.Column17.[ReadOnly] = True
			dataGridViewCellStyle11.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn2.DefaultCellStyle = dataGridViewCellStyle11
			Me.DataGridViewTextBoxColumn2.FillWeight = 55F
			Me.DataGridViewTextBoxColumn2.HeaderText = "CGST %"
			Me.DataGridViewTextBoxColumn2.Name = "DataGridViewTextBoxColumn2"
			Me.DataGridViewTextBoxColumn2.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn2.Visible = False
			dataGridViewCellStyle12.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.Column9.DefaultCellStyle = dataGridViewCellStyle12
			Me.Column9.FillWeight = 70F
			Me.Column9.HeaderText = "CGST Amt"
			Me.Column9.Name = "Column9"
			Me.Column9.[ReadOnly] = True
			Me.Column9.Visible = False
			dataGridViewCellStyle13.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.Column10.DefaultCellStyle = dataGridViewCellStyle13
			Me.Column10.FillWeight = 55F
			Me.Column10.HeaderText = "SGST %"
			Me.Column10.Name = "Column10"
			Me.Column10.[ReadOnly] = True
			Me.Column10.Visible = False
			dataGridViewCellStyle14.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.Column11.DefaultCellStyle = dataGridViewCellStyle14
			Me.Column11.FillWeight = 70F
			Me.Column11.HeaderText = "SGST Amt"
			Me.Column11.Name = "Column11"
			Me.Column11.[ReadOnly] = True
			Me.Column11.Visible = False
			dataGridViewCellStyle15.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.Column12.DefaultCellStyle = dataGridViewCellStyle15
			Me.Column12.FillWeight = 50F
			Me.Column12.HeaderText = "IGST %"
			Me.Column12.Name = "Column12"
			Me.Column12.[ReadOnly] = True
			Me.Column12.Visible = False
			dataGridViewCellStyle16.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.Column13.DefaultCellStyle = dataGridViewCellStyle16
			Me.Column13.FillWeight = 70F
			Me.Column13.HeaderText = "IGST Amt"
			Me.Column13.Name = "Column13"
			Me.Column13.[ReadOnly] = True
			Me.Column13.Visible = False
			dataGridViewCellStyle17.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.Column14.DefaultCellStyle = dataGridViewCellStyle17
			Me.Column14.FillWeight = 50F
			Me.Column14.HeaderText = "CESS %"
			Me.Column14.Name = "Column14"
			Me.Column14.[ReadOnly] = True
			Me.Column14.Visible = False
			dataGridViewCellStyle18.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn3.DefaultCellStyle = dataGridViewCellStyle18
			Me.DataGridViewTextBoxColumn3.FillWeight = 70F
			Me.DataGridViewTextBoxColumn3.HeaderText = "CESS Amt"
			Me.DataGridViewTextBoxColumn3.Name = "DataGridViewTextBoxColumn3"
			Me.DataGridViewTextBoxColumn3.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn3.Visible = False
			dataGridViewCellStyle19.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.Column6.DefaultCellStyle = dataGridViewCellStyle19
			Me.Column6.HeaderText = "Total"
			Me.Column6.Name = "Column6"
			Me.Column6.[ReadOnly] = True
			dataGridViewCellStyle20.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.Column18.DefaultCellStyle = dataGridViewCellStyle20
			Me.Column18.FillWeight = 20F
			Me.Column18.HeaderText = "Purchase Rate"
			Me.Column18.Name = "Column18"
			Me.Column18.[ReadOnly] = True
			Me.Column18.Visible = False
			dataGridViewCellStyle21.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.Column19.DefaultCellStyle = dataGridViewCellStyle21
			Me.Column19.HeaderText = "Margin"
			Me.Column19.Name = "Column19"
			Me.Column19.[ReadOnly] = True
			Me.Column19.Visible = False
			dataGridViewCellStyle22.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft
			Me.Column22.DefaultCellStyle = dataGridViewCellStyle22
			Me.Column22.HeaderText = "Description"
			Me.Column22.Name = "Column22"
			Me.Column22.[ReadOnly] = True
			Me.Column22.Visible = False
			Me.Column25.HeaderText = "Temp Qty"
			Me.Column25.Name = "Column25"
			Me.Column25.[ReadOnly] = True
			Me.Column25.Visible = False
			Me.Column26.HeaderText = "IMEI-1"
			Me.Column26.Name = "Column26"
			Me.Column26.[ReadOnly] = True
			Me.Column26.Visible = False
			Me.Column27.HeaderText = "IMEI-2"
			Me.Column27.Name = "Column27"
			Me.Column27.[ReadOnly] = True
			Me.Column27.Visible = False
			dataGridViewCellStyle23.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			dataGridViewCellStyle23.Format = "N2"
			Me.Column28.DefaultCellStyle = dataGridViewCellStyle23
			Me.Column28.HeaderText = "MRP"
			Me.Column28.Name = "Column28"
			Me.Column28.[ReadOnly] = True
			dataGridViewCellStyle24.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			dataGridViewCellStyle24.Format = "N2"
			dataGridViewCellStyle24.NullValue = Nothing
			Me.Column30.DefaultCellStyle = dataGridViewCellStyle24
			Me.Column30.HeaderText = "Taxable Amt"
			Me.Column30.Name = "Column30"
			Me.Column30.[ReadOnly] = True
			Me.Column30.Visible = False
			dataGridViewCellStyle25.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.Column31.DefaultCellStyle = dataGridViewCellStyle25
			Me.Column31.HeaderText = "Alt Qty"
			Me.Column31.Name = "Column31"
			Me.Column31.[ReadOnly] = True
			Me.Column31.Visible = False
			dataGridViewCellStyle26.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter
			Me.Column32.DefaultCellStyle = dataGridViewCellStyle26
			Me.Column32.HeaderText = "Alt Unit"
			Me.Column32.Name = "Column32"
			Me.Column32.[ReadOnly] = True
			Me.Column32.Visible = False
			dataGridViewCellStyle27.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter
			Me.Column33.DefaultCellStyle = dataGridViewCellStyle27
			Me.Column33.HeaderText = "Tax Type"
			Me.Column33.Name = "Column33"
			Me.Column33.[ReadOnly] = True
			Me.Column33.Visible = False
			dataGridViewCellStyle28.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			dataGridViewCellStyle28.Format = "N2"
			Me.Column35.DefaultCellStyle = dataGridViewCellStyle28
			Me.Column35.HeaderText = "Total MRP"
			Me.Column35.Name = "Column35"
			Me.Column35.[ReadOnly] = True
			Me.Column35.Visible = False
			dataGridViewCellStyle29.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter
			Me.Column36.DefaultCellStyle = dataGridViewCellStyle29
			Me.Column36.HeaderText = "Free Offer Qty"
			Me.Column36.Name = "Column36"
			Me.Column36.[ReadOnly] = True
			Me.Column36.Visible = False
			dataGridViewCellStyle30.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter
			Me.Column37.DefaultCellStyle = dataGridViewCellStyle30
			Me.Column37.HeaderText = "Main Unit"
			Me.Column37.Name = "Column37"
			Me.Column37.[ReadOnly] = True
			Me.Column37.Visible = False
			Me.Column38.HeaderText = "Batch/Serial"
			Me.Column38.Name = "Column38"
			Me.Column38.[ReadOnly] = True
			Me.Column38.Visible = False
			Me.Column39.HeaderText = "Mfg Date"
			Me.Column39.Name = "Column39"
			Me.Column39.[ReadOnly] = True
			Me.Column39.Visible = False
			Me.Column40.HeaderText = "Exp Date"
			Me.Column40.Name = "Column40"
			Me.Column40.[ReadOnly] = True
			Me.Column40.Visible = False
			Me.Column41.HeaderText = "Size"
			Me.Column41.Name = "Column41"
			Me.Column41.[ReadOnly] = True
			Me.Column41.Visible = False
			Me.Column42.HeaderText = "Colour"
			Me.Column42.Name = "Column42"
			Me.Column42.[ReadOnly] = True
			Me.Column42.Visible = False
			Me.Column52.HeaderText = "Column52"
			Me.Column52.Name = "Column52"
			Me.Column52.[ReadOnly] = True
			Me.Column52.Visible = False
			Me.Column53.HeaderText = "Column53"
			Me.Column53.Name = "Column53"
			Me.Column53.[ReadOnly] = True
			Me.Column53.Visible = False
			Me.Column54.HeaderText = "Column54"
			Me.Column54.Name = "Column54"
			Me.Column54.[ReadOnly] = True
			Me.Column54.Visible = False
			Me.Column55.HeaderText = "Column55"
			Me.Column55.Name = "Column55"
			Me.Column55.[ReadOnly] = True
			Me.Column55.Visible = False
			Me.Column56.HeaderText = "Column56"
			Me.Column56.Name = "Column56"
			Me.Column56.[ReadOnly] = True
			Me.Column56.Visible = False
			Me.Column57.HeaderText = "Stockid"
			Me.Column57.Name = "Column57"
			Me.Column57.[ReadOnly] = True
			Me.Column57.Visible = False
			Me.Column58.HeaderText = "Points"
			Me.Column58.Name = "Column58"
			Me.Column58.[ReadOnly] = True
			Me.Column58.Visible = False
			Me.pbgiftqr.Location = New Global.System.Drawing.Point(445, 349)
			Me.pbgiftqr.Name = "pbgiftqr"
			Me.pbgiftqr.Size = New Global.System.Drawing.Size(84, 82)
			Me.pbgiftqr.TabIndex = 1846
			Me.pbgiftqr.TabStop = False
			Me.pbgiftqr.Visible = False
			Me.Picture.BorderStyle = Global.System.Windows.Forms.BorderStyle.FixedSingle
			Me.Picture.Image = Global.BillPoint.My.Resources.Resources.photo
			Me.Picture.Location = New Global.System.Drawing.Point(535, 349)
			Me.Picture.Name = "Picture"
			Me.Picture.Size = New Global.System.Drawing.Size(108, 82)
			Me.Picture.SizeMode = Global.System.Windows.Forms.PictureBoxSizeMode.StretchImage
			Me.Picture.TabIndex = 1845
			Me.Picture.TabStop = False
			Me.Picture.Visible = False
			MyBase.AutoScaleDimensions = New Global.System.Drawing.SizeF(6F, 13F)
			MyBase.AutoScaleMode = Global.System.Windows.Forms.AutoScaleMode.Font
			MyBase.ClientSize = New Global.System.Drawing.Size(800, 450)
			MyBase.Controls.Add(Me.listView1)
			MyBase.Controls.Add(Me.pbgiftqr)
			MyBase.Controls.Add(Me.Picture)
			MyBase.Controls.Add(Me.DataGridView1)
			MyBase.Controls.Add(Me.GroupBox5)
			MyBase.Name = "frmStock_Settlement"
			MyBase.ShowIcon = False
			MyBase.StartPosition = Global.System.Windows.Forms.FormStartPosition.CenterParent
			Me.Text = "Stock_Settlement"
			Me.GroupBox5.ResumeLayout(False)
			Me.GroupBox5.PerformLayout()
			CType(Me.DataGridView1, Global.System.ComponentModel.ISupportInitialize).EndInit()
			CType(Me.pbgiftqr, Global.System.ComponentModel.ISupportInitialize).EndInit()
			CType(Me.Picture, Global.System.ComponentModel.ISupportInitialize).EndInit()
			MyBase.ResumeLayout(False)
		End Sub

		' Token: 0x04004082 RID: 16514
		Private components As Global.System.ComponentModel.IContainer
	End Class
End Namespace
