Namespace BillPoint
	' Token: 0x020001F5 RID: 501
		Public Partial Class frmSerialwiseReport
		Inherits Global.System.Windows.Forms.Form

		' Token: 0x06008E69 RID: 36457 RVA: 0x00685568 File Offset: 0x00683768
		<Global.System.Diagnostics.DebuggerNonUserCode()>
		Protected Overrides Sub Dispose(disposing As Boolean)
			Try
				Dim flag As Boolean = disposing AndAlso Me.components IsNot Nothing
				If flag Then
					Me.components.Dispose()
				End If
			Finally
				MyBase.Dispose(disposing)
			End Try
		End Sub

		' Token: 0x06008E6A RID: 36458 RVA: 0x006855B8 File Offset: 0x006837B8
		<Global.System.Diagnostics.DebuggerStepThrough()>
		Private Sub InitializeComponent()
			Dim dataGridViewCellStyle As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle2 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle3 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle4 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle5 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle6 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle7 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle8 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle9 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle10 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle11 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle12 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle13 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle14 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle15 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle16 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle17 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle18 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle19 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle20 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle21 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle22 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle23 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle24 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle25 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle26 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle27 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle28 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle29 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle30 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle31 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle32 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle33 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle34 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle35 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle36 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle37 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle38 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle39 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle40 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle41 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle42 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle43 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle44 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle45 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle46 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle47 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle48 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle49 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle50 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle51 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle52 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle53 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle54 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle55 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle56 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle57 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle58 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle59 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle60 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle61 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle62 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle63 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle64 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle65 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle66 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle67 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle68 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle69 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle70 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle71 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle72 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle73 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle74 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle75 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle76 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle77 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle78 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim dataGridViewCellStyle79 As Global.System.Windows.Forms.DataGridViewCellStyle = New Global.System.Windows.Forms.DataGridViewCellStyle()
			Dim componentResourceManager As Global.System.ComponentModel.ComponentResourceManager = New Global.System.ComponentModel.ComponentResourceManager(GetType(Global.BillPoint.frmSerialwiseReport))
			Me.Panel1 = New Global.System.Windows.Forms.Panel()
			Me.GroupBox5 = New Global.System.Windows.Forms.GroupBox()
			Me.dgwPurchaseReturn = New Global.System.Windows.Forms.DataGridView()
			Me.DataGridViewTextBoxColumn58 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn59 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn60 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn61 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn62 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn63 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn64 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn65 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn66 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn67 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn68 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn69 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn70 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn71 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn72 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn73 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn74 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn75 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn76 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn77 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn78 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn79 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn80 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn81 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn82 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column37 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.GroupBox4 = New Global.System.Windows.Forms.GroupBox()
			Me.dgwSalesReturn = New Global.System.Windows.Forms.DataGridView()
			Me.DataGridViewTextBoxColumn33 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn34 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn35 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn36 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn37 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn38 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn39 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn40 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn41 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn42 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn43 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn44 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn45 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn46 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn47 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn48 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn49 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn50 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn51 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn52 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn53 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn54 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn55 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn56 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn57 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column36 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.GroupBox3 = New Global.System.Windows.Forms.GroupBox()
			Me.dgwPurchase = New Global.System.Windows.Forms.DataGridView()
			Me.DataGridViewTextBoxColumn1 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn2 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn3 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn4 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn5 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn6 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn7 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn8 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn9 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn10 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn11 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn12 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn13 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn14 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn15 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn16 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn17 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn18 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn19 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn20 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn21 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn22 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn23 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn24 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn25 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn26 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn27 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn28 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn29 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn30 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn31 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.DataGridViewTextBoxColumn32 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column33 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column34 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column35 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.colSerial = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.GroupBox1 = New Global.System.Windows.Forms.GroupBox()
			Me.dgw = New Global.System.Windows.Forms.DataGridView()
			Me.Column2 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column3 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column14 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column6 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column16 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column17 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column13 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column15 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column18 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column4 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column9 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column1 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column8 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column5 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column19 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column11 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column20 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column12 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column21 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column27 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column22 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column7 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column10 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column23 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column24 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column25 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column26 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column28 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column29 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column30 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column31 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Column32 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.colSerialNo1 = New Global.System.Windows.Forms.DataGridViewTextBoxColumn()
			Me.Label5 = New Global.System.Windows.Forms.Label()
			Me.txtSerialNumber = New Global.System.Windows.Forms.TextBox()
			Me.lblTotalAmount = New Global.System.Windows.Forms.Label()
			Me.Label6 = New Global.System.Windows.Forms.Label()
			Me.Panel2 = New Global.System.Windows.Forms.Panel()
			Me.Label8 = New Global.System.Windows.Forms.Label()
			Me.ComboBox2 = New Global.System.Windows.Forms.ComboBox()
			Me.Button1 = New Global.System.Windows.Forms.Button()
			Me.Label3 = New Global.System.Windows.Forms.Label()
			Me.TextBox1 = New Global.System.Windows.Forms.TextBox()
			Me.ComboBox1 = New Global.System.Windows.Forms.ComboBox()
			Me.GroupBox2 = New Global.System.Windows.Forms.GroupBox()
			Me.btnGetData = New Global.GelButtons.GelButton()
			Me.dtpDateTo = New Global.System.Windows.Forms.DateTimePicker()
			Me.Label2 = New Global.System.Windows.Forms.Label()
			Me.Label4 = New Global.System.Windows.Forms.Label()
			Me.dtpDateFrom = New Global.System.Windows.Forms.DateTimePicker()
			Me.Panel5 = New Global.System.Windows.Forms.Panel()
			Me.GelButton1 = New Global.GelButtons.GelButton()
			Me.btnReset = New Global.GelButtons.GelButton()
			Me.Label1 = New Global.System.Windows.Forms.Label()
			Me.SaveFileDialog1 = New Global.System.Windows.Forms.SaveFileDialog()
			Me.GroupBox6 = New Global.System.Windows.Forms.GroupBox()
			Me.Panel1.SuspendLayout()
			Me.GroupBox5.SuspendLayout()
			CType(Me.dgwPurchaseReturn, Global.System.ComponentModel.ISupportInitialize).BeginInit()
			Me.GroupBox4.SuspendLayout()
			CType(Me.dgwSalesReturn, Global.System.ComponentModel.ISupportInitialize).BeginInit()
			Me.GroupBox3.SuspendLayout()
			CType(Me.dgwPurchase, Global.System.ComponentModel.ISupportInitialize).BeginInit()
			Me.GroupBox1.SuspendLayout()
			CType(Me.dgw, Global.System.ComponentModel.ISupportInitialize).BeginInit()
			Me.Panel2.SuspendLayout()
			Me.GroupBox2.SuspendLayout()
			Me.Panel5.SuspendLayout()
			Me.GroupBox6.SuspendLayout()
			MyBase.SuspendLayout()
			Me.Panel1.BackColor = Global.System.Drawing.Color.White
			Me.Panel1.BorderStyle = Global.System.Windows.Forms.BorderStyle.FixedSingle
			Me.Panel1.Controls.Add(Me.GroupBox6)
			Me.Panel1.Controls.Add(Me.GroupBox5)
			Me.Panel1.Controls.Add(Me.GroupBox4)
			Me.Panel1.Controls.Add(Me.GroupBox3)
			Me.Panel1.Controls.Add(Me.GroupBox1)
			Me.Panel1.Controls.Add(Me.lblTotalAmount)
			Me.Panel1.Controls.Add(Me.Label6)
			Me.Panel1.Controls.Add(Me.Panel2)
			Me.Panel1.Controls.Add(Me.GroupBox2)
			Me.Panel1.Controls.Add(Me.Panel5)
			Me.Panel1.Controls.Add(Me.Label1)
			Me.Panel1.Dock = Global.System.Windows.Forms.DockStyle.Fill
			Me.Panel1.Location = New Global.System.Drawing.Point(0, 0)
			Me.Panel1.Name = "Panel1"
			Me.Panel1.Size = New Global.System.Drawing.Size(1469, 684)
			Me.Panel1.TabIndex = 2
			Me.GroupBox5.Controls.Add(Me.dgwPurchaseReturn)
			Me.GroupBox5.Location = New Global.System.Drawing.Point(718, 380)
			Me.GroupBox5.Name = "GroupBox5"
			Me.GroupBox5.Size = New Global.System.Drawing.Size(738, 278)
			Me.GroupBox5.TabIndex = 68
			Me.GroupBox5.TabStop = False
			Me.GroupBox5.Text = "Purchase Return"
			Me.dgwPurchaseReturn.AllowUserToAddRows = False
			Me.dgwPurchaseReturn.AllowUserToDeleteRows = False
			dataGridViewCellStyle.BackColor = Global.System.Drawing.Color.FloralWhite
			Me.dgwPurchaseReturn.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle
			Me.dgwPurchaseReturn.Anchor = Global.System.Windows.Forms.AnchorStyles.Top Or Global.System.Windows.Forms.AnchorStyles.Bottom Or Global.System.Windows.Forms.AnchorStyles.Left Or Global.System.Windows.Forms.AnchorStyles.Right
			Me.dgwPurchaseReturn.BackgroundColor = Global.System.Drawing.Color.White
			Me.dgwPurchaseReturn.ColumnHeadersBorderStyle = Global.System.Windows.Forms.DataGridViewHeaderBorderStyle.[Single]
			dataGridViewCellStyle2.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter
			dataGridViewCellStyle2.BackColor = Global.System.Drawing.Color.DarkViolet
			dataGridViewCellStyle2.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 8.25F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			dataGridViewCellStyle2.ForeColor = Global.System.Drawing.Color.White
			dataGridViewCellStyle2.SelectionBackColor = Global.System.Drawing.Color.LightSteelBlue
			dataGridViewCellStyle2.SelectionForeColor = Global.System.Drawing.SystemColors.HighlightText
			dataGridViewCellStyle2.WrapMode = Global.System.Windows.Forms.DataGridViewTriState.[True]
			Me.dgwPurchaseReturn.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2
			Me.dgwPurchaseReturn.ColumnHeadersHeight = 30
			Me.dgwPurchaseReturn.Columns.AddRange(New Global.System.Windows.Forms.DataGridViewColumn() { Me.DataGridViewTextBoxColumn58, Me.DataGridViewTextBoxColumn59, Me.DataGridViewTextBoxColumn60, Me.DataGridViewTextBoxColumn61, Me.DataGridViewTextBoxColumn62, Me.DataGridViewTextBoxColumn63, Me.DataGridViewTextBoxColumn64, Me.DataGridViewTextBoxColumn65, Me.DataGridViewTextBoxColumn66, Me.DataGridViewTextBoxColumn67, Me.DataGridViewTextBoxColumn68, Me.DataGridViewTextBoxColumn69, Me.DataGridViewTextBoxColumn70, Me.DataGridViewTextBoxColumn71, Me.DataGridViewTextBoxColumn72, Me.DataGridViewTextBoxColumn73, Me.DataGridViewTextBoxColumn74, Me.DataGridViewTextBoxColumn75, Me.DataGridViewTextBoxColumn76, Me.DataGridViewTextBoxColumn77, Me.DataGridViewTextBoxColumn78, Me.DataGridViewTextBoxColumn79, Me.DataGridViewTextBoxColumn80, Me.DataGridViewTextBoxColumn81, Me.DataGridViewTextBoxColumn82, Me.Column37 })
			Me.dgwPurchaseReturn.Cursor = Global.System.Windows.Forms.Cursors.Hand
			dataGridViewCellStyle3.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft
			dataGridViewCellStyle3.BackColor = Global.System.Drawing.SystemColors.Window
			dataGridViewCellStyle3.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 8.25F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			dataGridViewCellStyle3.ForeColor = Global.System.Drawing.SystemColors.ControlText
			dataGridViewCellStyle3.SelectionBackColor = Global.System.Drawing.SystemColors.Highlight
			dataGridViewCellStyle3.SelectionForeColor = Global.System.Drawing.SystemColors.HighlightText
			dataGridViewCellStyle3.WrapMode = Global.System.Windows.Forms.DataGridViewTriState.[False]
			Me.dgwPurchaseReturn.DefaultCellStyle = dataGridViewCellStyle3
			Me.dgwPurchaseReturn.EnableHeadersVisualStyles = False
			Me.dgwPurchaseReturn.GridColor = Global.System.Drawing.Color.White
			Me.dgwPurchaseReturn.Location = New Global.System.Drawing.Point(6, 19)
			Me.dgwPurchaseReturn.MultiSelect = False
			Me.dgwPurchaseReturn.Name = "dgwPurchaseReturn"
			Me.dgwPurchaseReturn.[ReadOnly] = True
			Me.dgwPurchaseReturn.RowHeadersBorderStyle = Global.System.Windows.Forms.DataGridViewHeaderBorderStyle.[Single]
			dataGridViewCellStyle4.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft
			dataGridViewCellStyle4.BackColor = Global.System.Drawing.Color.DarkViolet
			dataGridViewCellStyle4.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 8.25F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			dataGridViewCellStyle4.ForeColor = Global.System.Drawing.Color.White
			dataGridViewCellStyle4.SelectionBackColor = Global.System.Drawing.Color.OrangeRed
			dataGridViewCellStyle4.SelectionForeColor = Global.System.Drawing.Color.White
			dataGridViewCellStyle4.WrapMode = Global.System.Windows.Forms.DataGridViewTriState.[True]
			Me.dgwPurchaseReturn.RowHeadersDefaultCellStyle = dataGridViewCellStyle4
			Me.dgwPurchaseReturn.RowHeadersWidth = 25
			Me.dgwPurchaseReturn.RowHeadersWidthSizeMode = Global.System.Windows.Forms.DataGridViewRowHeadersWidthSizeMode.DisableResizing
			dataGridViewCellStyle5.BackColor = Global.System.Drawing.Color.White
			dataGridViewCellStyle5.Font = New Global.System.Drawing.Font("Tahoma", 8.25F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			dataGridViewCellStyle5.SelectionBackColor = Global.System.Drawing.Color.DarkSlateGray
			dataGridViewCellStyle5.SelectionForeColor = Global.System.Drawing.Color.White
			Me.dgwPurchaseReturn.RowsDefaultCellStyle = dataGridViewCellStyle5
			Me.dgwPurchaseReturn.RowTemplate.Height = 25
			Me.dgwPurchaseReturn.RowTemplate.Resizable = Global.System.Windows.Forms.DataGridViewTriState.[False]
			Me.dgwPurchaseReturn.SelectionMode = Global.System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect
			Me.dgwPurchaseReturn.Size = New Global.System.Drawing.Size(726, 253)
			Me.dgwPurchaseReturn.TabIndex = 62
			Me.dgwPurchaseReturn.TabStop = False
			Me.DataGridViewTextBoxColumn58.HeaderText = "PR No."
			Me.DataGridViewTextBoxColumn58.Name = "DataGridViewTextBoxColumn58"
			Me.DataGridViewTextBoxColumn58.[ReadOnly] = True
			dataGridViewCellStyle6.Format = "dd/MM/yyyy"
			Me.DataGridViewTextBoxColumn59.DefaultCellStyle = dataGridViewCellStyle6
			Me.DataGridViewTextBoxColumn59.HeaderText = "PR Date"
			Me.DataGridViewTextBoxColumn59.Name = "DataGridViewTextBoxColumn59"
			Me.DataGridViewTextBoxColumn59.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn60.HeaderText = "Tax Type"
			Me.DataGridViewTextBoxColumn60.Name = "DataGridViewTextBoxColumn60"
			Me.DataGridViewTextBoxColumn60.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn61.HeaderText = "Purchase Invoice No."
			Me.DataGridViewTextBoxColumn61.Name = "DataGridViewTextBoxColumn61"
			Me.DataGridViewTextBoxColumn61.[ReadOnly] = True
			dataGridViewCellStyle7.Format = "dd/MM/yyyy"
			Me.DataGridViewTextBoxColumn62.DefaultCellStyle = dataGridViewCellStyle7
			Me.DataGridViewTextBoxColumn62.HeaderText = "Purchase Invoice Date"
			Me.DataGridViewTextBoxColumn62.Name = "DataGridViewTextBoxColumn62"
			Me.DataGridViewTextBoxColumn62.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn63.HeaderText = "Supplier Name"
			Me.DataGridViewTextBoxColumn63.Name = "DataGridViewTextBoxColumn63"
			Me.DataGridViewTextBoxColumn63.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn64.HeaderText = "State"
			Me.DataGridViewTextBoxColumn64.Name = "DataGridViewTextBoxColumn64"
			Me.DataGridViewTextBoxColumn64.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn65.HeaderText = "GSTIN"
			Me.DataGridViewTextBoxColumn65.Name = "DataGridViewTextBoxColumn65"
			Me.DataGridViewTextBoxColumn65.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn66.HeaderText = "Product Name"
			Me.DataGridViewTextBoxColumn66.Name = "DataGridViewTextBoxColumn66"
			Me.DataGridViewTextBoxColumn66.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn67.HeaderText = "HSN Code"
			Me.DataGridViewTextBoxColumn67.Name = "DataGridViewTextBoxColumn67"
			Me.DataGridViewTextBoxColumn67.[ReadOnly] = True
			dataGridViewCellStyle8.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			dataGridViewCellStyle8.Format = "N2"
			Me.DataGridViewTextBoxColumn68.DefaultCellStyle = dataGridViewCellStyle8
			Me.DataGridViewTextBoxColumn68.HeaderText = "Purchase Rate"
			Me.DataGridViewTextBoxColumn68.Name = "DataGridViewTextBoxColumn68"
			Me.DataGridViewTextBoxColumn68.[ReadOnly] = True
			dataGridViewCellStyle9.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn69.DefaultCellStyle = dataGridViewCellStyle9
			Me.DataGridViewTextBoxColumn69.HeaderText = "Return Qty."
			Me.DataGridViewTextBoxColumn69.Name = "DataGridViewTextBoxColumn69"
			Me.DataGridViewTextBoxColumn69.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn70.HeaderText = "UOM"
			Me.DataGridViewTextBoxColumn70.Name = "DataGridViewTextBoxColumn70"
			Me.DataGridViewTextBoxColumn70.[ReadOnly] = True
			dataGridViewCellStyle10.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn71.DefaultCellStyle = dataGridViewCellStyle10
			Me.DataGridViewTextBoxColumn71.HeaderText = "Discount %"
			Me.DataGridViewTextBoxColumn71.Name = "DataGridViewTextBoxColumn71"
			Me.DataGridViewTextBoxColumn71.[ReadOnly] = True
			dataGridViewCellStyle11.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn72.DefaultCellStyle = dataGridViewCellStyle11
			Me.DataGridViewTextBoxColumn72.HeaderText = "Discount"
			Me.DataGridViewTextBoxColumn72.Name = "DataGridViewTextBoxColumn72"
			Me.DataGridViewTextBoxColumn72.[ReadOnly] = True
			dataGridViewCellStyle12.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn73.DefaultCellStyle = dataGridViewCellStyle12
			Me.DataGridViewTextBoxColumn73.HeaderText = "CGST %"
			Me.DataGridViewTextBoxColumn73.Name = "DataGridViewTextBoxColumn73"
			Me.DataGridViewTextBoxColumn73.[ReadOnly] = True
			dataGridViewCellStyle13.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn74.DefaultCellStyle = dataGridViewCellStyle13
			Me.DataGridViewTextBoxColumn74.HeaderText = "CGST"
			Me.DataGridViewTextBoxColumn74.Name = "DataGridViewTextBoxColumn74"
			Me.DataGridViewTextBoxColumn74.[ReadOnly] = True
			dataGridViewCellStyle14.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn75.DefaultCellStyle = dataGridViewCellStyle14
			Me.DataGridViewTextBoxColumn75.HeaderText = "SGST %"
			Me.DataGridViewTextBoxColumn75.Name = "DataGridViewTextBoxColumn75"
			Me.DataGridViewTextBoxColumn75.[ReadOnly] = True
			dataGridViewCellStyle15.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn76.DefaultCellStyle = dataGridViewCellStyle15
			Me.DataGridViewTextBoxColumn76.HeaderText = "SGST/UTGST"
			Me.DataGridViewTextBoxColumn76.Name = "DataGridViewTextBoxColumn76"
			Me.DataGridViewTextBoxColumn76.[ReadOnly] = True
			dataGridViewCellStyle16.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn77.DefaultCellStyle = dataGridViewCellStyle16
			Me.DataGridViewTextBoxColumn77.HeaderText = "IGST %"
			Me.DataGridViewTextBoxColumn77.Name = "DataGridViewTextBoxColumn77"
			Me.DataGridViewTextBoxColumn77.[ReadOnly] = True
			dataGridViewCellStyle17.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn78.DefaultCellStyle = dataGridViewCellStyle17
			Me.DataGridViewTextBoxColumn78.HeaderText = "IGST"
			Me.DataGridViewTextBoxColumn78.Name = "DataGridViewTextBoxColumn78"
			Me.DataGridViewTextBoxColumn78.[ReadOnly] = True
			dataGridViewCellStyle18.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn79.DefaultCellStyle = dataGridViewCellStyle18
			Me.DataGridViewTextBoxColumn79.HeaderText = "CESS %"
			Me.DataGridViewTextBoxColumn79.Name = "DataGridViewTextBoxColumn79"
			Me.DataGridViewTextBoxColumn79.[ReadOnly] = True
			dataGridViewCellStyle19.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn80.DefaultCellStyle = dataGridViewCellStyle19
			Me.DataGridViewTextBoxColumn80.HeaderText = "CESS"
			Me.DataGridViewTextBoxColumn80.Name = "DataGridViewTextBoxColumn80"
			Me.DataGridViewTextBoxColumn80.[ReadOnly] = True
			dataGridViewCellStyle20.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn81.DefaultCellStyle = dataGridViewCellStyle20
			Me.DataGridViewTextBoxColumn81.HeaderText = "Total Amount"
			Me.DataGridViewTextBoxColumn81.Name = "DataGridViewTextBoxColumn81"
			Me.DataGridViewTextBoxColumn81.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn82.HeaderText = "Barcode"
			Me.DataGridViewTextBoxColumn82.Name = "DataGridViewTextBoxColumn82"
			Me.DataGridViewTextBoxColumn82.[ReadOnly] = True
			Me.Column37.HeaderText = "SerialNo"
			Me.Column37.Name = "Column37"
			Me.Column37.[ReadOnly] = True
			Me.GroupBox4.Controls.Add(Me.dgwSalesReturn)
			Me.GroupBox4.Location = New Global.System.Drawing.Point(9, 380)
			Me.GroupBox4.Name = "GroupBox4"
			Me.GroupBox4.Size = New Global.System.Drawing.Size(696, 278)
			Me.GroupBox4.TabIndex = 67
			Me.GroupBox4.TabStop = False
			Me.GroupBox4.Text = "Sales Return"
			Me.dgwSalesReturn.AllowUserToAddRows = False
			Me.dgwSalesReturn.AllowUserToDeleteRows = False
			dataGridViewCellStyle21.BackColor = Global.System.Drawing.Color.FloralWhite
			Me.dgwSalesReturn.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle21
			Me.dgwSalesReturn.Anchor = Global.System.Windows.Forms.AnchorStyles.Top Or Global.System.Windows.Forms.AnchorStyles.Bottom Or Global.System.Windows.Forms.AnchorStyles.Left Or Global.System.Windows.Forms.AnchorStyles.Right
			Me.dgwSalesReturn.BackgroundColor = Global.System.Drawing.Color.White
			Me.dgwSalesReturn.ColumnHeadersBorderStyle = Global.System.Windows.Forms.DataGridViewHeaderBorderStyle.[Single]
			dataGridViewCellStyle22.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter
			dataGridViewCellStyle22.BackColor = Global.System.Drawing.Color.DarkViolet
			dataGridViewCellStyle22.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 8.25F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			dataGridViewCellStyle22.ForeColor = Global.System.Drawing.Color.White
			dataGridViewCellStyle22.SelectionBackColor = Global.System.Drawing.Color.LightSteelBlue
			dataGridViewCellStyle22.SelectionForeColor = Global.System.Drawing.SystemColors.HighlightText
			dataGridViewCellStyle22.WrapMode = Global.System.Windows.Forms.DataGridViewTriState.[True]
			Me.dgwSalesReturn.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle22
			Me.dgwSalesReturn.ColumnHeadersHeight = 30
			Me.dgwSalesReturn.Columns.AddRange(New Global.System.Windows.Forms.DataGridViewColumn() { Me.DataGridViewTextBoxColumn33, Me.DataGridViewTextBoxColumn34, Me.DataGridViewTextBoxColumn35, Me.DataGridViewTextBoxColumn36, Me.DataGridViewTextBoxColumn37, Me.DataGridViewTextBoxColumn38, Me.DataGridViewTextBoxColumn39, Me.DataGridViewTextBoxColumn40, Me.DataGridViewTextBoxColumn41, Me.DataGridViewTextBoxColumn42, Me.DataGridViewTextBoxColumn43, Me.DataGridViewTextBoxColumn44, Me.DataGridViewTextBoxColumn45, Me.DataGridViewTextBoxColumn46, Me.DataGridViewTextBoxColumn47, Me.DataGridViewTextBoxColumn48, Me.DataGridViewTextBoxColumn49, Me.DataGridViewTextBoxColumn50, Me.DataGridViewTextBoxColumn51, Me.DataGridViewTextBoxColumn52, Me.DataGridViewTextBoxColumn53, Me.DataGridViewTextBoxColumn54, Me.DataGridViewTextBoxColumn55, Me.DataGridViewTextBoxColumn56, Me.DataGridViewTextBoxColumn57, Me.Column36 })
			Me.dgwSalesReturn.Cursor = Global.System.Windows.Forms.Cursors.Hand
			dataGridViewCellStyle23.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft
			dataGridViewCellStyle23.BackColor = Global.System.Drawing.SystemColors.Window
			dataGridViewCellStyle23.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 8.25F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			dataGridViewCellStyle23.ForeColor = Global.System.Drawing.SystemColors.ControlText
			dataGridViewCellStyle23.SelectionBackColor = Global.System.Drawing.SystemColors.Highlight
			dataGridViewCellStyle23.SelectionForeColor = Global.System.Drawing.SystemColors.HighlightText
			dataGridViewCellStyle23.WrapMode = Global.System.Windows.Forms.DataGridViewTriState.[False]
			Me.dgwSalesReturn.DefaultCellStyle = dataGridViewCellStyle23
			Me.dgwSalesReturn.EnableHeadersVisualStyles = False
			Me.dgwSalesReturn.GridColor = Global.System.Drawing.Color.White
			Me.dgwSalesReturn.Location = New Global.System.Drawing.Point(6, 19)
			Me.dgwSalesReturn.MultiSelect = False
			Me.dgwSalesReturn.Name = "dgwSalesReturn"
			Me.dgwSalesReturn.[ReadOnly] = True
			Me.dgwSalesReturn.RowHeadersBorderStyle = Global.System.Windows.Forms.DataGridViewHeaderBorderStyle.[Single]
			dataGridViewCellStyle24.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft
			dataGridViewCellStyle24.BackColor = Global.System.Drawing.Color.DarkViolet
			dataGridViewCellStyle24.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 8.25F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			dataGridViewCellStyle24.ForeColor = Global.System.Drawing.Color.White
			dataGridViewCellStyle24.SelectionBackColor = Global.System.Drawing.Color.OrangeRed
			dataGridViewCellStyle24.SelectionForeColor = Global.System.Drawing.Color.White
			dataGridViewCellStyle24.WrapMode = Global.System.Windows.Forms.DataGridViewTriState.[True]
			Me.dgwSalesReturn.RowHeadersDefaultCellStyle = dataGridViewCellStyle24
			Me.dgwSalesReturn.RowHeadersWidth = 25
			Me.dgwSalesReturn.RowHeadersWidthSizeMode = Global.System.Windows.Forms.DataGridViewRowHeadersWidthSizeMode.DisableResizing
			dataGridViewCellStyle25.BackColor = Global.System.Drawing.Color.White
			dataGridViewCellStyle25.Font = New Global.System.Drawing.Font("Tahoma", 8.25F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			dataGridViewCellStyle25.SelectionBackColor = Global.System.Drawing.Color.DarkSlateGray
			dataGridViewCellStyle25.SelectionForeColor = Global.System.Drawing.Color.White
			Me.dgwSalesReturn.RowsDefaultCellStyle = dataGridViewCellStyle25
			Me.dgwSalesReturn.RowTemplate.Height = 25
			Me.dgwSalesReturn.RowTemplate.Resizable = Global.System.Windows.Forms.DataGridViewTriState.[False]
			Me.dgwSalesReturn.SelectionMode = Global.System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect
			Me.dgwSalesReturn.Size = New Global.System.Drawing.Size(684, 253)
			Me.dgwSalesReturn.TabIndex = 61
			Me.dgwSalesReturn.TabStop = False
			Me.DataGridViewTextBoxColumn33.HeaderText = "SR No."
			Me.DataGridViewTextBoxColumn33.Name = "DataGridViewTextBoxColumn33"
			Me.DataGridViewTextBoxColumn33.[ReadOnly] = True
			dataGridViewCellStyle26.Format = "dd/MM/yyyy"
			Me.DataGridViewTextBoxColumn34.DefaultCellStyle = dataGridViewCellStyle26
			Me.DataGridViewTextBoxColumn34.HeaderText = "SR Date"
			Me.DataGridViewTextBoxColumn34.Name = "DataGridViewTextBoxColumn34"
			Me.DataGridViewTextBoxColumn34.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn35.HeaderText = "Tax Type"
			Me.DataGridViewTextBoxColumn35.Name = "DataGridViewTextBoxColumn35"
			Me.DataGridViewTextBoxColumn35.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn36.HeaderText = "Sales Invoice No."
			Me.DataGridViewTextBoxColumn36.Name = "DataGridViewTextBoxColumn36"
			Me.DataGridViewTextBoxColumn36.[ReadOnly] = True
			dataGridViewCellStyle27.Format = "dd/MM/yyyy"
			Me.DataGridViewTextBoxColumn37.DefaultCellStyle = dataGridViewCellStyle27
			Me.DataGridViewTextBoxColumn37.HeaderText = "Sales Invoice Date"
			Me.DataGridViewTextBoxColumn37.Name = "DataGridViewTextBoxColumn37"
			Me.DataGridViewTextBoxColumn37.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn38.HeaderText = "Customer Name"
			Me.DataGridViewTextBoxColumn38.Name = "DataGridViewTextBoxColumn38"
			Me.DataGridViewTextBoxColumn38.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn39.HeaderText = "State"
			Me.DataGridViewTextBoxColumn39.Name = "DataGridViewTextBoxColumn39"
			Me.DataGridViewTextBoxColumn39.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn40.HeaderText = "GSTIN/UID"
			Me.DataGridViewTextBoxColumn40.Name = "DataGridViewTextBoxColumn40"
			Me.DataGridViewTextBoxColumn40.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn41.HeaderText = "Product Name"
			Me.DataGridViewTextBoxColumn41.Name = "DataGridViewTextBoxColumn41"
			Me.DataGridViewTextBoxColumn41.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn42.HeaderText = "HSN Code"
			Me.DataGridViewTextBoxColumn42.Name = "DataGridViewTextBoxColumn42"
			Me.DataGridViewTextBoxColumn42.[ReadOnly] = True
			dataGridViewCellStyle28.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			dataGridViewCellStyle28.Format = "N2"
			Me.DataGridViewTextBoxColumn43.DefaultCellStyle = dataGridViewCellStyle28
			Me.DataGridViewTextBoxColumn43.HeaderText = "Sales Rate"
			Me.DataGridViewTextBoxColumn43.Name = "DataGridViewTextBoxColumn43"
			Me.DataGridViewTextBoxColumn43.[ReadOnly] = True
			dataGridViewCellStyle29.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn44.DefaultCellStyle = dataGridViewCellStyle29
			Me.DataGridViewTextBoxColumn44.HeaderText = "Return Qty."
			Me.DataGridViewTextBoxColumn44.Name = "DataGridViewTextBoxColumn44"
			Me.DataGridViewTextBoxColumn44.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn45.HeaderText = "UOM"
			Me.DataGridViewTextBoxColumn45.Name = "DataGridViewTextBoxColumn45"
			Me.DataGridViewTextBoxColumn45.[ReadOnly] = True
			dataGridViewCellStyle30.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn46.DefaultCellStyle = dataGridViewCellStyle30
			Me.DataGridViewTextBoxColumn46.HeaderText = "Discount %"
			Me.DataGridViewTextBoxColumn46.Name = "DataGridViewTextBoxColumn46"
			Me.DataGridViewTextBoxColumn46.[ReadOnly] = True
			dataGridViewCellStyle31.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn47.DefaultCellStyle = dataGridViewCellStyle31
			Me.DataGridViewTextBoxColumn47.HeaderText = "Discount"
			Me.DataGridViewTextBoxColumn47.Name = "DataGridViewTextBoxColumn47"
			Me.DataGridViewTextBoxColumn47.[ReadOnly] = True
			dataGridViewCellStyle32.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn48.DefaultCellStyle = dataGridViewCellStyle32
			Me.DataGridViewTextBoxColumn48.HeaderText = "CGST %"
			Me.DataGridViewTextBoxColumn48.Name = "DataGridViewTextBoxColumn48"
			Me.DataGridViewTextBoxColumn48.[ReadOnly] = True
			dataGridViewCellStyle33.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn49.DefaultCellStyle = dataGridViewCellStyle33
			Me.DataGridViewTextBoxColumn49.HeaderText = "CGST"
			Me.DataGridViewTextBoxColumn49.Name = "DataGridViewTextBoxColumn49"
			Me.DataGridViewTextBoxColumn49.[ReadOnly] = True
			dataGridViewCellStyle34.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn50.DefaultCellStyle = dataGridViewCellStyle34
			Me.DataGridViewTextBoxColumn50.HeaderText = "SGST %"
			Me.DataGridViewTextBoxColumn50.Name = "DataGridViewTextBoxColumn50"
			Me.DataGridViewTextBoxColumn50.[ReadOnly] = True
			dataGridViewCellStyle35.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn51.DefaultCellStyle = dataGridViewCellStyle35
			Me.DataGridViewTextBoxColumn51.HeaderText = "SGST/UTGST"
			Me.DataGridViewTextBoxColumn51.Name = "DataGridViewTextBoxColumn51"
			Me.DataGridViewTextBoxColumn51.[ReadOnly] = True
			dataGridViewCellStyle36.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn52.DefaultCellStyle = dataGridViewCellStyle36
			Me.DataGridViewTextBoxColumn52.HeaderText = "IGST %"
			Me.DataGridViewTextBoxColumn52.Name = "DataGridViewTextBoxColumn52"
			Me.DataGridViewTextBoxColumn52.[ReadOnly] = True
			dataGridViewCellStyle37.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn53.DefaultCellStyle = dataGridViewCellStyle37
			Me.DataGridViewTextBoxColumn53.HeaderText = "IGST"
			Me.DataGridViewTextBoxColumn53.Name = "DataGridViewTextBoxColumn53"
			Me.DataGridViewTextBoxColumn53.[ReadOnly] = True
			dataGridViewCellStyle38.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn54.DefaultCellStyle = dataGridViewCellStyle38
			Me.DataGridViewTextBoxColumn54.HeaderText = "CESS %"
			Me.DataGridViewTextBoxColumn54.Name = "DataGridViewTextBoxColumn54"
			Me.DataGridViewTextBoxColumn54.[ReadOnly] = True
			dataGridViewCellStyle39.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn55.DefaultCellStyle = dataGridViewCellStyle39
			Me.DataGridViewTextBoxColumn55.HeaderText = "CESS"
			Me.DataGridViewTextBoxColumn55.Name = "DataGridViewTextBoxColumn55"
			Me.DataGridViewTextBoxColumn55.[ReadOnly] = True
			dataGridViewCellStyle40.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn56.DefaultCellStyle = dataGridViewCellStyle40
			Me.DataGridViewTextBoxColumn56.HeaderText = "Total Amount"
			Me.DataGridViewTextBoxColumn56.Name = "DataGridViewTextBoxColumn56"
			Me.DataGridViewTextBoxColumn56.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn57.HeaderText = "Barcode"
			Me.DataGridViewTextBoxColumn57.Name = "DataGridViewTextBoxColumn57"
			Me.DataGridViewTextBoxColumn57.[ReadOnly] = True
			Me.Column36.HeaderText = "SerialNo"
			Me.Column36.Name = "Column36"
			Me.Column36.[ReadOnly] = True
			Me.GroupBox3.Controls.Add(Me.dgwPurchase)
			Me.GroupBox3.Location = New Global.System.Drawing.Point(712, 112)
			Me.GroupBox3.Name = "GroupBox3"
			Me.GroupBox3.Size = New Global.System.Drawing.Size(744, 255)
			Me.GroupBox3.TabIndex = 66
			Me.GroupBox3.TabStop = False
			Me.GroupBox3.Text = "Purchase"
			Me.dgwPurchase.AllowUserToAddRows = False
			Me.dgwPurchase.AllowUserToDeleteRows = False
			dataGridViewCellStyle41.BackColor = Global.System.Drawing.Color.FloralWhite
			Me.dgwPurchase.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle41
			Me.dgwPurchase.Anchor = Global.System.Windows.Forms.AnchorStyles.Top Or Global.System.Windows.Forms.AnchorStyles.Bottom Or Global.System.Windows.Forms.AnchorStyles.Left Or Global.System.Windows.Forms.AnchorStyles.Right
			Me.dgwPurchase.BackgroundColor = Global.System.Drawing.Color.White
			Me.dgwPurchase.ColumnHeadersBorderStyle = Global.System.Windows.Forms.DataGridViewHeaderBorderStyle.[Single]
			dataGridViewCellStyle42.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter
			dataGridViewCellStyle42.BackColor = Global.System.Drawing.Color.DarkViolet
			dataGridViewCellStyle42.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 8.25F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			dataGridViewCellStyle42.ForeColor = Global.System.Drawing.Color.White
			dataGridViewCellStyle42.SelectionBackColor = Global.System.Drawing.Color.LightSteelBlue
			dataGridViewCellStyle42.SelectionForeColor = Global.System.Drawing.SystemColors.HighlightText
			dataGridViewCellStyle42.WrapMode = Global.System.Windows.Forms.DataGridViewTriState.[True]
			Me.dgwPurchase.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle42
			Me.dgwPurchase.ColumnHeadersHeight = 30
			Me.dgwPurchase.Columns.AddRange(New Global.System.Windows.Forms.DataGridViewColumn() { Me.DataGridViewTextBoxColumn1, Me.DataGridViewTextBoxColumn2, Me.DataGridViewTextBoxColumn3, Me.DataGridViewTextBoxColumn4, Me.DataGridViewTextBoxColumn5, Me.DataGridViewTextBoxColumn6, Me.DataGridViewTextBoxColumn7, Me.DataGridViewTextBoxColumn8, Me.DataGridViewTextBoxColumn9, Me.DataGridViewTextBoxColumn10, Me.DataGridViewTextBoxColumn11, Me.DataGridViewTextBoxColumn12, Me.DataGridViewTextBoxColumn13, Me.DataGridViewTextBoxColumn14, Me.DataGridViewTextBoxColumn15, Me.DataGridViewTextBoxColumn16, Me.DataGridViewTextBoxColumn17, Me.DataGridViewTextBoxColumn18, Me.DataGridViewTextBoxColumn19, Me.DataGridViewTextBoxColumn20, Me.DataGridViewTextBoxColumn21, Me.DataGridViewTextBoxColumn22, Me.DataGridViewTextBoxColumn23, Me.DataGridViewTextBoxColumn24, Me.DataGridViewTextBoxColumn25, Me.DataGridViewTextBoxColumn26, Me.DataGridViewTextBoxColumn27, Me.DataGridViewTextBoxColumn28, Me.DataGridViewTextBoxColumn29, Me.DataGridViewTextBoxColumn30, Me.DataGridViewTextBoxColumn31, Me.DataGridViewTextBoxColumn32, Me.Column33, Me.Column34, Me.Column35, Me.colSerial })
			Me.dgwPurchase.Cursor = Global.System.Windows.Forms.Cursors.Hand
			dataGridViewCellStyle43.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft
			dataGridViewCellStyle43.BackColor = Global.System.Drawing.SystemColors.Window
			dataGridViewCellStyle43.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 8.25F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			dataGridViewCellStyle43.ForeColor = Global.System.Drawing.SystemColors.ControlText
			dataGridViewCellStyle43.SelectionBackColor = Global.System.Drawing.SystemColors.Highlight
			dataGridViewCellStyle43.SelectionForeColor = Global.System.Drawing.SystemColors.HighlightText
			dataGridViewCellStyle43.WrapMode = Global.System.Windows.Forms.DataGridViewTriState.[False]
			Me.dgwPurchase.DefaultCellStyle = dataGridViewCellStyle43
			Me.dgwPurchase.EnableHeadersVisualStyles = False
			Me.dgwPurchase.GridColor = Global.System.Drawing.Color.White
			Me.dgwPurchase.Location = New Global.System.Drawing.Point(6, 19)
			Me.dgwPurchase.MultiSelect = False
			Me.dgwPurchase.Name = "dgwPurchase"
			Me.dgwPurchase.[ReadOnly] = True
			Me.dgwPurchase.RowHeadersBorderStyle = Global.System.Windows.Forms.DataGridViewHeaderBorderStyle.[Single]
			dataGridViewCellStyle44.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft
			dataGridViewCellStyle44.BackColor = Global.System.Drawing.Color.DarkViolet
			dataGridViewCellStyle44.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 8.25F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			dataGridViewCellStyle44.ForeColor = Global.System.Drawing.Color.White
			dataGridViewCellStyle44.SelectionBackColor = Global.System.Drawing.Color.OrangeRed
			dataGridViewCellStyle44.SelectionForeColor = Global.System.Drawing.Color.White
			dataGridViewCellStyle44.WrapMode = Global.System.Windows.Forms.DataGridViewTriState.[True]
			Me.dgwPurchase.RowHeadersDefaultCellStyle = dataGridViewCellStyle44
			Me.dgwPurchase.RowHeadersWidth = 25
			Me.dgwPurchase.RowHeadersWidthSizeMode = Global.System.Windows.Forms.DataGridViewRowHeadersWidthSizeMode.DisableResizing
			dataGridViewCellStyle45.BackColor = Global.System.Drawing.Color.White
			dataGridViewCellStyle45.Font = New Global.System.Drawing.Font("Tahoma", 8.25F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			dataGridViewCellStyle45.SelectionBackColor = Global.System.Drawing.Color.DarkSlateGray
			dataGridViewCellStyle45.SelectionForeColor = Global.System.Drawing.Color.White
			Me.dgwPurchase.RowsDefaultCellStyle = dataGridViewCellStyle45
			Me.dgwPurchase.RowTemplate.Height = 25
			Me.dgwPurchase.RowTemplate.Resizable = Global.System.Windows.Forms.DataGridViewTriState.[False]
			Me.dgwPurchase.SelectionMode = Global.System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect
			Me.dgwPurchase.Size = New Global.System.Drawing.Size(732, 236)
			Me.dgwPurchase.TabIndex = 60
			Me.dgwPurchase.TabStop = False
			Me.DataGridViewTextBoxColumn1.HeaderText = "Invoice No."
			Me.DataGridViewTextBoxColumn1.Name = "DataGridViewTextBoxColumn1"
			Me.DataGridViewTextBoxColumn1.[ReadOnly] = True
			dataGridViewCellStyle46.Format = "dd/MM/yyyy"
			Me.DataGridViewTextBoxColumn2.DefaultCellStyle = dataGridViewCellStyle46
			Me.DataGridViewTextBoxColumn2.HeaderText = "Invoice Date"
			Me.DataGridViewTextBoxColumn2.Name = "DataGridViewTextBoxColumn2"
			Me.DataGridViewTextBoxColumn2.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn3.HeaderText = "Tax Type"
			Me.DataGridViewTextBoxColumn3.Name = "DataGridViewTextBoxColumn3"
			Me.DataGridViewTextBoxColumn3.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn4.HeaderText = "Supplier's Invoice No."
			Me.DataGridViewTextBoxColumn4.Name = "DataGridViewTextBoxColumn4"
			Me.DataGridViewTextBoxColumn4.[ReadOnly] = True
			dataGridViewCellStyle47.Format = "dd/MM/yyyy"
			Me.DataGridViewTextBoxColumn5.DefaultCellStyle = dataGridViewCellStyle47
			Me.DataGridViewTextBoxColumn5.HeaderText = "Supplier's Invoice Date"
			Me.DataGridViewTextBoxColumn5.Name = "DataGridViewTextBoxColumn5"
			Me.DataGridViewTextBoxColumn5.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn6.HeaderText = "Supplier Name"
			Me.DataGridViewTextBoxColumn6.Name = "DataGridViewTextBoxColumn6"
			Me.DataGridViewTextBoxColumn6.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn7.HeaderText = "State"
			Me.DataGridViewTextBoxColumn7.Name = "DataGridViewTextBoxColumn7"
			Me.DataGridViewTextBoxColumn7.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn8.HeaderText = "GSTIN"
			Me.DataGridViewTextBoxColumn8.Name = "DataGridViewTextBoxColumn8"
			Me.DataGridViewTextBoxColumn8.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn9.HeaderText = "Product Name"
			Me.DataGridViewTextBoxColumn9.Name = "DataGridViewTextBoxColumn9"
			Me.DataGridViewTextBoxColumn9.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn10.HeaderText = "HSN Code"
			Me.DataGridViewTextBoxColumn10.Name = "DataGridViewTextBoxColumn10"
			Me.DataGridViewTextBoxColumn10.[ReadOnly] = True
			dataGridViewCellStyle48.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			dataGridViewCellStyle48.Format = "N2"
			Me.DataGridViewTextBoxColumn11.DefaultCellStyle = dataGridViewCellStyle48
			Me.DataGridViewTextBoxColumn11.HeaderText = "Purchase Rate"
			Me.DataGridViewTextBoxColumn11.Name = "DataGridViewTextBoxColumn11"
			Me.DataGridViewTextBoxColumn11.[ReadOnly] = True
			dataGridViewCellStyle49.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn12.DefaultCellStyle = dataGridViewCellStyle49
			Me.DataGridViewTextBoxColumn12.HeaderText = "Qty."
			Me.DataGridViewTextBoxColumn12.Name = "DataGridViewTextBoxColumn12"
			Me.DataGridViewTextBoxColumn12.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn13.HeaderText = "UOM"
			Me.DataGridViewTextBoxColumn13.Name = "DataGridViewTextBoxColumn13"
			Me.DataGridViewTextBoxColumn13.[ReadOnly] = True
			dataGridViewCellStyle50.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn14.DefaultCellStyle = dataGridViewCellStyle50
			Me.DataGridViewTextBoxColumn14.HeaderText = "Discount %"
			Me.DataGridViewTextBoxColumn14.Name = "DataGridViewTextBoxColumn14"
			Me.DataGridViewTextBoxColumn14.[ReadOnly] = True
			dataGridViewCellStyle51.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn15.DefaultCellStyle = dataGridViewCellStyle51
			Me.DataGridViewTextBoxColumn15.HeaderText = "Discount"
			Me.DataGridViewTextBoxColumn15.Name = "DataGridViewTextBoxColumn15"
			Me.DataGridViewTextBoxColumn15.[ReadOnly] = True
			dataGridViewCellStyle52.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn16.DefaultCellStyle = dataGridViewCellStyle52
			Me.DataGridViewTextBoxColumn16.HeaderText = "CGST %"
			Me.DataGridViewTextBoxColumn16.Name = "DataGridViewTextBoxColumn16"
			Me.DataGridViewTextBoxColumn16.[ReadOnly] = True
			dataGridViewCellStyle53.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn17.DefaultCellStyle = dataGridViewCellStyle53
			Me.DataGridViewTextBoxColumn17.HeaderText = "CGST"
			Me.DataGridViewTextBoxColumn17.Name = "DataGridViewTextBoxColumn17"
			Me.DataGridViewTextBoxColumn17.[ReadOnly] = True
			dataGridViewCellStyle54.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn18.DefaultCellStyle = dataGridViewCellStyle54
			Me.DataGridViewTextBoxColumn18.HeaderText = "SGST %"
			Me.DataGridViewTextBoxColumn18.Name = "DataGridViewTextBoxColumn18"
			Me.DataGridViewTextBoxColumn18.[ReadOnly] = True
			dataGridViewCellStyle55.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn19.DefaultCellStyle = dataGridViewCellStyle55
			Me.DataGridViewTextBoxColumn19.HeaderText = "SGST/UTGST"
			Me.DataGridViewTextBoxColumn19.Name = "DataGridViewTextBoxColumn19"
			Me.DataGridViewTextBoxColumn19.[ReadOnly] = True
			dataGridViewCellStyle56.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn20.DefaultCellStyle = dataGridViewCellStyle56
			Me.DataGridViewTextBoxColumn20.HeaderText = "IGST %"
			Me.DataGridViewTextBoxColumn20.Name = "DataGridViewTextBoxColumn20"
			Me.DataGridViewTextBoxColumn20.[ReadOnly] = True
			dataGridViewCellStyle57.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn21.DefaultCellStyle = dataGridViewCellStyle57
			Me.DataGridViewTextBoxColumn21.HeaderText = "IGST"
			Me.DataGridViewTextBoxColumn21.Name = "DataGridViewTextBoxColumn21"
			Me.DataGridViewTextBoxColumn21.[ReadOnly] = True
			dataGridViewCellStyle58.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn22.DefaultCellStyle = dataGridViewCellStyle58
			Me.DataGridViewTextBoxColumn22.HeaderText = "CESS %"
			Me.DataGridViewTextBoxColumn22.Name = "DataGridViewTextBoxColumn22"
			Me.DataGridViewTextBoxColumn22.[ReadOnly] = True
			dataGridViewCellStyle59.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn23.DefaultCellStyle = dataGridViewCellStyle59
			Me.DataGridViewTextBoxColumn23.HeaderText = "CESS"
			Me.DataGridViewTextBoxColumn23.Name = "DataGridViewTextBoxColumn23"
			Me.DataGridViewTextBoxColumn23.[ReadOnly] = True
			dataGridViewCellStyle60.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.DataGridViewTextBoxColumn24.DefaultCellStyle = dataGridViewCellStyle60
			Me.DataGridViewTextBoxColumn24.HeaderText = "Total Amount"
			Me.DataGridViewTextBoxColumn24.Name = "DataGridViewTextBoxColumn24"
			Me.DataGridViewTextBoxColumn24.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn25.HeaderText = "Reverse Charges"
			Me.DataGridViewTextBoxColumn25.Name = "DataGridViewTextBoxColumn25"
			Me.DataGridViewTextBoxColumn25.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn26.HeaderText = "Product Code"
			Me.DataGridViewTextBoxColumn26.Name = "DataGridViewTextBoxColumn26"
			Me.DataGridViewTextBoxColumn26.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn27.HeaderText = "Barcode"
			Me.DataGridViewTextBoxColumn27.Name = "DataGridViewTextBoxColumn27"
			Me.DataGridViewTextBoxColumn27.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn28.HeaderText = "Colour"
			Me.DataGridViewTextBoxColumn28.Name = "DataGridViewTextBoxColumn28"
			Me.DataGridViewTextBoxColumn28.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn29.HeaderText = "Size"
			Me.DataGridViewTextBoxColumn29.Name = "DataGridViewTextBoxColumn29"
			Me.DataGridViewTextBoxColumn29.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn30.HeaderText = "Info"
			Me.DataGridViewTextBoxColumn30.Name = "DataGridViewTextBoxColumn30"
			Me.DataGridViewTextBoxColumn30.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn31.HeaderText = "Batch/Serial"
			Me.DataGridViewTextBoxColumn31.Name = "DataGridViewTextBoxColumn31"
			Me.DataGridViewTextBoxColumn31.[ReadOnly] = True
			Me.DataGridViewTextBoxColumn32.HeaderText = "Mfg Date"
			Me.DataGridViewTextBoxColumn32.Name = "DataGridViewTextBoxColumn32"
			Me.DataGridViewTextBoxColumn32.[ReadOnly] = True
			Me.Column33.HeaderText = "Exp Date"
			Me.Column33.Name = "Column33"
			Me.Column33.[ReadOnly] = True
			Me.Column34.HeaderText = "IMEI-1"
			Me.Column34.Name = "Column34"
			Me.Column34.[ReadOnly] = True
			Me.Column35.HeaderText = "IMEI-2"
			Me.Column35.Name = "Column35"
			Me.Column35.[ReadOnly] = True
			Me.colSerial.HeaderText = "SerialNo"
			Me.colSerial.Name = "colSerial"
			Me.colSerial.[ReadOnly] = True
			Me.GroupBox1.Controls.Add(Me.dgw)
			Me.GroupBox1.Location = New Global.System.Drawing.Point(9, 112)
			Me.GroupBox1.Name = "GroupBox1"
			Me.GroupBox1.Size = New Global.System.Drawing.Size(696, 261)
			Me.GroupBox1.TabIndex = 65
			Me.GroupBox1.TabStop = False
			Me.GroupBox1.Text = "Sales"
			Me.dgw.AllowUserToAddRows = False
			Me.dgw.AllowUserToDeleteRows = False
			dataGridViewCellStyle61.BackColor = Global.System.Drawing.Color.FloralWhite
			Me.dgw.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle61
			Me.dgw.Anchor = Global.System.Windows.Forms.AnchorStyles.Top Or Global.System.Windows.Forms.AnchorStyles.Bottom Or Global.System.Windows.Forms.AnchorStyles.Left Or Global.System.Windows.Forms.AnchorStyles.Right
			Me.dgw.BackgroundColor = Global.System.Drawing.Color.White
			Me.dgw.ColumnHeadersBorderStyle = Global.System.Windows.Forms.DataGridViewHeaderBorderStyle.[Single]
			dataGridViewCellStyle62.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter
			dataGridViewCellStyle62.BackColor = Global.System.Drawing.Color.DarkViolet
			dataGridViewCellStyle62.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 8.25F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			dataGridViewCellStyle62.ForeColor = Global.System.Drawing.Color.White
			dataGridViewCellStyle62.SelectionBackColor = Global.System.Drawing.Color.LightSteelBlue
			dataGridViewCellStyle62.SelectionForeColor = Global.System.Drawing.SystemColors.HighlightText
			dataGridViewCellStyle62.WrapMode = Global.System.Windows.Forms.DataGridViewTriState.[True]
			Me.dgw.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle62
			Me.dgw.ColumnHeadersHeight = 30
			Me.dgw.Columns.AddRange(New Global.System.Windows.Forms.DataGridViewColumn() { Me.Column2, Me.Column3, Me.Column14, Me.Column6, Me.Column16, Me.Column17, Me.Column13, Me.Column15, Me.Column18, Me.Column4, Me.Column9, Me.Column1, Me.Column8, Me.Column5, Me.Column19, Me.Column11, Me.Column20, Me.Column12, Me.Column21, Me.Column27, Me.Column22, Me.Column7, Me.Column10, Me.Column23, Me.Column24, Me.Column25, Me.Column26, Me.Column28, Me.Column29, Me.Column30, Me.Column31, Me.Column32, Me.colSerialNo1 })
			Me.dgw.Cursor = Global.System.Windows.Forms.Cursors.Hand
			dataGridViewCellStyle63.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft
			dataGridViewCellStyle63.BackColor = Global.System.Drawing.SystemColors.Window
			dataGridViewCellStyle63.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 8.25F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			dataGridViewCellStyle63.ForeColor = Global.System.Drawing.SystemColors.ControlText
			dataGridViewCellStyle63.SelectionBackColor = Global.System.Drawing.SystemColors.Highlight
			dataGridViewCellStyle63.SelectionForeColor = Global.System.Drawing.SystemColors.HighlightText
			dataGridViewCellStyle63.WrapMode = Global.System.Windows.Forms.DataGridViewTriState.[False]
			Me.dgw.DefaultCellStyle = dataGridViewCellStyle63
			Me.dgw.EnableHeadersVisualStyles = False
			Me.dgw.GridColor = Global.System.Drawing.Color.White
			Me.dgw.Location = New Global.System.Drawing.Point(6, 19)
			Me.dgw.MultiSelect = False
			Me.dgw.Name = "dgw"
			Me.dgw.[ReadOnly] = True
			Me.dgw.RowHeadersBorderStyle = Global.System.Windows.Forms.DataGridViewHeaderBorderStyle.[Single]
			dataGridViewCellStyle64.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft
			dataGridViewCellStyle64.BackColor = Global.System.Drawing.Color.DarkViolet
			dataGridViewCellStyle64.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 8.25F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			dataGridViewCellStyle64.ForeColor = Global.System.Drawing.Color.White
			dataGridViewCellStyle64.SelectionBackColor = Global.System.Drawing.Color.OrangeRed
			dataGridViewCellStyle64.SelectionForeColor = Global.System.Drawing.Color.White
			dataGridViewCellStyle64.WrapMode = Global.System.Windows.Forms.DataGridViewTriState.[True]
			Me.dgw.RowHeadersDefaultCellStyle = dataGridViewCellStyle64
			Me.dgw.RowHeadersWidth = 25
			Me.dgw.RowHeadersWidthSizeMode = Global.System.Windows.Forms.DataGridViewRowHeadersWidthSizeMode.DisableResizing
			dataGridViewCellStyle65.BackColor = Global.System.Drawing.Color.White
			dataGridViewCellStyle65.Font = New Global.System.Drawing.Font("Tahoma", 8.25F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			dataGridViewCellStyle65.SelectionBackColor = Global.System.Drawing.Color.DarkSlateGray
			dataGridViewCellStyle65.SelectionForeColor = Global.System.Drawing.Color.White
			Me.dgw.RowsDefaultCellStyle = dataGridViewCellStyle65
			Me.dgw.RowTemplate.Height = 25
			Me.dgw.RowTemplate.Resizable = Global.System.Windows.Forms.DataGridViewTriState.[False]
			Me.dgw.SelectionMode = Global.System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect
			Me.dgw.Size = New Global.System.Drawing.Size(684, 236)
			Me.dgw.TabIndex = 43
			Me.dgw.TabStop = False
			Me.Column2.HeaderText = "Invoice No."
			Me.Column2.Name = "Column2"
			Me.Column2.[ReadOnly] = True
			dataGridViewCellStyle66.Format = "dd/MM/yyyy"
			Me.Column3.DefaultCellStyle = dataGridViewCellStyle66
			Me.Column3.HeaderText = "Invoice Date"
			Me.Column3.Name = "Column3"
			Me.Column3.[ReadOnly] = True
			Me.Column14.HeaderText = "Tax Type"
			Me.Column14.Name = "Column14"
			Me.Column14.[ReadOnly] = True
			Me.Column6.HeaderText = "Customer Name"
			Me.Column6.Name = "Column6"
			Me.Column6.[ReadOnly] = True
			Me.Column16.HeaderText = "State"
			Me.Column16.Name = "Column16"
			Me.Column16.[ReadOnly] = True
			Me.Column17.HeaderText = "GSTIN/UID"
			Me.Column17.Name = "Column17"
			Me.Column17.[ReadOnly] = True
			Me.Column13.HeaderText = "Product Name"
			Me.Column13.Name = "Column13"
			Me.Column13.[ReadOnly] = True
			Me.Column15.HeaderText = "HSN Code"
			Me.Column15.Name = "Column15"
			Me.Column15.[ReadOnly] = True
			dataGridViewCellStyle67.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			dataGridViewCellStyle67.Format = "N2"
			Me.Column18.DefaultCellStyle = dataGridViewCellStyle67
			Me.Column18.HeaderText = "Sales Rate"
			Me.Column18.Name = "Column18"
			Me.Column18.[ReadOnly] = True
			dataGridViewCellStyle68.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.Column4.DefaultCellStyle = dataGridViewCellStyle68
			Me.Column4.HeaderText = "Qty."
			Me.Column4.Name = "Column4"
			Me.Column4.[ReadOnly] = True
			Me.Column9.HeaderText = "UOM"
			Me.Column9.Name = "Column9"
			Me.Column9.[ReadOnly] = True
			dataGridViewCellStyle69.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.Column1.DefaultCellStyle = dataGridViewCellStyle69
			Me.Column1.HeaderText = "Discount %"
			Me.Column1.Name = "Column1"
			Me.Column1.[ReadOnly] = True
			dataGridViewCellStyle70.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.Column8.DefaultCellStyle = dataGridViewCellStyle70
			Me.Column8.HeaderText = "Discount"
			Me.Column8.Name = "Column8"
			Me.Column8.[ReadOnly] = True
			dataGridViewCellStyle71.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.Column5.DefaultCellStyle = dataGridViewCellStyle71
			Me.Column5.HeaderText = "CGST %"
			Me.Column5.Name = "Column5"
			Me.Column5.[ReadOnly] = True
			dataGridViewCellStyle72.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.Column19.DefaultCellStyle = dataGridViewCellStyle72
			Me.Column19.HeaderText = "CGST"
			Me.Column19.Name = "Column19"
			Me.Column19.[ReadOnly] = True
			dataGridViewCellStyle73.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.Column11.DefaultCellStyle = dataGridViewCellStyle73
			Me.Column11.HeaderText = "SGST %"
			Me.Column11.Name = "Column11"
			Me.Column11.[ReadOnly] = True
			dataGridViewCellStyle74.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.Column20.DefaultCellStyle = dataGridViewCellStyle74
			Me.Column20.HeaderText = "SGST/UTGST"
			Me.Column20.Name = "Column20"
			Me.Column20.[ReadOnly] = True
			dataGridViewCellStyle75.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.Column12.DefaultCellStyle = dataGridViewCellStyle75
			Me.Column12.HeaderText = "IGST %"
			Me.Column12.Name = "Column12"
			Me.Column12.[ReadOnly] = True
			dataGridViewCellStyle76.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.Column21.DefaultCellStyle = dataGridViewCellStyle76
			Me.Column21.HeaderText = "IGST"
			Me.Column21.Name = "Column21"
			Me.Column21.[ReadOnly] = True
			dataGridViewCellStyle77.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.Column27.DefaultCellStyle = dataGridViewCellStyle77
			Me.Column27.HeaderText = "CESS %"
			Me.Column27.Name = "Column27"
			Me.Column27.[ReadOnly] = True
			dataGridViewCellStyle78.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.Column22.DefaultCellStyle = dataGridViewCellStyle78
			Me.Column22.HeaderText = "CESS"
			Me.Column22.Name = "Column22"
			Me.Column22.[ReadOnly] = True
			dataGridViewCellStyle79.Alignment = Global.System.Windows.Forms.DataGridViewContentAlignment.MiddleRight
			Me.Column7.DefaultCellStyle = dataGridViewCellStyle79
			Me.Column7.HeaderText = "Total Amount"
			Me.Column7.Name = "Column7"
			Me.Column7.[ReadOnly] = True
			Me.Column10.HeaderText = "Product Code"
			Me.Column10.Name = "Column10"
			Me.Column10.[ReadOnly] = True
			Me.Column23.HeaderText = "Barcode"
			Me.Column23.Name = "Column23"
			Me.Column23.[ReadOnly] = True
			Me.Column24.HeaderText = "IMEI(1)"
			Me.Column24.Name = "Column24"
			Me.Column24.[ReadOnly] = True
			Me.Column25.HeaderText = "IMEI(2)"
			Me.Column25.Name = "Column25"
			Me.Column25.[ReadOnly] = True
			Me.Column26.HeaderText = "Description"
			Me.Column26.Name = "Column26"
			Me.Column26.[ReadOnly] = True
			Me.Column28.HeaderText = "Batch/Serial"
			Me.Column28.Name = "Column28"
			Me.Column28.[ReadOnly] = True
			Me.Column29.HeaderText = "Mfg Date"
			Me.Column29.Name = "Column29"
			Me.Column29.[ReadOnly] = True
			Me.Column30.HeaderText = "Exp Date"
			Me.Column30.Name = "Column30"
			Me.Column30.[ReadOnly] = True
			Me.Column31.HeaderText = "Size"
			Me.Column31.Name = "Column31"
			Me.Column31.[ReadOnly] = True
			Me.Column32.HeaderText = "Colour"
			Me.Column32.Name = "Column32"
			Me.Column32.[ReadOnly] = True
			Me.colSerialNo1.HeaderText = "SerialNo"
			Me.colSerialNo1.Name = "colSerialNo1"
			Me.colSerialNo1.[ReadOnly] = True
			Me.Label5.AutoSize = True
			Me.Label5.Location = New Global.System.Drawing.Point(6, 28)
			Me.Label5.Name = "Label5"
			Me.Label5.Size = New Global.System.Drawing.Size(129, 13)
			Me.Label5.TabIndex = 64
			Me.Label5.Text = "Search  by serial number :"
			Me.txtSerialNumber.Location = New Global.System.Drawing.Point(9, 48)
			Me.txtSerialNumber.Name = "txtSerialNumber"
			Me.txtSerialNumber.Size = New Global.System.Drawing.Size(147, 20)
			Me.txtSerialNumber.TabIndex = 63
			Me.lblTotalAmount.AutoSize = True
			Me.lblTotalAmount.ForeColor = Global.System.Drawing.Color.Blue
			Me.lblTotalAmount.Location = New Global.System.Drawing.Point(817, 661)
			Me.lblTotalAmount.Name = "lblTotalAmount"
			Me.lblTotalAmount.Size = New Global.System.Drawing.Size(77, 13)
			Me.lblTotalAmount.TabIndex = 59
			Me.lblTotalAmount.Text = "lblTotalAmount"
			Me.Label6.AutoSize = True
			Me.Label6.ForeColor = Global.System.Drawing.Color.Crimson
			Me.Label6.Location = New Global.System.Drawing.Point(3, 661)
			Me.Label6.Name = "Label6"
			Me.Label6.Size = New Global.System.Drawing.Size(253, 13)
			Me.Label6.TabIndex = 58
			Me.Label6.Text = "Info : Double lick on cell to copy the Invoice number"
			Me.Panel2.BorderStyle = Global.System.Windows.Forms.BorderStyle.FixedSingle
			Me.Panel2.Controls.Add(Me.Label8)
			Me.Panel2.Controls.Add(Me.ComboBox2)
			Me.Panel2.Controls.Add(Me.Button1)
			Me.Panel2.Controls.Add(Me.Label3)
			Me.Panel2.Controls.Add(Me.TextBox1)
			Me.Panel2.Controls.Add(Me.ComboBox1)
			Me.Panel2.Location = New Global.System.Drawing.Point(575, 38)
			Me.Panel2.Name = "Panel2"
			Me.Panel2.Size = New Global.System.Drawing.Size(367, 68)
			Me.Panel2.TabIndex = 1
			Me.Label8.AutoSize = True
			Me.Label8.Location = New Global.System.Drawing.Point(175, 26)
			Me.Label8.Name = "Label8"
			Me.Label8.Size = New Global.System.Drawing.Size(58, 13)
			Me.Label8.TabIndex = 22
			Me.Label8.Text = "Tax Type :"
			Me.ComboBox2.Cursor = Global.System.Windows.Forms.Cursors.Hand
			Me.ComboBox2.DropDownStyle = Global.System.Windows.Forms.ComboBoxStyle.DropDownList
			Me.ComboBox2.FormattingEnabled = True
			Me.ComboBox2.Items.AddRange(New Object() { "GST", "NON GST" })
			Me.ComboBox2.Location = New Global.System.Drawing.Point(178, 42)
			Me.ComboBox2.Name = "ComboBox2"
			Me.ComboBox2.Size = New Global.System.Drawing.Size(129, 21)
			Me.ComboBox2.TabIndex = 2
			Me.Button1.BackColor = Global.System.Drawing.Color.Transparent
			Me.Button1.Cursor = Global.System.Windows.Forms.Cursors.Hand
			Me.Button1.FlatStyle = Global.System.Windows.Forms.FlatStyle.Flat
			Me.Button1.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 9F, Global.System.Drawing.FontStyle.Regular, Global.System.Drawing.GraphicsUnit.Point, 0)
			Me.Button1.ForeColor = Global.System.Drawing.Color.White
			Me.Button1.Image = CType(componentResourceManager.GetObject("Button1.Image"), Global.System.Drawing.Image)
			Me.Button1.Location = New Global.System.Drawing.Point(322, 13)
			Me.Button1.Name = "Button1"
			Me.Button1.Size = New Global.System.Drawing.Size(37, 37)
			Me.Button1.TabIndex = 3
			Me.Button1.TextAlign = Global.System.Drawing.ContentAlignment.MiddleRight
			Me.Button1.UseVisualStyleBackColor = False
			Me.Label3.AutoSize = True
			Me.Label3.Location = New Global.System.Drawing.Point(0, 2)
			Me.Label3.Name = "Label3"
			Me.Label3.Size = New Global.System.Drawing.Size(146, 13)
			Me.Label3.TabIndex = 15
			Me.Label3.Text = "Select Category and Search :"
			Me.TextBox1.Location = New Global.System.Drawing.Point(3, 43)
			Me.TextBox1.Name = "TextBox1"
			Me.TextBox1.Size = New Global.System.Drawing.Size(147, 20)
			Me.TextBox1.TabIndex = 1
			Me.ComboBox1.DropDownStyle = Global.System.Windows.Forms.ComboBoxStyle.DropDownList
			Me.ComboBox1.FormattingEnabled = True
			Me.ComboBox1.Items.AddRange(New Object() { "Sales Inovice No", "Sales Customer Name", "Sales Product Name", "Sales Product Code", "Sales Barcode", "Sales IMEI (1)", "Sales IMEI (2)", "Sales Description", "Sales Batch", "Sales Size", "Sales Colour", "Sales Return Inovice No", "Sales Return Customer Name", "Sales Return Product Name", "Sales Return Product Code", "Purchase Inovice No", "Purchase Customer Name", "Purchase Product Name", "Purchase Product Code", "Purchase Return Inovice No", "Purchase Return Customer Name", "Purchase Return Product Name", "Purchase Return Product Code" })
			Me.ComboBox1.Location = New Global.System.Drawing.Point(3, 19)
			Me.ComboBox1.Name = "ComboBox1"
			Me.ComboBox1.Size = New Global.System.Drawing.Size(147, 21)
			Me.ComboBox1.TabIndex = 0
			Me.GroupBox2.Controls.Add(Me.btnGetData)
			Me.GroupBox2.Controls.Add(Me.dtpDateTo)
			Me.GroupBox2.Controls.Add(Me.Label2)
			Me.GroupBox2.Controls.Add(Me.Label4)
			Me.GroupBox2.Controls.Add(Me.dtpDateFrom)
			Me.GroupBox2.Location = New Global.System.Drawing.Point(9, 30)
			Me.GroupBox2.Name = "GroupBox2"
			Me.GroupBox2.Size = New Global.System.Drawing.Size(337, 76)
			Me.GroupBox2.TabIndex = 0
			Me.GroupBox2.TabStop = False
			Me.GroupBox2.Text = "Search by Invoice Date"
			Me.btnGetData.Anchor = Global.System.Windows.Forms.AnchorStyles.Top Or Global.System.Windows.Forms.AnchorStyles.Right
			Me.btnGetData.BackColor = Global.System.Drawing.Color.MediumVioletRed
			Me.btnGetData.FlatAppearance.BorderSize = 0
			Me.btnGetData.FlatStyle = Global.System.Windows.Forms.FlatStyle.Flat
			Me.btnGetData.Font = New Global.System.Drawing.Font("Segoe UI Semibold", 12F, Global.System.Drawing.FontStyle.Bold, Global.System.Drawing.GraphicsUnit.Point, 0)
			Me.btnGetData.ForeColor = Global.System.Drawing.Color.White
			Me.btnGetData.GradientBottom = Global.System.Drawing.Color.FromArgb(45, 63, 83)
			Me.btnGetData.GradientTop = Global.System.Drawing.Color.RoyalBlue
			Me.btnGetData.Image = CType(componentResourceManager.GetObject("btnGetData.Image"), Global.System.Drawing.Image)
			Me.btnGetData.ImageAlign = Global.System.Drawing.ContentAlignment.MiddleLeft
			Me.btnGetData.Location = New Global.System.Drawing.Point(256, 36)
			Me.btnGetData.Name = "btnGetData"
			Me.btnGetData.Size = New Global.System.Drawing.Size(74, 30)
			Me.btnGetData.TabIndex = 516
			Me.btnGetData.Text = "Get Data"
			Me.btnGetData.TextAlign = Global.System.Drawing.ContentAlignment.MiddleRight
			Me.btnGetData.UseVisualStyleBackColor = False
			Me.dtpDateTo.CustomFormat = "dd/MM/yyyy"
			Me.dtpDateTo.Format = Global.System.Windows.Forms.DateTimePickerFormat.Custom
			Me.dtpDateTo.Location = New Global.System.Drawing.Point(131, 41)
			Me.dtpDateTo.Name = "dtpDateTo"
			Me.dtpDateTo.Size = New Global.System.Drawing.Size(119, 20)
			Me.dtpDateTo.TabIndex = 1
			Me.Label2.AutoSize = True
			Me.Label2.Location = New Global.System.Drawing.Point(128, 22)
			Me.Label2.Name = "Label2"
			Me.Label2.Size = New Global.System.Drawing.Size(26, 13)
			Me.Label2.TabIndex = 13
			Me.Label2.Text = "To :"
			Me.Label4.AutoSize = True
			Me.Label4.Location = New Global.System.Drawing.Point(3, 22)
			Me.Label4.Name = "Label4"
			Me.Label4.Size = New Global.System.Drawing.Size(36, 13)
			Me.Label4.TabIndex = 12
			Me.Label4.Text = "From :"
			Me.dtpDateFrom.CustomFormat = "dd/MM/yyyy"
			Me.dtpDateFrom.Format = Global.System.Windows.Forms.DateTimePickerFormat.Custom
			Me.dtpDateFrom.Location = New Global.System.Drawing.Point(6, 41)
			Me.dtpDateFrom.Name = "dtpDateFrom"
			Me.dtpDateFrom.Size = New Global.System.Drawing.Size(119, 20)
			Me.dtpDateFrom.TabIndex = 0
			Me.Panel5.BorderStyle = Global.System.Windows.Forms.BorderStyle.FixedSingle
			Me.Panel5.Controls.Add(Me.GelButton1)
			Me.Panel5.Controls.Add(Me.btnReset)
			Me.Panel5.Location = New Global.System.Drawing.Point(1148, 33)
			Me.Panel5.Name = "Panel5"
			Me.Panel5.Size = New Global.System.Drawing.Size(296, 68)
			Me.Panel5.TabIndex = 2
			Me.GelButton1.Anchor = Global.System.Windows.Forms.AnchorStyles.Top Or Global.System.Windows.Forms.AnchorStyles.Right
			Me.GelButton1.BackColor = Global.System.Drawing.Color.MediumVioletRed
			Me.GelButton1.FlatAppearance.BorderSize = 0
			Me.GelButton1.FlatStyle = Global.System.Windows.Forms.FlatStyle.Flat
			Me.GelButton1.Font = New Global.System.Drawing.Font("Segoe UI Semibold", 12F, Global.System.Drawing.FontStyle.Bold, Global.System.Drawing.GraphicsUnit.Point, 0)
			Me.GelButton1.ForeColor = Global.System.Drawing.Color.White
			Me.GelButton1.GradientBottom = Global.System.Drawing.Color.LimeGreen
			Me.GelButton1.GradientTop = Global.System.Drawing.Color.FromArgb(255, 128, 128)
			Me.GelButton1.Image = CType(componentResourceManager.GetObject("GelButton1.Image"), Global.System.Drawing.Image)
			Me.GelButton1.ImageAlign = Global.System.Drawing.ContentAlignment.MiddleLeft
			Me.GelButton1.Location = New Global.System.Drawing.Point(162, 9)
			Me.GelButton1.Name = "GelButton1"
			Me.GelButton1.Size = New Global.System.Drawing.Size(123, 43)
			Me.GelButton1.TabIndex = 519
			Me.GelButton1.Text = "&Export Excel"
			Me.GelButton1.TextAlign = Global.System.Drawing.ContentAlignment.MiddleRight
			Me.GelButton1.UseVisualStyleBackColor = False
			Me.GelButton1.Visible = False
			Me.btnReset.Anchor = Global.System.Windows.Forms.AnchorStyles.Top Or Global.System.Windows.Forms.AnchorStyles.Right
			Me.btnReset.BackColor = Global.System.Drawing.Color.MediumVioletRed
			Me.btnReset.FlatAppearance.BorderSize = 0
			Me.btnReset.FlatStyle = Global.System.Windows.Forms.FlatStyle.Flat
			Me.btnReset.Font = New Global.System.Drawing.Font("Segoe UI Semibold", 12F, Global.System.Drawing.FontStyle.Bold, Global.System.Drawing.GraphicsUnit.Point, 0)
			Me.btnReset.ForeColor = Global.System.Drawing.Color.White
			Me.btnReset.GradientBottom = Global.System.Drawing.Color.Red
			Me.btnReset.GradientTop = Global.System.Drawing.Color.FromArgb(255, 128, 128)
			Me.btnReset.Image = CType(componentResourceManager.GetObject("btnReset.Image"), Global.System.Drawing.Image)
			Me.btnReset.ImageAlign = Global.System.Drawing.ContentAlignment.MiddleLeft
			Me.btnReset.Location = New Global.System.Drawing.Point(34, 9)
			Me.btnReset.Name = "btnReset"
			Me.btnReset.Size = New Global.System.Drawing.Size(123, 43)
			Me.btnReset.TabIndex = 518
			Me.btnReset.Text = "&Reset"
			Me.btnReset.TextAlign = Global.System.Drawing.ContentAlignment.MiddleRight
			Me.btnReset.UseVisualStyleBackColor = False
			Me.Label1.Anchor = Global.System.Windows.Forms.AnchorStyles.Top Or Global.System.Windows.Forms.AnchorStyles.Left Or Global.System.Windows.Forms.AnchorStyles.Right
			Me.Label1.BackColor = Global.System.Drawing.Color.RoyalBlue
			Me.Label1.Font = New Global.System.Drawing.Font("Microsoft Sans Serif", 14.25F, Global.System.Drawing.FontStyle.Bold, Global.System.Drawing.GraphicsUnit.Point, 0)
			Me.Label1.ForeColor = Global.System.Drawing.Color.White
			Me.Label1.Location = New Global.System.Drawing.Point(-1, -1)
			Me.Label1.Name = "Label1"
			Me.Label1.Size = New Global.System.Drawing.Size(1485, 31)
			Me.Label1.TabIndex = 57
			Me.Label1.Text = "Serialwise Report"
			Me.Label1.TextAlign = Global.System.Drawing.ContentAlignment.MiddleCenter
			Me.GroupBox6.Controls.Add(Me.Label5)
			Me.GroupBox6.Controls.Add(Me.txtSerialNumber)
			Me.GroupBox6.Location = New Global.System.Drawing.Point(377, 30)
			Me.GroupBox6.Name = "GroupBox6"
			Me.GroupBox6.Size = New Global.System.Drawing.Size(166, 76)
			Me.GroupBox6.TabIndex = 69
			Me.GroupBox6.TabStop = False
			MyBase.AutoScaleDimensions = New Global.System.Drawing.SizeF(6F, 13F)
			MyBase.AutoScaleMode = Global.System.Windows.Forms.AutoScaleMode.Font
			Me.BackColor = Global.System.Drawing.Color.FromArgb(45, 63, 83)
			MyBase.ClientSize = New Global.System.Drawing.Size(1469, 684)
			MyBase.Controls.Add(Me.Panel1)
			Me.DoubleBuffered = True
			MyBase.FormBorderStyle = Global.System.Windows.Forms.FormBorderStyle.FixedSingle
			MyBase.Icon = CType(componentResourceManager.GetObject("$this.Icon"), Global.System.Drawing.Icon)
			MyBase.KeyPreview = True
			MyBase.Name = "frmSerialwiseReport"
			MyBase.ShowIcon = False
			MyBase.ShowInTaskbar = False
			MyBase.StartPosition = Global.System.Windows.Forms.FormStartPosition.CenterParent
			Me.Panel1.ResumeLayout(False)
			Me.Panel1.PerformLayout()
			Me.GroupBox5.ResumeLayout(False)
			CType(Me.dgwPurchaseReturn, Global.System.ComponentModel.ISupportInitialize).EndInit()
			Me.GroupBox4.ResumeLayout(False)
			CType(Me.dgwSalesReturn, Global.System.ComponentModel.ISupportInitialize).EndInit()
			Me.GroupBox3.ResumeLayout(False)
			CType(Me.dgwPurchase, Global.System.ComponentModel.ISupportInitialize).EndInit()
			Me.GroupBox1.ResumeLayout(False)
			CType(Me.dgw, Global.System.ComponentModel.ISupportInitialize).EndInit()
			Me.Panel2.ResumeLayout(False)
			Me.Panel2.PerformLayout()
			Me.GroupBox2.ResumeLayout(False)
			Me.GroupBox2.PerformLayout()
			Me.Panel5.ResumeLayout(False)
			Me.GroupBox6.ResumeLayout(False)
			Me.GroupBox6.PerformLayout()
			MyBase.ResumeLayout(False)
		End Sub

		' Token: 0x04003EEA RID: 16106
		Private components As Global.System.ComponentModel.IContainer
	End Class
End Namespace
